Amsterdam/signals-frontend

Dockerfile, Jenkinsfile, default.conf, docker-compose.yml
Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.
**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.
**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT …
=> toevoegen dockerfiles en jenkinsfile..

Jenkinsfile
Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.
**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.
**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT …
=> Jenkins file

src/shared/services/api/api.js
=> fix: url in production

environment.conf.acc.json, environment.conf.json, src/shared/services/auth/auth.js, src/shared/services/configuration/configuration.js
=> add: AUTH_ROOT in the configuration

src/shared/services/configuration/configuration.js
=> fix: opleiding deploy

src/index.html
=> add: different logging for production and the rest

src/signals/incident-management/containers/IncidentDetailPage/__snapshots__/index.test.js.snap, src/signals/incident-management/containers/IncidentDetailPage/components/PrintLayout/__snapshots__/index.test.js.snap, src/signals/incident-management/containers/IncidentDetailPage/components/PrintLayout/index.js, src/signals/incident-management/containers/IncidentDetailPage/components/PrintLayout/index.test.js, src/signals/incident-management/containers/IncidentDetailPage/components/PrintLayout/style.scss, src/signals/incident-management/containers/IncidentDetailPage/index.js, src/signals/incident-management/containers/IncidentDetailPage/index.test.js
=> add: status list in the pdf

src/components/Footer/__snapshots__/index.test.js.snap, src/components/Footer/index.js, src/signals/incident/definitions/wizard-step-1-beschrijf.js
=> master to dev

Jenkinsfile, docker-compose.yml, package.json
=> fix: post signal in acceptation environment

src/components/Header/index.js, src/containers/HeaderContainer/__snapshots__/index.test.js.snap, src/containers/HeaderContainer/index.js, src/shared/services/auth/auth.js, src/signals/incident-management/components/IncidentManagementModule/__snapshots__/index.test.js.snap, src/signals/incident-management/components/IncidentManagementModule/index.test.js
De inlog-knop rechtsboven is nu helemaal weg.
=> Fixing #85

Dockerfile
=> add: ensure npm packages in the build version

src/signals/incident/definitions/wizard-step-1-beschrijf.js, src/signals/incident/definitions/wizard-step-4-email.js
=> fixed texts SIG-521-523-524

environment.conf.acc.json, environment.conf.json, src/shared/services/configuration/configuration.js, src/signals/incident/containers/IncidentContainer/saga.js
=> add: separate endpoint api for mltool

src/signals/incident/definitions/wizard-step-1-beschrijf.js
=> SIG-430: Add 'Telefoon - Adoptant' as source option for a new 'melding'

Jenkinsfile
=> Splitsen van develop naar acc en master naar prod

src/signals/incident-management/containers/IncidentOverviewPage/components/List/__snapshots__/index.test.js.snap, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.js, src/signals/incident-management/containers/IncidentOverviewPage/components/List/style.scss
=> Bugfix/SIG-549 fixed: new columns in admin list

src/signals/incident-management/containers/IncidentStatusContainer/components/Add/index.js, src/signals/incident-management/containers/IncidentStatusContainer/components/List/index.js, src/signals/incident-management/containers/IncidentStatusContainer/index.js, src/signals/incident-management/containers/IncidentStatusContainer/reducer.js, src/signals/incident-management/containers/IncidentStatusContainer/reducer.test.js, src/signals/incident-management/definitions/statusList.js
=> SIG-684: Do not show new statuses in 'change status dropdown' as they are not intended to be changed into by admins

src/signals/incident-management/definitions/statusList.js
=> SIG-684: Use proper Dutch names for the new extern statuses

src/shared/services/map-categories/index.js, src/shared/services/map-categories/index.test.js, src/signals/incident-management/containers/IncidentDetailPage/components/PrintLayout/__snapshots__/index.test.js.snap, src/signals/incident-management/containers/IncidentDetailPage/components/PrintLayout/index.js, src/signals/incident-management/containers/IncidentDetailPage/components/PrintLayout/style.scss
=> sig-830 fix print view: teksten passen niet op pagina en merker is niet gecentreerd op de kaart

src/index.html
The current piwik url is not publicly accessible, the updated one is
=> Bugfix: Use the correct piwik url

src/signals/incident-management/definitions/statusList.js
toegevoegd VERZOEK_TOT_AFHANDELING in filter maar niet in zelf toe te wijzen status
=> [SIG-1079] added VERZOEK_TOT_AFHANDELING to statuslist

src/signals/incident/definitions/wizard-step-1-beschrijf.js
=> [SIG-1072] refactored urgentie question

.nginx-prod.conf, src/index.html
Signed-off-by: Daniel Binkhuysen <daniel@binkhuysen.com>
=> update matomo url

src/signals/incident-management/containers/IncidentOverviewPage/saga.js, src/signals/incident-management/containers/IncidentOverviewPage/saga.test.js
wait for BE to deploy filters fix for V1
=> Hotfix: now using v1 list

src/signals/incident-management/components/CheckboxList/__test__/CheckboxList.test.js, src/signals/incident-management/components/CheckboxList/index.js, src/signals/incident-management/components/FilterForm/__test__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/__test__/parse.test.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/components/FilterForm/parse.js, src/signals/incident-management/containers/Filter/__tests__/reducer.test.js, src/signals/incident-management/containers/Filter/__tests__/saga.test.js, src/signals/incident-management/containers/Filter/index.js, src/signals/incident-management/containers/IncidentOverviewPage/saga.js
This PR renames
- `sub_slug` to `category_slug`
- `main_slug` to `maincategory_slug`
- `location__address_text` to `address_text`
- `priority__priority` to `priority`
- `status__state` to `status`
- `location__stadsdeel` to `stadsdeel`
- `incident_date_start` to ` incident_date`
=> SIG-1535 filter param rename

src/signals/incident-management/containers/Filter/saga.js, src/signals/incident-management/containers/IncidentOverviewPage/saga.js
This PR ensures that the filters endpoint is called correctly
=> (Fix) endpoint URL

src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js
This PR:
- Shows red bold text for incidents that have their priority set to 'high'
- Reformats the `MetaList` component file
- Doesn't add tests, because those are already pending in another PR (#282)
=> SIG-1522 Priority emphasis

package.json
fixed by moving amserdam-stijl to devdeps
=> Fixed boilerplate dll error amsterdam stijl

src/containers/SearchBar/index.js
Changes 'melding nummer' into 'meldingsnummer'
=> SIG-1624 Zoekveld placeholder change

src/signals/incident-management/components/FilterForm/styled.js
This PR contains a fix for the filter form footer element that was misaligned in IE.
=> SIG-1562 Filter modal footer position fix

src/components/PageHeader/index.js, src/signals/incident-management/containers/FilterTagList/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.js
This PR:
- Adjusts the page header font size (was lost in merge conflicts a couple of PRs ago)
- Re-aligns the tag list and only renders that tag list where there are tags to be shown
=> SIG-1632 Page header styling

src/components/PageHeader/index.js
Renders `h1` with `h3` styling
=> SIG-1632 Page header font size

src/signals/incident-management/components/FilterForm/index.js
PR contains minor change for filter form reset button label
=> SIG-1647 Button label change

src/signals/incident-management/components/FilterForm/index.js
This PR changes the label for one of the sections in the filter form
=> SIG-1646 Filter form section rename

src/containers/PageHeader/__tests__/PageHeader.test.js, src/containers/PageHeader/index.js, src/signals/incident-management/containers/MyFilters/components/FilterItem/__tests__/FilterItem.test.js, src/signals/incident-management/containers/MyFilters/components/FilterItem/index.js
This PR contains changes that show the refresh icon next to filter names in the `PageHeader` component and the `MyFilters` container
=> SIG-1663 refresh icon

src/components/SiteHeader/index.js
This PR fixes the position of the menubar for unauthorised used in IE11.
=> SIG-1677 Menu bar position fix

src/shared/types/index.js
This PR contains definitions for common types in the application that require validation on prop type level.
=> (Chore) Type definitions

src/signals/incident-management/containers/IncidentDetail/index.js, src/signals/incident-management/containers/IncidentDetail/index.test.js
geen test in de PR want die. zit in de detail test branch
=> [SIG-1704] fixes history and attachments call

Jenkinsfile
=> migrate to datapunt2

Jenkinsfile
Contains minor change that should (🤞) fix the broken build
=> Build fix release

Jenkinsfile
This release reverts previous changes made to the `Jenkinsfile`. Previous changes were related to the new environment in which the application will run, but production hasn't been migrated yet.
=> Revert build script change release

Dockerfile, Jenkinsfile, docker-compose.yml
This PR:
- groups commands in the `Dockerfile` and moves commands to other lines to improve container reuse
- applies different deploy environments for both `develop` and `master` branches
- adds a `build` stage for branches other than `develop` and `master`
- contains a change in the `Jenkinsfile` that will improve build times, because of more efficient image reuse
=> (Chore) Optimise Dockerfile

Dockerfile
This PR contains a fix for an issue that prevented commands to run in Docker, because of a missing `ARG` statement.
=> (Fix) Dockerfile

Jenkinsfile
This PR contains a change to the Jenkinsfile that allows running deploys in both `app` and `data` CI environments.
=> (Fix) Jenkinsfile

Jenkinsfile
This PR reverts a previous change that was mistakenly applied to the build pipeline configuration.
=> (Fix) Acceptance image push

Jenkinsfile
This PR removes the datapunt1 references from the `Dockerfile`
=> (Chore) Use DP2 registry

src/signals/incident/containers/KtoContainer/components/KtoForm/style.scss, src/signals/incident/containers/KtoContainer/index.js, src/signals/incident/containers/KtoContainer/style.scss
fixes the width of the KTO form in IE11
=> [SIG-1726] fixed width of kto containers in IE11

src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js
This PR contains a fix for the incident creation request body. The payload was accidentally wrapped in an object. The tests were adjusted to make sure that the payload signature is verified as well.
=> (Fix) Request payload

Jenkinsfile
=> (Fix) Missing Docker images

src/containers/SearchBar/__tests__/SearchBar.test.js, src/containers/SearchBar/index.js, src/signals/incident-management/containers/IncidentOverviewPage/saga.js
This PR contains a fix for the search field that, when submitted, wouldn't show filtered incidents.
=> (Fix) Search by ID

package-lock.json, src/components/TextArea/index.js, src/signals/incident-management/components/TextAreaInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/DescriptionWithClassificationInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/TextareaInput/__snapshots__/index.test.js.snap
This PR changes the `TextArea` component so that its contents are displayed with the correct font family.
=> [SIG-1835] - Textarea font family fix

Jenkinsfile
This PR fixes an issue in Jenkins where network connections were not cleaned after `docker-compose`
=> (Fix) Jenkins stage teardown

src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentPart/index.js, src/signals/incident-management/containers/IncidentSplitContainer/components/SplitDetail/index.js, src/signals/incident-management/containers/IncidentSplitContainer/components/SplitForm/index.js, src/signals/incident-management/containers/IncidentSplitContainer/index.js
in this PR in splitsen:
- added spacing above h1
- refactored all px into themeSpacing
=> added spacing above h1 in splitsen

src/signals/incident-management/containers/IncidentSplitContainer/components/SplitForm/index.js
#[428](https://github.com/Amsterdam/signals-frontend/pull/428) Fix splitsen issue SIG-2855
=> Patch release 2019-11-04

src/signals/incident-management/__tests__/selectors.test.js, src/signals/incident-management/components/FilterForm/__test__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/definitions/index.js, src/signals/incident-management/definitions/sourceList.js, src/signals/incident-management/reducer.js, src/signals/incident-management/selectors.js, src/signals/incident/definitions/wizard-step-1-beschrijf.js
This PR adds the section 'Bron' to the filter form. The list of hardcoded sources has been moved from the meldingen form to the `definitions` folder for reuse.
=> [SIG-1648] - Filter by source

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.test.js
This PR contains changes that show an alert when a default text with template characters is used to submit an incident's changed status.
=> [SIG-1856] - Message template alert

internals/testing/test-bundler.js, src/models/incident/saga.js, src/models/incident/saga.test.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js
This PR shows an alert on the incident detail page whenever a user encounters an error with the  403 error status.
=> [SIG-1914] Alert on incident patch 403

src/signals/incident-management/constants.js, src/signals/settings/users/containers/Overview/hooks/__tests__/useFetchUsers.test.js, src/signals/settings/users/containers/Overview/hooks/useFetchUsers.js
This PR changes the `useFetchUsers` hook so that both page and page size can be passed to it
=> (Chore) Fetch page-size

jest.config.js, src/signals/settings/index.js, src/signals/settings/routes.js, src/signals/settings/users/containers/Overview/index.js
This PR contains changes that ensures that routes can be resolved. Changes in `routes.js` weren't propagated to other related files.
=> (chore) Fix route resolve

src/signals/incident-management/definitions/statusList.js
=> [SIG-1538] added VERZOEK_TOT_AFHANDELING to list of changable statuses

src/shared/services/api/api.js, src/shared/services/api/api.test.js
This PR adds a function to the API service that returns a message related to a specific error status. If the status code is isn't registered, a default message is returned.
=> (chore) Error messages

src/components/List/index.js, src/containers/App/index.js, src/containers/App/index.test.js
This PR makes sure that, when a user is authenticated, the site footer isn't rendered
=> (chore) Remove site footer

src/signals/settings/users/containers/Detail/components/UserForm/index.js
This PR removes an accicentally left behind error message on a field in the user form
=> [SIG-1991] Remove error message

src/signals/settings/users/containers/Detail/__tests__/Detail.test.js, src/signals/settings/users/containers/Detail/index.js
Changes the user detail page title.
=> [SIG-1992] - Change user detail page title

src/signals/incident/components/form/PlainText/__snapshots__/index.test.js.snap, src/signals/incident/components/form/PlainText/index.js, src/signals/incident/components/form/PlainText/style.scss, src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.js
In this PR:
- added error-block in uitvraag form
- added warning text for kerstverlichting only in straatverlichting subcat
=> [SIG-1996] added kerstverlichting waarschuwing in error-block in uitvraag

src/signals/incident-management/containers/IncidentDetail/components/LocationForm/index.js
In this PR:
- fixed typo of button name
=> [SIG-1916] fixed button name locatie opslaan

src/components/FormFooter/index.js
=> [SIG-1999] FormFooter component overlaps checkboxes

src/hooks/useFormValidation.js, src/signals/settings/roles/containers/RoleFormContainer/components/RoleForm/__test__/RoleForm.test.js, src/signals/settings/roles/containers/RoleFormContainer/components/RoleForm/index.js
in this PR:
- validation error on name field only triggers after form submit
=> [SIG-1998] fixed validation of name in role form

package-lock.json, src/containers/App/saga.js, src/containers/App/saga.test.js, src/models/history/saga.js, src/models/incident/saga.js, src/models/incident/saga.test.js, src/shared/services/configuration/configuration.js, src/signals/incident-management/__tests__/saga.test.js, src/signals/incident-management/containers/DefaultTextsAdmin/saga.js, src/signals/incident-management/containers/DefaultTextsAdmin/saga.test.js, src/signals/incident-management/containers/IncidentOverviewPage/saga.js, src/signals/incident-management/containers/IncidentSplitContainer/saga.js, src/signals/incident-management/containers/IncidentSplitContainer/saga.test.js, src/signals/incident-management/saga.js, src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js, src/signals/incident/containers/KtoContainer/saga.js, src/signals/incident/containers/KtoContainer/saga.test.js, src/signals/incident/services/set-classification/index.js
This PR moves all endpoint references to the `Configuration` class and, where applicable, reformats files that were touched in the process.
=> (chore) Configuration endpoints

Dockerfile, Jenkinsfile, docker-compose.yml
=> Optimizing build speed to avoid building when lintint and testing

internals/testing/test-bundler.js, src/containers/App/saga.js, src/containers/App/saga.test.js, src/models/history/saga.js, src/models/incident/saga.js, src/models/incident/saga.test.js, src/shared/services/configuration/configuration.js, src/signals/incident-management/__tests__/saga.test.js, src/signals/incident-management/containers/DefaultTextsAdmin/saga.js, src/signals/incident-management/containers/DefaultTextsAdmin/saga.test.js, src/signals/incident-management/containers/IncidentOverviewPage/saga.js, src/signals/incident-management/containers/IncidentSplitContainer/saga.js, src/signals/incident-management/containers/IncidentSplitContainer/saga.test.js, src/signals/incident-management/saga.js, src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js, src/signals/incident/containers/KtoContainer/saga.js, src/signals/incident/containers/KtoContainer/saga.test.js, src/signals/incident/services/set-classification/index.js
=> [SIG-2011] UI permissions

src/signals/incident-management/containers/IncidentDetail/components/History/index.js
fixed typo whitespace to white-space
=> [SIG-1945] fixed newlines in history

src/containers/App/index.js, src/containers/App/index.test.js, src/test/utils.js
In this PR:
- added useEffect hook in app container that scrolls to top after each url change
- I have added the test as well
=> [SIG-1843] scroll to top overal in de app

src/signals/incident-management/definitions/stadsdeelList.js
In this PR: 
- added item to stadsdeel list
=> [SIG-1919] add to filter stadsdeel Niet bepaald

src/components/Footer/index.js
=> [SIG-1604] fixed footer background color

src/signals/incident-management/components/CheckboxList/__test__/CheckboxList.test.js, src/signals/incident-management/components/CheckboxList/index.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/containers/FilterTagList/__tests__/FilterTagList.test.js, src/signals/incident-management/containers/FilterTagList/index.js, src/signals/shared/filter/parse.js
In this PR:
- Added Selecteer Alles to status and stadsdeel in filters
- Added support for Status: Alles and Stadsdeel: Alles in FilterTagList
- everything is working and checked with Herjen
=> Sig 1915 filter select all for status and stadsdeel

src/components/SiteHeader/__tests__/SiteHeader.test.js, src/components/SiteHeader/index.js
This PR changes the logo's URL for when the application is showing the melding form.
=> [SIG-1989] Logo URL change

src/components/SiteHeader/__tests__/SiteHeader.test.js, src/components/SiteHeader/index.js
This PR adds a `Help` link to the site header for logged in users.
=> [SIG-1092] Help link

src/components/SiteHeader/index.js, src/signals/settings/departments/Detail/index.js, src/signals/settings/departments/Overview/index.js, src/signals/settings/index.js, src/signals/settings/routes.js
This PR contains configuration for the departments overview page and has stub components for both overview and detail containers which will be completed in a later PR.
=> [SIG-2046] Department route config

src/signals/incident-management/components/FilterForm/index.js
removes obsolete Label for status list and stadsdeel list
=> [SIG-2054] removed double labels for status list and stadsdeel list

src/components/SiteHeader/__tests__/SiteHeader.test.js, src/containers/App/selectors.js, src/signals/incident-management/components/RadioButtonList/index.js, src/signals/settings/__tests__/index.test.js, src/signals/settings/index.js, src/signals/settings/roles/containers/RoleFormContainer/__test__/RoleFormContainer.test.js, src/signals/settings/roles/containers/RoleFormContainer/components/RoleForm/__test__/RoleForm.test.js, src/signals/settings/roles/containers/RoleFormContainer/components/RoleForm/index.js, src/signals/settings/roles/containers/RoleFormContainer/index.js, src/signals/settings/roles/containers/RolesListContainer/__test__/RolesListContainer.test.js, src/signals/settings/roles/containers/RolesListContainer/components/RolesList/__test__/RolesList.test.js, src/signals/settings/roles/containers/RolesListContainer/components/RolesList/index.js, src/signals/settings/roles/containers/RolesListContainer/index.js, src/signals/settings/users/containers/Detail/__tests__/Detail.test.js, src/signals/settings/users/containers/Detail/components/UserForm/__tests__/UserForm.test.js, src/signals/settings/users/containers/Detail/components/UserForm/index.js, src/signals/settings/users/containers/Detail/index.js, src/signals/settings/users/containers/Overview/__tests__/Overview.test.js, src/signals/settings/users/containers/Overview/index.js
This PR applies permission checks to pages in the settings module. Where necessary, users are redirected, are shown a form with disabled fields or aren't shown interface elements when they lack the proper permissions.
=> [SIG-2013] Menu + page checks

src/components/SiteHeader/index.js, src/signals/incident-management/__tests__/reducer.test.js, src/signals/incident-management/reducer.js
This PR fixes a bug where the active page for the incident overview was reset after navigating.
=> [SIG-2055] Page set fix

src/signals/incident-management/containers/IncidentSplitContainer/index.js
the id param was removed from the route.
now using useParams
=> hot fix splitsen issue

src/signals/incident-management/containers/IncidentSplitContainer/index.test.js
=> added test for fetching services

src/signals/incident-management/containers/FilterTagList/index.js
added white-space: nowrap to all tags
checked in IE11 and FF63
=> [SIG-2057] fixed tagkeylist long tags over 2 lines

src/global.scss, src/signals/settings/users/containers/Detail/components/UserForm/index.js
- in IE11 the user form and role form have grey bodies: setting app height to 100vh makes sure the white background is everywhere in all pages
- removed the hint test form user form email
=> Sig 2057 edit user remove whitespace and subline email

src/signals/settings/users/containers/Overview/__tests__/Overview.test.js, src/signals/settings/users/containers/Overview/components/DataView/__tests__/DataView.test.js, src/signals/settings/users/containers/Overview/components/DataView/components/DataViewBody/index.js, src/signals/settings/users/containers/Overview/components/DataView/components/DataViewHeader/components/DataViewHeaderRow/index.js, src/signals/settings/users/containers/Overview/components/DataView/components/DataViewHeader/index.js, src/signals/settings/users/containers/Overview/components/DataView/index.js, src/signals/settings/users/containers/Overview/components/DataView/styled.js, src/signals/settings/users/containers/Overview/index.js, src/test/utils.js, src/utils/__tests__/fixtures/filteredUserData.json, src/utils/__tests__/fixtures/users.json
This PR refactors the UserOverview container and creates new DataView components.
=> SIG-1952 - Refactor 'User Overview' container.

src/signals/settings/users/containers/Overview/__tests__/Overview.test.js, src/signals/settings/users/containers/Overview/hooks/useFetchUsers.js, src/signals/settings/users/containers/Overview/index.js
Allow to filter users by username
=> SIG-1850 - Add filter by username to Users Overview.

src/shared/types/index.js, src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/components/CheckboxGroup.js, src/signals/incident-management/components/FilterForm/components/__tests__/CheckboxGroup.test.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/components/FilterForm/reducer.js, src/signals/incident-management/definitions/priorityList.js, src/signals/incident/containers/IncidentContainer/index.test.js, src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js, src/signals/incident/definitions/wizard-step-1-beschrijf.js, src/signals/shared/filter/parse.js
In this PR:
- now using CheckboxGroup instead of RadioGroup for priority in filter form
- hasToggle is now prop in CheckboxGroup
- in meldingsformulier priority now is RadioInput
- adds priority low to SplitForm
- adds priority low to Detail
=> Sig 2083 toevoegen melding urgentie laag

src/shared/services/auth/auth.js, src/shared/services/auth/auth.test.js
Reverts Amsterdam/signals-frontend#585
=> Revert "[SIG-2128] Variable redirect after login"

src/signals/incident/components/form/PlainText/__snapshots__/index.test.js.snap, src/signals/incident/components/form/PlainText/index.js, src/signals/incident/components/form/PlainText/style.scss, src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.js
Reverts Amsterdam/signals-frontend#495
=> Revert "[SIG-1996] added kerstverlichting waarschuwing in error-block in uitvraag"

src/signals/incident/containers/IncidentContainer/reducer.js, src/signals/incident/containers/IncidentContainer/reducer.test.js, src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js
This PR contains a fix for a previous merge where, after creating an incident, the wrong handling message was shown.
=> [SIG-2176] Show handling message on successful incident creation

src/signals/incident-management/containers/FilterTagList/__tests__/FilterTagList.test.js, src/signals/incident-management/containers/FilterTagList/index.js, src/signals/settings/users/containers/Overview/index.js
In this PRL:
- added priority translation
- fixed unit test
- reformatted code for lint error
=> [SIG-2083] fixed translation

src/components/SiteHeader/index.js
removed box-shadow from all non phone devices
=> Sig 2241 box shadow en logo positie 

src/shared/types/index.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/index.test.js, src/signals/incident-management/containers/IncidentDetail/index.js, src/signals/incident-management/containers/IncidentDetail/index.test.js, src/signals/incident-management/containers/MyFilters/__tests__/MyFilters.test.js, src/signals/incident-management/containers/MyFilters/components/FilterItem/__tests__/FilterItem.test.js
This PR contains a few changes that make the test output a bit cleaner; mostly proptype warnings that are suppressed by these changes.
=> (Chore) Clean up test logs

.gitignore, README.md
=> (Chore) Added some Node version notes to README

src/components/SiteHeader/__tests__/SiteHeader.test.js, src/components/SiteHeader/index.js
This PR fixes an issue where the global notification container would overlap the site header component. Correcting `z-index` values did the trick.
=> [SIG-2286] Main menu z-index fix

.prettierrc, src/signals/incident/components/IncidentForm/index.js, src/signals/incident/components/IncidentForm/index.test.js, src/signals/incident/components/IncidentNavigation/__snapshots__/index.test.js.snap, src/signals/incident/components/IncidentNavigation/index.test.js, src/signals/incident/components/IncidentPreview/index.js, src/signals/incident/components/IncidentPreview/services/is-visible/index.js, src/signals/incident/components/IncidentPreview/services/is-visible/index.test.js, src/signals/incident/components/IncidentWizard/index.js, src/signals/incident/components/IncidentWizard/index.test.js, src/signals/incident/components/IncidentWizard/services/on-next/index.js, src/signals/incident/definitions/wizard-step-1-beschrijf.js, src/signals/incident/services/check-visibility/index.js, src/signals/incident/services/check-visibility/index.test.js, src/signals/incident/services/format-conditional-form/index.js
This PR contains changes that remove the `isAuthenticated` prop passthrough and replace those with `isAuthenticated()` calls, simplifying components and functions.
=> (Chore) Remove isAuthenticated props

src/signals/incident-management/definitions/index.js, src/signals/incident-management/definitions/typesList.js
Adds the `types` definition file.
=> [SIG-2280] Incident types definition

src/components/Geocoder/Geocoder.jsx, src/components/Geocoder/ParksLayer.js, src/components/Geocoder/parks.json, src/shared/services/map-location/index.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Location/index.js, src/signals/incident-management/containers/IncidentDetail/components/LocationForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/LocationPreview/index.js, src/signals/incident-management/containers/IncidentDetail/components/MapDetail/index.js, src/signals/incident/components/form/MapInput/index.js
This PR:
- intergrates the click point selections on the parks layer with the rest of the application
- ensures the zoom parameter is a number all over in the application
- it uses the parks.json for the moment, this wil be served from a service later on
=> [react-maps] parks layer

src/signals/incident/containers/IncidentContainer/index.js
Added warning message about eventual delay with processing reports.
=> Sig 2415 alert plaatsen op meldingsformulier master

src/components/SiteHeader/index.js, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.js, src/signals/incident-management/containers/IncidentOverviewPage/components/List/style.scss, src/signals/incident/components/IncidentWizard/index.js, src/signals/settings/components/PageHeader/index.js, src/signals/settings/departments/Overview/index.js
@janjaap do we want test the font weights?
Maybe it would be better to define the style on one place, on the other hand it looks like most of the components needs to be refactored anyway so I kept it like it is.
=> [SIG-1025] header tekst verkeerd gestyled

src/signals/incident-management/definitions/typesList.js, src/signals/incident/definitions/wizard-step-1-beschrijf.js
This PR adds definition texts for incident types:
=> [SIG-2320] Type definition texts

src/components/History/index.js, src/signals/settings/categories/Detail/components/CategoryForm/__tests__/CategoryForm.test.js, src/signals/settings/categories/Detail/components/CategoryForm/index.js
This PR contains changes that render a category's history when it's available.
=> [SIG-2395] Category history

src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.test.js, src/signals/incident-management/routes.js
This PR contains changes that render a button in the incident overview page that can toggle the list view or the map view.
=> [SIG-2495] 24 Hour map route + page

src/signals/incident-management/containers/IncidentOverviewPage/components/Map/components/DetailPanel/__tests__/DetailPanel.test.js, src/signals/incident-management/containers/IncidentOverviewPage/components/Map/components/DetailPanel/index.js, src/signals/incident-management/containers/IncidentOverviewPage/components/Map/index.js
Map DetailPanel component. Note that the map click handler has to respond to marker clicks when marker clustering is implemented.
=> [SIG-2499] Detail panel

docker-compose.yml
This PR fixes a reference to the Docker registry.
=> (Chore) Registry reference

src/signals/incident-management/containers/IncidentOverviewPage/components/Map/index.js
Fixes a couple of layout issues; placement of the autosuggest field and placeholder in input.
=> (Chore) Map styling fixes

src/signals/incident-management/containers/IncidentOverviewPage/components/Map/index.js
This PR sets the page size to a fixes value and also memoizes the dates that are used so that requests use the same parameters between renders.
=> (Chore) Geography page size

src/components/MapInput/__tests__/reverseGeocoderService.test.js, src/shared/services/map-location/index.test.js, src/utils/__tests__/fixtures/PDOKResponseData.json
This PR contains a fix that should've been in a previous PR (#750).
=> (Chore) Fix straatnaam tests

src/signals/incident/containers/IncidentContainer/index.js, src/signals/incident/containers/IncidentContainer/index.test.js
This PR updates the text of the alert message on the first page
=> updates the text of the alert message on the first page

src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.test.js, src/signals/incident-management/index.js
This PR adds a referrer URL to the incident detail `DetailHeader` component's backlink.
=> [SIG-2542] Back to overview map

src/components/MapInput/__tests__/MapInput.test.js, src/components/MapInput/index.js, src/components/MapSelect/index.js, src/components/MapSelect/style.scss
This PR fixes some style issued in the OLV map related to the font family and the map positioning of the controls
=> Sig 2538 ovl style

src/components/MapSelect/index.js, src/components/MapSelect/style.scss
This PR fixes the font choice in the MapSelect component
=> [SIG-2538] adds Avenir Next to the MapSelect controls

src/signals/incident-management/__tests__/selectors.test.js, src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/containers/Filter/__tests__/Filter.test.js, src/signals/incident-management/containers/Filter/index.js, src/signals/incident-management/containers/FilterTagList/__tests__/FilterTagList.test.js, src/signals/incident-management/containers/FilterTagList/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.test.js, src/signals/incident-management/definitions/index.js, src/signals/incident-management/reducer.js, src/signals/incident-management/selectors.js, src/signals/shared/filter/__tests__/parse.test.js, src/signals/shared/filter/parse.js
This PR adds a checkbox group to the filter form. Most notable change in this PR is the removal of the datalists selector and the inclusion of its data in individual components. This change makes underlying components a bit more flexible and easier to test.
=> [SIG-2251] Type filter

src/signals/incident-management/containers/IncidentOverviewPage/components/Map/components/DetailPanel/index.js
This PR replaces the border with outline in the 24 hours map detail panel
=> [SIG-2541] adds outline instead of border to the detail panel

cypress/integration/changeSignalBeforeSubmit.spec.js, cypress/support/selectorsCreateSignal.js, package-lock.json, package.json
* Scenario's for changing a signal for a user who is not logged in
* Updates Cypress version to 4.5.0
=> SIG-2597 cypress tests for changing signal

src/containers/App/index.js, src/containers/App/index.test.js
Fixes an issue where, after logging in, the app's interface didn't reflect the logged in state.
=> (Chore) Fix authentication on app init

Jenkinsfile
=> (Chore) Skip cache stage

src/components/Button/__tests__/Button.test.js, src/components/Button/index.js, src/signals/incident-management/containers/IncidentDetail/components/AddNote/index.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/components/DownloadButton/index.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js
This PR solves the problems related to the button fonts from `asc` package by adding a Button component with the correct font.
=> [SIG-2552] fixes the font issues in incident detail buttons

src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Location/index.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Location/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/index.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/EditButton/__tests__/EditButton.test.js, src/signals/incident-management/containers/IncidentDetail/components/EditButton/index.js, src/signals/incident-management/containers/IncidentDetail/components/Highlight/index.js
This PR contains changes to inner components of the `IncidentDetail` container component and specifically to the detail `Location` component. The component is wrapped in a `HighLight` component so that, when the location is edited and saved, the change is reflected in the incident detail page with a yellow background that lights up and fades away to indicate to the user that the value has been updated.
Note that PR also contains a new component; `EditButton`. This component will be used in subsequent PRs to replace the existing buttons on the incident detail page.
=> [SIG-2447] Location highlight

docs/adr/0003-application-configuration-setup.md
This PR contains an ADR for a different configuration setup so that we can serve multiple brands and TLDs.
=> (Chore) Config setup ADR

src/signals/incident-management/containers/IncidentDetail/components/MetaList/components/ChangeValue/index.js, src/signals/incident-management/containers/IncidentSplitContainer/components/SplitForm/index.js
This PR fixes the font in the MetaList and SplitForm components
=> [SIG-2552] demi font for buttons in the MetaList and SplitForm components

src/signals/incident/definitions/wizard-step-1-beschrijf.js
This PR adds extra information to the incident form
=> [SIG-2514] adds an incident subtitle to the incident form

cypress/fixtures/graffiti.json, cypress/integration/changeSignalAfterSubmit.spec.js, cypress/support/selectorsManageIncidents.js, cypress/support/selectorsSignalDetails.js
Cypress tests for SIG-2380, change signal after submit. Scenario's:
* Change Location
* Change Status
* Change Urgency
* Change Type
* Change Category
=> Cypress tests for SIG-2380, change signal after submit

src/signals/incident/services/check-visibility/index.js, src/signals/incident/services/check-visibility/index.test.js
This PR adds documentation and tests for the `check-visibility` function
=> [SIG-2661] check-visibility tests

src/signals/incident-management/containers/DefaultTextsAdmin/components/DefaultTextsForm/index.js, src/signals/incident-management/containers/DefaultTextsAdmin/components/DefaultTextsForm/index.test.js, src/signals/incident-management/containers/DefaultTextsAdmin/saga.js, src/signals/incident-management/containers/DefaultTextsAdmin/saga.test.js
This PR increases the amount of default text fields that are shown on the default texts admin page.
Next to that, a successful call will show a notification with the number of stored texts, the category and the status.
=> [SIG-2646] Increase default texts amount

src/signals/settings/roles/containers/RoleFormContainer/components/RoleForm/index.js
This PR ensures visibility of the last role in the roles form
=> [SIG-2693] ensures visibility of the last role in the roles form

src/signals/incident-management/containers/IncidentSplitContainer/components/SplitForm/index.js, src/signals/incident-management/containers/IncidentSplitContainer/components/SplitForm/index.test.js, src/signals/incident-management/containers/IncidentSplitContainer/index.js, src/signals/incident-management/containers/IncidentSplitContainer/index.test.js, src/signals/incident-management/containers/IncidentSplitContainer/services/useFetchIncident/index.js, src/signals/incident-management/containers/IncidentSplitContainer/services/useFetchIncident/index.test.js
This PR moves the fetching of the incident data from the saga to the useFetch hook for the Split container. This simplifies the data fetching process
=> [SIG-2658] use fetch with split incident

cypress/fixtures/parkeeroverlast.json, cypress/integration/createSignalParkeeroverlast.spec.js, cypress/support/commandsCreateSignal.js, cypress/support/commandsRouting.js, cypress/support/selectorsSignalDetails.js
* SIG-2642 Cypress tests for parking flow
* Extracted some functions in signal creation flow
=> SIG-2642 Cypress tests for parking flow

Jenkinsfile
=> Use signals-amsterdam for deployment as next step

cypress/fixtures/wonenLeegstand.json, cypress/integration/createSignalParkeeroverlast.spec.js, cypress/integration/createSignalWonenLeegstand.spec.js, cypress/support/selectorsCreateSignal.js, cypress/support/selectorsSignalDetails.js
* Scenario's for Wonen - Leegstand
* Small changes in selectors
=> Cypress tests vacancy

src/signals/settings/roles/containers/RoleFormContainer/components/RoleForm/__test__/RoleForm.test.js, src/signals/settings/roles/containers/RoleFormContainer/components/RoleForm/index.js
This PR fixes a bug that prevents unchecking of the roles in the role settings page
=> [SIG-2692] role checkbox

cypress/fixtures/wonenVakantieVerhuur.json, cypress/integration/changeSignalBeforeSubmit.spec.js, cypress/integration/createSignalWonenLeegstand.spec.js, cypress/integration/createSignalWonenVakantieVerhuur.spec.js
* Scenario's for holiday rental (SIG-2718)
* Small fixes
=> [SIG-2718] Scenario's for holiday rental

src/signals/incident/definitions/wizard-step-2-vulaan/wonen.js
This PR contains a small fix for two typos in the upcoming release branch.
=> [SIG-2747] Fix typos

src/signals/incident/definitions/wizard-step-2-vulaan.js
This PR enables the `wonen` workflow in the incident submission form
=> (Chore) Enable wonen questions

src/components/InfoText/index.js, src/signals/incident-management/components/RadioInput/index.js, src/signals/incident-management/components/SelectInput/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/components/ChangeValue/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/components/ChangeValue/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js
This PR:
- adds `InfoText` component and
- replaces info text renders in several components with the `InfoText` component
- unifies the margins that are used in multiple components so that they all use the same values and margins can be collapsed where necessary
- alters the `ChangeValue` component so that it can render an info text below its form field(s)
=> [SIG-2744] Subcategory description

src/components/Button/index.js, src/components/ButtonBar/index.js, src/components/Checkbox/index.js, src/components/LoginPage/index.js, src/components/NextButton/index.js, src/components/PreviousButton/index.js, src/components/SelectInput/__tests__/SelectInput.test.js, src/components/SelectInput/index.js, src/components/TextArea/__tests__/TextArea.test.js, src/components/TextArea/index.js, src/signals/incident-management/components/TextAreaInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/DescriptionWithClassificationInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/TextareaInput/__snapshots__/index.test.js.snap
This PR adds components that will replace specific styling, now supplied by the `amsterdam-stijl` package. In a follow-up pull request, these components will be applied.
=> (Chore) amsterdam-stijl Removal helper components

cypress/fixtures/wonenOnderverhuur.json, cypress/integration/createSignalWonenOnderverhuur.spec.js
Cypress scenario's for category rental
=> [SIG-2720] Cypress tests rental

cypress/fixtures/wonenWoningDelen.json, cypress/integration/createSignalWonenWoningDelen.spec.js
Cypress tests for category share house
=> [SIG-2721] Cypress tests share house

cypress/fixtures/wonenWoningOverig.json, cypress/integration/createSignalWonenWoningOverig.spec.js
Cypress tests for subcategory other
=> [SIG-2722] Cypress tests other

environment.conf.json, src/components/Map/index.js, src/components/MapInput/index.js, src/signals/incident/components/form/MapInput/__snapshots__/index.test.js.snap
This PR adds the following maps configuration props:
- `maxZoom`
- `minZoom`
- `gemeentenaam`
=> (Chore) Maps configuration

src/signals/incident/components/IncidentWizard/index.js, src/signals/incident/containers/IncidentContainer/index.js, src/signals/incident/containers/IncidentContainer/index.test.js
Reverts Amsterdam/signals-frontend#896
=> Revert "(Chore) Lazy load wizard definition"

Jenkinsfile
This PR contains changes that, when a merge occurs in either `develop` or `master`, will call all of the corresponding jobs.
=> [SIG-2742] Call Weesp job from signals-frontend

.gitignore, internals/webpack/template.js
Easily allow changes to the environment configuration in a separate file. To change endpoint URL's for instance, to target a locally running backend.
=> Allow local development config in separate file

src/signals/incident-management/components/FilterForm/index.js
This PR fixes a the edit issue in the filter incidents name
=> [SIG-2761] allows the filter name to be changed in the filter page

src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.js
This PR removes one of the OVL question, moves another to a different position and gets rid of redundant `className` props.
=> [SIG-2793] Move/delete OVL questions

src/components/FormFooter/index.js, src/components/Modal/index.js
This PR 
- fixes the font weight in the FormFooter component
- eliminates the fixed height in the Filter modal dialog
=> [SIG-2775] style fixes after updating to asc 0.20.0

src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.js
This PR applies changes to the text of OVL questions.
=> [SIG-2794] Textual changes

Jenkinsfile
This PR enables building Weesp jobs again since https://github.com/Amsterdam/signals-weesp/pull/3 has been merged
=> (Chore) Enable Weesp jobs

babel.config.js
=> (Chore) Remove babel debug

src/signals/incident/components/form/DateTimeInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/DateTimeInput/index.js
This PR makes sure that the alignment of date/time input elements in the incident form is correct.
=> [SIG-2808] Alignment of date/time form fields

src/signals/incident/containers/IncidentContainer/index.js, src/signals/incident/containers/IncidentContainer/index.test.js
This PR removes the alert message from the incident page
=> [SIG-2815] Remove the alert message from the incident page

package.json
This PR is merely meant to trigger a Netlify build/deploy and contains a trivial change.
=> (Chore) Trigger Netlify build

src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/__tests__/actions.test.js, src/signals/incident-management/components/FilterForm/__tests__/reducer.test.js, src/signals/incident-management/components/FilterForm/actions.js, src/signals/incident-management/components/FilterForm/constants.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/components/FilterForm/reducer.js
Not sure about the naming since the filter searches across multiple notes (`note_keyword`), feedback is welcome ;)
=> [SIG-2824] Add notes filter

environment.conf.json
This PR removes the unused AUTH_ROOT setting.
=> Remove unused AUTH_ROOT setting

package-lock.json, src/components/LocationMarker/__tests__/LocationMarker.test.js, src/components/LocationMarker/index.js, src/signals/incident/components/form/Header/index.js
This PR adds the `LocationMarker` component. This component doesn't actually render anything, because it taps directly into the Leaflet API to add vector layers to the map instance.
I tried using both `Circle` and `CircleMarker` from [Amsterdam/react-maps](https://github.com/Amsterdam/amsterdam-react-maps), but I ran into issues with the zoom buttons not being clickable or the `Circle` vector scaling unpredictably when zooming in or out.
=> [SIG-2900] LocationMarker component

src/components/GPSButton/__tests__/GPSButton.test.js, src/signals/incident/components/IncidentForm/index.js
This PR fixes the console error that states `Cannot update during an existing state transition`. Also an unittest of the GPSButton was fixed.
=> [SIG-2061] Fix Error in console when rendering the incident form

src/signals/incident-management/definitions/sourceList.js
This PR adds `Fixi Weesp` to the list of incident sources
=> [SIG-2902] Adds an extra incident source to the list

src/components/Footer/index.js
This PR changes the used tags in the `Footer` component to make sure that the font size has the correct value (16px instead of 18px).
=> [SIG-2905] Footer font size and line height adjustment

environment.conf.json, src/signals/incident-management/containers/IncidentOverviewPage/components/Map/index.js
=> Move back office zoom level to config

src/app.js
Contains a small fix for a wrongly referenced var.
=> (Fix) Wrong variable reference

environment.conf.schema.json
This PR update a couple of JSON fields
=> (Chore) Update JSON schema

src/shared/services/auth/auth.js, src/shared/services/auth/auth.test.js
This PR contains a fix for situations where `localStorage` is either not available or doesn't have a storage limit. In that case it falls back to `sessionStorage`.
=> [SIG-2053] sessionStorage fallback

src/signals/incident-management/definitions/statusList.js
This PR updates the warning texts of the status styles to match the send email functionality
=> [SIG-2995] Updates the status warnings

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js
This PR fixes the alignment and the text in the status form
=> [SIG-2993] Updates the styling and texts in the status form

Dockerfile
=> (Chore) Alpine pk install fix

docs/adr/0005-deploy-setup.md, docs/adr/README.md
This PR contains an ADR for a change in repository setup in order to ease the pain of deployment that we currently have.
=> [SIG-2921] ADR repo setup

src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.js, src/signals/incident-management/definitions/statusList.js
This PR:
- Converts the `List` component in the incident-management module into a functional component
- Adds the flag `shows_remaining_sla_days` to the status definitions list and references that flag in the `List` component instead of having hardcoded values in that component
=> [SIG-3013] Incidents list component; class => function

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js
This PR fixes the columns align in the change status page
=> [SIG-3027] Fix the columns align in the change status page

environment.conf.json
This PR updates the text of consentToContactSharing setting
=> [SIG-3038] Update the consentToContactSharing string

src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.js
This PR fixes the second part of the story where the extra text shown when the user selects the answer yes should be removed.
=> [SIG-3005] Removes the extra shown text when the answer is yes

src/signals/incident-management/components/RadioButtonList/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js
This PR reinstates `data-testid` attributes that were accidentally removed in a previous PR.
=> (Fix) Status form test-ids

src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Location/index.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Location/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/__tests__/StatusForm.test.js
This PR fixes a couple of tests that managed to fail themselves after a botched merge conflict in the outstanding release branch.
=> (Chore) Fix failing tests

src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/definitions/index.js, src/signals/incident-management/definitions/kindList.js, src/signals/shared/filter/parse.js
This PR adds a list of options to the `FilterForm` component to filter incidents by `kind`.
=> [SIG-2644] Kind filter

src/signals/incident-management/containers/FilterTagList/index.js, src/signals/incident-management/containers/MyFilters/components/FilterItem/index.js, src/signals/incident-management/containers/MyFilters/components/FilterItem/style.scss
This PR contains changes that slightly alter the spacing of elements in the `My filters` modal
=> [SIG-3113] 'My filters' styling adjustments

src/components/Footer/index.test.js, src/containers/App/index.test.js, src/shared/services/auth/auth.test.js, src/signals/incident-management/__tests__/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/__tests__/StatusForm.test.js, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.test.js, src/signals/incident-management/containers/LegacyIncidentSplitContainer/components/SplitDetail/index.test.js, src/signals/settings/users/Overview/__tests__/Overview.test.js, src/signals/settings/users/Overview/hooks/useFetchUsers.js
This PR resolves issues in test cases where the underlying components relied on the response of (async) fetch requests. Not all requests were properly awaited and caused error later on in unrelated test cases/suits.
=> (Chore) Fix async test issues

src/signals/incident-management/definitions/sourceList.js
This PR renames of the source props from 'Eigen organisatie' to 'Interne melding'
=> [SIG-3118] Rename source

src/shared/services/api/api.js
Minor typo fix in error message dictionary
=> [SIG-2093] Typo fix

src/signals/incident-management/containers/IncidentDetail/components/MetaList/components/ChangeValue/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js
This PR contains just a minor text change in the incident detail view
=> [SIG-3111] Update the Subcategorie text in the MetaList

internals/scripts/validate-config.js
This PR changes a call to `console.log` to `console.table` to ensure proper display of an object in the build output.
=> (Chore) console.table

src/containers/App/index.js, src/hooks/useFetch.js, src/shared/services/resolveClassification/index.js, src/signals/incident/components/IncidentClassification/index.js, src/signals/incident/components/IncidentClassification/index.test.js, src/signals/incident/components/form/DescriptionWithClassificationInput/index.js, src/signals/incident/components/form/DescriptionWithClassificationInput/index.test.js, src/signals/incident/containers/IncidentContainer/actions.js, src/signals/incident/containers/IncidentContainer/actions.test.js, src/signals/incident/containers/IncidentContainer/constants.js, src/signals/incident/containers/IncidentContainer/index.js, src/signals/incident/containers/IncidentContainer/reducer.js, src/signals/incident/containers/IncidentContainer/reducer.test.js
This PR implements the prefill of the category/subcategory from the url and disable the prediction service when the category/subcategory is prefilled
=> [SIG-3092] Set subcategory on url

src/signals/incident-management/index.js
This PR contains a minor change to the `incident-management` module in the `useEffect` mount hook.
=> (Chore) Incident-management module deps list

src/containers/App/index.js, src/containers/App/services.js, src/containers/App/services.test.js, src/models/index.js
This PR, fixes an autorization check in the backoffice.
=> [SIG-3159] Fixes the autorization check in the backoffice

src/components/InfoText/index.js, src/signals/incident/components/form/CategorySelect/CategorySelect.js, src/signals/incident/components/form/CategorySelect/CategorySelect.test.js
This PR adds the info text to the CategorySelect object.
=> [SIG-3178] add info text to CategorySelect

src/signals/incident/definitions/wizard-step-5-samenvatting.js
This PR shows the subcategory description in the summary.
=> [SIG-3901] Show the subcategory text in the summary

src/signals/incident/components/form/CategorySelect/CategorySelect.js
This PR displays the department list after the subcategory name in the category select
=> [SIG-3091] Show the departments list in the subcategory description

src/signals/incident/components/form/CategorySelect/CategorySelect.js
=> [SIG-3091] Fix typo

src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Location/index.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Location/index.test.js
This PR Prevents showing the stadsdeel two times
=> [SIG-3195] Prevents showing the stadsdeel two times

src/shared/services/resolveClassification/index.js, src/shared/services/resolveClassification/index.test.js
This PR Adds a default subcategory for `schoon` category
=> [SIG-3200] Adds a default subcategory for `schoon` category

src/components/ChildIncidents/__tests__/ChildIncidents.test.js, src/components/ChildIncidents/index.js, src/shared/types/index.js, src/signals/incident-management/containers/IncidentDetail/components/ChildIncidents/__tests__/ChildIncidents.test.js, src/signals/incident-management/containers/IncidentDetail/components/ChildIncidents/index.js, src/signals/incident-management/containers/IncidentDetail/constants.js, src/signals/incident-management/containers/IncidentDetail/index.js, src/utils/__tests__/fixtures/childIncidents.json
This PR highlights the child incidents that are changed in the parent incident, Allso adds a button to reset the highlight when there is no action required for the parent incident
=> [SIG-2882] Show changes in child incidents

src/signals/incident-management/containers/IncidentSplitContainer/IncidentSplitContainer.js
This PR correct the conditions for setting the parentIncident in the IncidentSplitContainer
=> fixes the condition for setting the parent incident

src/signals/incident-management/containers/IncidentDetail/components/MetaList/components/ChangeValue/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/components/ChangeValue/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js, src/signals/incident-management/definitions/index.js, src/utils/__tests__/fixtures/index.js
This PR adds functionality to the parent incidents so that the directed department can be changed
=> [SIG-2881] Change directing department

src/signals/incident-management/containers/IncidentSplitContainer/styled.js
As discussed with the designer
=> [SIG-3222] Select max-width change

src/components/ChildIncidents/index.js
This PR improves the display of the child incidents in the detail page
=> [SIG-3185] Align the last child column

src/signals/incident/components/form/Header/index.js
This PR fixes a small styling issue in the header of the incident form
=> [SIG-2475] Adjust the header margin to the 4px grid

src/signals/incident-management/containers/IncidentSplitContainer/IncidentSplitContainer.test.js, src/signals/incident-management/containers/IncidentSplitContainer/__tests__/IncidentSplitContainer.test.js
This PR Improves the test coverage in IncidentSplitContainer
=> (Chore) Improve test coverage in IncidentSplitContainer

src/components/ChildIncidents/index.js
This PR fixes the alignment in the changed child incidents
=> [SIG-3266] keeps the changed incident children aligned with the rest

src/signals/settings/users/Overview/index.js
This PR fixes the height of the username filter in the Users page.
=> [Bug] fixes the height of the searchbar in the users page

src/signals/settings/categories/Overview/__tests__/Overview.test.js, src/signals/settings/categories/Overview/index.js
This PR makes a minor textual change in the categories page
=> [SIG-3296] Changes the SLA column text for the categoies

src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.js
This PR re-adds the split button.
=> Readds split button

src/signals/incident/definitions/wizard-step-2-vulaan/wonen.js
- also squashed some bugs in the holiday rental questions
=> [SIG-3199] Remove holiday rental question

jest.config.js
This PR pins the coverageThreshold to the correct values
=> (Chore) Updates the coverageThreshold

app.base.json
This PR makes a minor change in the municipality autorization text
=> [SIG-3271] Change in the municipality autorization text

e2e-tests/cypress/integration/createSignals/changeSignalBeforeSubmit.spec.js, e2e-tests/cypress/integration/createSignals/createSignalContainer.spec.js, e2e-tests/cypress/integration/createSignals/createSignalLantaarnpaal.spec.js, e2e-tests/cypress/integration/createSignals/createSignalVerkeerslicht.spec.js, e2e-tests/cypress/integration/createSignals/createSignalWonenVakantieVerhuur.spec.js, e2e-tests/cypress/integration/createSignals/createSignalWonenWoningOverig.spec.js, e2e-tests/cypress/integration/handleSignals/deelmeldingen.spec.js, e2e-tests/cypress/support/commandsCreateSignal.js, e2e-tests/cypress/support/selectorsCreateSignal.js
* Added tests to detect bug SIG-3373 
* Added tests for SIG-3271 (change text agreement)
* Added tests for SIG-3199 (delete question for wonen)
=> [SIG-3373] Cypress tests date bug

src/components/GPSButton/index.js, src/components/PreviousButton/index.js, src/components/TextArea/index.js, src/signals/incident/components/IncidentPreview/index.js, src/signals/incident/components/form/FileInput/index.js, src/signals/incident/definitions/wizard-step-5-samenvatting.js
This PR fixes some low hanging fruit highlighted by a WCAG Accessbility Audit plugin and an external WCAG audit
=> [SIG-3346] Improves WCAG compatibility 

src/signals/incident-management/containers/DefaultTextsAdmin/components/SelectForm/index.test.js, src/signals/incident-management/containers/FilterTagList/__tests__/FilterTagList.test.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js, src/signals/incident/containers/IncidentContainer/saga.test.js, src/signals/settings/categories/Detail/__tests__/Detail.test.js, src/signals/shared/filter/__tests__/parse.test.js, src/utils/__tests__/fixtures/categories_private.json, src/utils/__tests__/fixtures/category.json, src/utils/__tests__/fixtures/incident.json
This PR:
- Updates the category json mock test data. 
- Fixes the unit tests
- No application functionality is affected
=> (Chore) Updates the category fixture for the tests

src/signals/incident/components/form/PlainText/index.js
This PR removes the opacity prop from the PlainText
=> [SIG-3268] Removes opacity prop

jest.config.js, src/signals/incident-management/__tests__/selectors.test.js, src/signals/incident-management/selectors.js
This PR 
- Fixes the bug of the directing deparment save in the filter
- Improves the unit test coverage
- Updates the unittest tresholds
=> [SIG-3382] Fixes saving of the directing department in the filter

src/signals/incident/components/form/PlainText/index.js, src/signals/incident/components/form/PlainText/index.test.js, src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.js
This PR adds a new `alert-inverted` style to the PlainText component.
=> [SIG-3268] Adds a new `alert-inverted` style to the PlainText component

src/signals/incident/components/form/PlainText/index.js
This PR changes the font in the PlainText alert-inverted style from bold to regular
=> [SIG-3268] The PlainText alert-inverted style uses regular font

src/signals/incident/components/form/FileInput/styles.js
This PR changes the contrast of border color of the foto placeholder to meet the wcag standards
=> [SIG-3319] Change the border color of the foto

jest.config.js, src/signals/incident-management/containers/IncidentSplitContainer/IncidentSplitContainer.js, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitForm/__tests__/IncidentSplitForm.test.js, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitForm/index.js
This PR disables save and cancel buttons during splitsing
=> [SIG-3387] Disable save and cancel buttons during splitsing

jest.config.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.test.js
This PR hides the delen button also when the status is s
=> [SIG-3392] Hides the  'delen' button when the the split status is s

app.base.json, internals/schemas/app.schema.json, src/components/AmsterdamLogo/index.js, src/components/Logo/index.js
This PR provides the required aria and role attributes to the Logo that are required for the WCAG
=> [SIG-3301] Add the aria and role attributes required by WCAG to the Logo

src/signals/incident/components/form/ContainerSelect/ContainerSelect.js, src/signals/incident/components/form/ContainerSelect/ContainerSelect.test.js, src/signals/incident/components/form/ContainerSelect/Intro/Intro.js, src/signals/incident/components/form/ContainerSelect/Intro/Intro.test.js, src/signals/incident/components/form/ContainerSelect/Intro/index.js, src/signals/incident/components/form/ContainerSelect/Selector/Selector.js, src/signals/incident/components/form/ContainerSelect/Selector/Selector.test.js, src/signals/incident/components/form/ContainerSelect/Selector/index.js, src/signals/incident/components/form/ContainerSelect/Summary/Summary.js, src/signals/incident/components/form/ContainerSelect/Summary/Summary.test.js, src/signals/incident/components/form/ContainerSelect/Summary/index.js, src/signals/incident/components/form/ContainerSelect/context.js, src/signals/incident/components/form/ContainerSelect/index.js, src/signals/incident/components/form/ContainerSelectRenderer/ContainerSelectRenderer.js, src/signals/incident/components/form/ContainerSelectRenderer/ContainerSelectRenderer.test.js, src/signals/incident/components/form/ContainerSelectRenderer/index.js, src/signals/incident/components/form/index.js, src/signals/incident/definitions/__tests__/wizard-step-5-samenvatting.test.js, src/signals/incident/definitions/wizard-step-2-vulaan/afval.js, src/signals/incident/definitions/wizard-step-5-samenvatting.js
This PR
- adds the ContainerSelect base control for handling container related issues
- implements basic navigation between the 3 view modes of this control
=> [SIG-3276] Add the ContainerSelect base component

src/components/MapInput/index.js, src/signals/incident-management/containers/IncidentOverviewPage/components/OverviewMap/OverviewMap.js, src/signals/incident/components/form/ContainerSelect/ContainerSelect.js, src/signals/incident/components/form/ContainerSelect/Intro/Intro.js, src/signals/incident/components/form/ContainerSelect/Intro/Intro.test.js, src/signals/incident/definitions/wizard-step-5-samenvatting.js
This PR adds the map location in the ContainerSelect Intro component
=> [SIG-3332] Intro map

src/components/AutoSuggest/__tests__/AutoSuggest.test.js, src/components/AutoSuggest/index.js, src/components/GPSButton/index.js
This PR fixes the issues that a submit event was triggered in the map container for AutoSuggest and GPSButton
=> [SIG-3045] Prevent default submit in the map container

.gitignore, Makefile
This PR adds an improvement to the Makefile to facilitate the end-to-end tests
=> (Chore) Improve e2e test support in the makefile

src/signals/incident/definitions/__tests__/wizard-step-5-samenvatting.test.js, src/signals/incident/definitions/wizard-step-2-vulaan/afval.js, src/signals/incident/definitions/wizard-step-5-samenvatting.js
This PR fixes a bug where rendering the container preview resulted in a blank page
=> [SIG-3333] Fix container preview 

docs/additional-questions.md
Adds `ifOneOf` meta attribute to the docs on additional questions.
=> (Chore) Update additional questions docs with ifOneOf

docs/additional-questions.md, src/signals/incident/components/form/Header/index.js, src/signals/incident/components/form/Header/index.test.js, src/signals/incident/definitions/wizard-step-1-beschrijf.js, src/signals/incident/services/custom-validators/index.js, src/signals/incident/services/custom-validators/index.test.js
To improve user experience, this PR adds (1) more specific error messages, and (2) the possibility to add a custom error message for the required validator.
=> [SIG-3309] more specific error messages

src/signals/incident-management/components/RadioButtonList/index.js, src/signals/incident/containers/KtoContainer/components/KtoForm/index.js
- On the Kto form, adds red border to radio buttons when required question is not answered
=> [SIG-3427] Adds red border to error state of radio buttons on Kto form

e2e-tests/cypress/fixtures/addresses/fietsNietje.json, e2e-tests/cypress/fixtures/predictions/fietsNietje.json, e2e-tests/cypress/fixtures/signals/afval.json, e2e-tests/cypress/fixtures/signals/fietsNietje.json, e2e-tests/cypress/integration/createSignals/createSignalFietsNietje.js, e2e-tests/cypress/integration/handleSignals/deelmeldingen.spec.js, e2e-tests/cypress/support/selectorsCreateSignal.js
* Test scenario for signal in category 'Fietsnietje'
* Deleted some testdata in afval.sjon
* Small fix in deelmeldingen test
=> [SIG-2369] Cypress tests fietsnietje

src/containers/App/saga.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-bedrijven-en-horeca.js
- Bug where filling in additional quests for bedrijven-en-horeca questions trigger a grey screen
=> [SIG-3476] Fix additional questions for bedrijven-en-horeca triggering grey screen

src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.js
- Removes christmas-specific notification from additional questions
=> [SIG-3440] Removes christmas-specific notification

src/signals/incident/components/form/ContainerSelect/Selector/Selector.tsx, src/signals/incident/components/form/ContainerSelect/WfsLayer/WfsLayer.test.tsx, src/signals/incident/components/form/ContainerSelect/WfsLayer/WfsLayer.tsx, src/signals/incident/components/form/ContainerSelect/types.ts
- Refactors wfs-layer
Some props for the WfsLayer were computed based on a dependency it itself uses as well. I moved that part to the WfsLayer itself.
=> (Chore) Refactor wfs layer

jest.config.js, src/signals/incident/components/form/ContainerSelect/ContainerSelect.test.tsx, src/signals/incident/components/form/ContainerSelect/ContainerSelect.tsx, src/signals/incident/components/form/ContainerSelect/ContainerSelectContext.tsx, src/signals/incident/components/form/ContainerSelect/Intro/Intro.test.js, src/signals/incident/components/form/ContainerSelect/Selector/Selector.test.tsx, src/signals/incident/components/form/ContainerSelect/Selector/Selector.tsx, src/signals/incident/components/form/ContainerSelect/types.ts, src/signals/incident/components/form/ContainerSelectRenderer/ContainerSelectRenderer.test.js, src/types/incident.ts
This PR converts the last Component of the ContainerSelect to typescript
=> (Chore) Converts the ContainerSelect to ts

jest.config.js, src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js
This PR replaces an unnecessary saga call with a synchronous normal function call.
=> (Chore) Fix call in saga

src/signals/incident/definitions/wizard-step-2-vulaan/afval.ts
- Makes container selection an optional field
=> [SIG-3421] Container selection optional

src/signals/incident/components/IncidentPreview/index.js
- Fix edit link position on the summary page (Mac only)
=> [SIG-3493] Fix edit link position in summary for mac users

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/__tests__/StatusForm.test.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/constants.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js
- Improves info message visibility when closing incident with open split incident(s)
=> [SIG-3433] Improve message visibility

src/signals/incident/components/form/ContainerSelect/Selector/SelectionPanel/SelectionPanel.tsx, src/signals/incident/components/form/ContainerSelect/Selector/SelectionPanel/__tests__/SelectionPanel.test.tsx
=> (Chore) Fixes optional text casing

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/constants.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js
- Changes text shown when closing child incident of split incident
=> Changes text when closing split incident

docs/adr/0010-naming-conventions.md, docs/adr/README.md
This PR consolidates the proposals from #1291
=> (Chore) Naming conventions ADR

jest.config.js, src/signals/incident/components/form/ContainerSelect/Selector/LegendToggleButton/LegendToggleButton.tsx, src/signals/incident/components/form/ContainerSelect/Selector/LegendToggleButton/__tests__/LegendToggleButton.test.tsx
- Always show "Legenda" text on legend panel button
=> [SIG-3540] Remove legend button icon

src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/index.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/index.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/types.ts
- Fix rendering incident data for answers with multiple checkbox inputs
=> [SIG-3551] Fix rendering incident data for answers with multiple checkbox inputs

Dockerfile
- Fix Docker build (missing types file)
=> (Chore) Fix Docker build

e2e-tests/cypress.json, e2e-tests/cypress/integration/createSignals/createSignalContainerOnMap.spec.ts, e2e-tests/cypress/integration/manageSettings/manageDepartments.spec.ts, e2e-tests/cypress/plugins/index.js
* Cypress tests SIG-3483
* Added ignoreTestFiles to cypress.json to ignore local tests
* Removed ignoreTestFiles from plugins.js because it didn't work
* Some small changes
=> [SIG-3483] Cypress tests for SIG-3483

src/signals/incident/components/IncidentForm/index.js, src/signals/incident/components/IncidentPreview/components/Map/index.js, src/signals/incident/components/IncidentPreview/index.js, src/signals/incident/components/form/FileInput/styles.js
Fix horizontal scrolling on 320px width:
- Image upload placeholders
- Map preview of location
- Long words in form and preview
Before
After
Before
After
Before
After
Before
After
=> [FE#109] [SIG-3318] Horizontal scroll

src/components/FormFooter/index.js, src/signals/settings/roles/containers/RoleFormContainer/components/RoleForm/index.js
- Fixes checkbox showing on top of form footer
I made a change in the checkbox component earlier, and forgot to check this specific form.
=> (Chore) Fixes checkbox showing on top of form footer

src/signals/incident/components/form/FileInput/styles.js
This PR changes the size of the file upload placeholder so that it fits on all devices
=> (Chore) Fixe the image upload size

e2e-tests/cypress/integration/createSignals/createSignalAfval.spec.ts, e2e-tests/cypress/integration/createSignals/createSignalContainerOnMap.spec.ts, e2e-tests/cypress/support/commandsCreateSignal.ts, e2e-tests/cypress/support/selectorsCreateSignal.ts
* Use button on thanks page to create another signal
* Increased wait time for zoom function in container scenario
=> [SIG-3564] Cypress tests create signal with button on thanks page

src/signals/incident/components/form/TextInput/index.js, src/signals/incident/definitions/wizard-step-3-telefoon.js, src/signals/incident/definitions/wizard-step-4-email.js
- Adds autofill to email and telephone input in incident form
=> [SIG-3317] Adds autofill to email and telephone input elements

src/components/GPSButton/index.js, src/components/Map/Map.js, src/components/MapInput/index.js
- Improve tabbing order of form elements in incident form
- Prevent location marker from being focusable
- Add focus outline to GPS button
=> [SIG-3312] tab focus order

src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.js
- Fixes console error for invalid color property
=> (Chore) Fixes console error for invalid color prop

src/signals/incident/definitions/__tests__/wizard-step-5-samenvatting.test.js, src/signals/incident/definitions/wizard-step-5-samenvatting.js
- Fall back to shortlabel in incident summary when using hardcoded addiational questions
=> [SIG-3600] Adds fallback to shortlablel in incident summary

src/signals/incident/components/form/FileInput/styles.js
- Match focus outline of file input with other input elements
Based on feedback by our designer.
=> (Chore) Change focus outline of file input to match other inputs

src/components/Input/index.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident/components/form/DescriptionInput/DescriptionInput.js, src/signals/incident/components/form/MultiTextInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/MultiTextInput/index.js, src/signals/incident/components/form/TextInput/index.js, src/signals/incident/components/form/TextareaInput/index.tsx
This PR improves accessibility for the TextInput and MultiTextInput controls.
=> [SIG-3443] Improve accessibility for textinput

src/signals/incident/components/IncidentForm/index.js, src/signals/incident/components/form/RadioInputGroup/RadioInputGroup.js
- Fixes radio button margin
- Fixes summary styling (was not applied properly)
=> [SIG-3445] radio button styling

e2e-tests/cypress/support/selectorsCreateSignal.ts
* Changed selector for input field
=> [SIG-3618] Cypress small fix

src/signals/incident/containers/KtoContainer/components/KtoForm/index.js
This PR fixes the alignment of the checkbox in the kto form
=> (Chore) Fix the checkbox alignment in kto form

src/containers/App/saga.test.ts, src/containers/App/saga.ts
=> [FE#121] Add is_active to sources endpoint url

src/shared/types/index.js, src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/components/FilterForm/reducer.js, src/signals/incident-management/components/RadioButtonList/index.js, src/signals/incident-management/definitions/index.js, src/signals/incident-management/definitions/punctualityList.ts
- Adds a filter for punctuality to the incident management view
=> [SIG-3566] - Add filter for punctuality

src/signals/incident/components/form/DateTimeInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/DateTimeInput/index.js
This PR links the description of the hour and minute to the select lists. It also removes the link from the Time label to the hours select control
=> [SIG-3446] Improve a11y for the DateTimeInput control

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/signals/incident/components/form/MapInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/MapInput/index.js
=> Add aria label to map

e2e-tests/cypress/fixtures/questions/questions.json, e2e-tests/cypress/integration/createSignals/createSignalKlokOnMap.spec.ts, e2e-tests/cypress/integration/createSignals/createSignalLantaarnpaal.spec.ts, e2e-tests/cypress/support/questions.d.ts, e2e-tests/cypress/support/selectorsCreateSignal.ts, src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.ts
This PR removes one extra question for the `klok` and one for the `straatverlichting` subcategory
=> [SIG-3517] Removes one klok and one straatverlichting questions

e2e-tests/cypress/integration/handleSignals/signalsOverviewMap.spec.ts
=> [SIG-3646] Cypress test small fix

src/components/AutoSuggest/index.js, src/components/MapInput/index.js
This PR set the aria-label for the MapInput on the autosuggest input element for a11y.
=> [SIG-3302] Set aria-label on the autosuggest input

src/app.js
Reverts Amsterdam/signals-frontend#1472
=> Revert "(Chore) Trigger reloading of the ServiceWorker on new release"

src/signals/incident/components/form/RadioInput/index.js
- Fixes text wrapping on Safari for radio button labels
=> [SIG-] Fixes text wrapping for radio button labels

e2e-tests/cypress.env.json, e2e-tests/cypress/integration/_localRun/ktoNotSatisfied.spec.ts, e2e-tests/cypress/integration/_localRun/ktoSatisfied.spec.ts, e2e-tests/cypress/support/commandsGeneral.ts, e2e-tests/cypress/support/commandsRequests.ts, e2e-tests/cypress/support/selectorsKTO.ts, e2e-tests/cypress/support/texts.ts
* Cypress tests KTO form
* Tests only run in local environment with mailhog and Celery running in backend
=> [SIG-2355] Cypress tests KTO form

src/signals/incident/definitions/wizard-step-2-vulaan/afval.ts
This PR fixes the url call to the wfs containers
=> [Bug] Fix the containers wfs call

src/signals/incident/components/form/ContainerSelect/Selector/WfsLayer/WfsLayer.tsx, src/signals/incident/components/form/ContainerSelect/Selector/WfsLayer/__tests__/WfsLayer.test.tsx, src/signals/incident/components/form/ContainerSelect/context.tsx, src/signals/incident/components/form/ContainerSelect/types.ts, src/signals/incident/definitions/wizard-step-2-vulaan/afval.ts
- Allow additional filter configuration for WFS requests
=> [SIG-3632] Allow additional filters for wfs requests

src/signals/settings/categories/Detail/components/CategoryForm/CategoryForm.tsx
- Fixes not being able to change category afhandeltermijn (werk)dagen
=> [SIG-3655] Fix not being able to change category afhandeltermijn (werk)dagen

src/components/ErrorMessage/ErrorMessage.tsx, src/signals/incident/components/form/GlobalError/GlobalError.js, src/signals/incident/components/form/Header/Header.tsx
- Adds error role as html attribute to error messages (improves A11Y)
=> [SIG-3652] Adds error role to error messages for A11Y

e2e-tests/package-lock.json, e2e-tests/package.json
=> (Chore) Update SSRI

e2e-tests/cypress/fixtures/questions/questions.json, e2e-tests/cypress/fixtures/signals/jongeren.json, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-van-en-door-personen-of-groepen.ts
- Changes additional question text
=> [SIG-3599] Change additional question text

src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.js
=> Make the incident list horizontally scrollable

src/signals/incident/definitions/wizard-step-2-vulaan.js, src/signals/incident/definitions/wizard-step-2-vulaan/civieleConstructies.ts, src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.ts
- Fixes bug where question was not shown
=> [SIG-3666] Moves bruggen subcategory question to correct category

docker-compose.yml
Resolves a TS error caused by a type being dependent on `app.amsterdam.json`
=> (Chore) Fixes running local source with docker-compose

src/components/Modal/index.js
This PR fixes the styling of the FilterForm dialog after updating `asc`
=> (Chore) Fix the modal filter form display

src/signals/incident/components/form/ContainerSelect/Selector/WfsLayer/ContainerLayer/ContainerLayer.tsx
- Improves readability of alt attributes for containers
=> (Chore) Improves alt attribute for container icons

e2e-tests/cypress/integration/createSignals/createSignalChangeSubcategory.spec.ts, e2e-tests/cypress/integration/manageSettings/manageCategories.spec.ts, e2e-tests/cypress/integration/manageSettings/manageDepartments.spec.ts, src/components/SiteHeader/__tests__/SiteHeader.test.js, src/components/SiteHeader/index.js, src/signals/settings/categories/Detail/__tests__/Detail.test.js, src/signals/settings/categories/Detail/index.js, src/signals/settings/categories/Overview/__tests__/Overview.test.js, src/signals/settings/categories/Overview/index.js, src/signals/settings/departments/Overview/index.js
This PR renames the Category to subcategory throughout the application
=> [SIG-3553] Change category to subcategory

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/signals/incident-management/__tests__/index.test.js, src/signals/incident-management/containers/ReporterContextContainer/ReporterContextContainer.tsx, src/signals/incident-management/containers/ReporterContextContainer/__tests__/ReporterContextContainer.test.tsx, src/signals/incident-management/containers/ReporterContextContainer/index.ts, src/signals/incident-management/index.js, src/signals/incident-management/routes.js
- Adds featureFlag `enableReporterContext`
- Adds empty router for reporter context
=> [SIG-3673] Empty reporter context page & feature flag

src/__tests__/checkStore.test.ts, src/containers/App/actions.ts, src/containers/App/reducer.test.ts, src/containers/App/reducer.ts, src/containers/App/saga.test.ts, src/containers/App/saga.ts, src/containers/App/selectors.ts, src/containers/App/services.test.ts, src/containers/App/services.ts, src/containers/App/types.ts, src/types/index.ts, src/utils/__tests__/injectSaga.test.tsx, src/utils/__tests__/injectSagaModel.test.ts, src/utils/__tests__/reducerInjectors.test.ts, src/utils/__tests__/request.test.ts, src/utils/__tests__/sagaInjectors.test.ts, src/utils/checkStore.ts, src/utils/index.ts, src/utils/injectReducerModel.ts, src/utils/injectSaga.tsx, src/utils/injectSagaModel.ts, src/utils/maxSelection.ts, src/utils/reducerInjectors.ts, src/utils/request.ts, src/utils/sagaInjectors.ts
Ran prettier with automated fix: `npx prettier --write .`
=> (Chore) Prettier fix on all source files

e2e-tests/cypress/fixtures/addresses/brug.json, e2e-tests/cypress/fixtures/predictions/brug.json, e2e-tests/cypress/fixtures/signals/brug.json, e2e-tests/cypress/integration/createSignals/createSignalBrug.spec.ts, e2e-tests/cypress/integration/manageSettings/manageCategories.spec.ts, e2e-tests/cypress/support/commandsCreateSignal.ts, e2e-tests/cypress/support/selectorsCreateSignal.ts, e2e-tests/cypress/support/selectorsSettings.ts, e2e-tests/package.json
* Scenario signal category bridge
* Update cypress to 7.2.0
* Small change to stabilize manage categories tests
=> [SIG-3714] Cypress tests create signal bridge

src/signals/incident-management/containers/ReporterContainer/ReporterContainer.tsx, src/signals/incident-management/containers/ReporterContainer/components/FeedbackStatus.tsx, src/signals/incident-management/containers/ReporterContainer/components/IncidentListItem.tsx
- Fixes grey border color
- Change to bold font in feedback status text
- Change to correct bold font for incident id/category
- Prevent category text from wrapping (use ellipsis)
- Prevent incident creation date from moving to newline
=> [SIG-3730] Reporter components styling

src/signals/incident/definitions/wizard-step-5-samenvatting.js
- Show civiele-constructies answers in summary page for hardcoded questions
=> [SIG-3731] Show civiele-constructies answers in summary page for hardcoded questions

src/containers/App/reducer.test.ts, src/containers/App/reducer.ts, src/containers/App/saga.ts, src/containers/App/selectors.test.ts, src/containers/App/selectors.ts, src/utils/index.ts, src/utils/injectReducer.tsx, src/utils/injectSaga.tsx, src/utils/maxSelection.ts, src/utils/request.ts
- Fixes bug where user was redirected after refreshing on a settings page (e.g. users page)
=> [SIG-3719] Fix redirect before fetching permissions on settings pages

jest.config.js, src/signals/incident-management/containers/ReporterContainer/ReporterContainer.tsx, src/signals/incident-management/containers/ReporterContainer/__tests__/ReporterContainer.test.tsx, src/signals/incident-management/containers/ReporterContainer/__tests__/useFetchReporter.test.ts, src/signals/incident-management/containers/ReporterContainer/useFetchReporter.ts, src/types/api/reporter.ts
Adds pagination to the incident list from the same reporter
=> [SIG-3688] samenhang pagination

src/components/ChildIncidentDescription/ChildIncidentDescription.tsx, src/components/ChildIncidentDescription/__tests__/ChildIncidentDescription.test.tsx, src/components/ChildIncidentDescription/index.ts, src/components/ChildIncidents/ChildIncidents.js, src/signals/incident-management/containers/IncidentDetail/IncidentDetail.js, src/signals/incident-management/containers/IncidentDetail/__tests__/IncidentDetail.test.js, src/signals/incident-management/containers/IncidentDetail/__tests__/reducer.test.js, src/signals/incident-management/containers/IncidentDetail/actions.ts, src/signals/incident-management/containers/IncidentDetail/components/ChildIncidents/__tests__/ChildIncidents.test.js, src/signals/incident-management/containers/IncidentDetail/components/ChildIncidents/index.js, src/signals/incident-management/containers/IncidentDetail/constants.js, src/signals/incident-management/containers/IncidentDetail/reducer.ts, src/signals/incident-management/containers/IncidentDetail/types.ts
- Adds split incident text to list in parent incident view
=> [SIG-3686] Adds split incident text to list in parent incident view

src/signals/incident-management/containers/ReporterContainer/components/IncidentDetail.tsx, src/signals/incident-management/containers/ReporterContainer/components/__tests__/IncidentDetail.test.tsx
Align grid
Change copy
Open link in new tab
=> [SIG-3748] design, copy & UX fixes

src/signals/settings/components/Overview/components/Overview.tsx
Sets the correct font and line height for the settings overview page
=> (Chore) Fix styling for the settings page

app.amsterdam.json, src/components/MapSelect/index.js, src/components/MapSelect/index.test.js
Double curly brackets are not allowed
=> [SIG-3744] Fix uri-template formatting

src/components/MapInput/index.js, src/signals/incident/components/form/MapInput/touchGestureMessage.ts
- Change gesture handling text to be displayed in the center of the screen
=> [SIG-2564] Center map text

src/signals/incident-management/containers/IncidentDetail/IncidentDetail.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Area/Area.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Area/__tests__/Area.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Area/index.ts, src/signals/incident-management/containers/IncidentDetail/components/Detail/index.js
Adds area link to the incident detail page
=> [SIG-3781] Add area link to incident detail page

.github/workflows/ci.yml, package.json, src/components/ChildIncidents/ChildIncidents.js, src/components/MapInput/__tests__/MapInput.test.js, src/components/Select/Select.test.js, src/signals/incident-management/containers/IncidentSplitContainer/IncidentSplitContainer.test.js, src/signals/incident/components/IncidentWizard/index.test.js, src/signals/incident/components/form/MapSelect/iconMapping.test.js, src/signals/incident/components/form/MapSelect/index.test.js, src/signals/settings/components/Overview/components/Overview.tsx
There's still a lot to do - let's try to make the log clean again!
=> (Chore) Fixes unit test warnings

src/containers/App/selectors.ts, src/signals/settings/index.js
Makes `/settings` no longer a protected route
=> [Bug] remove settings from protected routes

src/components/AreaMap/AreaMap.tsx, src/shared/services/configuration/map-markers.ts
- Adds incident area center focus circle
=> [SIG-3785] Adds incident area center focus circle

e2e-tests/cypress/integration/createSignals/createSignalBrug.spec.ts, e2e-tests/cypress/integration/manageSettings/manageRoles.spec.ts, e2e-tests/cypress/support/commandsRouting.ts, e2e-tests/cypress/support/selectorsSettings.ts, e2e-tests/package-lock.json, e2e-tests/package.json
- Test sceneario's manage roles
- Update Cypress to 7.5.0
=> [SIG-3140] Cypress tests manage roles

src/components/SiteHeader/__tests__/SiteHeader.test.js, src/components/SiteHeader/index.js
- Changes header button text from _afhandelen_ to _overzicht_
=> Changes header button text to Overzicht

src/signals/incident-management/containers/IncidentDetail/components/Detail/index.js
- Also show link with '0 meldingen in de omgeving'
=> (Chore) Always show area link

src/signals/incident/components/form/FileInput/index.js
Adds `role="alert"` to error message for file input
=> [SIG-3809] Adds role alert to file input component

package-lock.json
Generate new lockfile with npm v7
=> (Chore) use npm 7 for lockfile generation

src/signals/incident-management/containers/IncidentDetail/components/Detail/index.js
Create a link for the phone number on the incident detail page
=> [SIG-3821] Create tel link on incident detail page

e2e-tests/cypress.json, e2e-tests/cypress/integration/handleSignals/sameArea.spec.ts, e2e-tests/cypress/support/commandsRequests.ts
=> [SIG-3862] Cypress tests area 50m fix

e2e-tests/cypress/integration/createSignals/createSignalChangeSubcategory.spec.ts, e2e-tests/cypress/integration/handleSignals/signalsOverviewMap.spec.ts, e2e-tests/cypress/integration/manageSettings/manageDepartments.spec.ts, e2e-tests/cypress/integration/manageSettings/manageUsers.spec.ts, e2e-tests/package-lock.json, e2e-tests/package.json
- Small fixes flakiness
- Cypress version 7.6.0
=> Cypress tests small fixes flakiness

app.amsterdam.json, e2e-tests/cypress/support/commandsCreateSignal.ts
Changes copy in the config file
=> [SIG-3700] Change consentToSharing copy

src/signals/incident-management/containers/AreaContainer/__tests__/AreaContainer.test.tsx
Add missing unit tests for AreaContainer component
=> (Chore) Add unit tests for AreaContainer

e2e-tests/cypress/fixtures/addresses/eikenprocessierups.json, e2e-tests/cypress/fixtures/eikenprocessierups/treeData01.json, e2e-tests/cypress/fixtures/eikenprocessierups/treeData02.json, e2e-tests/cypress/fixtures/predictions/containerNotOnMap.json, e2e-tests/cypress/fixtures/predictions/containerOnMap.json, e2e-tests/cypress/fixtures/predictions/eikenprocessierups.json, e2e-tests/cypress/fixtures/signals/eikenprocessierups.json, e2e-tests/cypress/integration/createSignals/createSignalContainerNotOnMap.spec.ts, e2e-tests/cypress/integration/createSignals/createSignalContainerOnMap.spec.ts, e2e-tests/cypress/integration/createSignals/createSignalEikenprocessierups.spec.ts, e2e-tests/cypress/integration/handleSignals/signalsOverviewMap.spec.ts, e2e-tests/cypress/support/selectorsCreateSignal.ts, e2e-tests/package-lock.json, e2e-tests/package.json
* Cypress tests eikenprocessierups
* Small changes in container tests
* Updated cypress version to 7.7.0
* Skipped flaky test
=> [SIG-3879] Cypress tests eikenprocessierups

publiccode.yml
=> (Chore) Updates publiccode short and long descriptions

publiccode.yml
=> Use correct repo URL in publiccode.yml

publiccode.yml
=> Add English to publiccode.yml

internals/testing/msw-server.ts, src/signals/incident/containers/IncidentReplyContainer/IncidentReplyContainer.tsx, src/signals/incident/containers/IncidentReplyContainer/__tests__/IncidentReplyContainer.test.tsx, src/signals/incident/containers/IncidentReplyContainer/constants.ts
Incident reply form:
- Change incident reply form error message text
- When form is not accessible due to incident status change, show above message
=> [SIG-3973] Message when incident reply form is no longer accessible

.github/workflows/ci.yml, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.js
=> [SIG-3914] Align high urgency icon

src/components/AreaMap/__tests__/AreaMap.test.tsx, src/components/OverviewMap/DetailPanel/DetailPanel.tsx, src/components/OverviewMap/types.ts, src/hooks/api/useBuildGetter.ts, src/shared/services/list-helpers/list-helpers.ts, src/signals/incident-management/containers/AreaContainer/__tests__/AreaContainer.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/MetaList/__tests__/MetaList.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/__tests__/StatusForm.test.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/actions.ts, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/reducer.ts, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/utils.ts, src/signals/incident-management/containers/IncidentDetail/types.ts, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.test.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/List/styles.ts, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.test.js, src/signals/incident-management/context.ts, src/signals/incident-management/definitions/priorityList.tsx, src/signals/incident-management/definitions/statusList.ts, src/signals/incident-management/definitions/types.ts, src/types/api/default-text.ts, src/types/api/geography.ts, src/types/api/incident-list.ts, src/types/api/incident.mock.ts, src/utils/__tests__/fixtures/incidents.json
- Refactors incident overview list to TypeScript
=> [SIG-3984] Incident overview TypeScript

internals/mocks/fixtures/report_signals-open.json, internals/mocks/fixtures/report_signals-reopen-requested.json, internals/testing/msw-server.ts, src/signals/incident-management/containers/Signaling/Signaling.tsx, src/signals/incident-management/containers/Signaling/__tests__/Signaling.test.tsx
Changes signaling page header text
=> [SIG-3970] Signaling header text change

src/hooks/api/__tests__/useGetReportOpen.test.ts, src/hooks/api/useGetReportOpen.ts, src/signals/incident-management/containers/Signaling/Signaling.tsx, src/signals/incident-management/containers/Signaling/__tests__/Signaling.test.tsx
This PR changes signaling column header texts.
=> Changes header texts

.gitignore, Makefile
This PR adds the `release` command to the Makefile. Note that it depends on the presence of both the files `.githubtoken` and `.jiratoken`.
=> (Chore) Makefile release command

e2e-tests/cypress/support/texts.ts, src/signals/incident-management/containers/Signaling/Signaling.tsx
- Titles on the signaling graph page are updated
=> [SIG-4016] Changes signaling graph title texts

package.json
Turned out that I used the wrong projecten in the proj4 compilation call. This PR corrects that.
=> (Chore) Fix proj4 compile

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/components/FooterContainer/__tests__/FooterContainer.test.tsx, src/components/FooterContainer/index.tsx, src/containers/App/index.tsx
Ik heb twee links aan de footer-bottom toegevoegd: 'over deze site' en 'toegankelijkheid'.
De footer heb ik zo veel mogelijk gebaseerd op de bestaande amsterdam-styled-component.
De footer top wijkt teveel af en daarom heb ik die gelaten zoals ie was.
=> New footer links - SIG 3519

src/components/pages/ArticlePage/Toegankelijkheidsverklaring.tsx
=> [SIG-4105] Fix links toegankelijkheidspagina

src/signals/incident-management/containers/IncidentOverviewPage/components/SubNav/SubNav.test.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/SubNav/SubNav.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/SubNav/index.ts, src/signals/incident-management/containers/IncidentOverviewPage/components/SubNav/styled.tsx
This PR:
- converts the `SubNav` component from JS to TS
- removes unnecessary wrapping elements from the component
=> [SIG-4028] Convert SubNav component to TS

src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.test.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/List/styles.ts, src/signals/incident-management/containers/IncidentOverviewPage/components/Sort/Sort.test.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/Sort/Sort.tsx, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/containers/IncidentOverviewPage/styled.tsx
This PR replaces the table header sorting options with the Sort component
=> [SIG-4116] Replace incident overview table header

package-lock.json, package.json, src/signals/incident-management/containers/IncidentOverviewPage/components/Sort/Sort.tsx
Adds the `@datapunt/matomo-tracker-react` package and tracks clicks on the `Sort` component
=> [SIG-4117] Matomo tracking

src/containers/App/index.tsx
Footer is back at the bottom in login screen.
=> [SIG-4123] Fix footer position in login screen

src/signals/incident-management/containers/IncidentOverviewPage/components/Sort/Sort.tsx
This PR fixes the alignment and font size of elements in the Sort component.
=> [SIG-3918] Sort alignment

src/app.js, src/containers/App/index.tsx
This PR sets up Matomo correctly for tracking links and events
=> [SIG-4117] Matomo setup

src/signals/incident/components/form/FormField/FormField.tsx, src/signals/incident/components/form/TextInput/TextInput.tsx, src/signals/incident/definitions/wizard-step-3-contact.js, src/types/reactive-form.ts
This PR contains a change that allows setting a custom width for a field in the incident form.
=> [SIG-4157] Form field width

app.amsterdam.json
Corrects the formatting of the municipality's phone number. Also see https://github.com/Amsterdam/signalen/pull/113
=> [SIG-4164] Correct phone number

app.amsterdam.json, src/signals/incident/definitions/wizard-step-3-contact.js
Changes both header and radio button label
=> [SIG-4184] Contact sharing text change

src/signals/incident-management/containers/IncidentDetail/components/ChangeValue/index.js, src/signals/incident-management/containers/IncidentOverviewPage/components/List/styles.ts
- high priority styling in detail view
- priority icon in list view
=> [SIG 4217] priority styling

src/signals/incident/components/IncidentPreview/index.js, src/signals/incident/components/IncidentPreview/index.test.js, src/signals/incident/definitions/wizard-step-4-summary.js
Removes columns, adds margins and section counters.
=> [SIG-4091] Restructure summary page

src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.ts
=> [SIG-4263] Label changes

src/signals/incident/components/form/MapSelectors/Asset/Selector/SelectionPanel/SelectionPanel.test.tsx, src/signals/incident/definitions/wizard-step-2-vulaan/afval.ts, src/signals/incident/definitions/wizard-step-2-vulaan/openbaarGroenEnWater.ts, src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.ts
Changes the call to action label for objects
=> [SIG-4264] CTA changes

src/signals/incident-management/containers/IncidentDetail/components/Detail/index.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/index.test.js
checks if phone number value of melding reporter has astrix.
If so, value is rendered in a link.
If not, value is rendered as text.
=> [SIG 4209] Only show link when phone number is visible

src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/ReportedLayer/style.css
=> [SIG 4198] Move reported icon to the right

package-lock.json, package.json
=> (Chore) Removes unused shelljs dep

src/signals/incident/containers/IncidentReplyContainer/components/FileInput/FileInput.tsx
Applies upload limit to incident reply container
=> (Chore) Apply 20MB file upload

src/signals/incident/definitions/__tests__/wizard-step-2-vulaan.test.js, src/signals/incident/definitions/wizard-step-2-vulaan.js
=> [SIG-4335] Removes block from step 2

src/signals/incident/components/IncidentWizard/index.js
=> Fix: Page title in new form (H1) should be bold

package-lock.json, package.json, src/signals/incident/components/IncidentWizard/index.js
Upgrades `@amsterdam/asc-ui` to latest (canary) version and changes the breakpoints at which the form should transition from large to small screen presentation.
=> [SIG-4096] New asc-ui version with updated StepByStepNav component

package-lock.json, src/signals/incident/components/IncidentWizard/index.js
References a stable release version of `@amsterdam/asc-ui`. In addition, sets a different breakpoint for the transition of the page and the step-by-step nav
=> Reference stable asc-ui release

src/components/FileInput/FileInput.tsx, src/components/TextArea/TextArea.test.tsx, src/components/TextArea/TextArea.tsx, src/signals/incident/components/form/FormField/FormField.tsx, src/signals/incident/components/form/FormField/index.test.tsx, src/signals/incident/containers/KtoContainer/components/KtoForm/index.js
- File input
- Text area
- Form field
- error in KTO form
=> Wrap error messages in div with role status

src/components/ViewerContainer/ViewerContainer.tsx
This PR fixes an issue where the page could not be scrolled anymore. This happens in step 2 of the incident form.
=> [SIG-4365] Fix page scroll

src/components/AddNote/AddNote.tsx, src/signals/incident/components/form/TextareaInput/AddNote.test.tsx, src/signals/incident/components/form/TextareaInput/AddNote.tsx, src/signals/incident/components/form/TextareaInput/TextareaInput.test.tsx, src/signals/incident/components/form/TextareaInput/TextareaInput.tsx, src/signals/incident/components/form/TextareaInput/index.tsx
This PR replaces the Textarea component in the `TextareaInput` with the more generic `AddNote` component.
=> [SIG-4082] TextareaInput => AddNote

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/__tests__/StatusForm.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/styled.tsx
NB: this PR branches from  SIG 4303.
=> [SIG 4363] Change status with select instead of radiobuttons in status form

src/signals/incident/components/form/MapSelectors/Asset/Selector/styled.tsx
Fixes an issue where the map zoom message appeared above the PDOK auto suggest drop down.
=> (Chore) Fix z-index

package-lock.json, package.json
Removes the `@pmmmwh/react-refresh-webpack-plugin` dep which wasn't used, but had a security issue.
=> (Chore) Remove unused dep

package-lock.json, package.json, src/components/SiteHeader/SiteHeader.test.js, src/components/SiteHeader/index.js
Replaces the `react-media` dependency with `react-responsive`.
See #2042 for reference
=> (Chore) Replace react media

src/signals/incident/components/form/MapSelectors/Asset/AssetSelect.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Intro/Intro.tsx
Changes the call-to-action of the map button to clarify its purpose
=> [SIG-4371] Map CTA

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/DefaultTexts/DefaultTexts.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/DefaultTexts/styled.ts, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/ModalHeader/ModalHeader.tsx
Fixes alignment and margins for elements in the default texts modal
=> [SIG-4461] Default texts modal UI fixes

src/signals/incident/components/form/HandlingMessage/HandlingMessage.test.tsx, src/signals/incident/components/form/HandlingMessage/HandlingMessage.tsx, src/signals/incident/definitions/wizard-step-5-bedankt.js
- Text addition to thank you page
- Decrease font size of component below to make it similar to Plain text component
=> [SIG 4377] Improve thank you page

src/signals/incident/components/IncidentPreview/IncidentPreview.test.tsx, src/signals/incident/components/IncidentPreview/IncidentPreview.tsx, src/signals/incident/components/form/DateTimeInput/DateTime.test.tsx, src/signals/incident/components/form/DateTimeInput/DateTime.tsx, src/signals/incident/components/form/DateTimeInput/DateTimeInput.test.tsx, src/signals/incident/components/form/DateTimeInput/DateTimeInput.tsx, src/signals/incident/containers/IncidentContainer/reducer.js, src/signals/incident/containers/IncidentContainer/reducer.test.js, src/signals/incident/definitions/__tests__/wizard-step-4-summary.test.js, src/signals/incident/definitions/wizard-step-2-vulaan/dateTime.ts, src/signals/incident/definitions/wizard-step-4-summary.js, src/signals/incident/services/custom-validators/custom-validators.test.ts, src/signals/incident/services/custom-validators/custom-validators.ts
Proposed changes will allow for the `DateTime` form component to be unselected as well as be a required element (as per the design).
=> [SIG-4294] Datetime question required

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/styled.tsx
Ensures spacing between notification element in the status form
=> [SIG-4462] Status form alert spacing

src/components/Map/Map.tsx
This PR will fix the zoom controls not being visible in the incident detail map
=> [SIG-4494] Zoom controls visibility fix

src/signals/settings/categories/Detail/components/CategoryForm/CategoryForm.tsx
=> [SIG 4403] Checked label never bold in category form

src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts
Changed the order of the answer options both for streetlights and clocks.
=> [SIG-4449] Not dangerous on top in streetlight answers

src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/index.ts, src/signals/incident/components/form/MapSelectors/Asset/Selector/NearbyLayer/NearbyLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/NearbyLayer/NearbyLayer.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/NearbyLayer/style.css
- Increased z-index of selected nearby marker
- Added SPDX-License identifiers
=> [SIG-4375] Selected nearby marker on top

src/signals/incident-management/components/Status/Status.tsx, src/signals/incident-management/containers/IncidentDetail/components/ChildIncidents/index.js
=> [SIG 4551] Bold style child incident title and status

src/signals/incident/containers/KtoContainer/index.js
https://datapunt.atlassian.net/browse/SIG-4530?atlOrigin=eyJpIjoiZmIzNzI2MTQ3MjAyNDRiMWIxMWViMjJlZjljNDY1MWYiLCJwIjoiaiJ9
=> [SIG 4530] Fix duplicate id error Fix duplicate id error and a broken.

src/app.js, src/global.css, src/index.html
https://datapunt.atlassian.net/browse/SIG-4547?atlOrigin=eyJpIjoiNmViYzIwMTc2OGRjNDNmYThjOGQ3Zjk3ODgwNDRjNjciLCJwIjoiaiJ9
=> [SIG 4547] Add spinner with white background when fetching data.

src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts
=> Add textual change.

src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.tsx
When using the gps location button to select a location on the map, the address of the location is retrieved and placed in the address input field.
=> [SIG 4568] Get address when using gps location

src/global.css
**for tester**
test mobile view, you'll see the spinner is centered!
=> [SIG 4547] Center spinner.

src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.tsx
=> [SIG 4416] Fix nearby incidents for caterpillar select map

src/signals/incident/definitions/wizard-step-5-bedankt.js
https://datapunt.atlassian.net/browse/SIG-3658?atlOrigin=eyJpIjoiMjFjYjViNjkyNjI0NGUxNmFjNzE2OGIzOTA2NDEwYWEiLCJwIjoiaiJ9
In this pr, the sig prefix is used for displaying 'meldingsnummer' on 'bedankt' page.
=> Add sig prefix.

src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.tsx
=> [SIG 4577] Get address when tree is selected if possible

src/components/AutoSuggest/AutoSuggest.tsx, src/components/AutoSuggest/components/SuggestList/SuggestList.test.tsx, src/components/AutoSuggest/components/SuggestList/SuggestList.tsx
https://datapunt.atlassian.net/browse/SIG-4478?atlOrigin=eyJpIjoiYWNlZTAyNmQ1YzZkNDcyYmE5NmIzZGQ3ODA5NDdhY2IiLCJwIjoiaiJ9
=> [ SIG 4478] Show feedback when fetching returns empty result.

src/signals/incident-management/containers/DefaultTextsAdmin/components/SelectForm/index.js
=> Increase test coverage

src/signals/incident/containers/KtoContainer/components/KtoForm/index.js, src/signals/incident/containers/KtoContainer/components/KtoForm/index.test.js
**voor reviewer**
in deze pr wordt er conditioneel een optout knop geshowed. by default wordt contact_allowed of true gezet.
=> [SIG 4582] Show contact conditionally.

src/components/AutoSuggest/components/SuggestList/SuggestList.test.tsx, src/components/AutoSuggest/components/SuggestList/SuggestList.tsx, src/signals/incident/containers/KtoContainer/components/KtoForm/index.js
https://datapunt.atlassian.net/browse/SIG-4478?atlOrigin=eyJpIjoiM2ZiYjA3NDZkZDVhNDJhMWEyZmNhNGMzYmI4NzlmOWIiLCJwIjoiaiJ9
**for testers**
when no result in suggest list, after adding 'aaa', then remove the hover of the the feedback list item and chevron.
=> [SIG 4478] Remove hover and chevron when no feedback in SuggestList.tsx.

.eslintrc.js
**for tester**
look in Ide, by removing a hook dep. There should be a warning if eslint is configured.
=> Add eslint hooks warning         'react-hooks/exhaustive-deps': 1.

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/__tests__/StatusForm.test.tsx, src/types/api/incident.ts, src/utils/__tests__/fixtures/incident.json
https://datapunt.atlassian.net/browse/SIG-4593?atlOrigin=eyJpIjoiYTUyODM1OGMzZWM5NGU5NWIwNTFmMjEyMTllYWVhZDkiLCJwIjoiaiJ9
B[efore opening a pull request, please ensure:
=> [SIG 4593] fix typo 

src/signals/incident/containers/KtoContainer/components/KtoForm/index.js
=> [SIG 4582] Update styling.

src/signals/incident/components/form/MapSelectors/Asset/AssetSelect.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetSelect.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/WfsLayer.tsx, src/signals/incident/components/form/MapSelectors/Asset/__tests__/withAssetSelectContext.tsx, src/signals/incident/components/form/MapSelectors/Asset/context.tsx, src/signals/incident/components/form/MapSelectors/types.ts, src/signals/incident/containers/IncidentContainer/reducer.js
=> [SIG 4529] Set max number of assets

src/signals/incident/definitions/wizard-step-2-vulaan/afval-container.ts, src/signals/incident/definitions/wizard-step-2-vulaan/eikenprocessierups.ts, src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts
=> [SIG 4529] Temp settings max number of assets to select

src/signals/incident/containers/IncidentContainer/reducer.test.js
=> [SIG 4529] Improve test coverage

src/signals/incident/components/form/MultiTextInput/__tests__/MultiTextInput.test.tsx
=> Add test for MultiTextInput.test.tsx.

src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/WfsLayer.tsx, src/signals/incident/containers/IncidentContainer/actions.test.js, src/signals/incident/containers/IncidentContainer/reducer.js, src/signals/incident/containers/IncidentContainer/reducer.test.js, src/signals/incident/containers/IncidentContainer/selectors.js, src/signals/incident/containers/IncidentContainer/selectors.test.js
=> [SIG 4529] Show max asset warning after max is reached

src/signals/incident/containers/KtoContainer/components/KtoForm/index.js, src/signals/incident/containers/KtoContainer/components/KtoForm/index.test.js, src/signals/incident/containers/KtoContainer/index.js, src/signals/incident/containers/KtoContainer/index.test.js
=> [SIG 4600] Thank you page dissatisfied no contact

src/signals/incident/definitions/wizard-step-2-vulaan/afval-container.ts, src/signals/incident/definitions/wizard-step-2-vulaan/eikenprocessierups.ts, src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts
Zodat de nieuwe (oude) functionaliteit nu gewoon naar productie kan voordat het is afgestemd.
=> [SIG 4529] Select one asset

src/signals/incident/containers/KtoContainer/components/KtoForm/index.js, src/signals/incident/containers/KtoContainer/index.js, src/signals/incident/containers/KtoContainer/index.test.js
=> [SIG 4600] Fix default state contact allowed

src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.tsx
=> [SIG 4647] Zoom when selecting on the map

package-lock.json, package.json, src/signals/incident/containers/KtoContainer/components/KtoForm/index.js, src/signals/incident/containers/KtoContainer/components/KtoForm/index.test.js, src/signals/incident/containers/KtoContainer/index.test.js
https://datapunt.atlassian.net/browse/SIG-4606?atlOrigin=eyJpIjoiY2YwZGFhYmIxZTZiNGQ2MThhYmVmYWFiM2M2ZTgxNjAiLCJwIjoiaiJ9
**Voor de testers**
pas de submit functie aan van de kto container, met een log ipv een redux actie die het formulier doorstuurt. Dan kun je loggen wat het verzonden wordt en hoef je niet de hele tijd een nieuwe melding te maken.
=> [SIG 4606] Add react hook form.

src/signals/incident/definitions/wizard-step-2-vulaan/afval-container.ts
=> Set max number of containers to 5

src/signals/incident/containers/KtoContainer/components/KtoForm/index.js, src/signals/incident/containers/KtoContainer/components/KtoForm/index.test.js, src/signals/incident/containers/KtoContainer/index.js, src/signals/incident/containers/KtoContainer/index.test.js
@kiruys 
na gesprek met Jelle bleek de kto flow toch nog niet helemaal goed te gaan. 
Zou het zo beter zijn?
=> Add changes to fix new flow.

src/signals/incident/containers/KtoContainer/components/KtoForm/index.js
https://datapunt.atlassian.net/browse/SIG-4606?atlOrigin=eyJpIjoiYzhhOTczZWU1M2YyNGNiZGIxOTczMmFkMzQxMGQ3YmMiLCJwIjoiaiJ9
=> [SIG 4606] Remove text.

src/signals/incident/containers/KtoContainer/components/KtoForm/index.test.js
=> [SIG 4606] Remove dead test code.

src/components/AreaMap/AreaMap.tsx, src/components/AreaMap/__tests__/AreaMap.test.tsx
=> Fix Area Map component

app.amsterdam.json, docs/adr/0003-application-configuration-setup.md, internals/schemas/app.schema.json, internals/scripts/helpers/config.js, internals/webpack/webpack.base.babel.js, package-lock.json, package.json, src/app.js, src/containers/App/index.tsx, src/index.html, src/signals/incident-management/containers/IncidentOverviewPage/components/Sort/Sort.tsx
=> Remove Matomo

src/signals/incident-management/containers/IncidentDetail/IncidentDetail.test.js, src/signals/incident-management/containers/IncidentDetail/IncidentDetail.tsx, src/signals/incident-management/containers/IncidentDetail/actions.ts, src/signals/incident-management/containers/IncidentDetail/components/MetaList/MetaList.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/reducer.test.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/reducer.test.tsx, src/signals/incident-management/containers/IncidentDetail/constants.ts, src/signals/incident-management/containers/IncidentDetail/index.ts, src/signals/incident-management/containers/IncidentDetail/reducer.test.tsx, src/signals/incident-management/containers/IncidentDetail/reducer.ts, src/signals/incident-management/containers/IncidentDetail/types.ts
=> Refactor IncidentDetail to typescript

src/signals/settings/categories/Detail/components/CategoryForm/CategoryForm.test.tsx, src/signals/settings/categories/Detail/components/CategoryForm/CategoryForm.tsx
https://datapunt.atlassian.net/browse/SIG-4658?atlOrigin=eyJpIjoiYzUxOWI4NGM5NmMyNDRlNWFhNzViMjViYzRhZmI3YTgiLCJwIjoiaiJ9
**voor tester**
update text in subcategorie formulier bijv @ http://localhost:3001/instellingen/categorie/113
=> [SIG 4658] Change text subcategorie

src/signals/incident/definitions/wizard-step-2-vulaan/afval-container.ts
=> Temp 4 containers

src/signals/incident-management/containers/IncidentDetail/components/LocationForm/index.tsx
See https://datapunt.atlassian.net/jira/software/c/projects/SIG/boards/40?modal=detail&selectedIssue=SIG-4691
=> [SIG 4691] Remove label from location form

src/containers/App/index.tsx
=> [SIG 4661] Reinstate ignore async lazy loading

src/signals/IncidentMap/IncidentMapContainer.tsx
=> [SIG 4661] Fix test coverage

default.conf
This adds GZIP compression support to NGINX to improve Lighthouse score.
=> Add GZIP compression in nginx for speed optimization

src/signals/incident/components/form/MapSelectors/components/MapMessage/MapMessage.tsx
Ticket: [SIG-4705](https://datapunt.atlassian.net/browse/SIG-4705)
The error message of the My Location could not be accessed with a keyboard.
Changed it so it makes use of the styled component Button
- Test fails because it doesn't recognise the variant="primary". Why is that?
- There are several ways buttons are implemented in the code. What is the convention at for this application?
=> [SIG-4705] changed svg to styled component button

.eslintrc.js
**for testing**
see tsx/jsx file, when adding a single quote in an elements tag.
=> Add eslint rule to prefer double quotes in jsx.

src/components/SiteHeader/incidentMapStyles.ts
=> [SIG 4661] Fix header on safari mobile

src/signals/incident/containers/KtoContainer/components/KtoForm/index.js, src/signals/incident/containers/KtoContainer/index.js
Changes to text has been made. Last checkbox ends with a dot (Linda agreed to let this stand while waiting for other checkboxes to get dots). Stories are being made so that in back end also all checkboxes end with a dot.
=> [SIG 4724] Textchanges in KTO-tevredenpage

src/components/SiteHeader/incidentMapStyles.ts
=> [SIG 4753] Fix mobile header in Safari

src/signals/incident/containers/KtoContainer/index.js
**Context:**
Door uw reactie weten we wat we kunnen verbeteren. 
U ontvangt direct een e-mail met een overzicht van uw reactie. Binnen 3 werkdagen leest u wat wij ermee gaan doen.
**Changed:**
- put the two text sections in one StyledParagraph
- added newline to last text section
- text changes applied
=> [SIG-4721] Changes to text and formatting KTO-ontevreden-bedankt page

package.json
Added a script that makes in possible to run tests in watch mode.
=> [config]: add test watch mode

src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.ts
Ticket[SIG-4755](https://datapunt.atlassian.net/browse/SIG-4755)
- aanvraag formulier url was niet correct
- changed url to working url
=> [SIG-4755]: change aanvraag formulier url

src/components/Markdown/Markdown.tsx, src/signals/incident/components/form/PlainText/index.js
##for testers
try to tab to the tabindex of the phone while the map is active in step 2. You can also use firefox dev tools to show all the tabindexes.
=> [SIG 4699] Add tabindex phone conditionally.

src/signals/IncidentMap/components/IncidentMap/IncidentMap.tsx, src/signals/IncidentMap/components/IncidentMap/styled.ts, src/signals/IncidentMap/containers/IncidentMapContainer.tsx
The map behaviour was not as expected.
- added some map options 
- removed unnecessary html
=> [SIG-4762]: Add new controls / styling meldingenkaart

src/signals/incident/definitions/wizard-step-3-contact.js
update some text
I updated the phone and email fields in wizard-3 and added a new item phone_email_text thats the heading for both email and phone.
(https://datapunt.atlassian.net/browse/SIG-4771?atlOrigin=eyJpIjoiMDdjMWM0MTYwYjhkNGE4MmI5YzYwMWMyYTUxNGEwN2YiLCJwIjoiaiJ9)
=> [SIG-4771] Update text contactpage.

.github/PULL_REQUEST_TEMPLATE.md
Added a ticket link to the PR Template so that everyone is triggered to add the Jira ticket link in their PR.
=> [Config]: add ticket link to template

src/signals/incident/definitions/wizard-step-3-contact.js
Ticket: [SIG-1234](https://datapunt.atlassian.net/browse/SIG-1234) 
- add new line
- ....
=> [SIG-4771]Add newline.

src/signals/incident/definitions/wizard-step-3-contact.js
Ticket: [SIG-4771](https://datapunt.atlassian.net/browse/SIG-4771)
- add trema
⬆️ 
=> Add accent.

src/signals/incident/components/IncidentForm/index.test.js, src/signals/incident/components/IncidentForm/index.tsx, src/signals/incident/components/IncidentNavigation/IncidentNavigation.test.tsx, src/signals/incident/components/IncidentNavigation/IncidentNavigation.tsx, src/signals/incident/components/IncidentWizard/IncidentWizard.tsx, src/signals/incident/components/form/GlobalError/GlobalError.js
Ticket: [SIG-4808](https://datapunt.atlassian.net/browse/SIG-4808)
make sure validation is triggered for every field after a change
test the first input field, beschrijving, location and mess around. Compare with meldingen.amsterdam.nl without making an incident.
=> [SIG-4808] Trigger validation for non text input fields.

src/signals/incident/components/IncidentForm/index.test.js, src/signals/incident/components/IncidentForm/index.tsx, src/signals/incident/components/IncidentForm/utils/scroll-to-invalid-element.ts, src/signals/incident/components/form/MapSelectors/Asset/Intro/Intro.tsx
Ticket: [SIG-4817](https://datapunt.atlassian.net/browse/SIG-4817)
- focus invalid element on submit.
- 
- make screen big with command + to simulate large screen, and check behaviour.
=> [SIG-4817] Scroll to invalid input if its validated.

src/signals/incident/components/IncidentForm/index.test.js, src/signals/incident/components/IncidentForm/utils/scroll-to-invalid-element.ts
Ticket: [SIG-4817](https://datapunt.atlassian.net/browse/SIG-4817)
=> [SIG-4817] Smooth scroll to invalid element. Add smooth scroll.

src/signals/incident/services/yup-resolver/index.ts
Ticket: [SIG-4816](https://datapunt.atlassian.net/browse/SIG-4816)
- don't be able to clear assetSelect in step 2 and skip validation
- fill refill validate in random order
=> [SIG-4816] During validation, validate the shape of the object locatie.

src/signals/incident/components/IncidentForm/index.tsx
https://datapunt.atlassian.net/browse/SIG-4825?atlOrigin=eyJpIjoiYWY3NmJlZWE2NGM3NDMwNWFkOTdjOGQ4MTI2YzQ5MTIiLCJwIjoiaiJ9
=> [SIG 4825] Add nested error support.

src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/styled.tsx
Ticket: [SIG-4772](https://datapunt.atlassian.net/browse/SIG-4772)
- typo with ";" in the styled file
- ran ESLint auto order in file
=> SIG-4772: fix input field out of view bug

src/signals/incident/services/yup-resolver/index.ts
Ticket: [SIG-4833](https://datapunt.atlassian.net/browse/SIG-4833)
=> Make address in location optional.

src/signals/incident/services/yup-resolver/index.ts
Ticket: [SIG-4834](https://datapunt.atlassian.net/browse/SIG-4834)
=> [SIG-4834] Refactor validation rules and fix vng related errors.

src/signals/incident/services/yup-resolver/index.ts
Ticket: [SIG-4834](https://datapunt.atlassian.net/browse/SIG-4834)
=> Refactor validation rules and fix vng related errors.

src/signals/incident/services/yup-resolver/index.test.ts, src/signals/incident/services/yup-resolver/index.ts
Ticket: [SIG-4834](https://datapunt.atlassian.net/browse/SIG-4834)
=> [SIG-4834] Check max on validation field before resolving validation field.

src/signals/incident/services/yup-resolver/index.test.ts, src/signals/incident/services/yup-resolver/index.ts
Ticket: [SIG-4834](https://datapunt.atlassian.net/browse/SIG-4834)
Clean the yup resolver code.
=> [SIG-4834] Refactored the yup schema creator. Some cleanup.

src/signals/incident/services/yup-resolver/index.test.ts, src/signals/incident/services/yup-resolver/index.ts
Ticket: [SIG-4846](https://datapunt.atlassian.net/browse/SIG-4846)
use 'verkeerslicht'
=> [SIG-4846] Fix verkeerslicht error checkbox.

src/signals/incident/definitions/wizard-step-4-summary.js
Ticket: [SIG-4845](https://datapunt.atlassian.net/browse/SIG-4845)
make address property optional when selecting streetlight.
https://github.com/Amsterdam/signals-frontend/compare/SIG_4845/make_adress_field_optional?expand=1 
=> [SIG-4845] Make address attribute optional.

src/signals/incident/services/yup-resolver/index.ts
Ticket: [SIG-4846](https://datapunt.atlassian.net/browse/SIG-4846)
fix verkeerslichten checkbox validation for refactored yup schema.
=> [SIG-4846] Fix verkeerslicht error checkbox for develop.

src/signals/IncidentMap/components/utils/get-filtered-incidents.ts
Cleanup get-filtered-incidents a little.
=> Cleanup get filtered incidents.

app.base.json, internals/schemas/app.schema.json, src/signals/incident/containers/KtoContainer/components/KtoForm/index.js, src/signals/incident/containers/KtoContainer/components/KtoForm/index.test.js, src/signals/incident/containers/KtoContainer/index.test.js, src/signals/incident/definitions/wizard-step-2-vulaan/dateTime.ts, src/signals/incident/services/custom-validators/custom-validators.test.ts, src/signals/incident/services/custom-validators/custom-validators.ts, src/signals/incident/services/yup-resolver/index.test.ts
Ticket: [SIG-4839](https://datapunt.atlassian.net/browse/SIG-4839)
=> [SIG-4839] Enable disable multiple kto questions.

src/signals/IncidentMap/components/DrawerOverlay/DetailPanel.test.tsx, src/signals/IncidentMap/components/DrawerOverlay/DetailPanel.tsx, src/signals/IncidentMap/components/DrawerOverlay/DrawerOverlay.test.tsx, src/signals/IncidentMap/components/DrawerOverlay/styled.ts, src/signals/IncidentMap/components/Header/styled.tsx
Ticket: [SIG-4667](https://datapunt.atlassian.net/browse/SIG-4667)
There were some comments on the styling of the detail panel. This PR fixes them.
- Format date
- Remove time
- Font weight values
- Margin top of detailPanel content
- grey line in mobile toggle button
=> [SIG-4667]: acceptance feedback

app.amsterdam.json, package-lock.json, package.json, src/app.js
Ticket: [SIG-4716](https://datapunt.atlassian.net/browse/SIG-4716)
Monitor frontend errors using azure insights.
=> [SIG-4716] Implement azure insights.

src/signals/incident/components/IncidentForm/index.tsx, src/signals/incident/components/form/DateTimeInput/DateTime.test.tsx, src/signals/incident/components/form/DateTimeInput/DateTime.tsx, src/signals/incident/definitions/wizard-step-2-vulaan/dateTime.ts, src/signals/incident/definitions/wizard-step-2-vulaan/wonen.ts, src/signals/incident/services/custom-validators/custom-validators.test.ts, src/signals/incident/services/custom-validators/custom-validators.ts, src/signals/incident/services/custom-validators/index.ts, src/signals/incident/services/yup-resolver/index.test.ts, src/signals/incident/services/yup-resolver/index.ts
Ticket: [SIG-4858](https://datapunt.atlassian.net/browse/SIG-4858)
=> [SIG-4858] Initial value datetime is back to undefined.

internals/schemas/app.schema.json
=> hotfix/Update app.schema.json v2.

internals/schemas/app.schema.json
=> hotfix/Update schema.

.github/workflows/build_and_push_to_docker_hub.yml, .github/workflows/build_and_push_to_github_container_registry.yml
This PR automates publishing to DockerHub and refactors the other workflow that pushes to Github Container Registry.
=> Automate publishing to DockerHub

src/signals/incident/components/form/FormField/FormField.tsx, src/signals/incident/services/yup-resolver/index.test.ts, src/signals/incident/services/yup-resolver/index.ts
Ticket: [SIG-4864](https://datapunt.atlassian.net/browse/SIG-4864)
=> Sig 4864/trafficlights and container location validation fix

src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx
Ticket: [SIG-4829](https://datapunt.atlassian.net/browse/SIG-4829)
=> SIG_4829/change_text

src/signals/incident/components/StepWizard/components/Wizard.tsx, src/signals/incident/components/StepWizard/index.test.tsx
Ticket: [SIG-4866](https://datapunt.atlassian.net/browse/SIG-4866)
**voor testers**
doorloop formulier, stuur op en ga naar bedankt pagina! Dat laatste lukte niet.
=> [SIG-4866] Fix setStep after submit summary step.

src/signals/incident/components/IncidentForm/index.test.js, src/signals/incident/containers/KtoContainer/components/KtoForm/index.test.js
Ticket: none
This PR refactors some test to remove the "wrap in Act" error.
=> [refactor] :remove wrap in act errors

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/shared/services/configuration/map-options.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/afval-container.ts, src/signals/incident/definitions/wizard-step-2-vulaan/eikenprocessierups.ts, src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts
Ticket: [SIG-4850](https://datapunt.atlassian.net/browse/SIG-4850)
=> Update maxNumberOfAssets for a couple of incident catagories.

src/signals/incident-management/components/CalendarInput/CalendarInput.test.tsx, src/signals/incident-management/components/CalendarInput/CalendarInput.tsx, src/signals/settings/users/Detail/__tests__/Detail.test.js, src/signals/settings/users/Detail/components/UserForm/index.js, src/signals/settings/users/Detail/index.js
Ticket: none
1) The test gave an error that it made an uncontrolled input controlled. However, the intention is to have a controlled component. Providing a default value does so. 
2) The second test complained about passing a NaN as left property which is not allowed. A closer look to what the test actually tested showed the code that it was intended to test did not do anything. I deleted it. 
_note: only two small changes. The rest is the result of running auto import fix_
=> [refactor] Make form controlled

app.amsterdam.json
Ticket: [SIG-4850](https://datapunt.atlassian.net/browse/SIG-4850)
=> Change maxNumberOfAssets for straatverlichtingKlokken.

src/signals/incident-management/components/CheckboxList/CheckboxList.test.tsx, src/signals/incident-management/components/CheckboxList/CheckboxList.tsx, src/signals/incident-management/definitions/statusList.ts, src/signals/incident/containers/KtoContainer/index.js
Ticket: [SIG-4823](https://datapunt.atlassian.net/browse/SIG-4823)
=> Feat 4823/kto topics ordering

.github/PULL_REQUEST_TEMPLATE.md
Update pull request template according new default branch.
=> Update pull request template.

src/signals/IncidentMap/components/FilterPanel/FilterPanel.test.tsx, src/signals/IncidentMap/components/FilterPanel/FilterPanel.tsx, src/signals/my-incidents/pages/RequestAccess.test.tsx, src/signals/my-incidents/pages/RequestAccess.tsx
Ticket: none
The content of the login page was not according to design but accidentally swapped with the expiredLink page.
=> [bugfix] Correct login page content

package-lock.json, src/signals/my-incidents/pages/BasePage.tsx, src/signals/my-incidents/pages/RequestAccess.test.tsx, src/signals/my-incidents/pages/RequestAccess.tsx, src/signals/my-incidents/pages/styled.ts
Ticket: [SIG-4757](https://datapunt.atlassian.net/browse/SIG-4757)
This PR implements the feedback from the acceptance environment version 2.10.1.
=> [fix]: my incidents login page acc feedback

src/signals/my-incidents/pages/styled.ts
Ticket: [SIG-4757](https://datapunt.atlassian.net/browse/SIG-4757)
Implemented comments of above ticket. Added some margin.
=> [fix]: My incidents login feedback

src/hooks/__tests__/useFetch.test.ts, src/hooks/useFetch.ts, src/shared/services/configuration/endpoint-definitions.js, src/signals/IncidentMap/components/FilterPanel/FilterCategory.tsx, src/signals/IncidentMap/components/FilterPanel/styled.ts, src/signals/my-incidents/__test__/incidents-list.ts, src/signals/my-incidents/__test__/index.ts, src/signals/my-incidents/__test__/provider-mock.ts, src/signals/my-incidents/components/EmailInput/EmailInput.test.tsx, src/signals/my-incidents/components/IncidentsList/IncidentsList.test.tsx, src/signals/my-incidents/components/IncidentsList/IncidentsList.tsx, src/signals/my-incidents/components/IncidentsList/index.ts, src/signals/my-incidents/components/IncidentsList/styled.ts, src/signals/my-incidents/containers/Routing.tsx, src/signals/my-incidents/context/provider.tsx, src/signals/my-incidents/hooks/useMyIncidents.test.tsx, src/signals/my-incidents/hooks/useMyIncidents.ts, src/signals/my-incidents/pages/Confirmation.test.tsx, src/signals/my-incidents/pages/Overview.test.tsx, src/signals/my-incidents/pages/Overview.tsx, src/signals/my-incidents/pages/RequestAccess.test.tsx, src/signals/my-incidents/pages/index.ts, src/signals/my-incidents/pages/styled.ts, src/signals/my-incidents/types.ts
Ticket: [SIG-4758](https://datapunt.atlassian.net/browse/SIG-4758)
This PR adds an overview page of my incidents.
- created OverviewPage
- fetch data based on token provided in url
- add tests 
=> [feat 4241]: my incidents overview

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/build_and_push_to_github_container_registry.yml, .github/workflows/ci.yml, .github/workflows/end-to-end.yml, scripts/initialize-backend.sh
Ticket: none
We changed the name of the `master` branch to `main`. This makes some word changes in the code as well.
=> [chore]: change master to main

docs/adr/0004-multi-tenant-architecture.md, docs/adr/0005-deploy-setup.md
Ticket: [SIG-4885](https://datapunt.atlassian.net/browse/SIG-4885)
=> [SIG-4885] Start removing jenkins references out of signals-frontend.

src/signals/my-incidents/components/EmailInput/EmailInput.tsx
Ticket: [SIG-4893](https://datapunt.atlassian.net/browse/SIG-4893)
=> Wait for promise to resolve to fix token cancellation.

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/shared/services/configuration/map-options.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts
Ticket: [SIG-4893](https://datapunt.atlassian.net/browse/SIG-4893)
This ticket splits the maxNumberOfAssets for straatverlichting en klokken.
Make sure to update the config on azure when releasing to acc or prod.
=> Split straatverlichting en klokken maxNumberOfAssets.

.github/review/values.yml, .github/workflows/review_cleanup.yml, .github/workflows/review_deploy.yml
- Update default configuration of review apps
- Deploy review apps when PR is created and then labeled
- Update to Helm chart version 4.5.0
=> Improve review apps

src/shared/services/configuration/endpoint-definitions.js, src/signals/my-incidents/components/IncidentsList/IncidentsList.test.tsx, src/signals/my-incidents/components/IncidentsList/IncidentsList.tsx, src/signals/my-incidents/pages/Overview.test.tsx, src/signals/my-incidents/pages/Overview.tsx, src/signals/my-incidents/types.ts
Ticket: [SIG-4908](https://datapunt.atlassian.net/browse/SIG-4908)
- fetch email address based on token from backend
- show email instead of mock data
- adjust test.
=> [feat-4908]: show user email

src/signals/incident-management/containers/IncidentDetail/IncidentDetail.tsx
Ticket: [SIG-4913](https://datapunt.atlassian.net/browse/SIG-4913)
Make location preview close again!
=> Pass dispatchClose directly to close LocationPreview component.

src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/index.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/index.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx
Ticket: [SIG-4912](https://datapunt.atlassian.net/browse/SIG-4912)
=> [bugfix-4912]: undefined with unknown container

src/signals/my-incidents/components/IncidentsList/IncidentsList.test.tsx, src/signals/my-incidents/components/IncidentsList/IncidentsList.tsx, src/signals/my-incidents/components/IncidentsList/styled.ts
Ticket: [SIG-4758](https://datapunt.atlassian.net/browse/SIG-4758)
=> [feat-4758]: feedback my-incidents overview page

.github/review/values.yml, app.amsterdam.json, app.base.json
Ticket: [SIG-4895](https://datapunt.atlassian.net/browse/SIG-4895)
=> Update theme color in signals frontend.

src/components/CheckboxList/CheckboxList.test.tsx, src/components/RadioButtonList/__tests__/RadioButtonList.test.tsx, src/signals/incident-management/definitions/priorityList.tsx, src/signals/incident-management/definitions/statusList.ts
https://datapunt.atlassian.net/browse/SIG-4919?atlOrigin=eyJpIjoiZTlhNjQwNDczY2QwNDBjNTlhNDRhMTc1YjE4NTNiMjkiLCJwIjoiaiJ9
There were topic showing for priority and statuses in the backoffice.
=> hotfix/Fix topics showing in backoffice.

e2e-tests/cypress/support/commandsCreateSignal.ts, src/signals/incident/definitions/wizard-step-1-beschrijf.js
Ticket: [SIG-4909](https://datapunt.atlassian.net/browse/SIG-4909)
=> [feat-4909]:Change text within incidents form's first step.

app.amsterdam.json, package-lock.json, package.json
**Context**
In order to get Azure Monitor to work, telemetry data needs to be forwarded to Azure Portal. Therefore the connection string needs to be added. 
See also https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript?tabs=snippet#npm-based-setup
Ticket: [SIG-4716](https://datapunt.atlassian.net/browse/SIG-4716)
**configuration**
- Connection string acceptance in app.amsterdam.json
- Connection string production in app.amsterdam.json
- Committed source code is …
=> [feat-4716]-Connection-string-added

internals/schemas/app.schema.json
Change schema to fix acc deployment.
=> [bug] Remove format uri from app schema json.

src/components/SiteHeader/SiteHeader.test.js, src/components/SiteHeader/index.js, src/containers/App/index.tsx, src/containers/SiteHeader/index.js, src/hooks/useDefaultHeader.ts, src/hooks/useTallHeader.ts
Ticket: [SIG-4911](https://datapunt.atlassian.net/browse/SIG-4911)
=> [feat 4911] show default tall header at myincidents

src/signals/incident/definitions/wizard-step-1-beschrijf.js
Ticket: [SIG-4922](https://datapunt.atlassian.net/browse/SIG-4922)
=> [feat-4922]:Add info text on top of incidents form's first step.

src/signals/IncidentMap/components/IncidentMap/IncidentMap.tsx, src/signals/IncidentMap/components/IncidentMap/usePaginatedIncidents.test.ts, src/signals/IncidentMap/components/IncidentMap/usePaginatedIncidents.ts
Ticket: [SIG-4923](https://datapunt.atlassian.net/browse/SIG-4923)
=> [feat-4923] use paginated features in IncidentMap.tsx.

src/components/AttachmentViewer/AttachmentViewer.tsx, src/components/AttachmentViewer/components/InteractiveImage/InteractiveImage.test.tsx, src/components/AttachmentViewer/components/InteractiveImage/InteractiveImage.tsx, src/components/AttachmentViewer/components/InteractiveImage/constants.ts, src/components/AttachmentViewer/components/InteractiveImage/styled.ts, src/components/AttachmentViewer/styles.ts
Users should be able to zoom attachment viewer images
Closes https://github.com/Signalen/product-steering/issues/311
=> [feat] Adds zoom to attachment viewer

src/signals/incident/components/IncidentForm/index.test.js, src/signals/incident/components/IncidentForm/index.tsx
Ticket: [SIG-4931](https://datapunt.atlassian.net/browse/SIG-4931)
put 1001 characters in the description field, for example by in inspector console:
``` 
copy('a'.repeat(1001))
```
press next and voila!
=> [fix-4931]: Add validation for description field.

docs/adr/0009-stop-mocking-fetch-in-tests.md
Ticket: [SIG-4800](https://datapunt.atlassian.net/browse/SIG-4800)
[SIG-4800]: https://datapunt.atlassian.net/browse/SIG-4800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIG-4800]: https://datapunt.atlassian.net/browse/SIG-4800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [chore-4800]: set adr to accepted

internals/webpack/webpack.prod.babel.js
Ticket: [SIG-4803](https://datapunt.atlassian.net/browse/SIG-4803)
Removed the legacy chuck since these packages are removed from the application.
[SIG-4803]: https://datapunt.atlassian.net/browse/SIG-4803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [chore-4803]: remove legacy chunk

src/signals/incident/containers/KtoContainer/components/KtoForm/index.js
Ticket: [SIG-4940](https://datapunt.atlassian.net/browse/SIG-4940)
[SIG-4940]: https://datapunt.atlassian.net/browse/SIG-4940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-4940]: Add dynamic kto subtitle based on enableMultipleKtoQuestions.

src/signals/IncidentMap/components/__test__/mock-incidents-without-icon.ts, src/signals/IncidentMap/components/utils/get-filtered-incidents.test.ts, src/signals/IncidentMap/components/utils/get-filtered-incidents.ts, src/signals/IncidentMap/types/incident-map.ts
Ticket: [SIG-4945](https://datapunt.atlassian.net/browse/SIG-4945)
[SIG-4945]: https://datapunt.atlassian.net/browse/SIG-4945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-4945]: add correct icons to filters Incident Map

src/signals/IncidentMap/components/IncidentMap/IncidentMap.test.tsx, src/signals/IncidentMap/components/IncidentMap/IncidentMap.tsx, src/signals/IncidentMap/components/IncidentMap/usePaginatedIncidents.test.ts, src/signals/IncidentMap/components/IncidentMap/usePaginatedIncidents.ts
Ticket: [SIG-4944](https://datapunt.atlassian.net/browse/SIG-4944)
##todo
[SIG-4944]: https://datapunt.atlassian.net/browse/SIG-4944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-4944]: Get paginated results in IncidentMap.tsx.

.github/PULL_REQUEST_TEMPLATE.md
Update jira link in PR Template
=> [chore]: changed PR template to new jira link

package-lock.json, src/components/MapInput/MapInput.test.js, src/components/MapInput/MapInput.tsx, src/components/MapInput/index.ts, src/components/MapInput/styled.tsx, src/shared/services/map-location/index.ts, src/shared/services/map-location/map-location.ts, src/signals/incident-management/components/MapInput/index.tsx, src/signals/incident/components/form/MapInput/index.tsx
Ticket: [SIG-4943](https://gemeente-amsterdam.atlassian.net/browse/SIG-4943)
Converted MapInput component to typescript and adjust folder structure.
[SIG-4943]: https://datapunt.atlassian.net/browse/SIG-4943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-4943]: changed MapInput to typescript

app.base.json
As the dashboard is not ready yet.
=> By default disable dashboard for now

app.base.json, internals/schemas/app.schema.json, src/signals/incident/containers/KtoContainer/components/KtoForm/index.js, src/signals/incident/containers/KtoContainer/components/KtoForm/index.test.js, src/signals/incident/containers/KtoContainer/index.test.js
Ticket: [SIG-4840](https://gemeente-amsterdam.atlassian.net/browse/SIG-4840)
**breaking** This pr involves changes to the app.base.json. Change them also here https://dev.azure.com/CloudCompetenceCenter/_git/SIA?path=/kubernetes/acceptatie/frontend/_base
[SIG-4840]: …
=> [feat-4840]: Name change feature flag enableMultipleKtoQuestions.

package-lock.json, package.json
Currently logout is broken for municipalities that use Keycloak 18
=> Update keycloak-js to 20.0.3 to support Keycloak version > 17

src/signals/IncidentMap/components/IncidentMap/usePaginatedIncidents.test.ts, src/signals/IncidentMap/components/IncidentMap/usePaginatedIncidents.ts
=> [chore]: Upping usePagination test

src/signals/incident-management/containers/Dashboard/components/Filter/styled.tsx, src/signals/incident-management/containers/Dashboard/components/styled.ts
**fixed**
- put area graph behind filter menu overlay
=> [bug]: Add zindexes.

internals/scripts/validate-base-config.js, internals/scripts/validate-config.js, internals/testing/msw-server.ts
Fixed some import order warnings in the internals/ folder.
=> [chore]: fixed import order internals folder

src/signals/IncidentMap/components/Header/styled.tsx
Ticket: [SIG-4987](https://gemeente-amsterdam.atlassian.net/browse/SIG-4987)
Making logo in IncidentMap responsive.
=> [fix-4987]:make logo IncidentMap responsive

app.amsterdam.json, src/signals/incident-management/containers/Dashboard/charts/area-chart.ts, src/signals/incident/containers/KtoContainer/index.js, src/signals/incident/containers/KtoContainer/index.test.js
Ticket: [SIG-5003](https://gemeente-amsterdam.atlassian.net/browse/SIG-5003)
Add a topic to "Over iets anders" answer in the negative feedback kto form. 
Currently vs. New
=> [fix-5003]: kto header

src/hooks/useFetch.ts, src/signals/incident-management/containers/Dashboard/Dashboard.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/Filter.test.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/OptionsList.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/SelectList.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/styled.tsx, src/signals/incident-management/containers/Dashboard/hooks/useDepartments.test.ts, src/signals/incident-management/containers/Dashboard/hooks/useDepartments.ts, src/signals/incident-management/containers/Dashboard/hooks/useFilter.test.ts, src/signals/incident-management/containers/Dashboard/hooks/useFilter.ts, src/signals/incident-management/containers/Dashboard/styled.ts, src/signals/incident-management/context.ts, src/signals/incident-management/index.js, src/types/api/incident.ts, src/utils/__tests__/fixtures/departments.json
**context**
implementing some requested changes of ux, plus making the opening menus mobile firstisch.
Ticket: [SIG-4898](https://gemeente-amsterdam.atlassian.net/browse/SIG-4898)
[SIG-4898]: https://datapunt.atlassian.net/browse/SIG-4898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
=> [feat 4898]: Dashboard filter changes

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/signals/incident/components/IncidentWizard/IncidentWizard.tsx
Ticket: [SIG-5033](https://gemeente-amsterdam.atlassian.net/browse/SIG-5033)
=> [feature-5033]: Make a strike alert in IncidentWizard.tsx configurable.

src/signals/incident-management/containers/Dashboard/components/Filter/styled.tsx
Added margins and changed lineheights to make focus states fit
Ticket: [SIG-5004](https://gemeente-amsterdam.atlassian.net/browse/SIG-5004)
=> [feat-5004]: Make focus visible on all browsers

src/signals/settings/components/Overview/components/Overview.tsx, src/signals/settings/components/Overview/components/__tests__/Overview.test.tsx, src/signals/settings/components/PageHeader/index.tsx
Ticket: [SIG-4986](https://gemeente-amsterdam.atlassian.net/browse/SIG-4986)
=> [feat-4986]: Show version number be at instellingen

src/signals/incident-management/containers/Dashboard/Dashboard.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/Filter.test.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/Filter.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/SelectList.tsx
Ticket: [SIG-5049](https://gemeente-amsterdam.atlassian.net/browse/SIG-5049)
The Wis Filter button didn't trigger the callback of the filters, therefore didn't fetch new data for the graphs.
=> [fix-5049]: Add callback call to Wis Filter button

src/signals/incident-management/containers/IncidentDetail/components/Attachments/Attachments.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/Attachments/Attachments.tsx, src/signals/incident-management/containers/IncidentDetail/components/Attachments/styles.ts, src/signals/incident-management/containers/IncidentDetail/utils/isPdf.test.ts, src/signals/incident-management/containers/IncidentDetail/utils/isPdf.ts, src/signals/incident/components/IncidentWizard/styled.tsx
Ticket: [SIG-4995](https://gemeente-amsterdam.atlassian.net/browse/SIG-4995)
=> [Feature-4995]: pdf weergeven in incidentDetail

src/signals/incident-management/containers/IncidentDetail/IncidentDetail.test.js, src/signals/incident-management/containers/IncidentDetail/components/Attachments/Attachments.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/Attachments/Attachments.tsx, src/signals/incident-management/containers/IncidentDetail/components/Attachments/styles.ts, src/signals/incident-management/containers/IncidentDetail/components/FileInput/FileInput.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/FileInput/FileInput.tsx, src/signals/incident-management/containers/IncidentDetail/utils/isPdf.test.ts, src/signals/incident-management/containers/IncidentDetail/utils/isPdf.ts, src/signals/incident/components/IncidentWizard/styled.tsx
Ticket: [SIG-4994](https://gemeente-amsterdam.atlassian.net/browse/SIG-4994)
=> [feat-4994]: Enable uploading pdf files in IncidentDetail

src/signals/incident/definitions/wizard-step-3-contact.js
Text change in wizard-step-3-contact. Text changed to:
Soms kan de gemeente niets doen. Een andere organisatie moet dan aan het werk. Als dat zo is kunnen wij uw melding soms doorsturen. Wij sturen uw telefoonnummer of e-mailadres mee. Maar dat doen we alleen als u dat goed vindt.
Ticket: [SIG-5084](https://gemeente-amsterdam.atlassian.net/browse/SIG-5084)
Be kind to code reviewers, please try to keep pull …
=> [feat-5084] text change in wizard-step-3-contact

src/shared/services/map-extra-properties/index.ts, src/shared/services/map-extra-properties/mapExtraPropertiesToJSX.tsx, src/shared/types/extraProperties.ts, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/index.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/index.tsx, src/signals/my-incidents/components/IncidentsDetail/ExtraProperties.test.tsx, src/signals/my-incidents/components/IncidentsDetail/ExtraProperties.tsx, src/signals/my-incidents/components/IncidentsDetail/IncidentsDetail.test.tsx, src/signals/my-incidents/components/IncidentsDetail/IncidentsDetail.tsx, src/signals/my-incidents/components/IncidentsDetail/styled.ts, src/signals/my-incidents/types.ts
Ticket: [SIG-4756](https://gemeente-amsterdam.atlassian.net/browse/SIG-4756)
We want to show the additional answers in the detail page of my incidents as well.
- Moved some types and logic from incident-management to shared folder.
- Create an ExtraProperties component for my-incidents
- Add tests
=> [feat-4756] my incidents extra questions

src/components/GlobalError/GlobalError.js, src/components/GlobalError/__tests__/GlobalError.test.js, src/signals/incident/definitions/wizard-step-2-vulaan/afval.ts, src/signals/incident/definitions/wizard-step-2-vulaan/dateTime.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-op-het-water.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-van-en-door-personen-of-groepen.ts, src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.ts, src/signals/incident/definitions/wizard-step-2-vulaan/wonen.ts, src/signals/incident/services/custom-validators/custom-validators.test.ts, src/signals/incident/services/custom-validators/custom-validators.ts, src/signals/incident/services/custom-validators/index.ts, src/signals/incident/services/yup-resolver/index.test.ts, src/signals/incident/services/yup-resolver/index.ts
context:
When asked the question Wanneer was het? in wizard-step-2 page, the user can report an incident in the future. This hinders that and notifies the user the incident has to be in the past.
changes:
Checks now if issue is reported in the future. If so, then error message.
Ticket: [SIG-5090](https://gemeente-amsterdam.atlassian.net/browse/SIG-5090)
Be kind to code reviewers, please try to keep pull …
=> [fix-5090]: fixes issues reported in the future

src/hooks/useFetch.ts, src/hooks/useFetchAll.ts
Ticket: [SIG-1234](https://gemeente-amsterdam.atlassian.net/browse/SIG-1234)
=> [5110-feat]: Add credentials to fetch api in useFetch/All hooks.

src/hooks/useFetch.ts, src/hooks/useFetchAll.ts
This reverts commit d7e8eeb9b3dff3bfe346f101c7bb11371899e0a4.
Ticket: [SIG-1234](https://gemeente-amsterdam.atlassian.net/browse/SIG-1234)
=> [feat-5110]: Revert "Add credentials to fetch api in useFetch/All hooks. (#2541)"

src/components/AutoSuggest/components/SuggestList/SuggestList.tsx, src/components/Select/Select.test.js, src/components/Select/Select.tsx, src/components/SelectSearch/SelectOption.test.tsx, src/components/SelectSearch/SelectOption.tsx, src/components/SelectSearch/SelectSearch.test.tsx, src/components/SelectSearch/SelectSearch.tsx, src/components/SelectSearch/index.ts, src/components/SelectSearch/styled.ts, src/hooks/useRoveFocus.test.ts, src/hooks/useRoveFocus.ts, src/signals/incident-management/components/SelectInputSearch/__tests__/SelectInputSearch.test.js, src/signals/incident-management/components/SelectInputSearch/index.js, src/signals/incident-management/containers/IncidentDetail/components/ChangeValue/ChangeValue.test.js, src/signals/incident-management/containers/IncidentDetail/components/ChangeValue/ChangeValue.tsx, src/signals/incident-management/containers/IncidentDetail/components/MetaList/MetaList.tsx
add new component that adds search to select func. Its accessible like a select.
Ticket: [SIG-5082](https://gemeente-amsterdam.atlassian.net/browse/SIG-5082)
=> [feat-5082]: Add select search combobox

src/components/SelectSearch/SelectSearch.test.tsx, src/components/SelectSearch/SelectSearch.tsx
Ticket: [SIG-5082](https://gemeente-amsterdam.atlassian.net/browse/SIG-5082)
=> [feat-5082]: Search in selectSearch by pressing alphanumeric values

src/signals/incident-management/containers/IncidentDetail/components/Attachments/Attachments.tsx, src/signals/incident-management/containers/IncidentDetail/components/FileInput/FileInput.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/FileInput/FileInput.tsx
Ticket: [SIG-5171](https://gemeente-amsterdam.atlassian.net/browse/SIG-5171)
=> [feat-5171]: Make fileinput accessible by focus + keypress enter label

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx
**Context**
Add featureFlag to prevention of closure of issue with Category Overig-Overig.. 
- add featureflag disableClosingCategoryOverigOverig
- add test
**Release Notes**
- add featureflag disableClosingCategoryOverigOverig to app.amsterdam.json to true
- add featureflag disableClosingCategoryOverigOverig to app.base.json to false
Ticket: [SIG-5176](https://gemeente-amsterdam.atlassian.net/browse/SIG-5176)
- Committed source code is headed by the correct SPDX license …
=> [bugfix-5176] Add featureFlag to prevention of closure of issues with category overig-overig

src/components/SelectSearch/SelectSearch.test.tsx, src/components/SelectSearch/SelectSearch.tsx
Ticket: [SIG-5185](https://gemeente-amsterdam.atlassian.net/browse/SIG-5185)
=> [fix-5185]: Select first option as default when pressing enter

src/signals/incident-management/containers/IncidentDetail/IncidentDetail.tsx
Ticket: [SIG-5172](https://gemeente-amsterdam.atlassian.net/browse/SIG-5172)
=> [fix-5172]: Fix double queries on IncidentDetail

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/constants.ts, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/reducer.ts, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/utils.ts, src/signals/incident-management/definitions/types.ts
Ticket: [SIG-5187](https://gemeente-amsterdam.atlassian.net/browse/SIG-5187)
=> [chore-5187]: refactor disable overig category

src/signals/incident-management/containers/IncidentDetail/IncidentDetail.tsx
=> Get history in incident detail when incident id changes

src/signals/settings/categories/components/CategoryForm.test.tsx, src/signals/settings/categories/components/CategoryForm.tsx
Ticket: [SIG-5184](https://gemeente-amsterdam.atlassian.net/browse/SIG-5184)
=> [feat-5184]: Remove is_public_accessible setting for main categories

src/signals/incident-management/containers/IncidentDetail/IncidentDetail.tsx
Ticket: [SIG-5205](https://gemeente-amsterdam.atlassian.net/browse/SIG-5205)
=> [bugfix-5205]: Fix unnecessary history calls but do sync history

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.tsx, src/signals/incident/definitions/wizard-step-2-vulaan/eikenprocessierups.ts
Ticket: [SIG-5210](https://gemeente-amsterdam.atlassian.net/browse/SIG-5210)
=> [bugfix:-5210]: Implement featureflag for gisib

src/signals/incident/definitions/__tests__/wizard-step-4-summary.test.js, src/signals/incident/definitions/wizard-step-2-vulaan/afval.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/afval.ts
Reverts Amsterdam/signals-frontend#2579
Due to miscommunication changes were made to the wrong aanvullende vragen. A new PR and story in Jira is being made and this one will be closed.
=> Revert "[feat-5164] Change in aanvullende vragen afval"

app.amsterdam.json
Revert when testing is successful on acceptance.
Ticket: [SIG-5219](https://gemeente-amsterdam.atlassian.net/browse/SIG-5219)
=> [feat-5219]: Change authEndpoint for test

app.amsterdam.json
Reverts Amsterdam/signals-frontend#2584
=> Revert "[feat-5219]: Change authEndpoint for test"

src/signals/incident/definitions/wizard-step-2-vulaan/overlast-van-dieren.ts
Ticket: [SIG-5060](https://gemeente-amsterdam.atlassian.net/browse/SIG-5060)
=> [feat-5060]: Text change harde stop

src/signals/incident/definitions/__tests__/wizard-step-4-summary.test.js, src/signals/incident/definitions/wizard-step-2-vulaan/afval.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/afval.ts
Created additional questions to subcategories:
asbest-accu
handhaving-op-afval
First question is not required, as discussed with Linda. The second one is.
Ticket: [SIG-5211](https://gemeente-amsterdam.atlassian.net/browse/SIG-5211)
=> [feat-5211] Aanvullende vragen handhaving-op-afval and Gedumpt-gevaarlijk-afval

src/components/AddNote/AddNote.tsx, src/signals/incident/components/form/TextareaInput/TextareaInput.test.tsx, src/signals/incident/components/form/TextareaInput/TextareaInput.tsx
Ticket: [SIG-1234](https://gemeente-amsterdam.atlassian.net/browse/SIG-1234)
=> First steps for adding subtitle to textareainput

src/components/AutoSuggest/AutoSuggest.test.tsx, src/components/SelectSearch/SelectSearch.test.tsx, src/components/SelectSearch/SelectSearch.tsx, src/signals/incident-management/components/SelectInputSearch/__tests__/SelectInputSearch.test.js, src/signals/incident-management/containers/IncidentDetail/IncidentDetail.test.js, src/signals/incident-management/containers/IncidentDetail/components/ChangeValue/ChangeValue.test.js, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/my-incidents/pages/Detail.tsx, src/signals/settings/SettingsModule.test.js, src/signals/settings/users/Overview/__tests__/Overview.test.tsx
Ticket: [SIG-5257](https://gemeente-amsterdam.atlassian.net/browse/SIG-5257)
Note:
Two small warning that I was unable to fix.
=> [chore-5257]: Remove errors jest

src/signals/incident-management/components/ChildIncidents/ChildIncidents.tsx, src/signals/incident-management/containers/IncidentDetail/components/MetaList/MetaList.tsx, src/signals/incident-management/containers/ReporterContainer/components/Header.tsx
Ticket: [SIG-5263](https://gemeente-amsterdam.atlassian.net/browse/SIG-5263)
**for testers**
1
2
3
=> [bug-5263]: Fix backlink, deel- and hoofdmelding links

src/signals/settings/categories/components/CategoryForm.test.tsx, src/signals/settings/categories/components/CategoryForm.tsx
Ticket: [SIG-5218](https://gemeente-amsterdam.atlassian.net/browse/SIG-5218)
=> [feat-5218]: Text change

src/signals/settings/categories/components/CategoryForm.test.tsx, src/signals/settings/categories/components/CategoryForm.tsx
Ticket: [SIG-5218](https://gemeente-amsterdam.atlassian.net/browse/SIG-5218)
=> [feat-5218]: Remove change form subcategory

src/signals/incident-management/containers/IncidentSplitContainer/IncidentSplitContainer.js, src/signals/incident-management/containers/IncidentSplitContainer/IncidentSplitContainer.test.js
Ticket: [SIG-5277](https://gemeente-amsterdam.atlassian.net/browse/SIG-5277)
=> [bug-5277]: Fix deelmelding link

src/signals/settings/categories/components/Detail.tsx
Ticket: [SIG-5119](https://gemeente-amsterdam.atlassian.net/browse/SIG-5119)
=> [bug-5119]: Fix onsubmit logic

package-lock.json
Updating packing with `npm audit fix`
=> [chore]: update packages

app.amsterdam.json, internals/schemas/app.schema.json, src/signals/incident/definitions/wizard-step-2-vulaan/eikenprocessierups.ts
**context**
we are currently using 'isBlocking' in acceptation and production. 
=> [Bug] add useGisib to app.amsterdam.json

src/components/DataView/__tests__/DataView.test.js, src/components/DataView/components/DataViewBody/index.js, src/components/List/__tests__/List.test.js, src/components/List/index.js, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.test.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.tsx, src/signals/incident-management/containers/StandardTextsAdmin/components/Summary/Summary.test.tsx, src/signals/incident-management/containers/StandardTextsAdmin/components/Summary/Summary.tsx, src/signals/incident/components/StepByStepNavClickable/StepByStepNavClickable.test.tsx, src/signals/incident/components/StepByStepNavClickable/StepByStepNavClickable.tsx, src/signals/my-incidents/pages/Confirmation.test.tsx, src/signals/settings/departments/Detail/index.js
**for testers**
go to the ticket, theres is an overview how the interactive listitems should work (button)
Ticket: [SIG-5173](https://gemeente-amsterdam.atlassian.net/browse/SIG-5173)
=> [feat-5173]: Add tabindexes and  role button to list items

src/signals/incident-management/containers/StandardTextsAdmin/components/OverviewPage/OverviewPage.tsx, src/signals/incident-management/containers/StandardTextsAdmin/components/SelectedSubcategories/SelectedSubcategories.tsx, src/signals/incident-management/containers/StandardTextsAdmin/components/styled.ts
Resolved feedback concerning styling from Linda
Link has now styling text-decoration: none.
Ticket: [SIG-5287](https://gemeente-amsterdam.atlassian.net/browse/SIG-5287)
=> [feat-5287] change styling

internals/mocks/fixtures/standard-texts/default.json, src/signals/incident-management/containers/StandardTextsAdmin/components/DetailPage/Detail.test.tsx, src/signals/incident-management/containers/StandardTextsAdmin/components/DetailPage/Detail.tsx
Ticket: none
Adjusting test of detailPage to cover the actual flow.
=> [chore]: Fix query tests

package.json, src/signals/incident-management/components/FilterForm/utils/has-too-many-filters-selected.ts, src/signals/incident-management/containers/StandardTextsAdmin/components/Summary/Summary.test.tsx
Ticket: none
Somehow the test coverage on `main` was down the threshold, therefore all PR's failed. This PR bumps it above the threshold again.
=> [chore]: Fix test coverage

app.amsterdam.json, src/signals/settings/SettingsModule.test.js, src/signals/settings/SettingsModule.tsx
=> [chore]: Change apiBaseUrl

src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitSelectInput/IncidentSplitSelectInput.tsx, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitSelectInput/__tests__/IncidentSplitSelectInput.test.js
Ticket: [SIG-5336](https://gemeente-amsterdam.atlassian.net/browse/SIG-5336)
=> [bug-5336]: Show selected option as display value

src/components/PageHeader/PageHeader.tsx, src/components/RadioButtonList/RadioButtonList.test.tsx, src/components/RadioButtonList/RadioButtonList.tsx, src/components/RadioButtonList/RadioButtonOption.tsx, src/components/RadioButtonList/index.tsx, src/components/RadioButtonList/styled.ts, src/components/RadioButtonList/types.ts, src/signals/incident-management/containers/StandardTextsAdmin/components/Filter/Filter.tsx
Ticket: none
Refactor radiobuttonList so that the buttonOption component as it's own file.
=> [chore]: Refactor radioButtonList

src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/styled.tsx
Ticket: [SIG-5286](https://gemeente-amsterdam.atlassian.net/browse/SIG-5286)
=> [fix-5286]: Remove flaky animation

src/components/DataView/components/DataViewBody/index.js, src/components/List/index.js, src/components/SelectSearch/SelectOption.tsx, src/components/Summary/Summary.tsx, src/signals/IncidentMap/components/FilterPanel/FilterCategory.tsx, src/signals/IncidentMap/components/IncidentLayer/IncidentLayer.tsx, src/signals/incident-management/containers/IncidentDetail/components/FileInput/FileInput.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.tsx, src/signals/incident-management/containers/StandardTextsAdmin/components/Summary/Summary.tsx, src/signals/incident/components/StepByStepNavClickable/StepByStepNavClickable.tsx, src/utils/on-button-press.test.ts, src/utils/on-button-press.ts
=> [chore] Extract on button press logic

src/components/CheckboxList/CheckboxList.tsx, src/components/RadioButtonList/RadioButtonOption.tsx, src/signals/incident/containers/KtoContainer/KtoContainer.tsx, src/signals/incident/containers/KtoContainer/components/KtoForm/KtoForm.tsx, src/signals/incident/containers/KtoContainer/utils.test.tsx, src/signals/incident/containers/KtoContainer/utils.ts
Ticket: [SIG-5266](https://gemeente-amsterdam.atlassian.net/browse/SIG-5266)
- Correct order in history. Open answer should come after the related checkbox/radiobutton
- max 1000 characters in textareas
=> [feat-5266]: kto over iets anders feedback

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/components/AreaMap/AreaMap.test.tsx, src/components/AreaMap/AreaMap.tsx, src/signals/incident-management/containers/AreaContainer/components/Filter/Filter.test.tsx, src/signals/incident-management/containers/AreaContainer/components/Filter/Filter.tsx
Ticket: [SIG-5389](https://gemeente-amsterdam.atlassian.net/browse/SIG-5389)
=> [feat-5389]: Make number configurable

src/signals/incident-management/containers/StandardTextsAdmin/components/OverviewPage/OverviewPage.test.tsx, src/signals/incident-management/containers/StandardTextsAdmin/components/OverviewPage/OverviewPage.tsx
Ticket: [SIG-5396](https://gemeente-amsterdam.atlassian.net/browse/SIG-5396)
=> [fix-5396]: Add count to title

src/components/ModalDialog/styled.ts, src/signals/incident-management/containers/IncidentDetail/components/EmailPreview/styled.ts
Ticket: [SIG-5295](https://gemeente-amsterdam.atlassian.net/browse/SIG-12345295)
PR feedback.
=> [fix-5295]: modal styling fix

package-lock.json, src/signals/incident-management/containers/AreaContainer/AreaContainer.test.tsx, src/signals/incident-management/containers/AreaContainer/AreaContainer.tsx
Ticket: [SIG-5360](https://gemeente-amsterdam.atlassian.net/browse/SIG-5360)
=> [fix-5360]: Fix redirect when closing invidents nearby overlay

src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/AssetLayer/AssetLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/AssetLayer/AssetLayer.tsx
Ticket: [SIG-5366](https://gemeente-amsterdam.atlassian.net/browse/SIG-5366)
=> [fix-5366]: Add keyboard accessibility to objects on location map

src/components/Notification/index.tsx, src/hooks/useFetch.ts, src/signals/incident-management/containers/StandardTextsAdmin/components/DetailPage/Detail.test.tsx, src/signals/incident-management/containers/StandardTextsAdmin/components/DetailPage/Detail.tsx, src/signals/settings/departments/Detail/index.js, src/signals/settings/hooks/useFetchResponseNotification.test.ts, src/signals/settings/hooks/useFetchResponseNotification.ts, src/signals/settings/users/Detail/index.js
Ticket: none
- Implemented useFetchResponse to standardTexts.
- Also slightly adjusted the hook so it shows a different message depending on the type of request
=> [fix]: fetch notification alignment

src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/AssetLayer/AssetLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/AssetLayer/AssetLayer.tsx
Reverts Amsterdam/signals-frontend#2660
=> Revert "[fix-5366]: Add keyboard accessibility to objects on location map"

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, internals/testing/api.ts, internals/testing/msw-server.ts, src/signals/incident-management/containers/IncidentDetail/IncidentDetail.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Contact/Cancel.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Contact/Contact.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Contact/Contact.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Contact/Edit.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Contact/styled.ts
**for deployment**
is behind feature flag showContactEdit
Ticket: [SIG-5352](https://gemeente-amsterdam.atlassian.net/browse/SIG-5352)
=> [feat-5352]: Add cancel verification email form

src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/AssetLayer/AssetLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/AssetLayer/AssetLayer.tsx
Ticket: [SIG-5366](https://gemeente-amsterdam.atlassian.net/browse/SIG-5366)
=> [fix-5366]: Add keyboard tab focus to object on location map

src/signals/incident-management/containers/StandardTextsAdmin/components/Summary/styled.ts
Ticket: [SIG-5130](https://gemeente-amsterdam.atlassian.net/browse/SIG-5130)
=> [feat-5130]: Change css so solution works on multiple browsers

src/signals/settings/hooks/useFetchResponseNotification.ts
cause sometimes you only want an error notification.
=> [chore] Improve readability and make isloading and redirectUrl optional 

src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Contact/Cancel.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Contact/Contact.test.tsx
Ticket: [SIG-5352](https://gemeente-amsterdam.atlassian.net/browse/SIG-5352)
=> [feat-5352]: Text change

src/signals/incident/components/form/MapSelectors/Asset/Selector/NearbyLayer/NearbyLayer.tsx
Reverts Amsterdam/signals-frontend#2669
=> Revert "[fix]: Add offset to nearby incident icons"

src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Contact/Contact.test.tsx
=> [chore]: Fix tests

src/components/RadioButtonList/RadioButtonList.test.tsx, src/components/RadioButtonList/RadioButtonOption.tsx, src/components/RadioButtonList/styled.ts, src/components/RadioButtonList/types.ts, src/signals/incident-management/containers/StandardTextsAdmin/components/Filter/Filter.tsx, src/signals/incident-management/containers/StandardTextsAdmin/components/OverviewPage/OverviewPage.tsx, src/signals/incident-management/containers/StandardTextsAdmin/types.ts, src/types/api/standard-texts.ts
Ticket: [SIG-5355](https://gemeente-amsterdam.atlassian.net/browse/SIG-5355)
=> [feat-5355]: Add facet count to radioOption

src/components/HistoryList/HistoryList.tsx
=> [fix]: Change react key in HistoryList due to ordering issues

internals/testing/api.ts, internals/testing/msw-server.ts, src/components/pages/VerificationPage/VerificationPage.test.tsx, src/components/pages/VerificationPage/VerificationPage.tsx, src/components/pages/VerificationPage/index.ts, src/components/pages/VerificationPage/styled.ts, src/containers/App/index.tsx, src/shared/services/configuration/endpoint-definitions.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Contact/Contact.test.tsx
validate token when mounted when changing contact data for a signal
Ticket: [SIG-5212](https://gemeente-amsterdam.atlassian.net/browse/SIG-5212)
=> [feat-5212]: Create VerificationPage

internals/scripts/helpers/config.js, src/index.html
Ticket: [SIG-5216](https://gemeente-amsterdam.atlassian.net/browse/SIG-5216)
- Add piwik key to configuration
```
piwik: {
id: "my secret"
}
```
=> [feat-5216]: Add Piwik script

src/signals/incident/components/IncidentForm/index.tsx, src/signals/incident/components/IncidentForm/styled.tsx, src/signals/incident/components/form/DateTimeInput/DateTimeInput.tsx, src/signals/incident/components/form/FileInputRenderer/index.js, src/signals/incident/components/form/MapSelectors/Asset/AssetSelectRenderer/AssetSelectRenderer.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/styled.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/styled.tsx
Add labels with for attribute, set fieldsets instead of labels for groups of labels.
Ticket: [SIG-5420](https://gemeente-amsterdam.atlassian.net/browse/SIG-5420)
=> [feat-5420]: Improve accessibility incidentForm

src/components/CloseButton/CloseButton.tsx, src/signals/my-incidents/components/LoginForm/LoginForm.tsx
Add labels with for attribute, arialabel to empty buttons and missing.
Ticket: [SIG-5422](https://gemeente-amsterdam.atlassian.net/browse/SIG-5422)
=> [feature-5422]: Improve accessibility mijn meldingen

internals/schemas/app.schema.json
=> [fix]: Add piwik schema attribute

internals/schemas/app.schema.json, internals/scripts/helpers/config.js, src/index.html
=> [fix]: Revert piwik stuff

internals/scripts/helpers/config.js
=> [chore]: Add Piwik script quotes

src/__tests__/utils.ts, src/components/GPSButton/GPSButton.tsx, src/hooks/useDeviceMode.test.ts, src/hooks/useDeviceMode.ts, src/signals/IncidentMap/components/DrawerOverlay/DrawerOverlay.tsx, src/signals/IncidentMap/components/DrawerOverlay/styled.ts, src/signals/IncidentMap/components/DrawerOverlay/types.ts, src/signals/IncidentMap/components/DrawerOverlay/utils.test.ts, src/signals/IncidentMap/components/DrawerOverlay/utils.ts, src/signals/IncidentMap/components/Header/Header.test.tsx, src/signals/IncidentMap/components/IncidentMap/IncidentMap.tsx, src/signals/IncidentMap/components/IncidentMap/Pin.test.tsx, src/signals/IncidentMap/components/IncidentMap/Pin.tsx, src/signals/IncidentMap/components/__test__/utils.ts, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.tsx, src/types/device.ts
Ticket: [SIG-5430](https://gemeente-amsterdam.atlassian.net/browse/SIG-5430)
While fixing this bug I centralized the useDeviceMode hook so it's globally available and easier in use.
To fix the bug I added some focusTrapOptions when on mobile.
=> [fix-5430]: Centralize useDeviceMode hook

src/global.css, src/signals/incident-management/containers/IncidentDetail/components/Attachments/Attachments.tsx, src/signals/incident-management/containers/IncidentDetail/components/ChangeValue/ChangeValue.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Contact/Contact.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Contact/Edit.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/styled.tsx
Ticket: [SIG-5431](https://gemeente-amsterdam.atlassian.net/browse/SIG-5431)
=> [feat-5431]: Improve accessibility IncidentDetail

src/signals/my-incidents/__test__/incidents-detail.ts, src/signals/my-incidents/components/History/styled.ts, src/signals/my-incidents/components/IncidentsDetail/ExtraProperties.tsx, src/signals/my-incidents/components/IncidentsDetail/IncidentsDetail.test.tsx, src/signals/my-incidents/components/IncidentsDetail/IncidentsDetail.tsx, src/signals/my-incidents/components/IncidentsDetail/styled.ts, src/signals/my-incidents/types.ts
Add a more descriptive html structure first. 
Then add captions and figures. Separate attachments created by municipality and by user.
Ticket: [SIG-5236](https://gemeente-amsterdam.atlassian.net/browse/SIG-5236)
=> [feat-5236]: Images in my incidents with and without subtitle

src/signals/incident-management/containers/ReporterContainer/useFetchReporter.test.ts
Ticket: none
Test should be fixed since it's flaky. Created a ticket for it: [5467](https://gemeente-amsterdam.atlassian.net/browse/SIG-5467)
=> [chore]: Disable useFetchReporter test since its flaky

src/signals/incident-management/containers/IncidentDetail/components/Attachments/Attachments.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/Attachments/Attachments.tsx
Ticket: [SIG-5466](https://gemeente-amsterdam.atlassian.net/browse/SIG-5466)
=> [fix-5466]: Only enable images to be publically  shown in my-incidents

src/signals/settings/departments/Overview/index.js, src/signals/settings/roles/containers/RolesListContainer/index.js, src/signals/settings/users/Overview/Overview.tsx
Ticket: [SIG-5312](https://gemeente-amsterdam.atlassian.net/browse/SIG-5312)
=> [feat-5312]: Add backlink to settings pages

src/signals/incident-management/saga.js
Ticket: [SIG-5474](https://gemeente-amsterdam.atlassian.net/browse/SIG-5474)
=> [bug-5474]: Encode Uri component to fix zoeken op email bug

src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.test.js
Ticket: [SIG-5488](https://gemeente-amsterdam.atlassian.net/browse/SIG-5488)
=> [fix-5488]: Hide thor button when main and subslug are overig

src/signals/settings/categories/components/Detail.tsx, src/signals/settings/categories/components/IconInput/IconInput.tsx
resolved feedback
- text changes & problem of not always showing icon when navigating to detail page 
One issue still open; how to refresh overview page when clicking back link
Ticket: [SIG-5019](https://gemeente-amsterdam.atlassian.net/browse/SIG-5019)
=> [feat-5019]: resolved feedback from Jelle and Linda

src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/Selector.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/styled.tsx
**updated with input ux**
Ticket: [SIG-5434](https://gemeente-amsterdam.atlassian.net/browse/SIG-5434)
=> [fix-5434]: Styling fixes

src/components/Select/Select.tsx
**context**
this error might duplicate rows. By adding a unique key this problem resolves.
=> [fix] fix two children with same key error

src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/LegendPanel/LegendPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/LegendToggleButton/LegendToggleButton.tsx
Ticket: [SIG-5531](https://gemeente-amsterdam.atlassian.net/browse/SIG-5531)
=> [fix-5531]: Change text and icon in LegendaToggleButton

src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/DetailPanel/DetailPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/DetailPanel/DetailPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/DetailPanel/styled.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/Selector.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/styled.tsx, src/signals/incident/components/form/MapSelectors/Asset/__tests__/withAssetSelectContext.tsx, src/signals/incident/components/form/MapSelectors/constants.ts, src/signals/incident/definitions/wizard-step-2-vulaan/__snapshots__/locatie.test.ts.snap, src/signals/incident/definitions/wizard-step-2-vulaan/afval-container.ts, src/signals/incident/definitions/wizard-step-2-vulaan/eikenprocessierups.ts, src/signals/incident/definitions/wizard-step-2-vulaan/locatie.ts, src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts, src/signals/settings/categories/constants.tsx
Change styling and remove no container found on map functionality.
Ticket: [SIG-5530](https://gemeente-amsterdam.atlassian.net/browse/SIG-5530)
[SIG-5530]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feature-5530]: Add zoeken op locatiekaart on desktop

src/components/Map/Map.tsx
Ticket: [SIG-5544](https://gemeente-amsterdam.atlassian.net/browse/SIG-5544)
[SIG-5544]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [task-5544]: Remove political message from leaflet map

src/signals/settings/roles/containers/RoleFormContainer/components/RoleForm/index.js, src/signals/settings/roles/containers/RoleFormContainer/index.js
Ticket: [SIG-5555](https://gemeente-amsterdam.atlassian.net/browse/SIG-5555)
[SIG-5555]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5555]: Fix success notification message en unnecessary calls/actions

app.amsterdam.json
=> [chore]: Remove double feature flag

src/components/Notification/__tests__/Notification.test.tsx, src/components/Notification/index.tsx, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.test.js, src/signals/incident-management/containers/IncidentOverviewPage/styled.tsx
Ticket: [SIG-5577](https://gemeente-amsterdam.atlassian.net/browse/SIG-5577)
note: this is a subtask, therefore merging with feature branch
[SIG-5577]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-5577]: filter disabling

src/signals/incident/definitions/wizard-step-1-beschrijf.js
Ticket: [SIG-5567](https://gemeente-amsterdam.atlassian.net/browse/SIG-5567)
[SIG-5567]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [chore-5567]: Change intro text

src/components/LoadingIndicator/index.js
Set spinner to 50% of viewport
Ticket: [SIG-5572](https://gemeente-amsterdam.atlassian.net/browse/SIG-5572)
[SIG-5572]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-5572]: restyling spinner

src/signals/incident/components/form/MapSelectors/Asset/AssetList/styled.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/DetailPanel/styled.tsx
Ticket: [SIG-5438](https://gemeente-amsterdam.atlassian.net/browse/SIG-5438)
[SIG-5438]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-5438]: Add 2 remaining styling fixes

src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitForm/__tests__/IncidentSplitForm.test.js, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitFormIncident/IncidentSplitFormIncident.tsx, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitFormIncident/__tests__/IncidentSplitFormIncident.test.tsx, src/signals/incident-management/containers/IncidentSplitContainer/styled.js
Ticket: [SIG-5551](https://gemeente-amsterdam.atlassian.net/browse/SIG-5551)
[SIG-5551]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-5551]: Add delete functionality

src/components/AutoSuggest/AutoSuggest.tsx, src/components/PDOKAutoSuggest/PDOKAutoSuggest.tsx, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.tsx
Cache formatPDOKResponse so it doesnt induce an infinite loop
=> [fix] PDOKAutoSuggest.tsx bug

src/signals/incident-management/containers/IncidentOverviewPage/components/SortIcon/SortIcon.test.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/SortIcon/SortIcon.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/SortIcon/styled.tsx
Ticket: [SIG-5575](https://gemeente-amsterdam.atlassian.net/browse/SIG-5575)
[SIG-5575]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5575]: Relate chevron to sorting option

src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/styled.tsx
Ticket: [SIG-5590](https://gemeente-amsterdam.atlassian.net/browse/SIG-5590)
[SIG-5590]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5590]: Fix height

src/signals/incident-management/components/FilterForm/FilterForm.tsx
Ticket: [SIG-5591](https://gemeente-amsterdam.atlassian.net/browse/SIG-5591)
[SIG-5591]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5591]: Add clear input

src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitFormIncident/IncidentSplitFormIncident.tsx, src/signals/incident-management/containers/IncidentSplitContainer/styled.js
Ticket: [SIG-5540](https://gemeente-amsterdam.atlassian.net/browse/SIG-5540)
[SIG-5540]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5540]: Split form style fixes

src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/WfsLayer/utils/map-data-to-selectable-feature.test.ts, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/WfsLayer/utils/map-data-to-selectable-feature.ts, src/signals/incident/components/form/MapSelectors/types.ts
Ticket: [SIG-5589](https://gemeente-amsterdam.atlassian.net/browse/SIG-5589)
[SIG-5589]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-5589]: Add caterpillar to selectable objects

src/signals/incident-management/components/FilterForm/FilterForm.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/DetailPanel/DetailPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/DetailPanel/DetailPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/DetailPanel/styled.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/styled.tsx
Ticket: [SIG-5592](https://gemeente-amsterdam.atlassian.net/browse/SIG-5592)
[SIG-5592]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5592]: Fix pinned location and placeholder note search

src/signals/incident-management/containers/IncidentOverviewPage/components/List/styles.ts
=> [fix]: Fix Safari box shadow css bug

src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.tsx
Ticket: [SIG-5484](https://gemeente-amsterdam.atlassian.net/browse/SIG-5484)
Story feedback
[SIG-5484]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5484]: Remove outline on click

src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/WfsLayer/utils/get-object-type.test.ts, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/WfsLayer/utils/get-object-type.ts
Ticket: [SIG-5588](https://gemeente-amsterdam.atlassian.net/browse/SIG-5588)
Story feedback
[SIG-5588]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5588]: Fix issue when properties is an array

src/hooks/useRestoreScrollPosition.ts
Ticket: [SIG-5485](https://gemeente-amsterdam.atlassian.net/browse/SIG-5485)
Ticket feedback
[SIG-5485]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5485]: Fix that safari does not set scrollY to 0 when navigating

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/WfsLayer/WfsLayer.tsx
Ticket: [SIG-5598](https://gemeente-amsterdam.atlassian.net/browse/SIG-5598
)
[SIG-5598]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-5598]: Add api key for dataplatform

src/signals/incident/definitions/wizard-step-2-vulaan/overlast-van-dieren.ts
Ticket: [SIG-5602](https://gemeente-amsterdam.atlassian.net/browse/SIG-5602)
[SIG-5602]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-5602]: Change info message on subcategory rats

src/signals/incident/services/map-controls-to-params/map-controls-to-params.ts
=> [fix]: better check for formatISO input

src/signals/my-incidents/components/IncidentsList/IncidentsList.tsx, src/signals/my-incidents/components/IncidentsList/styled.ts
Ticket: [SIG-5604](https://gemeente-amsterdam.atlassian.net/browse/SIG-5604)
[SIG-5604]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5604]: Change My Incidents status text color

src/signals/incident/definitions/wizard-step-2-vulaan/overlast-bedrijven-en-horeca.ts
Ticket: [SIG-5622](https://gemeente-amsterdam.atlassian.net/browse/SIG-5622)
[SIG-5622]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-5622]: Add VTH events subcategory

src/components/AddNote/AddNote.tsx, src/components/TextArea/TextArea.test.tsx, src/components/TextArea/TextArea.tsx, src/components/TextArea/styled.ts, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitForm/IncidentSplitForm.tsx, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitFormIncident/IncidentSplitFormIncident.tsx
Ticket: [SIG-5616](https://gemeente-amsterdam.atlassian.net/browse/SIG-5616)
[SIG-5616]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-5616]: text area description

src/signals/incident/components/form/MapSelectors/Asset/AssetList/AssetList.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetList/AssetList.tsx
Ticket: [SIG-5676](https://gemeente-amsterdam.atlassian.net/browse/SIG-5676)
Fixes this issue:
[SIG-5676]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5676]: Make heading conditional

src/signals/incident/components/form/MapSelectors/Asset/Selector/NearbyLayer/NearbyLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/NearbyLayer/NearbyLayer.tsx, src/signals/incident/containers/IncidentContainer/saga.test.js, src/signals/incident/containers/IncidentContainer/selectors.js
Ticket: [SIG-5677](https://gemeente-amsterdam.atlassian.net/browse/SIG-5677)
[SIG-5677]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-5677]: Do not query current incidents when category is not public available

src/signals/settings/categories/components/CategoryForm.test.tsx, src/signals/settings/categories/components/CategoryForm.tsx, src/signals/settings/categories/components/Detail.tsx, src/signals/settings/categories/components/IconInput/IconInput.tsx
=> [chore]: Fix security issue

.github/review/values.yml, app.amsterdam.json
We the migration the keycloak url needed to be updated.
=> Change keycloak url

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/constants.ts
Ticket: [SIG-5687](https://gemeente-amsterdam.atlassian.net/browse/SIG-5687)
This is the FE work needed to increase the reply mail max length. ~~This also needs some BE work though, so this PR will stay on 'Draft' until that work is finished~~ The BE work is done and deployed to acc.
[SIG-5687]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5687]: Increase reply mail max length

src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx
Ticket: [SIG-5874](https://gemeente-amsterdam.atlassian.net/browse/SIG-5874)
[SIG-5874]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5874]: Fix mobile drawer bug

package-lock.json, package.json
Update dependencies to fix Dependabot security alerts.
=> [chore]: Update dependencies

package-lock.json, src/signals/incident-management/containers/IncidentDetail/components/Attachments/EditAttachment..tsx
Ticket: [SIG-5969](https://gemeente-amsterdam.atlassian.net/browse/SIG-5969)
[SIG-5969]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5969]: Update ws in lockfile to fix security warnings

src/signals/incident/components/ReplyForm/TextArea/TextArea.tsx
Ticket: [SIG-5836](https://gemeente-amsterdam.atlassian.net/browse/SIG-5836)
[SIG-5836]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix]: Change question color incident reply

src/signals/incident/components/IncidentPreview/IncidentPreview.tsx
Ticket: [SIG-5955](https://gemeente-amsterdam.atlassian.net/browse/SIG-5955)
[SIG-5955]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5955]: Fix typo

src/global.css
Ticket: [SIG-5858](https://gemeente-amsterdam.atlassian.net/browse/SIG-5858)
[SIG-5858]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix]: set global webkit-text-size-adjust

src/signals/incident/definitions/wizard-step-2-vulaan/overlast-bedrijven-en-horeca.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-bedrijven-en-horeca.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-van-en-door-personen-of-groepen.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-van-en-door-personen-of-groepen.ts
Ticket: [SIG-6018](https://gemeente-amsterdam.atlassian.net/browse/SIG-6018)
[SIG-6018]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-6018]: Change THOR aanvullende vragen

src/containers/App/index.test.tsx
=> [chore]: Fix App test

src/signals/incident-management/containers/StandardTextsAdmin/components/OverviewPage/OverviewPage.tsx
Ticket: [SIG-6210](https://gemeente-amsterdam.atlassian.net/browse/SIG-6210)
[SIG-6210]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-6210]: Fix navigation bug

src/signals/incident/definitions/wizard-step-2-vulaan.js, src/signals/incident/definitions/wizard-step-2-vulaan/auto-scooter-bromfietswrak.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/auto-scooter-bromfietswrak.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-in-de-openbare-ruimte.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-in-de-openbare-ruimte.ts
Ticket: [SIG-6174](https://gemeente-amsterdam.atlassian.net/browse/SIG-6174)
[SIG-6174]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Change aanvullende vragen auto-, bromfiets-, scooterwrak

src/components/FormField/FormField.tsx, src/signals/incident/definitions/wizard-step-2-vulaan/afval-container.ts, src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts
Ticket: [SIG-6244](https://gemeente-amsterdam.atlassian.net/browse/SIG-6244)
[SIG-6244]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-6244]: Properly check for validateObjectLocation in FormField

src/signals/incident/definitions/wizard-step-5-bedankt.js
This changes the button text to 'Doe nog een melding' and has been discussed with @someren.
=> [feat]: Change button text from 'Doe een melding' to 'Doe nog een melding'

app.base.json, internals/mocks/fixtures/attachments.json, src/signals/incident-management/containers/IncidentDetail/components/Attachments/Attachments.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/ForwardToExternal/ForwardToExternal.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/ForwardToExternal/ForwardToExternal.tsx, src/signals/incident/containers/ExternalReplyContainer/components/ExplanationSection/ExplanationSection.test.tsx, src/signals/incident/containers/ExternalReplyContainer/components/ExplanationSection/ExplanationSection.tsx
Ticket: [SIG-6165](https://gemeente-amsterdam.atlassian.net/browse/SIG-6165)
[SIG-6165]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-6165]:  Hide PDFs from forward to external

src/components/NextButton/NextButton.tsx, src/signals/incident/components/IncidentNavigation/IncidentNavigation.test.tsx, src/signals/incident/components/IncidentNavigation/IncidentNavigation.tsx
Ticket: [SIG-1234](https://gemeente-amsterdam.atlassian.net/browse/SIG-1234)
=> [feat-6288]: Restyle submit button for the app version

src/components/FileInput/FileInput.tsx
Ticket: [SIG-6315](https://gemeente-amsterdam.atlassian.net/browse/SIG-6315)
[SIG-6315]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-6315]: Add capture=camera to file input accept

src/components/FileInput/FileInput.tsx
Ticket: [SIG-6315](https://gemeente-amsterdam.atlassian.net/browse/SIG-6315)
[SIG-6315]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-6315]: Add dummy value to file input

src/signals/incident/definitions/wizard-step-2-vulaan.js, src/signals/incident/definitions/wizard-step-2-vulaan/afval-rolcontainer.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/afval-rolcontainer.ts
Ticket: [SIG-6294](https://gemeente-amsterdam.atlassian.net/browse/SIG-6294)
[SIG-6294]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-6294]: Change rolcontainer questions

src/signals/incident/definitions/wizard-step-2-vulaan/afval-rolcontainer.ts
Ticket: [SIG-6294](https://gemeente-amsterdam.atlassian.net/browse/SIG-6294)
[SIG-6294]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-6294]: Remove periods from answer categories

src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.ts
Ticket: [SIG-6229](https://gemeente-amsterdam.atlassian.net/browse/SIG-6229)
[SIG-6229]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove "Wanneer was het" question in wegen-verkeer

src/components/HistoryList/HistoryList.test.tsx, src/components/HistoryList/HistoryList.tsx
Ticket: [SIG-6389](https://gemeente-amsterdam.atlassian.net/browse/SIG-6389)
[SIG-6389]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Show emphasized text in History list

src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.ts
Ticket: [SIG-6461](https://gemeente-amsterdam.atlassian.net/browse/SIG-6461)
[SIG-6461]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-6461]: Add correct redirect url to fietsnietjes aanvraagformulier

app.amsterdam.json
Ticket: [SIG-6494](https://gemeente-amsterdam.atlassian.net/browse/SIG-6494)
[SIG-6494]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-6494]: Add new urls

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/signals/incident-management/components/FilterForm/FilterForm.tsx, src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.tsx, src/signals/incident-management/containers/FilterTagList/FilterTagList.js, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.test.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.tsx
Ticket: [SIG-6484](https://gemeente-amsterdam.atlassian.net/browse/SIG-6484)
[SIG-6484]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-6484]: Allow sort and filter on GGW districts

src/signals/incident/definitions/wizard-step-2-vulaan/overlast-van-dieren.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-van-dieren.ts
Ticket: [SIG-6471](https://gemeente-amsterdam.atlassian.net/browse/SIG-6471)
[SIG-6471]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-6471]: Change 'overlast van dieren' additional questions

src/signals/incident/definitions/wizard-step-2-vulaan/overlast-van-dieren.ts
Ticket: [SIG-6471](https://gemeente-amsterdam.atlassian.net/browse/SIG-6471)
[SIG-6471]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [chore-6471]: Change spelling error

src/signals/incident/definitions/wizard-step-2-vulaan/afval-thor.ts
Ticket: [SIG-6482](https://gemeente-amsterdam.atlassian.net/browse/SIG-6482)
[SIG-6482]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-6482]: Change grofvuil to grof afval

src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.test.tsx
=> Add test case when enableSortAndFilterStadsdeel is false

src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts
Ticket: [SIG-6791](https://gemeente-amsterdam.atlassian.net/browse/SIG-6791)
[SIG-6791]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adjust straatverlichting additional questions

src/signals/incident/definitions/wizard-step-2-vulaan.js, src/signals/incident/definitions/wizard-step-2-vulaan/maaien.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/maaien.ts, src/signals/incident/definitions/wizard-step-2-vulaan/snoeien.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/snoeien.ts, src/signals/incident/definitions/wizard-step-4-summary.js
Ticket: [SIG-6676](https://gemeente-amsterdam.atlassian.net/browse/SIG-6676)
[SIG-6676]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adjust snoeien-maaien aanvullende vragen
