Amsterdam/signals-frontend

src/components/Header/__snapshots__/index.test.js.snap, src/components/Header/index.js, src/containers/App/index.js, src/containers/HeaderContainer/__snapshots__/index.test.js.snap, src/containers/HeaderContainer/index.js, src/shared/services/auth/auth.js, src/signals/incident-management/components/IncidentManagementModule/__snapshots__/index.test.js.snap, src/signals/incident-management/components/IncidentManagementModule/index.test.js
Men vond het verwarrend dat er in de incident-wizard pagina's (ook zichtbaar
voor burgers) inlog-knoppen zichtbaar waren, terwijl burgers niet kunnen
inloggen.
Deze patch maakt de inlog-knoppen onzichtbaar wanneer het pad van de huidige
URL begint met "/incident/".
Niet gedaan. Het betreft een hot-fix, base en target zijn daarom `master`.
Ik kon nergens vinden hoe dat moet...
=> Hot fix om login-knoppen onzichtbaar te maken voor burgers.

src/signals/incident-management/components/FilterForm/__test__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/components/FilterForm/parse.js, src/signals/incident-management/containers/Filter/index.js, src/signals/incident-management/containers/IncidentOverviewPage/reducer.js
This PR adds a group of checkboxes to the incident filter form. For that to work, the options needed to be present in the state and, as such, are hardcoded in the `incidentOverviewPage` initial state of the `IncidentOverviewPage` reducer.
=> SIG-1340 Feedback filter options

src/signals/incident-management/components/FilterForm/__test__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/__test__/parse.test.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/components/FilterForm/parse.js, src/signals/incident-management/components/RadioButtonList/index.js, src/signals/incident-management/containers/Filter/__tests__/saga.test.js, src/signals/incident-management/containers/Filter/index.js, src/signals/incident-management/containers/Filter/saga.js, src/signals/incident-management/containers/IncidentOverviewPage/reducer.js
This PR:
- Alters the `Form` container's saga so that updating and saving filter a filter is handled by a detached task. This was necessary, because the actions to update and save a filter were called from the `Filter` form component that was unmounted before the saga's async request could be completed.
- Also changes said saga so that the filter endpoints receive the data format they expect; the `options` prop was missing.
- Inject the `activeFilter` data from the store into the `Filter` form component; the data from `IncidentOverviewPage` didn't have all the props, like `id`
- Changes saga tests to unit tests to ensure coverage
- Adds a `RadioButtonList` component
=> (Fix) Filter post payload

src/components/SiteHeader/index.js
This PR fixes an alignment issue of the menu items in IE11
Before:
After:
=> SIG-1563 Menu item alignment

src/signals/incident-management/components/FilterForm/__test__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/__test__/parse.test.js, src/signals/incident-management/components/FilterForm/index.js
This PR contains a fix for the date field where, when the value was cleared after it contained a value before, the filter would still pick up the previous filled value.
Note that this fix doesn't come with a test, because of the inability to test the datepicker package. See https://github.com/Hacker0x01/react-datepicker/issues/1578 for reference.
=> SIG-1563 Clearing date field fix

src/signals/incident/containers/IncidentContainer/index.js
This PR reverts a previous change (https://github.com/Amsterdam/signals-frontend/commit/1dfe492b05b2c74b35dd3a402f93b4bbec94af95#diff-285fc137232757bf65f49b8a2d7515e2) that inadvertedly reverted other changes which caused the 'Melden' page to have a wrong lay-out.
=> SIG-1563 Melden page lay-out fix

src/polyfills.js
This PR contains an extra polyfill that targets missing support for `Object.entries` which targets older browsers and IE specifically.
=> SIG-1630 Filter save bug

src/signals/incident-management/components/FilterForm/styled.js
In IE, the reset button didn't have a white background color.
=> SIG-1634 Filter form reset button background color

src/signals/incident-management/components/SelectInput/index.js, src/signals/incident-management/containers/DefaultTextsAdmin/components/DefaultTextsForm/index.js, src/signals/incident-management/containers/DefaultTextsAdmin/components/DefaultTextsForm/style.scss, src/signals/incident-management/containers/DefaultTextsAdmin/components/SelectForm/index.js
This PR:
- Adjusts the appearance of defaults texts section headers
- Uses `@datapunt/asc-ui` component to style the form's buttons
- Adds a check to the `SelectInput` component so that, when no value is passed for its `display` prop, no container element is rendered
=> SIG-1637 Standaard teksten lay-out adjustments

src/shared/services/map-categories/index.js, src/shared/services/map-categories/index.test.js, src/signals/incident-management/components/CheckboxList/__test__/CheckboxList.test.js, src/signals/incident-management/components/CheckboxList/index.js, src/signals/incident-management/components/FilterForm/__test__/parse.test.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/components/FilterForm/parse.js, src/signals/incident-management/containers/Filter/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.test.js
This PR contains changes that fix an issue where checkboxes in a group were checked where they shouldn't be. The origin of the issue was values of slug properties of categories coming from the API. This fix in this PR no longer matches on slugs, but on id's (or keys).
=> SIG-1640 Checkbox group selection fix

src/signals/incident-management/components/CheckboxList/__test__/CheckboxList.test.js, src/signals/incident-management/components/CheckboxList/index.js, src/utils/__tests__/fixtures/categories.json
This PR contains a fix for errors that popped up when editing a stored filter. The cause was a faulty check in the `CheckboxList` component that determined what the value for a checkbox should be. A test has been added to ensure that this issue doesn't occur again.
=> SIG-1563 CheckboxList error fix

src/signals/incident-management/containers/MyFilters/components/FilterItem/__tests__/FilterItem.test.js, src/signals/incident-management/containers/MyFilters/components/FilterItem/index.js
This PR fixes an issue where, in IE11, an error would be thrown when `document.dispatchEvent` would be called.
=> SIG-1650 Edit filter button fix

internals/webpack/webpack.prod.babel.js
In production, the formdata polyfill was missing in the application's entries.
=> (Hotfix) Formdata polyfill

src/containers/SearchBar/__tests__/SearchBar.test.js, src/containers/SearchBar/index.js
This PR contains a fix for the issue where, when pressing keys on a numeric keypad, the keys would not be accepted by the `SearchBar` input element. The restriction has been removed completely, since entering invalid values doesn't lead to a breaking application and we will have to remove the restriction anyway when search is expanded from ID to all fields in the db.
=> SIG-1676 Fix keypad issue

src/signals/incident-management/containers/IncidentDetail/index.js
This PR fixes an issue where both map and pictures weren't displayed at 100% of the width of their container.
Before:
After:
=> SIG-1659 Incident detail preview full-width

src/components/SiteHeader/index.js
This PR fixes a small screen lay-out problem for the main menu.
**Before**
---
**After**
=> SIG-1669 Mobile header layout

src/components/PageHeader/index.js, src/containers/PageHeader/index.js, src/signals/incident-management/components/FilterForm/__test__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/containers/Filter/__tests__/saga.test.js, src/signals/incident-management/containers/IncidentOverviewPage/actions.js, src/signals/incident-management/containers/IncidentOverviewPage/actions.test.js, src/signals/incident-management/containers/IncidentOverviewPage/constants.js, src/signals/incident-management/containers/IncidentOverviewPage/saga.js, src/signals/incident-management/containers/IncidentOverviewPage/saga.test.js
This PR:
- Adds a generator to the `IncidentOverviewPage` saga that is invoked whenever the `fetchIncidents` generator is invoked
- The new generator contains a race condition between two different actions; one that starts and another one that ends the generator
- Sets a 2 minute refresh interval for incidents. The interval only applies whenever the active filter has been set to be refreshed periodically
=> SIG-1665 Two minute incidents refresh

src/signals/incident-management/containers/IncidentDetail/index.js, src/signals/incident-management/containers/IncidentDetail/index.test.js
This release contains a hotfix that resolves an issue where an incident's history and attachments would not be reloaded on navigation from incident detail to incident detail.
=> Incident history fix release

package-lock.json, package.json, src/components/Footer/__snapshots__/index.test.js.snap, src/components/Footer/index.js, src/components/SiteHeader/__tests__/SiteHeader.test.js, src/components/SiteHeader/index.js, src/components/ThemeProvider/index.js, src/containers/App/index.js, src/containers/App/index.test.js, src/containers/App/reducer.js, src/containers/App/reducer.test.js, src/containers/App/saga.js, src/containers/PageHeader/index.js, src/containers/SiteHeader/index.js, src/models/incident/saga.test.js, src/shared/services/api/api.js, src/shared/services/api/api.test.js, src/shared/services/auth/auth.js, src/shared/services/auth/auth.test.js, src/signals/incident-management/components/IncidentManagementModule/index.js, src/signals/incident-management/components/IncidentManagementModule/index.test.js, src/signals/incident/containers/IncidentContainer/index.js, src/signals/incident/containers/IncidentContainer/index.test.js
This PR contains changes that prevents component from rerendering when the `makeSelectIsAuthenticated` selector updates its value and passes a different prop value to the appropriate components. 
The previous asynchronous behaviour caused several issues.; logging in wouldn't always redirect the user to the incidents overview page and the header component would render its `tall` version and, after getting a different value for the authentication, would render its `short` version.
=> (Chore) Remove authenticated selector

src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/components/DownloadButton/index.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/components/DownloadButton/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.test.js, src/signals/incident-management/containers/IncidentDetail/index.js, src/signals/incident-management/containers/IncidentDetail/index.test.js
This PR removes the requirement for both `IncidentDetail` container and its `DetailHeader` component for receiving a value for their `accessToken` props and moves that responsibility to the `DownloadButton` components.
The proposed change is a fix on top of the #351 PR.
=> (Chore) DownloadButton access token

src/signals/incident/components/form/RadioInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/RadioInput/index.js, src/signals/incident/components/form/RadioInput/index.test.js
This PR alters the `RadioInput` component so that the warning with regards to using the `checked` attribute in combination with a `onClick` handler instead of an `onChange` handler, isn't shown anymore.
=> (Chore) Prevent warning

Jenkinsfile, docker-compose.yml
This PR removes the `build` stage from the current build stages. The `build` stage wasn't needed since, when there is a new version of the code, the build is run anyway, regardless of which stage runs when.
=> (Chore) Remove container

src/components/TextArea/__tests__/TextArea.test.js, src/components/TextArea/index.js, src/signals/incident-management/components/TextAreaInput/__snapshots__/index.test.js.snap, src/signals/incident-management/components/TextAreaInput/index.js, src/signals/incident-management/components/TextInput/index.js, src/signals/incident/components/form/DescriptionWithClassificationInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/DescriptionWithClassificationInput/index.js, src/signals/incident/components/form/DescriptionWithClassificationInput/index.test.js, src/signals/incident/components/form/MultiTextInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/MultiTextInput/index.js, src/signals/incident/components/form/MultiTextInput/index.test.js, src/signals/incident/components/form/TextInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/TextInput/index.js, src/signals/incident/components/form/TextInput/index.test.js, src/signals/incident/components/form/TextareaInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/TextareaInput/index.js, src/signals/incident/components/form/TextareaInput/index.test.js
This PR fixes an issue in IE11 where, when the contents of a textarea was scrolled, it would leave a trail of horizontal lines in front of the content. The cause of this behaviour was the element's box-shadow.
In order to fix the problem, the `<textarea>` elements in the application have been replaced by styled components. This also goes for `<input type"text">` elements where applicable.
=> SIG-1713 Textarea scroll lines fix

Jenkinsfile, internals/webpack/webpack.prod.babel.js
This PR removes the reference to `.htaccess` from the offline plugin configuration. The plugin is set to not cache the `.htaccess` file, but since that file is forbidden to access and the server returns a 403, the service worker's response is faulty.
Next to that, the `NODE_ENV` settings in the `Jenkinsfile` have been removed since the `Dockerfile` always sets that var to 'production'
=> (Chore) Remove .htaccess reference

src/models/history/reducer.js
Please note: When the detail page is loaded, all services are called simultaneously:
`this.props.onRequestIncident(this.props.id);
this.props.onRequestHistoryList(this.props.id);
this.props.onRequestAttachments(this.props.id);
`
the incident is already emptied:
`    case REQUEST_INCIDENT:`
`    return state`
`    .set('loading', true)`
`      .set('error', false)`
`        .set('id', action.payload)`
`        .set('incident', null);`
and the attachments are already emptied:
`case REQUEST_ATTACHMENTS:`
`    return state`
`    .set('attachments', fromJS([]));`
In this PR:
- added only emptying of the history when called.
=> [SIG-1803] when REQUEST_HISTORY_LIST the redux state is emptied now

src/components/SiteHeader/index.js, src/components/TextArea/index.js
This PR renders a `<textarea>` element instead the `<TextArea>` component from `asc-ui` to overcome attributes being applied that shouldn't be applied, like `spellCheck={false}`.
In addition to that, this PR corrects the position of the `#header:after` element in IE11.
=> [SIG-1841] - Textarea spellcheck allow

src/components/Modal/__tests__/Modal.test.js, src/components/Modal/index.js
Fix for a problem where, when a modal was opened, the contents could not be scrolled on iOS devices.
=> [SIG-1714] - Modal scroll on smaller screens

internals/webpack/webpack.prod.babel.js
The health endpoint `version.txt` doesn't need to be cached by the serviceworker.
=> (Chore) Exclude version.txt in serviceworker

.eslintrc.js, .prettierrc, src/signals/incident-management/.eslintrc.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/containers/Filter/__tests__/Filter.test.js, src/signals/incident-management/containers/IncidentDetail/components/Highlight/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident/components/form/CheckboxInput/index.test.js, src/signals/incident/components/form/DateTimeInput/index.test.js, src/signals/incident/components/form/DescriptionWithClassificationInput/index.test.js, src/signals/incident/components/form/FileInput/index.test.js, src/signals/incident/components/form/Header/index.test.js, src/signals/incident/components/form/HiddenInput/index.test.js, src/signals/incident/components/form/MapInput/index.test.js, src/signals/incident/components/form/MapSelect/index.test.js, src/signals/incident/components/form/MultiTextInput/index.test.js, src/signals/incident/components/form/RadioInput/index.test.js, src/signals/incident/components/form/SelectInput/index.test.js, src/signals/incident/components/form/TextInput/index.test.js, src/signals/incident/components/form/TextareaInput/index.test.js, src/signals/incident/definitions/components/Concat/index.test.js, src/signals/incident/definitions/components/Ul/index.test.js
This PR contains a change that should improve readability. It changes this:
```jsx
wrapper = shallow(<CheckboxInput
handler={handler}
parent={parent}
touched={touched}
hasError={hasError}
getError={getError}
/>);
```
into this:
```jsx
wrapper = shallow(
<CheckboxInput
handler={handler}
parent={parent}
touched={touched}
hasError={hasError}
getError={getError}
/>
);
```
=> (Chore) Adjust eslint rules

package-lock.json, src/components/SiteHeader/index.js
This PR fixes an issue where the site header would not be displayed correctly on smaller screens. This was due to a change in a component in the ASC-UI lib.
**Before**
**After**
=> [SIG-1732] Mobile header fix

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js
This PR sets the line-height for the status change feedback block.
Before:
After:
=> [SIG-1782] Toelichting line-height

src/containers/App/index.test.js, src/containers/App/reducer.js, src/containers/App/reducer.test.js, src/containers/App/saga.test.js, src/shared/services/api/api.test.js, src/shared/services/auth/auth.js, src/shared/services/auth/auth.test.js, src/signals/incident-management/__tests__/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/components/DownloadButton/index.test.js, src/signals/incident/containers/IncidentContainer/index.test.js
This PR replaces all occurrences of `sessionStorage` with `localStorage` which persists the authenticated user across browser windows and tabs.
Note: for now, only authentication data is stored in `localStorage` so it's okay to have tests mock `localStorage.getItem` and `localStorage.getItem`, but when more data is stored, those tests need to be changed and their mocks be more specific.
=> [SIG-1745] Move authenticated session from sessionstorage to localstorage

src/signals/incident/components/IncidentPreview/components/ListObjectValue/style.scss
=> fix for IE11 by removing family

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.js
This PR adds extra checks to the `IncidentOverviewPage` component for the modal closing logic. It sometimes happens that `closeFilterModal` handler is called when the modal isn't opened. This happened for me when I tried to make a screenshot of a part of the page and pressed the ESCAPE button to cancel making a screenshot.
=> (Fix) Active element warning

internals/webpack/webpack.base.babel.js, package-lock.json, package.json, src/components/List/__tests__/List.test.js, src/components/List/index.js, src/components/Pager/index.js, src/components/Pager/index.test.js, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.test.js, src/signals/settings/index.js, src/signals/settings/routes.js, src/signals/settings/users/containers/Overview/__tests__/Overview.test.js, src/signals/settings/users/containers/Overview/hooks/__tests__/useFetchUsers.test.js, src/signals/settings/users/containers/Overview/hooks/useFetchUsers.js, src/signals/settings/users/containers/Overview/index.js
This PR contains changes that allow users overview navigation elements to navigate from page to page.
In order to do so, this PR:
- simplifies the `List` component so that it is not responsible anymore for pushing a state to the history stack
- takes the calculation for the total number of pages out of the current `Pager` component
- skips `Pager` component tests (component will be replaced in later PR)
- adds route definitions for the `settings` module
- changes the `Users` overview container so that it responds to both `page` state value changes as well as `location` changes
- uses the `AbortController` web API to make sure that pending XHR requests get canceled whenever the `useFetchUsers` hook unmounts.
=> (Chore) page-to-page navigation

src/signals/settings/users/containers/Overview/__tests__/Overview.test.js, src/signals/settings/users/containers/Overview/index.js
This PR removes one of the listeners in the `UsersOverview` container component. As it turns out, the logic wasn't necessary and was actually blocking navigation from the users detail page back to the overview page.
=> (chore) Remove complex logic

src/models/incident/saga.js, src/models/incident/saga.test.js
The API response bodies haven't got a uniform format. This PR hardcodes the 403 alert message to overcome that problem.
=> (chore) Hardcode 403 message

src/signals/settings/users/containers/Detail/__tests__/Detail.test.js, src/signals/settings/users/containers/Detail/hooks/__tests__/useFetchUser.test.js, src/signals/settings/users/containers/Detail/hooks/useFetchUser.js, src/signals/settings/users/containers/Detail/index.js
This PR puts the responsibility for determining if a form should based on the state in the `UserDetail` component instead of tightly coupling the component and the `useFetchUser` hook.
Additional test were added to ensure the functional side of the change.
=> (chore) Simplify useFetchUser hook

src/components/Input/__tests__/Input.test.js, src/components/Input/index.js, src/signals/settings/users/containers/Detail/components/UserForm/index.js
This PR changes the `Input` component so that it can display an error message related to that field.
=> [SIG-1971] Input field error message

src/index.html
This PR adds a `<script>` tag to the public html file so that Pingdom can track RUM
=> (chore) Pingdom script

src/components/Input/__tests__/Input.test.js, src/components/Input/index.js
This PR adds a coloured border to an input element whenever it's status should display an error
=> (chore) Input error styling

src/components/FormFooter/__tests__/FormFooter.test.js, src/components/FormFooter/index.js
This PR alters the `FormFooter` component so that callback function props are no longer required to render any of the buttons. Callback functions can programmatically be set later or by setting a form
s `onReset` or `onSubmit` attributes.
=> (chore) Change FormFooter render requirements

Jenkinsfile
This PR contains a change that will (hopefully) prevent failing Jenkins builds in the future. An analysis of failing jobs lead to finding error messages that were related to Docker trying to remove already removed containers or trying to remove containers that already had been marked for removal. 
The issue, as it turned out, was that names used for individual containers, weren't unique. Because any pull request runs two builds that use a container with the same name, the clean-up process encountered problems unrelated to the code, but still failed.
Replacing `GIT_COMMIT` with `BUILD_TAG` should fix this issue, because the build tag contains either the Github PR number or the branch name as well as the current build number. That combination makes it unique across builds.
=> (chore) Change Docker project name

src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.js, src/signals/incident-management/containers/IncidentOverviewPage/components/List/style.scss
In this PR:
- removed id styling 
- in the incident list table cells are now completely clickable
Please note the version has been approved by Herjen
=> Sig 1965 open melding in browser tab fix

src/signals/incident-management/containers/IncidentOverviewPage/index.test.js
This PR removes an `async` declaration from a test case. Jest kept waiting for the function to be resolved, but that never happened within the configured default timeout (5000 ms).
=> (fix) Removes async indicator

src/components/Pagination/__tests__/Pagination.test.js, src/components/Pagination/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.test.js
This PR:
replaces the incidents list with a notification when no incidents are returned from the filter request
makes sure that the Pagination component doesn't render any navigation buttons when there isn't more than one page to be displayed
=> [SIG-1818] 0 Meldingen gevonden

src/signals/incident-management/components/FilterForm/__test__/FilterForm.test.js, src/signals/settings/__tests__/index.test.js
This PR contains changes that should prevent Jenkins from tripping over async tests that do not use `await` or return anything
=> (chore) Remove async from tests

src/signals/incident-management/components/FilterForm/__test__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js
This PR contains that ensures that the address field in the filter form is emptied when the form's reset button is clicked.
=> [SIG-2006] Clear address field on form reset

src/signals/incident-management/index.js
This PR replaces a `<Fragment>` component with a `react-router-dom` `<Switch>` component.
I encountered an issue where opening an incident detail page and then reloading that page, would load the incident overpage instead of staying on the detail page. This was due to the fact that the `<Route>` components weren't wrapped in a `<Switch>` and thus encountered more than one match and rendered the last found route's component.
=> (chore) Switch instead of Fragment

internals/testing/test-bundler.js
This PR contains a change to the test setup so that, when tests are run in Jenkins, or whatever CI, console warn messages will be suppressed. Those messages are generated by dependencies are of no importance in the CI log.
=> (chore) Prevent log pollution

src/signals/incident-management/components/CalendarInput/CustomInput.js, src/signals/incident-management/components/CalendarInput/__tests__/CalendarInput.test.js, src/signals/incident-management/components/CalendarInput/__tests__/CustomInput.test.js, src/signals/incident-management/components/CalendarInput/index.js
This PR adds the `CalendarInput` and `CustomInput` components. They both are needed to render a date input field like so:
instead of:
=> [SIG-2038] Date field helper components

src/signals/incident-management/containers/IncidentOverviewPage/saga.js, src/signals/incident-management/containers/IncidentOverviewPage/saga.test.js
This PR contains changes that, despite receiving a response with a `500` status code, make sure that `requestIncidentsSuccess` is dispatched. In the case of the search endpoint, a `500` status code means that the Elasticsearch index is corrupt, for whatever reason. Since there is no other endpoint to fall back to and we still need to show feedback to the user, showing a search result with `0 meldingen` is considered to be better than showing an error notification.
=> [SIG-1816] - Error handling for corrupted elastic index

src/signals/incident-management/__tests__/reducer.test.js, src/signals/incident-management/components/FilterForm/__test__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/reducer.js
This PR fixes an issue where, when the filter form was reset, the global store wasn't properly updated and, as a result, rendered the `FilterForm` component with the wrong data.
In addition, this PR:
- contains fixes for tests for the `FilterForm` component
- wraps functions with `useCallback`
- fixes another issue with the `name` field where its contents couldn't be altered after resetting the form (replacing `defaultValue` with `value`)
- makes specific props required instead of leaving them optional
=> (fix) Clear filter

src/components/SiteHeader/__tests__/SiteHeader.test.js, src/components/SiteHeader/index.js, src/containers/App/actions.js, src/containers/App/actions.test.js, src/containers/App/reducer.js, src/containers/App/reducer.test.js, src/containers/App/saga.js, src/containers/App/saga.test.js, src/containers/App/selectors.js, src/containers/App/selectors.test.js, src/containers/SiteHeader/__tests__/SiteHeader.test.js, src/containers/SiteHeader/index.js, src/shared/services/auth/auth.js, src/shared/services/configuration/configuration.js, src/shared/types/index.js, src/utils/__tests__/fixtures/user.json
This PR replaces the `v0` user endpoint with the `v1` endpoint. The former returned a list of permission identifiers as string. The latter returns multiple lists of objects that need to be parsed and computed. 
Therefore, this PR:
- changes the `AUTH_ME_ENDPOINT` property of the `Configuration` class
- adds a `permissionsType` type
- updates the `user` fixture
- changes the `global` state signature by removing `userName`, `userScopes` and `accessToken` in favour of a single `user` entry
- adds new selectors:
- `makeSelectUserPermissions`: returns the permission objects aggregated from user roles and individual permissions
- `makeSelectUserPermissionCodeNames`: returns a list similar to what the `v0` returns
- `makeSelectUserCan`: returns a boolean indicating the presence of an individual …
=> [SIG-2012] Replace auth v0 endpoint

src/shared/types/index.js, src/signals/incident-management/components/FilterForm/__test__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/components/FilterForm/styled.js, src/signals/incident-management/containers/FilterTagList/__tests__/FilterTagList.test.js, src/signals/incident-management/containers/FilterTagList/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.test.js, src/signals/shared/filter/__tests__/parse.test.js, src/signals/shared/filter/parse.js
This PR adds an extra date field to the `Filter` form component. The initial field, which was tied to `incident_date` has been replaced by `created_after` and `created_before` filter fields.
Since the date fields should only show dates (no times) and the API expects and returns a string that contains both date and time, incoming and outgoing data are converted to match those requirements.
The `FilterTagList` container needed to combine the possible selected dates into one tag element, so that it can display three different date range options, like so:
- `Datum: 09-12-2019 t/m nu`
- `Datum: 09-12-2019 t/m 24-12-2019`
- `Datum: t/m 24-12-2019`
=> [SIG-2004] Date fields

src/containers/App/saga.js, src/containers/App/saga.test.js, src/shared/services/api/api.js, src/shared/services/api/api.test.js, src/signals/settings/users/containers/Overview/__tests__/Overview.test.js, src/signals/settings/users/containers/Overview/hooks/__tests__/useFetchUsers.test.js, src/signals/settings/users/containers/Overview/hooks/useFetchUsers.js
This PR fixes an issue where, in Firefox 43, JSON responses from a RESTful API endpoint weren't parsed by the browser and resulted in empty pages or error notifications about content that could not be retrieved.
The solution was fairly simple; add `Accept: 'application/json'` to the request headers.
=> (Chore) FF Instellingen fixes

src/signals/incident-management/index.js
This PR fixes an issue where no search request was dispatched after submitting the search form. The problem was caused by an incorrectly defined set of dependencies for the `IncidentManagement` module `useEffect` hook.
=> [SIG-2122] Vrij zoeken fix

internals/webpack/webpack.base.babel.js, src/signals/settings/users/containers/Detail/hooks/useFetchUser.js, src/signals/settings/users/containers/Overview/hooks/useFetchUsers.js
This PR fixes an issue in IE11 where the application stopped working when an overview page component was unmounted while it was loading. The cause of this was that the `abortcontroller-polyfill` wasn't applied.
=> [SIG-2126] AbortController polyfill

src/components/SiteHeader/index.js
This PR fixes a z-index issue in IE11 where the site header menu wasn't visible after the previous release.
=> [SIG-2219] - (Fix) Main menu visibility IE11

src/index.html
Pingdom was a temporary measure for monitoring the site's performance. Since it has been discontinued, the script tag in the public HTML can also go.
=> (Chore) Remove Pingdom script

src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js
This PR contains a fix for the `FilterForm` component where a change in the form's values was incorrectly derived. The form's update handler didn't take into account if a filter was a new filter or an existing one.
=> (fix) Change in form values

src/signals/incident-management/__tests__/selectors.test.js, src/signals/incident-management/containers/FilterTagList/index.js, src/signals/incident-management/reducer.js, src/signals/incident-management/selectors.js
An exception is thrown when the filters list is rendered in the filter modal
The `priority` field was recently changed from a single string to a list of strings. Storing filters after that change goes as expected. However, previously stored filters do not contain the values that the application expects and therefore runs into unparsable data.
The incoming data is converted before it is sent to the parser function.
=> [SIG-2238] Incompatible filter data

src/models/categories/__tests__/saga.test.js, src/models/categories/__tests__/selectors.test.js, src/models/categories/saga.js, src/models/categories/selectors.js, src/signals/incident-management/components/FilterForm/components/CategoryGroups.js
This PR contains a change that makes sure that all categories are returned from their selectors, sorted by name.
Next to that, the endpoint request has been given a query parameter that ensures that all categories will be retrieved, since the default response limit is capped to `100`.
=> [SIG-2177] Sort categories by name

src/signals/shared/filter/__tests__/parse.test.js, src/signals/shared/filter/parse.js
Some users complained about not being able to access their stored filters.
The problem was caused by filtered out, inactive, categories.
The list of categories is retrieved from the public categories endpoint. In the JSON output, some categories are marked as inactive (`is_active: false`). Those inactive categories are filtered out by the `App` container saga after the list has been retrieved.
Prior to deactivating certain categories, there were users that stored a filter that contained the, previously active, filter.
The parse function that converts incoming data into an application readably format, didn't take into account that there could also be no match between the values coming from stored filters and the full of categories.
Pretty straightforward: filtering out empty values after …
=> [SIG-2263] Inactive categories throw exception in Mijn Filters

src/signals/incident-management/__tests__/saga.test.js, src/signals/incident-management/saga.js
added SPLIT_INCIDENT_SUCCESS to incident-management saga watch
=> [SIG-2165] fix for fetching incidents when and split was successful

src/signals/settings/roles/containers/RolesListContainer/index.js, src/signals/settings/users/containers/Overview/index.js
In this PR:
- it is no longer possible to click a user detail when you no not have change_user permission
- it is no longer possible to click a role detail when you no not have change_group permission
- there is no test in the PR because all useCans are mocked with implementation false, so the change to  change_group and change_user will not trigger an error
=> Sig 2119 view rechten op gebruikers tonen en dan doorklikken geeft wit scherm

src/signals/incident-management/components/CheckboxList/__tests__/CheckboxList.test.js, src/signals/incident-management/components/CheckboxList/index.js
This PR contains changes to the `CheckboxList` component that allow rendering disabled checkboxes. 
In addition, to indicate that boxes have been disabled, a box' wrapper has been given an opacity of `0.2` which looks like this:
=> [SIG-2048] allow for disabled checkboxes

internals/testing/test-bundler.js, package-lock.json, package.json, src/hooks/__tests__/useFetch.test.js, src/hooks/useFetch.js
This PR adds a generic `useFetch` hook. The hook contains asynchronous request handlers and can be used as follows
```jsx
const MyComponent = ({ id }) => {
const { isLoading, error, data, get } = useFetch();
useEffect(() => {
const params = { foo: 'bar' };
// method get can be given a query parameter object as its 
// second function parameter
get(`${ENDPOINT_URL}${id}`, params);
}, []);
return isLoading ? (
<LoadingIndicator />
) : (
// do something with data
);
```
```jsx
const MyComponent = ({ id }) => {
const { isLoading, isSuccess, error, data, patch } = useFetch();
useEffect(() => {
if (isSuccess) {
global.alert('Success!!!1!);
}
}, [isSuccess]);
const onSubmit = formData => {
patch(`${ENDPOINT_URL}${id}`, formData);
};
return isLoading ? (
<LoadingIndicator />
) : (
<FormComponent …
```
=> [SIG-2049] useFetch hook

src/signals/settings/hooks/__tests__/useConfirmedCancel.test.js, src/signals/settings/hooks/__tests__/useFetchResponseNotification.test.js, src/signals/settings/hooks/useConfirmedCancel.js, src/signals/settings/hooks/useFetchResponseNotification.js
This PR adds two custom hooks for the `settings` module:
- `useConfirmedCancel`
- `useFetchResponseNotification`
This hook can be used to show a confirmation (`window.confirm`) message when a form's cancel button is clicked. It takes the URL to redirect to after cancel as parameter and returns a function that takes a single parameter: `isPristine` and is to be used as follows:
```jsx
const MyComponent = () => {
const redirectOnCancelURL = '/some-overview-page';
const [state, dispatch] = useReducer(reducer);
const confirmedCancel = useConfirmedCancel(redirectOnCancelURL);
const onFormCancel = () => {
const formData = new FormData(document.forms[0]);
// ...
const isPristine = isEqual(formData, state);
confirmedCancel(isPristine);
};
return (
<form onCancel={onFormCancel}>
...
<button …
```
=> [SIG-2048] Custom hooks

src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js, src/signals/incident/services/map-values/index.js
This PR contains a fix for an issue that was introduced by the categories public endpoint removal.
Submitting an incident can have a payload that contains the `extra_properties` prop. This prop contains all the extra questions (aanvullende vragen/uitvraagpagina's) that a specific incident category dictates.
The contents of that payload are shown on the incident detail page below the location map.
In a previous refactor, the call to the `mapControlsToParams` function contained an object with a wrong set of properties. This caused the result of the function to not contain the extra properties that were added to the incident on creation.
The previous refactor of the incident container saga has been partially reverted and tests have been adapted so that the correct procedure is asserted.
=> [SIG-2308] Fix for not showing extra properties

src/signals/incident-management/containers/IncidentDetail/components/MetaList/components/ChangeValue/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js
This PR contains a fix for a previously merged PR (#649). This change allow rendering different components in the incident detail's `MetaList` component by setting a default and setting a specific component where necessary.
Extra tests were added to assert the functional aspects of the change.
=> [SIG-2314] Fix for radio button list display

src/models/categories/__tests__/selectors.test.js, src/models/categories/selectors.js, src/signals/settings/categories/Overview/index.js
A previous change (#658) caused the categories overview to only show active categories instead of showing both active and inactive categories.
This pull fixes that by adding selectors that return all categories and subcategories.
=> [SIG-2331] Categories overview only shows active categories

src/signals/settings/departments/Overview/__tests__/Overview.test.js, src/signals/settings/departments/Overview/index.js
This PR contains changes that remove `react-redux`'s `connect` function, making the departments overview container a lot cleaner.
Test have been rewritten to cover the changes in the component.
=> (Chore) Remove connect from departments overview

.eslintrc.js, src/signals/settings/users/containers/Overview/__tests__/Overview.test.js, src/signals/settings/users/containers/Overview/index.js
This PR contains changes that remove react-redux's `connect` function, making the `users overview container` a lot cleaner.
Test have been rewritten to cover the changes in the component.
(Text has been borrowed from Jan Jaap ;)
=> Chore remove connect from contacts overview

docs/adr/0001-fetching-incidents.md, docs/adr/0002-using-local-state-in-settings-module.md, src/signals/settings/__tests__/actions.test.js, src/signals/settings/__tests__/reducer.test.js, src/signals/settings/actions.js, src/signals/settings/constants.js, src/signals/settings/context.js, src/signals/settings/index.js, src/signals/settings/reducer.js, src/signals/settings/users/containers/Detail/__tests__/Detail.test.js, src/signals/settings/users/containers/Detail/index.js, src/signals/settings/users/containers/Overview/__tests__/Overview.test.js, src/signals/settings/users/containers/Overview/index.js
Navigating from the users overview page to a user detail page, after a user's data was posted before that navigation occurred, lead the application into an endless loop, causing errors and freezing the page.
The cause was the state that was pushed onto the history stack. Removing it solved the problem. It is, however, unclear why providing a value for a history item's state lead to an endless loop. I looked into issues concerning `redux`, `react-router-dom` and `connected-react-router`, but I couldn't find the problem.
The reason that a value for a history item's state was needed, was that the filter selection needed to be retained when navigating from the overview page to a detail page and back again.
In order to keep that functionality, the `settings` module has been changed so that it …
=> [SIG-2358] User overview page infinite loop on navigation

src/shared/services/configuration/configuration.js, src/shared/services/file-upload-channel/index.js, src/signals/incident/components/form/RadioInput/index.js, src/signals/incident/containers/IncidentContainer/actions.js, src/signals/incident/containers/IncidentContainer/actions.test.js, src/signals/incident/containers/IncidentContainer/constants.js, src/signals/incident/containers/IncidentContainer/reducer.js, src/signals/incident/containers/IncidentContainer/reducer.test.js, src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js, src/signals/incident/services/map-controls-to-params/index.js, src/signals/incident/services/map-controls-to-params/index.test.js
This PR contains changes that effectively phase out the use of the v0 signals creation endpoint.
- Renames `INCIDENT_ENDPOINT` constant in the configuration class to `INCIDENT_PUBLIC_ENDPOINT` and alters the URL to match the v1 endpoint
- `IncidentContainer` saga has been rewritten so that:
+ an incident can be created both as authorized and unauthorized user; the public endpoint doesn't allow setting `priority`
+ image uploads are blocking (previously, those were non-blocking and lead to file uploads not being completed)
- `INCIDENT_PRIVATE_ENDPOINT` constant to the configuration class
- Every now and then error popped up in Sentry saying `Unable to get property 'info' of undefined or null reference`. A minor change to one of the `RadioInput` components fixed that issue. Included in this …
=> [SIG-2333] v0 ⇨ v1 replace

src/signals/incident/containers/IncidentContainer/index.test.js, src/signals/incident/containers/IncidentContainer/reducer.js, src/signals/incident/containers/IncidentContainer/reducer.test.js, src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js, src/signals/incident/definitions/wizard-step-1-beschrijf.js, src/utils/__tests__/fixtures/incident.json
This PR applies changes to the incident submission form configuration so that the `type` property can be passed on incident POST.
In order to do so, this PR:
- changes the default values for an incident in the `IncidentContainer` reducer,
- adds an option to the `wizard-step-1-beschrijf` form configuration
- alters the `IncidentContainer` saga so that the fields 'priority', 'source' and 'type' can only be set by an authenticated user
- updates the incident JSON fixture so that its contents reflect the API's output
=> [SIG-2281] Form configuration for incident type

src/models/incident/reducer.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js, src/signals/incident-management/containers/IncidentDetail/index.js, src/signals/incident-management/containers/IncidentDetail/index.test.js
This PR adds a component to the incident detail page with which the incident type can be patched.
**Component in preview mode**
---
**Component in edit mode**
=> [SIG-2307] Incident type patch

src/signals/incident-management/containers/IncidentSplitContainer/components/SplitForm/index.js, src/signals/incident-management/containers/IncidentSplitContainer/components/SplitForm/index.test.js, src/signals/incident-management/containers/IncidentSplitContainer/index.test.js
This PR fixes a bug on the incident split page where, if three incident parts were selected, all parts would get the default value for `type` instead of the selected value.
Note that a couple of test cases have been removed. This, because tests were breaking without any particular reason and I also couldn't find the reason why that was. When the `IncidentSplitContainer` component is refactored to remove the `connect` dependency, the tests won't be needed anyway 🤷‍♂
=> [SIG-2442] Bug on split page

src/signals/incident-management/components/CheckboxList/index.js
This PR contains a fix for type check mismatch in the `CheckboxList` component. 
The problem arose when an option was unchecked, but that change wasn't reflected by the list of options returned by the component's `onChange` handler. This was caused by the fact that an option's id was compared to the value of the corresponding HTML element's `data-id` attribute. The latter is always a string and the former can be either a string or a number.
By casting the comparing values to a string the issue is resolved.
=> (Chore) Fix type mismatch

src/hooks/__tests__/useFetch.test.js, src/hooks/useFetch.js
This PR fixes a bug where resources could not be loaded and returned a `401` response from the API until the page was reloaded.
The problem came from the request headers being defined outside the `useFetch` hook. When a user enters the site and the session is expired, the request headers are set without the bearer token.
When that same user authenticates without reloading the site, the request headers still have the bearer token missing. This is only solved by reloading the page so that the bearer token is included in the request headers.
By placing the initialisation of the request headers inside the `useFetch` hook function, the issue is resolved.
=> (Chore) Fix fetch GET

src/containers/App/index.js, src/containers/App/index.test.js, src/signals/incident/containers/IncidentContainer/index.js, src/signals/incident/containers/IncidentContainer/index.test.js, src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js
This PR contains changes that fixes an issue where, after an incident had been submitted, the state that held the incident's data, was not cleared.
The `IncidentContainer` contained a listener for changes to the browser's location, but a crucial change was not picked up properly and that was the navigation away from the last page in the incident submission process.
By moving the listener to the `App` container this problem was solved.
=> [SIG-2447] Incident reset on page navigation

src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js
This PR contains a change that filters out fields that are not allowed by the `POST` API endpoint for incidents.
Previously, the responsible saga contained a blacklist. That list has been turned into a whitelist.
=> [SIG-2450] Limit params in incident POST payload

src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js
A previous PR removed the `handling_message` prop from the pre-POST data in the `IncidentContainer` saga. This PR corrects that error.
=> (Chore) Include handling message in pre-POST data

src/components/PDOKAutoSuggest/index.js, src/hooks/__tests__/useFetch.test.js, src/hooks/useFetch.js, src/shared/services/configuration/configuration.js, src/shared/services/map-location/index.js, src/signals/incident-management/__tests__/selectors.test.js, src/signals/incident-management/containers/IncidentOverviewPage/components/Map/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/reducer.js
This PR contains a skeleton Map component for the incident overview page. 
In order for the map to be functional, this PR:
- applies changes to the `PDOKAutoSuggest` component so that the list of fields, for which values should be retrieved from the geocoding service,is configurable. That also goes for the function that parsed the service's output. One doesn't go without the other in this case.
- applies changes to the `useFetch` hook so that its parameter values can both be scalar as well as array values
- requests data from the geography service on mount and update of the map component
=> [SIG-2498] Map component

src/components/AutoSuggest/index.js, src/components/PageHeader/index.js, src/global.scss, src/signals/incident-management/containers/FilterTagList/index.js, src/signals/incident-management/containers/IncidentOverviewPage/components/Map/index.js, src/signals/incident-management/containers/IncidentOverviewPage/components/SubNav/__tests__/SubNav.test.js, src/signals/incident-management/containers/IncidentOverviewPage/components/SubNav/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.test.js, src/signals/incident-management/containers/IncidentOverviewPage/style.scss, src/signals/incident-management/containers/IncidentOverviewPage/styled.js
This PR adds a section to the incident overview page that has a tabbed list of links that can toggle the list and the map on that page.
Next to that, this PR:
- adjusts the margins of the `PageHeader` component to make the tabbed list fit
- sets the overflow of the `body` to 'scroll' so that the page scrollbar is always visible and the page never jumps when navigating from a long page to a short page
- moves `IncidentOverview` styled components into their own file
=> [SIG-1505] Map toggle buttons

src/components/MapInput/__tests__/reverseGeocoderService.test.js, src/components/MapInput/services/reverseGeocoderService.js
This PR contains a fix for an error thrown by the browser when clicking on a map
> The page at 'https://signals-acceptance.netlify.com/incident/beschrijf' was loaded over HTTPS, but requested an insecure resource 'http://geodata.nationaalgeoregister.nl/locatieserver/revgeo?type=adres&rows=1&fl=id,weergavenaam,straatnaam_verkort,huis_nlt,postcode,woonplaatsnaam,centroide_ll&X=121341.20009083288&Y=487474.240461711&distance=50'. This request has been blocked; the content must be served over HTTPS.
=> (Chore) Fix https URL

src/components/MapInput/__tests__/MapInput.test.js, src/components/MapInput/index.js
This PR contains a fix for when a click on a map doesn't have a corresponding address. There was also another issue that popped up; the response data wasn't properly formatted; solved this by providing the `AutoSuggest` component with the proper formatting function.
=> [SIG-2515] Fix for location without address

package-lock.json, src/components/AutoSuggest/index.js, src/components/MapInput/index.js, src/components/PDOKAutoSuggest/__tests__/PDOKAutoSuggest.test.js, src/components/PDOKAutoSuggest/index.js
This PR contains changes that allow setting a `placeholder` attribute on the `AutoSuggest` component's input element.
=> (Chore) Placeholder for AutoSuggest input element

src/components/Map/index.js, src/components/MapInput/index.js, src/components/MapSelect/index.js, src/signals/incident-management/components/MapInput/__snapshots__/index.test.js.snap, src/signals/incident-management/components/MapInput/index.js, src/signals/incident-management/containers/IncidentOverviewPage/components/Map/index.js
This PR:
- adds zoom controls to all interactive map instances
- disables scroll wheel zoom while maintaining the ability to pinch zoom and do a two-finger scroll on mobile
=> Sig 2519 map zoom controls

src/shared/services/map-location/index.js
This PR contains a change in the list of fields that are retrieved from the geocoder service. Instead of `straatnaam_verkort`, `straatnaam` is used now.
=> (Chore) Full street name from geoservice

src/components/MapInput/__tests__/MapInput.test.js, src/components/MapInput/__tests__/reverseGeocoderService.test.js, src/components/MapInput/index.js, src/components/MapInput/services/reverseGeocoderService.js
This PR contains a fix for the geocoding service where it didn't retrieve the stadsdeel for locations that didn't have a resolved address.
=> (Chore) Always retrieve stadsdeel

src/signals/incident-management/containers/IncidentOverviewPage/components/Map/index.js, src/signals/shared/filter/parse.js
This PR contains a fix for the date/time string formats that are used as parameters for the API. The format used was faulty, because it sent hours as `24` instead of `00`.
=> (Fix) Date/time string

src/components/SiteHeader/index.js
This PR makes the 'Melden' link in the main menu an anchor that bypasses the react router logic so that, whenever the 'Melden' link is clicked, the page is fully reloaded.
This fixes an issue where the incident global state isn't properly purged after an incident has been submitted. This lead to data being submitted in incidents that was submitted in prior incidents.
Note that this is a quick fix and should be followed by a proper clean-up of the application's state.
=> (Fix) Perpetuating state

src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/index.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/index.test.js
This PR fixes an issues where, for older incidents, the `ExtraProperties` component would throw an error. A while ago, the API expected a different structure for extra properties for incidents, namely an object where it's keys were the properties' labels and its values, well, the values. Currently, the API expects an array of objects. The current implementation of the `ExtraProperties` components expects an array which leads to the incidents that still have objects for values to throw an exception in the incident detail page.
=> [SIG-2545] Fix for extra_properties object

src/signals/incident-management/components/RadioInput/index.js, src/signals/incident-management/components/RadioInput/index.test.js
This PR contains a fix for a faulty assumption in the `RadioInput` component in the incident management module. The component assumed that all items in its `values` prop had an `info` prop present, which wasn't the case.
=> [SIG-2536] Fix for missing value in RadioInput component

src/signals/incident-management/containers/IncidentSplitContainer/components/SplitForm/index.js, src/signals/incident-management/containers/IncidentSplitContainer/components/SplitForm/index.test.js
This PR fixes an issue where, when the split page submit button was clicked more than once, the API would respond with a `400` or `412` response code.
On clicking the button, the submit is disabled so that it can only be clicked once. Note that `useRef` hasn't been applied, because of the limitation of the `asc-ui` Button component; doesn't use `forwardRef`.
=> [SIG-2544] Fix double submission split page

src/components/MapInput/__tests__/MapInput.test.js, src/components/MapInput/index.js, src/hooks/__tests__/useDelayedDoubleClick.test.js, src/hooks/useDelayedDoubleClick.js, src/signals/settings/users/Overview/__tests__/Overview.test.js, src/test/utils.js, src/utils/__tests__/fixtures/geosearch.json
This PR enables double click zoom by delaying clicks. The functionality is handled by a custom hook.
Note that tests have been added to increase test coverage on the `MapInput` component.
=> [SIG-2546] Map double click

src/components/AutoSuggest/__tests__/AutoSuggest.test.js, src/components/AutoSuggest/index.js, src/components/MapInput/__tests__/MapInput.test.js, src/components/MapInput/index.js, src/test/utils.js
This PR applies changes to the `AutoSuggest` and `MapInput` components so that the marker can be removed from the map whenever the auto suggest input field is emptied.
=> [SIG-2540] Remove marker on input clear

src/signals/incident-management/__tests__/saga.test.js, src/signals/incident-management/saga.js
This PR fixes a faulty redirect when editing an incident's details after having submitted the search form. The problem here was that the responsible saga always redirected the application back to the overview page when an incident was updated, regardless of which action triggered the saga.
The proposed change has the saga only redirect to the overview page when the search query is set, not when it has already been set.
=> [SIG-2531] Fix redirect from incident edit

src/hooks/__tests__/useFetch.test.js, src/hooks/useFetch.js
This PR fixes an issue where the application would throw error unrelated to pending actions. This was due to the fact that in the `useFetch` custom hook, the error message was set on a freezed object.
=> (Chore) Exception message assignment

src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/components/CheckboxGroup.js, src/signals/incident-management/components/FilterForm/index.js
This PR fixes a warning that was thrown in the `FilterForm` component after updating React from `16.13.0` to `16.13.1`:
> Warning: Cannot update a component (`FilterForm`) while rendering a different component (`CheckboxList`). To locate the bad setState() call inside `CheckboxList`, follow the stack trace as described in https://fb.me/setstate-in-render
Both the `CheckboxList` component as well as the `FilterForm` component updated the state of the `CheckboxList` component. What happened:
1. Click on checkbox updates internal state of `CheckboxList`
2. Internal state update calls callback prop in `FilterForm`
3. `FilterForm` updates its internal state
4. Updated internal `FilterForm` state is propagated to the `CheckboxList` component through its `defaultValue` prop
5. `CheckboxList` …
=> [SIG-2575] Checkboxlist state bug

src/components/MapSelect/index.js, src/components/Pagination/components/PaginationItem/index.js
This PR corrects the Avenir Next Regular font name. Because the name didn't match the arial font was used in MapSelect and PaginationItem components
=> SIG-2538 corrects the Avenir Next font name

src/signals/incident-management/__tests__/saga.test.js, src/signals/incident-management/saga.js
This PR removes a push to `/manage/incidents` after a search incidents request has been performed since this push is duplicate. There is another push performed in `src/containers/App/saga.js`.
=> (Chore) Remove redirect

src/signals/incident-management/components/CheckboxList/__tests__/CheckboxList.test.js, src/signals/incident-management/components/CheckboxList/index.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/settings/departments/Detail/components/CategoryLists/__tests__/CategoryLists.test.js, src/signals/settings/departments/Detail/components/CategoryLists/index.js
This PR fixes a warning that was shown when the `CheckboxList` component was updated by a parent component. The underlying issue was a matter of timing. What happened was:
1. a checkbox is checked
2. `CheckboxList` internal state is updated
3. the parent component's `onChange` handler is called
4. parent component updates its internal state and sends the updated state to the `CheckboxList` component
5. `CheckboxList` internal state is updated if the incoming values differ from the internal state
Steps 4 and 5 happen short after one another which renders the parent component while the child component is rerendering. This caused the warning to show up.
The solution was to move the `onChange` handler call from the call stack to the event loop.
=> (Chore) Fix checkboxlist state update warning

src/signals/incident/components/IncidentPreview/index.js, src/signals/incident/components/IncidentPreview/index.test.js
This PR contains a minor change to the incident preview section header width to ensure that the contents of the section header are shown on one line on as many screen widths as possible.
=> [SIG-1421] Summary page section header width

src/containers/App/index.js, src/shared/services/auth/auth.js, src/shared/services/auth/auth.test.js
This PR contains a fix for the following scenario:
- user logs in
- access token expires (after a set time in the future)
- user tries to access `/manage/incidents`
- data is requested from a private API endpoint
- endpoint responds with `401` (unauthorized) status code
- error notification is shown about not being able to load resources
The issue was caused by a faulty check on the presence of the acces token that is present in localstorage. The `isAuthenticated()` function only checked if there was an access token and not if the access token was actually a valid token or hadn't expired yet.
=> [SIG-2551] Fix for alert shown for logged out users

package-lock.json, package.json, src/signals/incident/containers/IncidentContainer/reducer.js, src/signals/incident/containers/IncidentContainer/reducer.test.js
This pull request contains a fix for the following scenario:
- user fills in incident form
- prediction service returns with a category that sends the user through a specific workflow
- user clicks edit details button in submission summary page
- prediction service returns with a different category than before
- user completes filling in form
- summary page shows values for both workflows
The cause of this was that the state wasn't properly cleared whenever a determining factor in the state (in this case `category` and/or `subcategory`) changed.
The solution was to clear all values for which the prop name was prefixed with `extra` when the prediction service returned with a category.
=> [SIG-2610] Persistent incident state fix

Jenkinsfile
This PR changes assumptions about cached Docker images being present into conditions to make sure that, whenever a cached image cannot be retrieved, the build doesn't break.
=> (Chore) Conditional image cache

.github/workflows/ci.yml
This PR introduces continuous integration using GitHub Actions. This allows pull requests from external contributors to be tested securely.
- The [GitHub Actions](https://help.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions) manual served as template of this setup.
- NPM modules are cached between builds.
- Code coverage report is uploaded using [artifacts](https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts).
This setup is easily extendible for testing against multiple Node versions with the [build matrix feature](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix).
We could optimize this setup further by caching the apt install step and …
=> Run tests using GitHub Actions

.github/workflows/ci.yml
Actions for internal pull requests currently run twice. This PR fixes this behavior.
Related to Signalen/backend#18
=> Do not run GitHub Actions twice for internal pull requests

src/components/ChildIncidents/__tests__/ChildIncidents.test.js, src/components/ChildIncidents/index.js, src/signals/incident-management/containers/IncidentDetail/components/ChildIncidents/__tests__/ChildIncidents.test.js, src/signals/incident-management/containers/IncidentDetail/components/ChildIncidents/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js, src/signals/incident-management/containers/IncidentDetail/index.js, src/utils/__tests__/fixtures/incident.json
This PR contains a new component; `ChildIncidents` that replaces the inline list of child incidents on the incident detail page.
The component supports passing multiple values and by default requires an `id` to be present.
Each child in the list can be given a status (currently, none of the items will get one). The status is indicated by a pseudo element with a background color and right border.
=> [SIG-2616] Deelmelding component

src/signals/incident-management/containers/IncidentDetail/components/AttachmentViewer/index.js, src/signals/incident-management/containers/IncidentDetail/components/AttachmentViewer/index.test.js
This PR adds keyboard navigation to the incident detail `AttachmentViewer` component and removes the callback function, because the component handles its own state now.
=> [SIG-2447] AttachmentViewer keyboard nav

src/signals/settings/users/Overview/__tests__/Overview.test.js, src/signals/settings/users/Overview/index.js
This PR fixes a bug in the UsersOverview. When the search filter was removed by clicking the clear button, no action was triggered.
=> clears the user search filter when the clear button is pressed

Jenkinsfile, docker-compose.yml
This PR removes the test and lint stages from the `Jenkinsfile` as well as test and lint container settings in the `docker-compose.yml`. The stages aren't needed since they are covered by Github actions.
=> (Chore) Remove Jenkins stages

src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.test.js
This PR ensures that the back link in the incident detail always navigate to the incidents overview excepting the situation when the incident detail is opened from the overview map. In the last case the back link will return to the overview map of incidents
=> [SIG-2565] fix backlink when navigating from the map overview

src/shared/types/index.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.test.js, src/signals/incident-management/containers/IncidentDetail/index.js
This PR places a link to the main incident (whenever an incident has a parent) in the `DetailHeader` component on the incident detail page.
=> [SIG-2659] DetailHeader main incident link

src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js
This PR removes the parent link from the `MetaList` component in the incident detail page.
=> [SIG-2660] Remove parent link from MetaList

src/signals/incident/definitions/wizard-step-5-samenvatting.js
This PR fixes an issue where the incident summary page would crash. The cause of this was the use of references to components that didn't exist anymore.
=> (FIX) [SIG-2690] Wonen questions crash

src/signals/incident/definitions/wizard-step-2-vulaan.js
This PR removes the 'wonen' category questions from the incident submission form. Some parts are untested and need changes. To prevent errors in incident submissions, the safest bet is to temporarily remove the category altogether.
=> [SIG-2690] Remove wonen category

internals/webpack/template.js
This PR fixes the production build. The problem was that the production build was looking for a file (`environment.conf.json`) that wasn't present at the moment of execution.
=> (Fix) Borken build

src/signals/incident/components/form/RadioInputGroup/index.js, src/signals/incident/containers/KtoContainer/components/RadioInputGroup/__snapshots__/index.test.js.snap, src/signals/incident/containers/KtoContainer/components/RadioInputGroup/index.js, src/signals/incident/containers/KtoContainer/components/RadioInputGroup/index.test.js, src/signals/incident/definitions/kto.js
This PR contains a fix for the KTO form where the submit button wouldn't get out of its disabled state. This was caused by a previous PR that refactored the `RadioInputGroup` component, but didn't take into account that, in that component, the function `parent.meta.updateIncident` actually isn't `updateIncident` in the context of the KTO form, but is actually `updateKTO` 🙄
=> [SIG-2748] Fix KTO form submission

src/signals/incident/components/IncidentPreview/components/ListObjectValue/__tests__/ListObjectValue.test.js, src/signals/incident/components/IncidentPreview/components/ListObjectValue/index.js
This PR fixes an error in the incident submission summary page where a checkbox value was evaluated as if it was an array of objects.
=> [SIG-2750] Fix for error in summary page

src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js
This PR removes the department name from the incident detail `MetaList` component since its going to be displayed as part of the subcategory name.
=> [SIG-2712] Remove responsible department indicator

src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js
This PR contains a fix for the `FilterForm` component where both `name` and `refresh` fields weren't populated by values from stored filters.
Tests have been added to ensure the functionality of both fields.
=> [SIG-2733] Fix for not showing filter name

src/signals/incident/components/IncidentWizard/index.js, src/signals/incident/containers/IncidentContainer/index.js, src/signals/incident/containers/IncidentContainer/index.test.js
This PR contains changes that load the wizard's definition files in a lazy fashion. I noticed that the code inside the definition files gets executed in every module that is loaded in the application. For instance, when loading one of the settings pages, the entire wizard definition is imported and its code gets executed, even though that code is unrelated to said settings page.
The solution is to lazy load the definitions module, so that only when the `Incident` container is loaded, the definitions file is loaded as well.
=> (Chore) Lazy load wizard definition

src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js, src/signals/incident-management/containers/IncidentDetail/index.js
This PR:
- adds a space between the department names that are shown behind the selected category name in the incident detail page
- removes the unused `makeSelectSubCategories` selector from the `IncidentDetail` container
=> (Chore) Add space

src/signals/incident/definitions/__tests__/wizard-step-5-samenvatting.test.js, src/signals/incident/definitions/wizard-step-5-samenvatting.js
This PR contains a fix for an issue where the value for single checkbox wasn't shown in the incident form's summary.
=> [SIG-2760] Single checkbox values

src/signals/incident/components/form/DescriptionWithClassificationInput/index.js, src/signals/incident/components/form/DescriptionWithClassificationInput/index.test.js
This PR prevents that an unnecessary api prediction call is made when the decription text area is left empty in the IncidentForm
=> [SIG-1741] minor fix for empty predictions in the incident form

src/signals/incident-management/containers/IncidentDetail/components/Detail/index.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/index.test.js
This PR adds the rendering of the `sharing_allowed` prop to the `IncidentDetail` `Detail` component
=> [SIG-2778] Show information sharing option in incident detail

src/signals/incident-management/components/RadioInput/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js
This PR contains changes that make sure that only departments that are responsible for handling incidents that are categorized by specific categories, are shown behind the subcategory name in the select element in the incident detail page.
Note that this PR also contains a change to an unrelated component `RadioInput`, because of a warning in the Jest output about the use of both `checked` and `defaultChecked` props on that component.
=> [SIG-2786] Show only responsible departments

src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js
This PR contains a fix for an issue where the 'sharing allowed' checkbox would be ticked and unticked, the value passed on to the API would be of an unsupported format. By conditional chaining and falling back to 'false' this issue is resolved.
=> (Chore) Fix toggling sharing checkbox

internals/webpack/webpack.base.babel.js, package-lock.json, package.json, src/components/AmsterdamLogo/__tests__/AmsterdamLogo.test.js, src/components/AmsterdamLogo/index.js, src/components/Input/index.js, src/components/MapInput/index.js, src/components/MapSelect/index.js, src/components/Notification/styled.js, src/components/SiteHeader/__tests__/SiteHeader.test.js, src/components/SiteHeader/index.js, src/containers/SearchBar/index.js, src/signals/incident-management/containers/IncidentOverviewPage/styled.js
Thie PR updates the `asc` packages to 0.20.0 and solves a breaking change around the the site Logo. A SIA variant of the Amsterdam Logo is added to this project because the default logo provided by asc is not according to the design of SIA.
=> [SIG-2775] update asc packages

Jenkinsfile
This PR comments out the lines that deploy the application for the Weesp instance. It caused the Weesp config to be deployed to acc.meldingen.amsterdam.nl, since acc.meldingen.weesp.nl isn't yet available.
=> (Chore) Comment Weesp job

internals/webpack/template.js, package-lock.json, package.json, src/components/MapInput/__tests__/MapInput.test.js, src/components/MapInput/index.js
This PR:
- applies a change to the webpack `template` file so that configuration files are merged instead of fully replaced
- has the `MapInput` component look for the `stadsdeel` prop in the map options configuration and when it finds it uses that value instead of performing an extra BAG request
=> [SIG-2573] Prevent extra BAG request

src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.js
This PR changes the logic of showing the `extra_straatverlichting_gevaar` question in the incident form.
=> [SIG-2810] Show correct questions

.eslintrc.js, internals/webpack/webpack.base.babel.js, jsconfig.json, package-lock.json, package.json
This PR:
- configures Webpack module aliases
- adds `jsconfig.json` so that, at least, VS Code can resolve modules with CMD-click
=> (Chore) jsconfig.json

src/signals/incident/components/form/SelectInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/SelectInput/index.js, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-op-het-water.js, src/signals/incident/definitions/wizard-step-5-samenvatting.js
This PR fixes an issue where the boat company name was not shown on the summary page.
=> [SIG-2757] Show the `rederij` name in the summary

.eslintrc.cli.js, .eslintrc.js, internals/webpack/webpack.base.babel.js, jsconfig.json, package.json, src/signals/incident-management/containers/IncidentDetail/index.js
This PR fixes an issue where VS Code wasn't able to resolve module located in the `src` folder. As it turned out, the lint configuration that is used by VS Code needs a `node` setting where running the linter from the command line does not. The latter requires the Webpack config to be able to resolve module properly.
=> (Fix) import/no-unresolved

src/signals/incident-management/components/CheckboxList/index.js
This PR:
- fixes an issue in firefox were when in the filters the `Alles selecteren` is selected, the hidden checkbox determines an outline to be shown over the whole width of the screen.
=> [SIG-2790] Fix the checkbox visibility in firefox

environment.conf.json, src/signals/incident/definitions/__tests__/wizard-step-2-vulaan.test.js, src/signals/incident/definitions/wizard-step-2-vulaan.js
This PR
- adds a new property in the application configuration: `hasExtraProps`
- when this property si set to false, no extra questionary wil be presented to the user.
- this property will be used to switch off the extra questionaries for the Wesp implementation
Note that the specific configuration of the build repositories for Weesp and Amsterdam wil be done after this PR is Approved
=> [SIG-2754] Add configuration for showing the extra questionary

src/signals/incident-management/containers/IncidentDetail/components/AddNote/index.js, src/signals/incident-management/containers/IncidentDetail/components/AddNote/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/LocationForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/LocationForm/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/DefaultTexts/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.test.js, src/signals/incident-management/containers/IncidentDetail/index.js, src/signals/incident-management/containers/IncidentDetail/index.test.js
This PR moves the responsibility of dispatching the `patchIncident` action from the `IncidentDetail` container to its underlying components. This in preparation of the refactoring of the `IncidentDetail` container and the introduction of `useContext` and `useReducer` for that container.
=> (Chore) Move dispatch to underlying components

src/containers/App/reducer.js, src/containers/App/reducer.test.js, src/signals/incident-management/__tests__/reducer.test.js, src/signals/incident-management/reducer.js
This PR fixes the issue that when a filter is applied, the search term was not reseted in the search bar.
=> resets the search query when a filter is applied

internals/webpack/webpack.prod.babel.js
So in the end we don't need the option and it does not do anything. :blush: 
I know where it went wrong, and why I thought we needed this option, will explain offline.
=> (Chore) Remove unneeded OfflinePlugin option

src/app.js, src/shared/services/configuration/configuration.js, src/shared/services/configuration/configuration.test.js
This PR changes the configuration service so that it doesn't throw an exception whenever a missing config prop is encountered, but returns `undefined`. This to prevent `try/catch` structures throughout the code.
=> (Chore) Return undefined instead of throwing

internals/webpack/webpack.base.babel.js, src/app.js
This PR adds a console.log with the version and build information of the application at start.
- the printed version is the version that is set in the package.json.
- the build version is 'develoment|production' depending on the NODE_ENV.
- this requires that in the release workflow `npm version [<newversion> | major | minor | patch]` will be called for the new releases.
=> [Chore] Add the version information to the runtime

src/signals/incident-management/definitions/stadsdeelList.js
This PP adds the `Weesp` and `Amsterdamse Bos` options to the filters and to the Incident detail in the backoffice
=> [SIG-2861] Add Weesp and Amsterdamse bos to the stadsdeel options

src/signals/incident-management/definitions/stadsdeelList.js
- Issue where the `Weesp` and `Het Amsterdamse Bos` were not shown in the filters and on the incident detail page
=> Release v1.18.1 Weesp and Amsterdamse bos

internals/webpack/webpack.prod.babel.js
This PR contains changes that make sure that `manifest.json` is copied in the `build` folder. Not having the file there throws an error when spinning up the `amsterdam` or `weesp` container.
=> (Chore) Copy manifest.json

internals/webpack/webpack.prod.babel.js
This PR contains a change to the Webpack configuration that turns this:
```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
npm.date-fns.3a589dbe91b6a9264b2d.chunk.js (818 KiB)
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
main (1.43 MiB)
```
into this:
```
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
main (657 KiB)
```
=> (Chore) Exclude date-fns from main bundle

.eslintrc.js, .prettierrc, internals/testing/test-bundler.js, src/components/AutoSuggest/__tests__/AutoSuggest.test.js, src/components/AutoSuggest/index.js, src/components/PDOKAutoSuggest/__tests__/PDOKAutoSuggest.test.js, src/hooks/useDelayedDoubleClick.js, src/signals/incident-management/containers/DefaultTextsAdmin/components/DefaultTextsForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/components/DownloadButton/index.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/components/DownloadButton/index.test.js, src/signals/incident/components/form/CheckboxInput/index.js, src/signals/incident/components/form/DateTimeInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/DateTimeInput/index.js, src/signals/incident/components/form/MapSelect/index.js, src/signals/settings/__tests__/index.test.js, src/signals/settings/categories/Detail/__tests__/Detail.test.js, src/signals/settings/categories/Overview/__tests__/Overview.test.js, src/signals/settings/components/PageHeader/index.js, src/signals/settings/departments/Detail/__tests__/Detail.test.js, src/signals/settings/departments/Detail/index.js, src/signals/settings/departments/Overview/__tests__/Overview.test.js, src/signals/settings/users/Overview/__tests__/Overview.test.js, src/signals/settings/users/Overview/index.js
This PR contains fixes for several tests that used deprecated functions from `@testing-library/react`. All tests have been run with the `--runInBand --detectOpenHandles` options to detect memory leaks. Where necessary, tests have been modified to prevent leaks.
Next to that, a small modification has been added to the linter configuration that prevented formatting files without generating  unnecessary changes.
For a couple of components where `useCallback` is used in conjunction with Lodash' `debounce` function, the linter has been disabled for the `react-hooks/exhaustive-deps` rule.
=> [SIG-2873] Fix tests

src/shared/services/file-upload-channel/index.js
We are using an HTTP/2 load balancer in front of our Signalen deployments. As HTTP/2 does not support a reason phrase, the frontend shows an upload error to the user while the upload is actual successful. This PR fixes this behavior.
From the spec:
> HTTP/2 does not define a way to carry the version or reason phrase that is included in an HTTP/1.1 status line.
https://tools.ietf.org/html/rfc7540#section-8.1.2.4
Fixes https://github.com/Signalen/backend/issues/37
=> Do not check xhr.statusText as this is not supported in HTTP/2

src/models/categories/__tests__/selectors.test.js, src/models/categories/selectors.js, src/signals/incident-management/components/SelectInput/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentPart/index.js
This PR fixes an issue where the subcategory select wouldn't show the responsible department names after the subcategory name. The cause was a change in the `SelectInput` component in the `incident-management` module.
I reverted the change and moved the responsibility of generating the string that combines the responsible department names to the subcategory selector. That allows us to use the value anywhere. That's also why I added it to the split form as well.
=> [SIG-2875] Show responsible department codes

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.test.js
This PR fixes three issues on the status form page:
1. Alignment of the header
2. Excess padding on the form
3. Not showing of the current status of the incident. It appears that there are statuses that are set on an incident, but cannot be selected by an admin. A status would be shown in the list of radio buttons where the appropriate status radio button would be selected, but that isn't possible for statuses that are not in that list. In that case, the status is printed above the form, like so:
=> [SIG-2846] Alignment status form

src/signals/incident-management/containers/IncidentOverviewPage/components/Map/__tests__/Map.test.js, src/signals/incident-management/containers/IncidentOverviewPage/components/Map/index.js
This PR fixes an issue where a request to the incidents geography endpoint would result in a `400` error response. The cause was a faulty date/time string after merging #974.
=> [SIG-2889] 24-Hour map request fix

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/DefaultTexts/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/DefaultTexts/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.test.js
This PR changes the layout of the status form so that the options and the input area are both located in the left column and the defaults texts in the right column instead of the default texts pushing the input area down the page.
=> [SIG-2894] Status form layout fix

.github/MAINTAINERS.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml
This PR contains changes that make sure that the correct Node version is used when running Github actions.
=> (Chore) Node 12 for Github actions

src/components/GPSButton/__tests__/GPSButton.test.js, src/components/GPSButton/index.js, src/components/LocationMarker/index.js, src/components/Map/__tests__/Map.test.js, src/components/Map/index.js, src/components/MapInput/index.js, src/components/MapSelect/index.js, src/components/MapSelect/index.test.js, src/shared/services/map-location/index.js, src/shared/services/map-location/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/MapDetail/index.test.js, src/signals/incident/components/form/MapInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/MapInput/index.js, src/signals/incident/components/form/MapSelect/index.js, src/signals/incident/components/form/MapSelect/index.test.js
This PR combines #999 and #1001 and ties them together in the map components.
It also:
- alters the `GPSButton` component so that, when the button is toggled off, not another geolocation request is performed
- adds `onLocationOutOfBounds` prop to the `GPSButton` component
- add `pointWithinBounds` function to the `map-location` service
- has the `LocationMarker` component render an empty `<span>` so that a `data-testid` attribute can be rendered and checked for in other tests
- has the `Map` component render the `GPSButton` component and show notifications when the location cannot be retrieved or is out of bounds
=> [SIG-2899] GPS functionality

src/components/GPSButton/__tests__/GPSButton.test.js, src/components/GPSButton/index.js
This PR contains a small addition to the `GPSButton` component that prevents multiple geolocation requests to be fired when another request is pending.
In addition to that, a test case has been added to increase the component's coverage to 100%
=> (Chore) Prevent multiple geolocation requests

src/components/GPSButton/index.js, src/components/LocationMarker/index.js, src/components/Map/index.js
This PR:
- changes the opacity of the `LocationMarker` accuracy circle
- makes sure the location dot is rendered on top of the accuracy circle
- sets the distance between the gps button and the zoom buttons
=> [SIG-2087] GPS Button modifications

src/hooks/__tests__/useEventEmitter.test.js, src/hooks/index.js, src/hooks/useEventEmitter.js, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/containers/MyFilters/index.js
This PR adds the `useEventEmitter` hook that allows us to do
```jsx
// somewhere in the application
const payload = { foo: 'bar' };
emit('myEvent', payload);
...
// somewhere deep down in a component
useEffect(() => {
const listener = payload => {
const { foo } = payload;
// do something with payload
};
listenFor('myEvent', listener);
return () => {
unlisten('myEvent', listener);
};
}, []);
=> (Chore) useEventEmitter hook

.eslintrc.js, src/signals/incident-management/containers/IncidentOverviewPage/components/Map/index.js
This implements:
-  feedback changes
- enabled no-extra-parens rule
- moved remaining cypress configuration to overrides
- moved import/no-webpack-loader-syntax to recommended rules
=> [SIG-2886] Add more ESLint rules (Last Part)

Dockerfile, Jenkinsfile, internals/webpack/webpack.base.babel.js, package-lock.json, package.json, src/app.js
This PR contains changes to the `Jenkinsfile` that prevent automatic deploys to production on merges to `master`. Instead, only tags can be deployed. This change forces us to explicitly tag the `master` branch before each and every release. This also allows a rollback in case something went horribly wrong on deployment, for instance when we forget to include a required configuration prop in one of the `signals-amsterdam` or `signals-weesp` repositories.
Note that:
- the env var `GIT_COMMIT` has been replaced by `GIT_TAG`, which effectively will be a tag or `develop`
- both `version` and `description` props have been removed from `package.json`; neither are required and only make sense when the repository is published through NPM, which we never will. Also, having a `version` prop doesn't …
=> Chore jenkinsfile prevent auto prod deploys

src/components/ChildIncidents/__tests__/ChildIncidents.test.js, src/components/ChildIncidents/index.js, src/shared/types/index.js, src/signals/incident-management/containers/IncidentDetail/__tests__/IncidentDetail.test.js, src/signals/incident-management/containers/IncidentDetail/__tests__/reducer.test.js, src/signals/incident-management/containers/IncidentDetail/components/ChildIncidents/__tests__/ChildIncidents.test.js, src/signals/incident-management/containers/IncidentDetail/components/ChildIncidents/index.js, src/signals/incident-management/containers/IncidentDetail/constants.js, src/signals/incident-management/containers/IncidentDetail/index.js, src/signals/incident-management/containers/IncidentDetail/reducer.js, src/utils/__tests__/fixtures/childIncidents.json
This PR:
- adjusts the `IncidentDetail` container component so that it retrieves child incidents
- extracts the `IncidentDetail` reducer into a separate file and adds tests
- changes the `ChildIncidents` components in order to display the correct data
=> [SIG-2800] Child incidents call

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.test.js
This PR hides the send email checkbox in the detail form for the next statuses:
- `Ingepland`, `Heropend`, `Geannuleerd` en `Afgehandeld`
=> [SIG-2994] Hides the send email checkbox for several statuses in the detail form

src/shared/services/auth/auth.js
Errors related to unauthenticated sessions pop up in Sentry. This PR contains a change to the error message that is thrown whenever a state token can not be validated so that we have a clearer picture of why this error is thrown.
=> (Chore) More explicit error message in auth service

Dockerfile
This commit runs *apk upgrade* instead of *apk update* this is required
since the repository origin points to `latest-stable` which is different
from the image version `v3.11`
I've also placed back the *community* repository since it was missing
=> (Chore) fix Docker image

environment.conf.json, internals/webpack/template.js, package-lock.json, package.json, src/index.html, start.sh
This PR contains changes that allow tracking of visitors that do not have javascript support.
In order to accomplish that, a few changes had to be made to ensure that, at build-time, all env vars were correctly replaced; the previous implementation only replaced the first occurrences.
Next to that change, the error message that is shown, has been translated to Dutch.
=> (Chore) Matomo noscript tracking

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.test.js
This PR contains a change that resets the value of the `send_email` field in the status form so that, when a status is selected that should not show the checkbox, will not send the previously selected value to the API.
=> [SIG-3004] Prevent send_email flag to be sent

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.test.js, src/signals/incident-management/definitions/statusList.js
This PR ensures that the `send_email` checkbox in the status form will also be shown in case the selected status equals 'Geannuleerd'. 
The hardcoded status keys are removed from the `StatusForm` component and converted to boolean values in the `statusList` definition file.
=> [SIG-3007] Show send_email checkbox for cancelled status

src/signals/incident-management/__tests__/reducer.test.js, src/signals/incident-management/__tests__/selectors.test.js, src/signals/incident-management/reducer.js, src/signals/incident-management/selectors.js
This PR applies a change to the incident management module's state so that loading incidents has its own flag and a distinction can be made between loading of different resources.
=> [SIG-3012] Incidents loading state

environment.conf.json, src/index.html
This PR contains a change to the analytics service URL. Apparently, the Matomo JS tracker expects the URL to end with a slash 🤦‍♂️
=> (Fix) Matomo URL

src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.js
This PR hides the `optioneel` text for the `fietsrek-nietje` question
=> [SIG-3005] Hides the `optioneel` text for `fietsrek-nietje`

internals/schemas/environment.conf.schema.json
This PR, updates the json schema in order to allow the autosuggest control to search addressed in more than one municipality. This change was needed to meet the requirements for the implementation of the `Amsterdamsebos` configuration
=> [SIG-2471] - Allows the autosuggest to search in more than one municipality

src/signals/incident-management/definitions/statusList.js
This PR enables the definition of a default text for all statuses that can be selected in change status page
=> [SIG-3003] Adds default text capabilities for all statuses

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.test.js
This PR changes the logic in the `StatusForm` component for disabling the submit button. Prior to this change, the submit button was disabled whenever the form values didn't validate. After the change, the submit button is also disabled when the current incident status is a status that cannot be selected in the status form.
=> [SIG-3006] Disabling status form submit button

src/components/MapStatic/index.js
The `MapStatic` component references an image that doesn't seem to be hosted any more. This PR fixes that issue by referencing an internal image.
=> [SIG-3036] Replace marker image reference

src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js, src/signals/incident/definitions/wizard.js
This PR 
- Prevents the resetting of the incident data on error by introducing an `opslaan` step to the wizard.
- The navigation to the `incident/bedankt` occurs only when the saving of the incident is successfull
- This is the preferred solution because on slow internet the address will show `incident/bedankt` during save and will switch to `incident/fout`. 
- With this implementation 'incident/opslaan' will be shown in the address bar during the save operation.
=> [SIG-2160] Adds a loading state to the wizzard

internals/schemas/environment.conf.schema.json
Used in review apps and end-to-end test environments.
=> Allow Sentry and Matomo configuration flag to be null

src/components/AutoSuggest/index.js
This PR fixes an issue where, in Safari, the `AutoSuggest` component has margin between the input element and its outline.
=> [SIG-2851] Autocomplete shadow margin fix

README.md, environment.conf.json, internals/schemas/environment.conf.schema.json
This PR should improve setting up Signalen for new users.
- Improve development, test and deployment instructions.
- Refer to the public Docker registry for pre-build images.
- Refer to Helm charts for easy deployment on Kubernetes.
- Add example settings of the theme object.
Closes Signalen/frontend#68
=> Improve development, test and deployment instructions

src/components/MapInput/__tests__/reverseGeocoderService.test.js, src/components/MapInput/services/reverseGeocoderService.js, src/shared/services/map-location/index.js, src/shared/services/map-location/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Location/index.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Location/index.test.js
This PR contains a fix for when the PDOK service returns with a `500` response. The result of that is that an incident doesn't have a resolved address, just GPS coordinates. Since the backend resolves the 'stadsdeel', a change was necessary in the `Location` component of the `IncidentDetail` container to be able to show the resolved stadsdeel.
=> [SIG-2975] Handle failing PDOK response

src/signals/incident-management/containers/IncidentDetail/components/Detail/index.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/index.test.js
This PR changes the order of the `phone` and `email` field values in the incident detail page. It also makes them conditionally visible.
=> [SIG-2295] Field order

src/signals/incident-management/containers/IncidentDetail/components/AddNote/index.js, src/signals/incident-management/containers/IncidentDetail/components/AddNote/index.test.js
This PR makes the submit button for the `AddNote` component form always clickable. For visual feedback, an error message is shown when the text area is left empty when the form is submitted.
=> [SIG-3078] AddNote component validation

src/signals/settings/categories/Detail/__tests__/Detail.test.js, src/signals/settings/categories/Detail/components/CategoryForm/index.js, src/signals/settings/hooks/useFetchResponseNotification.js, src/signals/settings/users/Detail/__tests__/Detail.test.js, src/signals/settings/users/Detail/components/UserForm/index.js, src/signals/settings/users/Detail/index.js
This PR contains changes that render a user's edit history in the user detail page. For that, this PR:
- Adds an extra request to the `UserDetail` component to retrieve the history
- Applies layout changes to the `UserForm` component so that its children are properly aligned
- Rewrites all the tests for the `UserDetail` component
- Applies a fix to the `useFetchResponseNotification` hook that prevents unnecessary rerenders for every component that uses that hook.
=> [SIG-1848] User history

src/components/PDOKAutoSuggest/__tests__/PDOKAutoSuggest.test.js, src/hooks/useFetch.js
This PR replaces the `useState` calls in the `useFetch` hook with one `useReducer` call. This reduces the number of rerenders of any component that uses the `useFetch` hook.
=> (Chore) Refactor useFetch hook

internals/schemas/environment.conf.schema.json
The `matomo` and `sentry` entries in the environment config can be optional, instead of allowing them to have a value of `null` while being required.
=> Make matomo and sentry entries optional

src/signals/incident-management/definitions/typesList.js
closes Signalen/frontend#72
Remove reference to Amsterdam which was still left in the description of a type.
=> Remove reference to Amsterdam.

src/components/History/index.js
This one-liner changes the alignment of the `History` definition list from:
to:
=> (Fix) History alignment

src/signals/incident-management/components/RadioButtonList/index.js, src/signals/incident-management/components/RadioInput/index.js, src/signals/incident/components/form/RadioInput/index.js, src/signals/settings/categories/Detail/components/CategoryForm/index.js
This PR changes the appearance of checkbox and radio button labels so that those labels won't span the whole width of their containers.
Note that, next to the mentioned change, a change has also been applied to the `CategoryForm` component to overcome misalignment of elements on the page.
=> [SIG-3083] Form styling

src/signals/incident-management/containers/IncidentDetail/components/Detail/index.js, src/signals/incident-management/containers/IncidentDetail/components/Detail/index.test.js
This PR ensures that both phone and email labels in the incident detail page are always visible, regardless of presence of value for those fields.
=> [SIG-3094] Phone/email label visibility

src/components/MapStatic/index.js, src/hooks/useFetch.js, src/signals/incident-management/containers/IncidentOverviewPage/components/Map/index.js, src/signals/incident-management/containers/IncidentSplitContainer/services/useFetchIncident/index.js
This PR fixes a couple of issues with regards of the use of the `useFetch` hook by components.
First of all, the `AbortController` in the `useFetch` hook could not be used as a internal hook dependency, because it was regenerated at every render. To overcome this, the `useMemo` hook was used. That also applied to the `requestHeaders` variable.
Memoizing the `AbortController` instance allowed for setting it as a dependency of the `useEffect` hook. This ensures that the correct object instance is called when a component unmounts.
Second, the internal `get` and `modify` methods weren't wrapped in a `useCallback` hook and thus returned a new instance with every consecutive render and could not be used as dependency by components that implemented `useFetch`.
As a bonus, the `PUT` method is …
=> (Chore) Fix useFetch hook internal handlers

internals/schemas/environment.conf.schema.json
The configuration option `map` > `tiles` > `options` > `subdomains` should be optional. Currently only Amsterdam is using it.
=> Make the map tiles subdomains config optional

src/signals/shared/filter/__tests__/parse.test.js, src/signals/shared/filter/parse.js
IMHO the backend should accept dates without the timestamps so we don't need this prone to error logic on the front-end.
When the dates from the filter form are stored the reducer will append time strings to the dates.
When a user re-opens the filter form when dates are stored, the reducer assumes dates without time string,s this pull request fixes this by stripping the time string before the date gets further processed by the reducer.
=> [SIG-3103] Fix incident date filter

Dockerfile
This PR makes sure that the Cypres binary is not installed when `npm i` is run in the Dockerfile
=> (Chore) Skip Cypress binary install

src/signals/incident-management/containers/IncidentSplitContainer/Form.js, src/signals/incident-management/containers/IncidentSplitContainer/IncidentSplitContainer.js, src/signals/incident-management/containers/IncidentSplitContainer/__tests__/IncidentSplitContainer.test.js, src/signals/incident-management/containers/IncidentSplitContainer/index.js
This PR adds the `IncidentSplitContainer` component that:
- fetches incident data on mount
- renders a form (for now, uses a stub component which needs to be replaced)
- posts data on form submission
- shows a notification on error or success and redirects to the incident page
=> [SIG-2969] Split container

src/signals/incident-management/components/CheckboxList/index.js, src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/components/FilterForm/styled.js, src/signals/incident-management/containers/FilterTagList/__tests__/FilterTagList.test.js, src/signals/incident-management/containers/FilterTagList/index.js, src/signals/incident-management/definitions/directingDepartmentList.js, src/signals/incident-management/definitions/index.js, src/signals/shared/filter/parse.js
This PR adds the following block to the `FilterForm` component:
Note that the `Checkbox` component in the `CheckboxList` component has been replaced with our own component (which, in turn, also uses the asc-ui `Checkbox` component), because our own component shows a checkbox with a white background instead of a transparent background.
=> [SIG-2866] Regie filter block

src/signals/incident/components/IncidentForm/index.js
This PR reverts a previous change to the submission form's "Thank you" page. The page's width should've been the same as the rest of the form pages instead of spanning full width.
=> (Chore) Bedankt page form width

src/components/AutoSuggest/__tests__/AutoSuggest.test.js, src/components/AutoSuggest/index.js, src/components/Label/__test__/Label.test.js, src/components/Label/index.js, src/components/MapInput/__tests__/MapInput.test.js, src/components/MapInput/index.js, src/components/PDOKAutoSuggest/__tests__/PDOKAutoSuggest.test.js, src/hooks/__tests__/useDebounce.test.js, src/hooks/__tests__/useDelayedDoubleClick.test.js, src/hooks/index.js, src/hooks/useDebounce.js, src/hooks/useDelayedDoubleClick.js, src/signals/settings/users/Overview/__tests__/Overview.test.js, src/signals/settings/users/Overview/index.js, src/test/utils.js
Numerous tests were breaking unexpectedly across builds. Most of these breaking tests used either the Lodash `debounce` function or were dependent on `useDelayedDoubleClick` hook, which was also depending on `debounce`.  By removing said dependency and replacing `debounce` with a custom hook (`useDebounce`), the issue seems to be solved; tests are passing consistently.
By getting rid of `debounce` and the subsequent `resolveAfterMs` test utility function, there is more fine grained control over components in tests.
=> (Chore) Remove lodash/debounce

src/containers/App/index.js, src/signals/incident/containers/IncidentContainer/index.js, src/signals/incident/containers/IncidentContainer/index.test.js
This PR fixes an issue that was found in acceptance. The problem was that the category was not preset and the prediction tool was not disabled when the correct presset link was used. In production mode, initialization of the incident container reducer was done after the InidentClassification events were triggered. The solution was to move the IncidentClassification component to the IncidentContainer in order to ensure the correct handling of the redux events.
=> [SIG-3092] Bugfix preset the incident classification 

src/signals/incident-management/containers/IncidentSplitContainer/IncidentSplitContainer.js, src/signals/incident-management/containers/IncidentSplitContainer/__tests__/IncidentSplitContainer.test.js
This PR copies the `attachments` prop from the original incident into the created 'deelmeldingen' on split form post.
=> [SIG-3154] Deelmelding attachments

src/signals/incident/components/form/DescriptionWithClassificationInput/index.js, src/signals/incident/components/form/DescriptionWithClassificationInput/index.test.js
This bug fixes a bug that prevented updating the description value when the predictions were disabled
=> [SIG-3092] Updates the description value when the predictions are disabled

src/components/Footer/index.js, src/containers/App/index.js, src/containers/App/index.test.js, src/signals/incident-management/__tests__/index.test.js, src/signals/incident-management/index.js, src/signals/settings/__tests__/index.test.js, src/signals/settings/index.js
This PR moves the fetch of subcategories to the `App` container level. Previously, subcategories were retrieved in the `incident-management` and `settings` modules. Since subcategories are also required in the `incident` modules, it makes sense to move the responsibility of retrieving the data to the highest level in the application.
=> [SIG-3156] Fetch subcategories at App level

src/signals/incident/components/form/CategorySelect/CategorySelect.js, src/signals/incident/components/form/CategorySelect/CategorySelect.test.js
This PR displays an default text in the CategorySelect component.
=> [SIG-3091] Add default text to subcategory select input

src/containers/App/index.js
This PR disables the lazy loading of the IncidentContainer. This enforces the correct loading of the Leaflet component and prevents incorrect display of the map tiles in some cases (for instance OverviewMap)
=> (Chore) Fix map overview tiles

src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js
Due to a previous change, the parameters `category` and `subcategory` weren't sent to the `questions` endpoint anymore. This change fixes that bug.
Unit test has been updated to catch this in the future.
=> Fix cat and subcat sent to questions endpoint

src/signals/incident-management/containers/IncidentDetail/__tests__/reducer.test.js, src/signals/incident-management/containers/IncidentDetail/index.js, src/signals/incident-management/containers/IncidentDetail/reducer.js
This PR ensure that when updating an incident (for example changing the priority), the children are not retested.
=> [SIG-3183] Keeps the children when updating the incident

src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/components/FilterForm/reducer.js, src/signals/incident-management/containers/FilterTagList/__tests__/FilterTagList.test.js, src/signals/incident-management/containers/FilterTagList/index.js, src/signals/incident-management/definitions/changedChildrenList.js, src/signals/incident-management/definitions/index.js, src/signals/shared/filter/parse.js
This PR adds the `has_changed_children` filter so the user can filter the main incidents on changes in the children incidents
=> [SIG-2879] Adds  the has_changed_children filter

src/signals/settings/departments/Overview/__tests__/Overview.test.js, src/signals/settings/users/Detail/__tests__/Detail.test.js, src/signals/settings/users/Detail/components/UserForm/__tests__/UserForm.test.js
This PR applies DRY rules to the departments fixture. The conversion to the internal format is already done in the `utils/__tests__/fixtures`
=> (Chore) Removes duplicated conversion code for departments

src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.js, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.test.js
Removed fixed-width columns for the incident list in the back office. The accompaning comment indicated it was done to make sure icon and text would not be wrapped.
Replaced it with the much simpler `white-space: nowrap` which also achieves this goal.
Setting explicit widths is very fragile and decreases maintainability and refactorability significantly!
Also made it possible to explicitly set a cell to nowrap. This is useful for the date column in this case.
A unit test has been provided.
=> Replace fixed column widths with nowrap

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/__tests__/StatusForm.test.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/constants.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/styled.js, src/signals/incident-management/containers/IncidentDetail/index.js, src/signals/incident-management/definitions/statusList.js
This PR shows a warning when the state of a parent incident is changed to Closed (`afgehandeld` or `geannuleerd`) and one of its children is not yet Closed.
=> [SIG-2884] Show a warning when the state of the child incidents is not closed

src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitFormIncident/__tests__/IncidentSplitFormIncident.test.js, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitFormIncident/index.js
Fixes bug where, if the incident was previously splitted _X_ times, the incident split form would open with _X_ forms.
=> Fix split incident form opening with multiple incident forms

internals/scripts/validate-base-config.js, package.json
The pre-commit hook validated the configuration in `app.base.json`, including any extended configuration in `app.json`. It only needs to validate `app.base.json` however, since `app.json` won't be committed as it's ignored.
This makes it easier to keep some extended configuration in `app.json` in development, while switching branches.
`validate-base-config.js` in this PR is a copy of `validate-config.js` with the only difference that it does `const { baseConfig } = require('./helpers/config');` instead of `const { config } = require('./helpers/config');`.
=> Validate base config on pre commit hook

src/models/departments/selectors.js, src/shared/types/index.js, src/signals/incident-management/containers/IncidentSplitContainer/IncidentSplitContainer.js, src/signals/incident-management/containers/IncidentSplitContainer/__tests__/IncidentSplitContainer.test.js, src/signals/incident-management/containers/IncidentSplitContainer/__tests__/parentIncidentFixture.json, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitForm/__tests__/IncidentSplitForm.test.js, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitForm/index.js, src/utils/__tests__/fixtures/departments.json, src/utils/__tests__/fixtures/incident.json
This PR fixes a bug that didn't select by default the directing department from the parent in the split form
=> [SIG-3262] Add the directing department value from the parent to the split form

src/signals/incident-management/containers/DefaultTextsAdmin/components/DefaultTextsForm/index.js, src/signals/incident-management/containers/DefaultTextsAdmin/components/SelectForm/index.js, src/signals/incident-management/containers/DefaultTextsAdmin/components/SelectForm/index.test.js, src/signals/incident-management/containers/DefaultTextsAdmin/index.js, src/signals/incident-management/containers/DefaultTextsAdmin/index.test.js
closes Signalen/frontend#80
The bug is explained in the issue mentioned above.
There is no hard-coded default value set anymore for the subcategory, to fetch the default texts for, on load. Instead, the first subcategory in the list will be programmatically selected and used.
=> [FE#80] Auto load first subcategory in the list

app.base.json, internals/schemas/app.schema.json, src/components/Map/index.js
closes Signalen/frontend#81
There was a reference left in the code to Amsterdam by means of the site's address. This PR moves this to the language section of the configuration `language.siteAddress`.
**Update to `app.base.json`**
`language.siteAddress`
The site's address, for having a means of referencing the site by its address.
Default value: `meldingen.amsterdam.nl`.
=> [FE#81] Move site address reference to configuration

internals/testing/test-bundler.js, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitForm/__tests__/IncidentSplitForm.test.js, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitFormIncident/__tests__/IncidentSplitFormIncident.test.js, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitFormIncident/index.js, src/signals/incident-management/containers/IncidentSplitContainer/styled.js
When clicking the button 'Extra deelmelding toevoegen', the view should scroll to the newly added incident split form.
=> [SIG-3260] Adds scroll to split incident when added

src/models/departments/useDirectingDepartments.js, src/models/departments/useDirectingDepartments.test.js, src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js, src/signals/incident-management/containers/IncidentSplitContainer/IncidentSplitContainer.js, src/signals/incident-management/definitions/changedChildrenList.js, src/signals/incident-management/definitions/directingDepartmentList.js, src/signals/incident-management/definitions/index.js, src/utils/__tests__/fixtures/index.js
This PR
- Moves the selector for the directing departments to a separate hook
- Uses the departments can_direct prop to determine if a department should be included in the directing departments list.
=> (Chore) Improve directing department selection

src/components/PDOKAutoSuggest/__tests__/PDOKAutoSuggest.test.js, src/components/PDOKAutoSuggest/index.js
closes Signalen/backend#73
With multiple municipalities configured in `map.municipality` in `app.json`, the results of the PDOK suggest service was unpredictable. Some cities within a municipality configured would not show up in the suggest results. While other municipalities not configured would show up in the suggest results.
It turns out that calling the PDOK suggest service with the following parameter is not giving the expected results:
```
fq=gemeentenaam:"boxtel" "altena"
```
When we write this parameter as follows, we do get the expected results:
```
fq=gemeentenaam:"boxtel"gemeentenaam:"altena"
```
This should be updated accordingly in the backend as well.
The following request will give you the expected results of the `Mezenlaan` in `Boxtel`.
```
➜ curl …
```
=> Fix PDOK suggest for multiple municipalities

src/components/PDOKAutoSuggest/__tests__/PDOKAutoSuggest.test.js, src/components/PDOKAutoSuggest/index.js
Use the more intuitive solr syntax for the request to the PDOK suggest service. As explained in Amsterdam/signals#628.
Use
```
gemeentenaam:("den bosch" "boxtel" "altena")
```
instead of
```
gemeentenaam:"den bosch" gemeentenaam:"boxtel" gemeentenaam:"altena"
```
=> Use more intuitive solr syntax for suggest request

src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Location/index.js
closes Signalen/frontend#85
Fixes the bug described in the issue mentioned above.
It makes sure the leaflet map, for the location thumbnail on the incident detail page, updates afther the location has been edited. This is done by adding a `key` prop to the `MapDetail` with the lat/lng value of the location.
This is the map that is being used for other municipalities than Amsterdam. Amsterdam has a static map server for serving images of a map. For other municipalities a leaflet map is being used. We might switch to a static map server for other municipalities in the future as well.
=> Update leaflet map thumbnail on location change

src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.js
This PR prevents the 'delen' button to be shown. 
Background info:
The incident split functionality was developed and accepted, but the customer is not yet ready to make use of it in the coming release. This commit will be reverted when the customer is ready. 
Concerning the e2e tests, @arjandata is aware of this change, and the periodic e2e tests will succeed because the deelmeldingen tests are not (yet) enabled.
=> [SIG-3283] Hides split button

src/signals/incident-management/containers/IncidentDetail/index.js
This PR fixes a problem that occured after the parent incident was closed or canceled; The open child incidents are automatically canceled, but this change was not direct visible in the detail page.
=> [SIG-3269] Refresh the incident children after each incident change

src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.js
This PR reverts #1221 and makes the incident split button visible again.
=> [SIG-3286] Revert "#1221 from Amsterdam/SIG-3283-hide-split-button"

src/signals/incident/containers/IncidentContainer/services.js, src/signals/incident/containers/IncidentContainer/services.test.js
All additional questions (coming from the backend) should have their answer inside the `extra_properties` parameter of the signal in the POST request creating the signal.
This PR makes sure this is done by default and should not have to be configured for every question in the database.
The `required` property on a question (coming from the backend) is now also being picked up. Whenever it's `true`, the `required` validator is being added to the `options.validators` property.
=> Post additional questions through extra_properties

docs/README.md, docs/additional-questions.md, docs/serviceworker-proxy.md
For now, the additional questions coming from the backend can be configured in the Jango admin. This PR creates documentation to give a simple overview of how to configure those questions and what the possible options are.
=> (Chore) Docs overview on configuring questions

src/app.js
This minor change makes sure that `Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://meldingen.amsterdam.nl/') with script ('https://meldingen.amsterdam.nl/sw.js'): An unknown error occurred when fetching the script.` errors won't be popping up in Sentry logs.
=> (Chore) serviceworker installation condition

src/models/categories/__tests__/selectors.test.js, src/models/categories/selectors.js
This PR fixes a bug where in the display name of the subcategory the departments list were missing
=> [SIG-3029] Uses the extendedName for the subcategory in the category list

src/signals/incident-management/containers/IncidentDetail/components/ChangeValue/index.js, src/signals/incident-management/containers/IncidentDetail/components/ChangeValue/index.test.js
This PR initializes the ChangeValue state each time the incident changes. This fixes a bug where bij navigation to a different incident, the edit state of a change value remained open.
=> [SIG-3324] Reset the edit mode when the incident is changed

.eslintrc.yaml, jest.config.js
This enables the possibility to run Jest (from node_modules, system or npx) from everywhere
For example:
```
cd ~/ga/signals-frontend/src/hooks
npx jest --coverage --watch src
jest --coverage --watch IncidentSplitContainer
```
Or 😎 :
```
node /home/jpoppe/ga/signals-frontend/node_modules/.bin/jest \
--config /home/jpoppe/ga/signals-frontend/jest.config.js \
--runTestsByPath /home/jpoppe/ga/signals-frontend/src/components/ChildIncidents/__tests__/ChildIncidents.test.js \
--watch
```
- also added jest.config.js to Node module overrides in the ESLint configuration
=> (Chore) Make it possible to run Jest outside the project root directory

src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.js, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.test.js
This PR marks with a grey `play` icon all the child incidents in the overview list
=> [SIG-3288] Show an icon for the child incidents in the overview

src/signals/incident/components/form/PlainText/style.scss, src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.js, src/signals/incident/definitions/wizard-step-2-vulaan/wonen.js
This PR 
- adds a temporary message about the Christmas lights in the `straatverlichting` additional questions. 
- fixes a small style issue on displaying the PlainText component with `alert` type
- adds a not existing category to make possible disabling of this message when required
=> [SIG-3268] Enable Christmas lights message

src/signals/incident/definitions/wizard-step-2-vulaan/wonen.js
This PR fixes the following bugs:
- When entering 'vakantieverhuur' step-2 questions, all first-level questions should be visible
- When answering 'Weet ik niet' on the first question, the same questions are shown as when answering 'Ja' or 'Nee'
- When entering 'wonen overig' step-2 questions, only the first question should be visible
=> [SIG-3385] Fixes conditional rendering of vakantieverhuur questions

src/signals/incident/services/map-paths/index.js, src/signals/incident/services/map-paths/index.test.js
This PR adds the category_url of the incident to the answer of every extra question. 
Functionally, this means that the backend is able to relate questions/answers on an incident to a specific (sub)category. This allows for filtering where only users with rights to specific categories can see the answers to those questions.
=> Adds category_url to value of extra questions

Dockerfile
This PR adds the app.amsterdam.json to the docker container. This was missing and generated a crash in the build pipeline.
=> (Chore) Fix the build configuration for amsterdam

package-lock.json, package.json, src/components/SiteHeader/__tests__/SiteHeader.test.js, src/components/SiteHeader/index.js
This PR:
- updates the `asc` package to the last version
- replaces the `h1` element with a `div` for accessibility
- fixes the focus style of the `select` elements
- fixes the alignment of the clear button in the search text field of the header
=> [SIG-3308] Replace h1 from the logo

jest.config.js, src/signals/incident/components/form/ContainerSelect/ContainerList/ContainerList.js, src/signals/incident/components/form/ContainerSelect/ContainerList/ContainerList.test.js, src/signals/incident/components/form/ContainerSelect/ContainerList/index.js, src/signals/incident/components/form/ContainerSelect/ContainerSelect.js, src/signals/incident/components/form/ContainerSelect/ContainerSelect.test.js, src/signals/incident/components/form/ContainerSelect/Intro/Intro.js, src/signals/incident/components/form/ContainerSelect/Intro/Intro.test.js, src/signals/incident/components/form/ContainerSelect/Selector/Selector.js, src/signals/incident/components/form/ContainerSelect/Selector/Selector.test.js, src/signals/incident/components/form/ContainerSelect/Summary/Summary.js, src/signals/incident/components/form/ContainerSelect/Summary/Summary.test.js, src/signals/incident/definitions/wizard-step-2-vulaan/afval-icons.js, src/signals/incident/definitions/wizard-step-2-vulaan/afval.js
This PR:
- adds a generic definition for the map items
- adds the metadata configuration for the ContainerSelect
- adds svg icons for the specific implementations (will later be moved to the backoffice)
- add temporary (test) functionality for adding containers
- renders the added containers in the Summary component
=> [SIG-3333] Container selection component

app.amsterdam.json, src/components/MapInput/index.js
This PR hides the map attribution text for the screen readers
=> [SIG-3370] Hide attribution on screen readers

eslint-plugin-amsterdam/typescript.js
Ensures that objects/arrays/imports/exports have dangling commas when multi-line
=> (Chore) Adds comma-dangle ts config

src/components/SiteHeader/index.js
- Changes 'Melden' link in header to be a client-side route
=> [SIG-3424] 'Melden' link as a client-side route

docs/additional-questions.md, package-lock.json, package.json, src/signals/incident/components/form/PlainText/index.js, src/signals/incident/components/form/PlainText/index.test.js
closes Signalen/frontend#97
Parse and render markdown for the value of the `PlainText` field in the incident wizard.
Do this only when the `fetchQuestionsFromBackend` feature flag is enabled.
=> [FE#97] Allow markdown for PlainText value

src/signals/incident-management/components/CheckboxList/CheckboxList.js, src/signals/incident-management/components/CheckboxList/CheckboxList.test.js, src/signals/incident-management/components/FilterForm/components/CategoryGroups.js, src/signals/incident-management/components/FilterForm/index.js
- Clicking on a checkbox and then pressing 'Enter' did not submit the filter selection
- Clicking on 'Alles selecteren' or 'Niets selecteren' for Category filters did not work
- Clicking on 'Alles selecteren' or 'Niets selecteren' and then pressing 'Enter' did not submit the filter selection
=> [SIG-3417] Fix 'Enter' behaviour for filtering on Firefox/Safari on Mac

src/signals/incident/components/form/PlainText/index.js, src/signals/incident/components/form/PlainText/index.test.js
Injecting incident values into the `PlainText` value wasn't been done anymore in case of parsing and rendering markdown (#1323). This injection functionality has been added again, in case of markdown, with this PR.
=> Fix incident value injection for Markdown in PlainText

src/signals/incident/components/form/FileInput/index.js, src/signals/incident/components/form/FileInput/styles.js
- Adds outline to file upload button when element is focused
Previously, when using `Tab` to navigate to the file upload button, it was unclear that it was focused (the file input is a hidden input). Now, the element depicting the upload button will show an outline.
=> (Chore) Add outline to file upload element when focused

src/components/SiteHeader/index.js
- Remove client-side route to trigger reset of incident form data
=> [SIG-3455] Revert "Changes 'melden' link to a client-side route"

src/signals/incident/containers/IncidentContainer/reducer.js, src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js, src/signals/incident/containers/IncidentContainer/services.js, src/signals/incident/containers/IncidentContainer/services.test.js
closes Signalen/frontend#98
When logged in, the questions were not fetched from the backend (`fetchQuestionsFromBackend`) in case of manual selection (override) of the category. This has been fixed in this PR.
=> [FE#98] Fix fetch questions on manual category selection

src/components/Modal/index.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/components/FilterForm/styled.js
closes Signalen/frontend#95
A few minor changes:
* Fix the bottom padding of the filters modal. With the right column being taller, there was no problem. With the left column being taller there was not enough padding at the bottom, making the last controls disappear below the footer. The padding has been straightened out. For the `ModalInner` `height: calc(100vh - (60px + 40px));` (60 for the header and 40 for the padding). For the `FilterForm` `padding-bottom: 86px;` (66 for the footer plus 20 padding).
* Move the 'assigned to' filter above the 'source' filter. This gives it enough space for the auto-suggest dropdown to appear, without having to scroll down after it folds open.
* Add `z-index: 2;` to the footer to keep it on top of the auto-suggest.
=> [FE#95] Fix bottom padding of filters modal

src/hooks/__tests__/useFetch.test.js, src/hooks/useFetch.js, src/shared/services/auth/auth.js
- Bug that caused old access tokens to be used in authenticated requests
=> [SIG-3465] Expired authentication error when logged in with Keycloak

src/app.js, src/configureStore.test.js, src/test/utils.js, src/utils/reducerInjectors.test.js, src/utils/sagaInjectors.test.js
This PR fixes a error that occured in the tests after the changing the state base structure from immutable to plain JS object
=> (Chore) Replace Imutable.Map with {} as initialState in tests

src/signals/incident/components/IncidentPreview/index.js
- Changes summary list to conform to A11Y 
Previously, the summary list was a mix of an unordered list and a description list. Now it's just a description list.
=> [SIG-3306] Improves A11Y for summary page

jest.config.js, src/components/LoginPage/index.js, src/components/LoginPage/index.test.js, src/containers/App/saga.test.ts, src/containers/App/saga.ts
This PR removes the ADW button and references. The existing `Inloggen Keycloak` button is renamed to `Inloggen ADW`
=> [SIG-3462] Removes the ADW/Grip button references

src/components/IconList/IconList.tsx, src/signals/incident/components/form/ContainerSelect/components/Selector/components/LegendPanel/index.tsx, src/signals/incident/components/form/ContainerSelect/components/Selector/components/LegendToggleButton/__tests__/index.test.tsx, src/signals/incident/components/form/ContainerSelect/components/Selector/components/LegendToggleButton/index.tsx, src/signals/incident/components/form/ContainerSelect/components/Selector/components/ViewerContainer/__tests__/index.test.tsx, src/signals/incident/components/form/ContainerSelect/components/Selector/components/ViewerContainer/index.tsx, src/signals/incident/components/form/ContainerSelect/components/Selector/index.tsx
This PR fixes UX and styling based on a review by our designer
- Map drawer should be open by default
- Map drawer subtitle should be shown as a paragraph in the content area
- Selection submit button should be active always
- Remove vertical scroll on map
- Fix map buttons shadow and font
- Add slide-in animation to legend
- Prevent icons shrinking when labels in icon list are long
=> [SIG-3339] Container map drawer

.eslintrc.js, eslint-plugin-amsterdam/react.js, eslint-plugin-amsterdam/typescript.js, src/components/AutoSuggest/__tests__/AutoSuggest.test.js, src/components/Label/Label.test.tsx, src/containers/App/index.test.tsx, src/containers/App/index.tsx, src/containers/App/saga.ts, src/containers/MapContext/index.js, src/signals/incident-management/containers/IncidentDetail/IncidentDetail.js, src/signals/incident-management/containers/IncidentDetail/IncidentDetail.test.js, src/signals/incident-management/containers/IncidentDetail/components/AttachmentViewer/index.test.js, src/signals/incident-management/index.js, src/signals/settings/departments/Detail/index.js, src/signals/settings/index.js, src/types/index.ts
This PR
- Fixes the linting errors that occured after the update of the packages
- Adds a new override section for lint rules specific to tests to the eslint config file
- Promotes few linting rules to the amsterdam plugin
=> (Chore) Fix the new linting rules after package update

jest.config.js, src/signals/incident/components/IncidentPreview/components/ContainerListPreview/ContainerListPreview.test.tsx, src/signals/incident/components/IncidentPreview/components/ContainerListPreview/ContainerListPreview.tsx, src/signals/incident/components/form/ContainerSelect/__tests__/context.test.tsx, src/signals/incident/components/form/ContainerSelect/components/ContainerList/__tests__/index.test.tsx, src/signals/incident/components/form/ContainerSelect/components/ContainerList/index.tsx, src/signals/incident/components/form/ContainerSelect/components/Selector/components/WfsLayer/components/ContainerLayer/index.tsx, src/signals/incident/components/form/ContainerSelect/components/Selector/index.tsx, src/signals/incident/components/form/ContainerSelect/components/Summary/__tests__/index.test.js, src/signals/incident/components/form/ContainerSelect/components/Summary/index.js, src/signals/incident/components/form/ContainerSelect/types.ts, src/signals/incident/definitions/__tests__/wizard-step-5-samenvatting.test.js, src/signals/incident/definitions/wizard-step-2-vulaan/afval.ts, src/signals/incident/definitions/wizard-step-5-samenvatting.js
This PR restructures the item structure by removing the iconUrl property as this is not expected by the api.
=> [SIG-3484] Remove icon url when posting incident

src/components/Input/index.js, src/signals/incident-management/components/CheckboxList/CheckboxList.js, src/signals/incident-management/components/FilterForm/index.js, src/signals/incident-management/components/RadioInput/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js, src/signals/incident/components/form/CheckboxInput/index.js, src/signals/incident/containers/KtoContainer/components/KtoForm/index.js, src/signals/settings/roles/containers/RoleFormContainer/components/RoleForm/index.js
This PR 
- Ensures that the checkbox labels don't get bold when the checkbox is selected
- Implements the naming conventions that a 3td party component will not be renamed unless there are name conflicts with another component. When only a `style` is applied, the `Styled<ComponentName>` will be used for consistency.
=> [SIG-3494] Fix style in checkbox label

internals/schemas/app.schema.json, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.js
The filename of the PDF you can download for an incident needs to be changed.
Now using `configuration.language.shortTitle` in the filename.
=> Update PDF filename

src/components/AutoSuggest/__tests__/AutoSuggest.test.js, src/components/AutoSuggest/index.js
closes Signalen/frontend#100
Fixes two bugs:
- Puts `z-index` on the dropdown list of `AutoSuggest` instead of the whole component. This prevents the bug we had where the calendar pop out of a control above would render below the input element of the `AutoSuggest` (see images below).
- The `onClear` function of the AutoSuggest was not required. It was called, however, without checking if it was defined. Found this bug when pressing escape with focus on the AutoSuggest of the map view in the back office.
Normal:
Before:
After:
=> [FE#100] Bug Auto suggest z-index

Dockerfile
- Fix Docker build
Since the file handling application configuration was converted to TypeScript, the example file from which the config type is inferred needs to be present during build time. 
This PR fixes the deploy (and e2e tests).
=> (Chore) Fix Docker build

src/signals/incident-management/__tests__/selectors.test.js, src/signals/incident-management/selectors.js
closes Signalen/frontend#102
- The selected `source` was not maintained in a saved filter.
- The same goes for `area` in case the feature flag `fetchDistrictsFromBackend` is turned on. This still requires a change in the backend as well, though. (Signalen/backend#111)
=> [FE#102] Source in saved filter

src/signals/incident-management/__tests__/saga.test.js, src/signals/incident-management/saga.js, src/signals/incident-management/selectors.js, src/signals/shared/filter/__tests__/parse.test.js, src/signals/shared/filter/parse.js
closes Signalen/frontend#104
Saving a filter on `area` should convert the filter key `area` to `area_code`.
Dependant on a fix in the backend as well: Amsterdam/signals#708.
We can merge independently of the bugfix in the backend since it's not working now anyway.
=> [FE#104] Save filter with area_code

src/signals/incident/components/form/ContainerSelect/Selector/SelectionPanel/SelectionPanel.tsx, src/signals/incident/components/form/ContainerSelect/Selector/Selector.tsx, src/signals/incident/components/form/ContainerSelect/Selector/ZoomMessage/ZoomMessage.tsx, src/signals/incident/components/form/ContainerSelect/Selector/__tests__/Selector.test.tsx
- Fix styling based on review comments
Regarding the brackets change `(${breakpoint('max-width', 'tabletM')})`, contrary to what I first thought, they do 'fix' a linting error but break the functionality itself. Looks like there is a bug in the VSCode styled components plugin (there are multiple reports about this on GitHub).
=> [SIG-3414] Fix map select design comments

internals/mocks/fixtures/departments.json, internals/testing/msw-server.ts, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js
fixes Signalen/frontend#105
depends on Amsterdam/signals#714
**Problem**
For the form field of 'assigned user' of an incident, the users were filtered on department in the FE. This was based on a list of users fetched from the users endpoint. This is not a full list of all users but the first 'page' of 100 users. This gave problems.
**Solution**
The users are now filtered on the BE by means of a request to the user endpoint with the `profile_department_code` filter param.
=> [FE#105] Filter users on department through endpoint

src/signals/incident/services/map-controls-to-params/index.js, src/signals/incident/services/map-controls-to-params/index.test.js
- Fix incident form retaining data when using 'back' button
=> [SIG-3556] Fix incident form retaining data from previous submissions

src/signals/incident/components/form/ContainerSelect/Selector/Selector.tsx
This PR adds a box shadow to the container map drawer for better UX.
=> [SIG-3535] Add box shadow to the mobile version of the drawer

src/components/MapInput/index.js
- Fixes horizontal scroll bar shown on iOS and macOS when on the first step of the incident page
The horizontal scroll bar was only shown on smaller screens (mobile/tablet)
=> [SIG-3515] Prevent horizontal scroll bar on first step incident page (iOS/macOS)

e2e-tests/cypress/integration/createSignals/createSignalContainerOnMap.spec.ts, src/signals/incident/components/form/ContainerSelect/Selector/WfsLayer/ContainerLayer/ContainerLayer.tsx
This PR solves a bug in the container selection; When the spiderfied version of the cluster was closed by clicking in the map, the selected cluster was lost.
=> [SIA-3574] Prevents the selected cluster from closing

src/signals/incident/definitions/__tests__/wizard-step-5-samenvatting.test.js, src/signals/incident/definitions/wizard-step-5-samenvatting.js
- Change summary labels to match question labels
Based on A11Y feedback, labels in the summary page now match the question labels. This prevents confusion for the users when identifying questions.
=> [SIG-3315] Changes summary labels to match question labels

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/styled.js, src/signals/incident/definitions/wizard-step-5-samenvatting.js
- Hides summary checkbox label inadvertently added in https://github.com/Amsterdam/signals-frontend/pull/1428
- Fixes alignment of checkbox label
=> [SIG-3315] Hide summary checkbox label

src/signals/incident-management/components/CheckboxList/CheckboxList.js, src/signals/incident-management/components/CheckboxList/CheckboxList.test.js
- Prevents setting empty id on filter checkbox label
When in the incident management page and pressing "Filteren", selecting "Alles selecteren" on the Status field triggered a console log, because the label has a `for` attribute set to empty string (and the accompanying checkbox input is not rendered).
=> (Chore) Fixes console warning for empty string id

.github/workflows/end-to-end.yml
- Trigger e2e test run every time a PR is opened or edited
This will increase visibility of the e2e tests and make sure that regressions are noticed early on. The results of the (currently failing) e2e tests can be viewed [`here`](https://dashboard.cypress.io/projects/xdzm5k/runs?branches=%5B%5D&committers=%5B%5D&flaky=%5B%5D&page=1&status=%5B%5D&tags=%5B%5D&timeRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D)
=> (Chore) Adds opened/edited PR to e2e test triggers

src/signals/incident-management/containers/IncidentDetail/IncidentDetail.js, src/signals/incident-management/containers/IncidentDetail/__tests__/IncidentDetail.test.js
fixes Signalen/frontend#117
Added scroll to top when you open the edit status form of an incident. And again when closing the form.
See the issue mentioned above for the details of the problem.
=> [FE#117] Add scroll to top

jest.config.js, src/components/MapSelect/index.js, src/signals/incident/components/form/MapSelect/index.js, src/signals/incident/components/form/MapSelectGeneric/index.js
This PR adds the id and aria-describedby attributes on the MapSelect and MapSelectGeneric components for accessibility
=> [SIG-3624] Adds a11y to the MapSelect component

.github/workflows/end-to-end.yml, Dockerfile, Makefile, docker-compose.yml
This PR adds an `frontend-dev` development configuration service to the docker-compose. This enables changes in the sources when running the application in development mode. 
- Use `make start` to run the application in dev mode
- Use `docker-compose up frontend` to start the application as a container. This command will be used in the `gh-actions` as well for the `e2e-tests`.
=> (Chore) Add development configuration to docker-compose

src/signals/incident/components/form/ContainerSelect/Intro/Intro.tsx
- Prevents interaction with background map in container selection flow
Specifically, it was possible to select/drag/zoom the map shown in the background of the `<Intro />` component.
=> [SIG-3633] Prevent interaction with background map in container selection flow

Dockerfile
This PR fixes the jenkins build by adding the app.amsterdam.json to the base docker layer. The types defined in this file are now used as typescript types so the reference of this file is needed for the build
=> (Fix) Add the app.amsterdam.json to the docker base layer

src/signals/incident/definitions/wizard-step-2-vulaan/overlast-op-het-water.ts
This PR hides the optional questions of the subcategory `overlast-op-het-water-snel-varen` when the type of boat is not selected
=> [SIG-3578] Hide questions when no radio option selected

src/app.js
This PR solves the problem of force reloading the application when a new version is released and the service worker is updated.
The added console.log statements are just temporary for process monitoring purpose and will be removed in a later version.
=> (Chore) Trigger reloading of the ServiceWorker on new release

src/components/Input/Input.tsx
- Removes native red border seen on Firefox for invalid fields
=> [SIG-3438] Removes native red border on invalid fields

docker-compose.yml, src/components/ThemeProvider/index.tsx
Restores changes to `docker-compose.yml` and adds type information for passed config object
=> (Chore) add type annotation for config

src/signals/incident-management/components/CheckboxList/CheckboxList.js
Restore removed guard that prevents double triggering the `onClick` handler
=> [SIG-3672] Prevent double trigger on Toggle

src/components/Modal/index.js
- Fixes modal styling bug
With the recent Amsterdam Styled Components update, the Modal component passes the className prop to a different element.
=> [SIG-3692] Fix modal styling affected by ASC change

src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.js, src/signals/incident-management/containers/IncidentDetail/components/MetaList/index.test.js, src/utils/__tests__/fixtures/incident.json
Adds process time to the `MetaList` component on the incident detail page
=> [SIG-3689] Add process time to MetaList

src/components/Modal/index.js
Reverts Amsterdam/signals-frontend#1522
=> Revert "[SIG-3692] Fix modal styling affected by ASC change"

e2e-tests/cypress/integration/_localRun/ktoNotSatisfied.spec.ts, e2e-tests/cypress/integration/_localRun/ktoSatisfied.spec.ts, e2e-tests/cypress/integration/handleSignals/deelmeldingen.spec.ts, e2e-tests/cypress/support/selectorsDjangoAdmin.ts, e2e-tests/cypress/support/texts.ts
Due to a change in the backend, there are no default mail templates available. This fix adds a mail template.
=> [SIG-3697] Cypress tests KTO fix mail

src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js
- Fix name, note and address inputs not clearing when clicking "Nieuw filter" button
Didn't go with the `createRef` solution discussed earlier - where the uncontrolled input value would be set to empty outside of react - because React complained about it (console error) and I feel like the current solution is more in line with 'normal' usage of React.
=> [SIG-3691] Clear name/address/note fields when clear button is clicked

src/components/Label/Label.tsx, src/signals/incident/components/form/CategorySelectRenderer/CategorySelectRenderer.js, src/signals/incident/components/form/CheckboxInput/CheckboxInput.js, src/signals/incident/components/form/ContainerSelectRenderer/ContainerSelectRenderer.js, src/signals/incident/components/form/DateTimeInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/DateTimeInput/index.js, src/signals/incident/components/form/DescriptionInputRenderer/DescriptionInputRenederer.js, src/signals/incident/components/form/FileInputRenderer/index.js, src/signals/incident/components/form/FormField/FormField.tsx, src/signals/incident/components/form/FormField/__tests__/index.test.tsx, src/signals/incident/components/form/FormField/index.ts, src/signals/incident/components/form/Header/Header.tsx, src/signals/incident/components/form/Header/__tests__/index.test.tsx, src/signals/incident/components/form/MapInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/MapInput/index.js, src/signals/incident/components/form/MapSelect/index.js, src/signals/incident/components/form/MapSelectGeneric/index.js, src/signals/incident/components/form/MultiTextInput/MultiTextInput.tsx, src/signals/incident/components/form/RadioInputGroup/RadioInputGroup.js, src/signals/incident/components/form/RadioInputGroup/__tests__/RadioInputGroup.test.js, src/signals/incident/components/form/SelectInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/SelectInput/index.js, src/signals/incident/components/form/TextInput/TextInput.tsx, src/signals/incident/components/form/TextareaInput/TextareaInput.tsx, src/signals/incident/containers/KtoContainer/components/KtoForm/index.js
- Removes role radiogroup as A11Y review found it an insufficient solution
- Updates header component to optionally render fieldset/legend instead of a label
- Use fieldset/legend for KTO form
=> [SIG-3682] Use Fieldset with Legend for radio group form input

src/signals/incident/components/form/FormField/FormField.tsx
- Prevents wrapping of legend text for radio button form input (Only in Safari)
=> [SIG-3711] Prevent wrapping of radio button legend text

src/signals/incident-management/containers/ReporterContainer/__tests__/useFetchReporter.test.ts
Fixes flaky unit test by resetting the handlers after each test run
=> (Chore) fix flaky unit test

e2e-tests/cypress/integration/handleSignals/sorting.spec.ts
* it is possible to have an empty address due to a new feature (automatic creation of deelmeldingen).
=> [SIG-3709] Cypress small fix

src/signals/settings/categories/Detail/__tests__/Detail.test.js, src/signals/settings/categories/Detail/index.js
Upon saving a category where a key has value `null`, the key was being overwritten with an empty string.
=> [SIG-3765] Prevent null category description from being updated to empty string

package-lock.json, package.json, src/signals/incident/components/form/MapInput/__snapshots__/index.test.js.snap, src/signals/incident/components/form/MapInput/index.js, src/signals/incident/components/form/MapInput/touchGestureMessage.ts
Adds a message to the incident selection map when mobile users try to pan the map using one finger.
The supplied options text has some required values that are unused (unless programmatically enabled).
=> [SIG-2564] Show message when touch device users scroll the incident location selection map

e2e-tests/cypress/integration/handleSignals/statusTransitionsOfSignal.spec.ts, src/signals/incident-management/definitions/statusList.ts
Now, display values from the backend correspond with those hard-coded in the front-end.
=> [SIG-3685] Update status names to correspond with backend values

publiccode.yaml
Added publiccode.yaml following the standard of:
https://docs.italia.it/italia/developers-italia/publiccodeyml-en/en/master/index.html
We have filled in as much information as we could.
But we suggest to check if they are correct.
Adding the publiccode.yaml file allows Dash Kube to correctly index this component at the commonground page found at:
https://dashkube.com/commonground
It also allows for one button installation of the signalen application via Dash Kube.
Changes suggested by @bartjkdp and @Ainali have been done.
=> Feature publiccode

internals/schemas/app.schema.json
- It is now possible to use template urls (e.g. https://data.nl?location={location})
=> [SIG-3744] Allow uri-templates in klokken/verlichting configuration

src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.js, src/signals/incident-management/components/FilterForm/index.js
- Removes guard for updating saved filter with empty name
Instead the list is filtered with the new values (but the saved filter is not updated).
=> [SIG-3693] Remove guard for updating saved filter with empty name

docker-compose.yml
Feedback functionality does not work "out of the box" on development due to missing environment configuration.
Closes Signalen/backend#141
=> Make sure feedback functionality works on development as well

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/__tests__/StatusForm.test.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/constants.ts, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/utils.ts
Design review concluded that this notification is better left out.
=> [SIG-3733] Remove external status change notification

src/signals/incident-management/containers/IncidentSplitContainer/IncidentSplitContainer.test.js, src/signals/incident-management/containers/ReporterContainer/__tests__/useFetchReporter.test.ts
Fixing a couple of minor issues in tests. In general, every unit test that covers a component that directly or indirectly makes use of the `useFetch` hook or otherwise performs an asynchronous request, should await render results. There are more tests in which these issues occur. Will be tackled gradually in future PRs.
=> (chore) Fix async test warnings

package-lock.json, src/app.js
This PR ensures that Sentry will log errors again. Since PR https://github.com/Amsterdam/signals-frontend/pull/1568, logging wasn't possible, because of the Sentry package upgrade. Its [changelog](https://github.com/getsentry/sentry-javascript/blob/master/CHANGELOG.md#600) explicitly mentions no breaking changes if (and only if) a configuration flag is set. If the flag is not set, by default, session data is sent along with the log POSTs. The receiving server responds with a CORS header fault because of that.
=> (Chore) Enable Sentry logging

e2e-tests/cypress/integration/createSignals/createSignalErrorMessages.spec.ts, e2e-tests/cypress/integration/handleSignals/signalsDashboard.spec.ts, e2e-tests/cypress/integration/handleSignals/signalsOverviewMap.spec.ts, e2e-tests/cypress/integration/manageSettings/manageDepartments.spec.ts, e2e-tests/cypress/support/commandsRequests.ts, e2e-tests/cypress/support/commandsRouting.ts, e2e-tests/cypress/support/texts.ts, e2e-tests/package-lock.json, e2e-tests/package.json, e2e-tests/webpack.config.js
Couple of fixes:
- ensure map tiles are stubbed for each integration test
- removal of unused vars
- correct assertion of texts on screen
Upgrades:
- Webpack
- Cypress
- ts-loader
Removes some unused dependencies and added a Webpack 5 nodejs polyfill dep to accomodate for the missing browser utils that Webpack doesn't automatically include after the latest major release.
=> [SIG-3990] Flaky tests fix

e2e-tests/cypress/support/commandsFiltering.ts
Changes fix tests that will break on slower network connections; filtering the incident overview page hasn't updated the table view when the e2e assertions are run. A delay of 500ms fixes that issue, albeit not for all cases. On really slow (or congested) networks, the tests might still fail.
=> (Chore) Fix flaky

e2e-tests/cypress/support/selectorsSettings.ts, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/__tests__/StatusForm.test.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/index.tsx
- Double underscores are now a special character in default texts, alongside '{{' and '}}'
=> [SIG-3989] Double underscores as special characters in default texts validation

src/index.html
Since version 15, [Safari supports the theme-color meta](https://css-tricks.com/meta-theme-color-and-trickery/) tag. Apparently not something we'd want. This PR fixes that.
=> [SIG-4019] Safari toolbar color fix

app.base.json, internals/schemas/app.schema.json, src/containers/App/index.test.tsx, src/containers/App/index.tsx
Adds `appMode` feature flag and prevents rendering of the site header when flag is set.
=> [SIG-3952] Hide header in app mode

src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.test.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/List/styles.ts
- Bugfix: instead of only the 'data' part of a row being clickable, it is now possible to click anywhere in the row to navigate to an incident
- Tabbing through incidents skips to the next row instead of cycling through all data cells in the row
=> [SIG-4011] Make incident overview table lines clickable

.github/workflows/end-to-end.yml
The GitHub actions will be run when the `release` PR is created
=> (Chore) Remove step to run GitHub actions for release branches

src/signals/incident-management/containers/IncidentOverviewPage/components/SubNav/SubNav.js, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/containers/IncidentOverviewPage/styled.tsx
- On incident overview page, tabs are now aligned with the pagination component
=> [SIG-4010] Fixes alignment of tabs on overview page

Dockerfile
`lodash/merge` is used for validating application config in the NGINX layer. Usage of this dependency was changed in #1798 - preventing the container from running correctly.
=> (Chore) Adds lodash install to nginx layer

internals/webpack/webpack.base.babel.js, src/app.js
Assets from the `src/images` folder weren't loaded in the client. This PR fixes that.
=> (Chore) Fix favicon loading

src/shared/services/auth/services/keycloak.test.ts, src/shared/services/auth/services/keycloak.ts
On login, the application should return to the same page as where the login flow was started. 
This also fixes an issue where when running the application on `localhost`, the user was not able to reach the incident form page.
=> (Chore) Prevent keycloak redirect to overview page on login

.github/workflows/end-to-end.yml
E2E job should
- [Fail](https://github.com/Amsterdam/signals-frontend/actions/runs/1304048385) step when build fails
- [Fail](https://github.com/Amsterdam/signals-frontend/actions/runs/1303502021) step when a job fails 
- [Succeed](https://github.com/Amsterdam/signals-frontend/actions/runs/1303504515) when build+tests succeed
Removed step to print dashboard URL because this URL is already printed in every E2E step
=> (Chore) Change GitHub actions config to break pipeline on broken build

src/components/pages/ArticlePage/Toegankelijkheidsverklaring.tsx
- Url Amsterdamse Bos
- Aanpassing tekst (januari -> maart)
- Url toegankelijkheidsverklaring
=> Fixes toegankelijkheidspagina - SIG 4103, 4104, 4107

src/containers/App/index.tsx
This PR fixes an issue where pages could not be scrolled where the height of the content exceeded the height of the viewport.
=> (Hotfix) contain:content blocker

src/components/HistoryList/HistoryList.tsx, src/components/HistoryList/__tests__/HistoryList.test.tsx, src/components/SiteHeader/index.js, src/signals/incident/components/form/HandlingMessage/HandlingMessage.tsx, src/signals/incident/components/form/HandlingMessage/__tests__/HandlingMessage.test.tsx, src/signals/incident/services/map-dynamic-fields/index.js, src/signals/incident/services/map-dynamic-fields/index.test.js
This PR contains changes that allow for Markdown as input format for any form that renders into a `History` component as well as the 'Thank you' page of the incident form.
Note that a change to the `mapDynamicFields` function was necessary to prevent the Markdown parser to trip over the string that was returned by that function whenever an entry could not be returned.
=> [SIG-4099] Markdown parse

src/containers/App/index.tsx
Fixes an issue where, when the height of a page's content would exceed the height of the viewport, it could not be scrolled.
=> [SIG-4113] Scroll block in status form

src/signals/incident-management/containers/IncidentOverviewPage/components/Sort/Sort.test.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/Sort/Sort.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/Sort/index.ts
This PR adds the `Sort` component. This will replace the incident overview table header in an upcoming PR.
=> [SIG-4115] Sort dropdown

src/signals/incident-management/containers/IncidentOverviewPage/components/Sort/Sort.tsx
This corrects different options in the sort dropdown so that the correct parameter is sent to the API.
Note that the `created_at` ordering option follows a different pattern than the rest of the options.
=> [SIG-4115] Sort dropdown options correct

src/signals/incident-management/containers/IncidentOverviewPage/index.js
This PR makes sure that the Sort dropdown isn't shown when viewing the map instead of the list on the incident overview page
=> [SIG-3918] Only show Sort when rendering list

default.conf
The changes in this PR will force `index.html` to never cache. This will prevent errors with outdated code when a visitor hasn't visited the site for a long time.
=> [SIG-4124] No caching for index.html

src/containers/App/reducer.test.ts, src/containers/App/saga.test.ts, src/containers/App/selectors.test.ts, src/containers/App/selectors.ts, src/containers/App/types.ts, src/signals/incident/components/form/CategorySelect/CategorySelect.test.js, src/signals/incident/definitions/__tests__/wizard-step-1-beschrijf.test.js, src/signals/incident/definitions/wizard-step-1-beschrijf.js
A source will only be shown as option in case its can_be_selected property is true.
Please note that this change depends on SIG-4044.
Before merging this PR, it should be tested when SIG-4044 is available on acceptance.
=> [SIG-4045] Filter source options

src/signals/incident-management/containers/IncidentDetail/components/MetaList/MetaList.tsx, src/signals/incident-management/containers/IncidentDetail/components/MetaList/__tests__/MetaList.test.tsx
closes Signalen/frontend#119
When both feature flags`assignSignalToEmployee` and `assignSignalToDepartment` are turned on. The employee should not be visible as long as a department has not been selected yet.
=> Show employee when department has been selected

src/components/OverviewMap/OverviewMap.test.tsx, src/components/OverviewMap/OverviewMap.tsx
This PR fixes an issue where, when the `geography` endpoint doesn't return a result set (no incidents registered in the past 24 hours), the map wouldn't be rendered because of an exception.
The likelihood of this situation occurring in production is next to nill, but could still occur.
=> [SIG-4134] Fix no features error

src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/List/styles.ts
This PR sets the widths of the `id` and the `day` column to fixed values so that, when the table is sorted, the columns don't 'jump'.
=> [SIG-4139] Fixes column widths

Dockerfile
Installing packages under Nginx in the signalsfrontend container didn't work anymore, because of unknown reasons. Switching to yarn, installing packages globally, worked.
=> (hotfix) Docker NPM install

Dockerfile
Switching to Yarn to install run-time dependencies worked, but installing them globally. This PR fixes that.
=> (Fix) Yarn no global install of dependencies

docs/adr/0006-forms.md, src/signals/incident/components/IncidentPreview/components/Map/index.js, src/signals/incident/components/IncidentPreview/components/Map/index.test.js, src/signals/incident/components/IncidentPreview/index.js, src/signals/incident/components/IncidentPreview/index.test.js, src/signals/incident/components/form/WithHeading/WithHeading.tsx, src/signals/incident/definitions/__tests__/wizard-step-4-summary.test.js, src/signals/incident/definitions/wizard-step-4-summary.js
This PR:
- Adds a `Contact` section to the incident form summary page
- Renders the `WithHeading` component in a `<div />` wrapper to make sure that the parent fieldset CSS rules don't mess up the alignment
- Makes sure that the `WithHeading` component pass on the correct values to its child component (the `parent` prop is required by `react-reactive-form`, but isn't automatically passed down when creating a wrapper component)
- Fixes an unrelated test (for the `Map` component) that polluted the test output
=> Sig 4147 adjust summary page

src/signals/incident/components/IncidentForm/index.js, src/signals/incident/components/IncidentForm/index.test.js
This PR fixes an issue where the incident form cannot be submitted when the list of controls doesn't have a field that can or should be validated. Apparently, `react-reactive-form` sets the status of the form to `DISABLED` when there are no controls in a form's configuration.
=> [SIG-4040] Fix form submit

src/signals/incident/components/form/PlainText/index.js, src/signals/incident/definitions/__tests__/wizard-step-2-vulaan.test.js, src/signals/incident/definitions/wizard-step-1-beschrijf.js, src/signals/incident/definitions/wizard-step-2-vulaan.js, src/signals/incident/definitions/wizard-step-3-contact.js
Adds `ignoreVisibility` prop to `meta` objects to ensure that field controls are ignore where required. Without this prop, the incident form will always jump from step 1 to step 2 instead of skipping step 2 when there are no extra questions for a specific category.
=> (Fix) Helptext visibilty

src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.tsx
This PR contains a fix for the `AssetSelector` position on the screen after the page has been scrolled down. This would render the portal an amount of pixels up instead of filling the screen top to bottom and left to right.
=> (Fix) Asset selector position

src/components/Notification/styled.tsx, src/global.css
This PR removes or overrides the use of the CSS rule `will-change`. Its use is highly discouraged.
Also see https://github.com/Leaflet/Leaflet/pull/7872
The additions to `global.css` can be reverted as soon as the change to the Leaflet repo has been released.
=> (Chore) Prevent resource depletion (in Firefox)

src/signals/incident/definitions/wizard-step-3-contact.js
Move help text below the navigation buttons
=> [SIG-4262] Contact page help text placement

src/signals/incident/components/form/MapSelectors/Clock/ClockLayer/ClockLayer.tsx, src/signals/incident/components/form/MapSelectors/Streetlight/StreetlightLayer/StreetlightLayer.tsx, src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.ts
This PR adds a property equalizer filter for both clocks and street lights WFS calls. This ensures that only the required data is provided and not the entire dataset for both clocks and street light.
=> [SIG-4273] Request appropriate dataset for openbare straatverlichting

src/components/AreaMap/AreaMap.tsx, src/components/OverviewMap/OverviewMap.tsx, src/shared/services/map-location/index.ts, src/shared/services/map-location/map-location.test.ts, src/shared/services/map-location/map-location.ts, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Location/index.js, src/signals/incident-management/containers/IncidentDetail/components/LocationForm/index.js, src/signals/incident-management/containers/IncidentDetail/components/MapDetail/index.js, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/AssetLayer/AssetLayer.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/ReportedLayer/ReportedLayer.tsx, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.tsx, src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js
This PR:
- contains a fix for setting the map center for a location that only has coordinates and no address
- renames functions in the `map-location` module so that they correctly reflect their purpose and return value
=> [SIG-4260] Fix map center

src/components/OverviewMap/OverviewMap.test.tsx, src/components/OverviewMap/OverviewMap.tsx, src/signals/incident-management/containers/IncidentOverviewPage/index.js
- Added refresh as prop to OverviewMap component. When refresh is true, polling is enabled.
- Added a test to show that no polling occurs when refresh is unset en polling does occur when refresh is set.
=> [SIG 4127] Only refresh overview map when refresh is set to true in active filter

src/signals/incident/components/IncidentPreview/components/AssetListPreview/AssetListPreview.test.tsx, src/signals/incident/components/IncidentPreview/components/AssetListPreview/AssetListPreview.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetList/AssetList.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetList/AssetList.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetSelect.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetSelect.tsx, src/signals/incident/components/form/MapSelectors/Asset/Intro/Intro.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/SelectionPanel/SelectionPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/AssetLayer/AssetLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/AssetLayer/AssetLayer.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/ReportedLayer/ReportedLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/ReportedLayer/ReportedLayer.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/WfsLayer.tsx, src/signals/incident/components/form/MapSelectors/Asset/__tests__/withAssetSelectContext.tsx, src/signals/incident/components/form/MapSelectors/Asset/types.ts, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.tsx, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarSelectRenderer/CaterpillarSelectRenderer.test.tsx, src/signals/incident/components/form/MapSelectors/Clock/ClockLayer/ClockLayer.tsx, src/signals/incident/components/form/MapSelectors/Clock/ClockSelectRenderer/ClockSelectRenderer.test.tsx, src/signals/incident/components/form/MapSelectors/Streetlight/StreetlightLayer/StreetlightLayer.tsx, src/signals/incident/components/form/MapSelectors/Streetlight/StreetlightSelectRenderer/StreetlightSelectRenderer.test.tsx, src/signals/incident/components/form/MapSelectors/types.ts, src/signals/incident/definitions/wizard-step-2-vulaan/openbaarGroenEnWater.ts, src/utils/__tests__/fixtures/caterpillarsSelection.tsx
- Moved reported icons to separate layer (making the caterpillar layer more similar to the others)
- Cleaned up double types. Moved general map selectors types into `mapselectors/types` and kept types specific for asset select in `asset/types`
=> [SIG 4198] Separate reported layer for caterpillar layer

src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts
This changes the URL references in the straatlichting and klokken configuration so that the correct global config props are referenced.
=> (Chore) Corrects layers endpoints

package-lock.json, package.json
This PR removes the `add-asset-html-webpack-plugin` NPM package which wasn't used, but did pose a high vulnerability threat.
=> (Chore) Removes unused dependency

src/signals/incident/definitions/__tests__/wizard-step-2-vulaan.test.js, src/signals/incident/definitions/wizard-step-2-vulaan.js, src/signals/incident/definitions/wizard-step-2-vulaan/locatie.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/locatie.ts
Contains a change that will always show the `AssetSelect` intro in step 2 when a category prediction doesn't have a corresponding set of questions. In addition, the `locatieFn` named export has been removed, since it wasn't used.
=> [SIG-4299] Always show location map

src/signals/incident/definitions/__tests__/wizard-step-2-vulaan.test.js, src/signals/incident/definitions/wizard-step-2-vulaan.js, src/signals/incident/definitions/wizard-step-2-vulaan/openbaarGroenEnWater.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-van-dieren.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-van-en-door-personen-of-groepen.ts
These changes will always render a step 2 with a location map, regardless of the value of the `showVulaanControls` configuration feature flag.
=> [SIG-4334] Ensures showing location map in step 2

src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/WfsLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/WfsLayer.tsx
Necessary to make the following wfs service work:
`https://data.haarlem.nl/geoserver/wfs?request=GetFeature&service=wfs&outputFormat=json&typeNames=gemeentehaarlem:bor_afvalinzamel&version=2.0.0&srsName={srsName}&bbox={west},{south},{east},{north},{srsNameSmall}`
=> Add small crs value for use with bbox query string

src/signals/incident/components/IncidentPreview/index.js, src/signals/incident/components/IncidentWizard/index.js, src/signals/incident/definitions/wizard-step-4-summary.js
Contains the following:
- Shows subheader on summary page
- Makes all headings and strong elements bolder (700 instead of 500)
- Changes section heading contents
- Changes edit link text for Locatie en vragen
- Adjusts padding for edit links on smaller screens
=> [SIG-4091] Visual changes summary page

src/components/GPSButton/GPSButton.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/styled.tsx
This PR contains a change that will position the map close button to the top right of its parent viewercontainer component, effectively positioning the auto suggest field between the GPS button and the map close button.
=> [SIG-4352] Close button position

src/signals/incident/definitions/wizard-step-3-contact.js
This change will disable autocomplete for the `phone` and `email` fields in Safari. This browser allows prefilling all known fields. This is currently not supported and will be fixed at a later date. Until then, we should not allow prefilling more than one field at a time.
=> [SIG-4265] Autocomplete contact fields

src/signals/incident/components/IncidentPreview/IncidentPreview.test.tsx, src/signals/incident/components/IncidentPreview/IncidentPreview.tsx, src/signals/incident/components/IncidentPreview/components/DateTime/__snapshots__/index.test.js.snap, src/signals/incident/components/IncidentPreview/components/DateTime/index.js, src/signals/incident/components/IncidentPreview/components/ListObjectValue/index.js, src/signals/incident/components/IncidentPreview/components/MapPreview/MapPreview.test.tsx, src/signals/incident/components/IncidentPreview/index.ts, src/types/incident.ts
This PR:
- converts the `IncidentPreview` component to TS
- adds a fallback message in said component when a section doesn't have entries to display
=> [SIG-4344] Empty section fallback

src/signals/incident/components/form/MapSelectors/Asset/Selector/SelectionPanel/SelectionPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/SelectionPanel/SelectionPanel.tsx
This PR removes the direct dependency between selecting a location on the map and checking the 'The object is not on the map' box in the selection panel.
=> [SIG-4274] Optional checked box

src/components/IconList/IconList.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetList/AssetList.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/StatusLayer/StatusLayer.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/StatusLayer/utils.test.ts, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.tsx, src/utils/__tests__/fixtures/caterpillars.json
It was the case that if a tree was reported and was checked, the reported icon should be visible.
Now the checked icon has precedence, so if a tree is both reported and checked, the checked icon is shown.
=> [SIG 3889] Show isChecked status in Caterpillar layer

src/signals/incident/components/form/MapSelectors/Asset/Selector/SelectionPanel/SelectionPanel.tsx, src/signals/incident/definitions/wizard-step-2-vulaan/__snapshots__/locatie.test.ts.snap, src/signals/incident/definitions/wizard-step-2-vulaan/afval-container.ts, src/signals/incident/definitions/wizard-step-2-vulaan/locatie.ts
Each object map should have the sentence “Typ het dichtstbijzijnde adres of klik de locatie aan op de kaart” below "kies een container op de kaart".
The same text below the checkbox should be removed.
=> [SIG 4347] Consistent texts and fix spelling error

src/signals/incident/components/form/MapSelectors/Asset/AssetSelect.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetSelect.tsx, src/signals/incident/components/form/MapSelectors/Asset/Intro/Intro.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/SelectionPanel/SelectionPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/WfsLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Summary/Summary.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Summary/Summary.tsx, src/signals/incident/components/form/MapSelectors/Asset/__tests__/withAssetSelectContext.tsx, src/signals/incident/components/form/MapSelectors/Asset/context.tsx, src/signals/incident/components/form/MapSelectors/Asset/types.ts
This PR contains a change that simplifies the logic that shows the location description in the `Summary` component. For it to work, the "De container staat niet op de kaart" checkbox needed to clear the selection in the state when unchecked. That way it became possible to distinguish between no selected object and a selected, unknown, object.
=> [SIG-4274] Object on map label

src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/AssetLayer/AssetLayer.tsx
Status was visible in object description for streetlight objects in the backoffice.
This is now removed by adjusting the item label in the asset layer.
=> [SIG 4364] Do not show status in item label

src/signals/incident/components/IncidentPreview/components/MapPreview/MapPreview.test.tsx, src/signals/incident/components/IncidentPreview/components/MapPreview/MapPreview.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetSelect.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetSelect.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetSelectRenderer/AssetSelectRenderer.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/SelectionPanel/SelectionPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/SelectionPanel/SelectionPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/AssetLayer/AssetLayer.tsx, src/signals/incident/components/form/MapSelectors/Asset/Summary/Summary.tsx, src/signals/incident/components/form/MapSelectors/Asset/__tests__/withAssetSelectContext.tsx, src/signals/incident/components/form/MapSelectors/Asset/context.tsx, src/signals/incident/components/form/MapSelectors/Asset/types.ts, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.tsx, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarSelectRenderer/CaterpillarSelectRenderer.tsx, src/signals/incident/components/form/MapSelectors/Clock/ClockSelectRenderer/ClockSelectRenderer.tsx, src/signals/incident/components/form/MapSelectors/Streetlight/StreetlightSelectRenderer/StreetlightSelectRenderer.tsx, src/signals/incident/components/form/MapSelectors/constants.ts, src/signals/incident/components/form/MapSelectors/types.ts, src/signals/incident/containers/IncidentContainer/selectors.js, src/signals/incident/containers/IncidentContainer/selectors.test.js, src/signals/incident/definitions/wizard-step-2-vulaan/afval-container.ts, src/signals/incident/definitions/wizard-step-2-vulaan/openbaarGroenEnWater.ts, src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts, src/signals/incident/services/convert-value/index.js, src/signals/incident/services/convert-value/index.test.js, src/signals/incident/services/custom-validators/custom-validators.ts, src/signals/incident/services/custom-validators/index.test.ts, src/types/incident.ts
This PR fixes an issue where selecting a location on the map and ticking the 'not on the map' checkbox conflicted. To make it work, a new object type was added and the existing type was renamed. The asset select component now distinguishes `OBJECT_UNKNOWN` (was `UNREGISTERED_TYPE`) and `OBJECT_NOT_ON_MAP`.
Another issue was the validation of the form field; the way the validation works is that only the active form field can be validated. The field validation also needs the selected location (coordinates and address) to validate the field, because having coordinates is the only requirement. Because of this, the global state was altered so that the selected object, or item, on the map now also contains the selected coordinates.
**State before**
```
incidentContainer: {
incident: {
... …
```
=> [SIG-4274] Object not on map

src/components/GPSButton/GPSButton.test.tsx, src/components/GPSButton/GPSButton.tsx, src/components/GPSButton/__tests__/GPSButton.test.tsx
The change in this PR removes the watch functionality from the `GPSButton` component; hasn't been used since the introduction of the component and likely never will be. Also, `clearWatch` wasn't implemented.
=> (chore) Remove location watch

src/hooks/useDelayedDoubleClick.js, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.tsx
- Used existing delay function for detecting double clicks in Asset select map
- Enabled zooming in and out through scroll wheel in Asset select map
- Increased the delay from 200 to 300 ms.
=> [SIG 4367] Fix double clicks in Asset select map

src/components/OverviewMap/OverviewMap.tsx
Fixes an issue where an optional prop was referenced directly as a function instead of checking if the prop is a function.
=> (Fix) Function reference

src/signals/incident/containers/IncidentContainer/reducer.js, src/signals/incident/containers/IncidentContainer/reducer.test.js
Fixes an issue where different timestamps are shown in the incident detail page
=> [SIG-4422] Fix for incorrect incident start time

src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/styled.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/styled.tsx
This PR moves the `PDOKAutoSuggest` component from the map (asset `Selector`) to the detail panel. Note that this change isn't the full set of changes that are required to completely move the functionality. Just an intermediate step.
=> [SIG-4426] Move autosuggest

src/components/AutoSuggest/AutoSuggest.test.tsx, src/components/AutoSuggest/AutoSuggest.tsx, src/components/AutoSuggest/styled.tsx, src/components/Button/Button.tsx, src/components/Button/index.ts, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx
This PR:
- Adds a button to the `AutoSuggest` component that allows clearing the field
- Handles clearing the auto suggest field in the `DetailPanel` component. This will effectively clear the location in the global state and, subsequently, remove the marker from the map.
=> [SIG-4427] Clear autosuggest

package-lock.json, package.json, src/components/AutoSuggest/AutoSuggest.test.tsx, src/components/AutoSuggest/AutoSuggest.tsx, src/components/AutoSuggest/components/SuggestList/SuggestList.tsx, src/components/Map/Map.tsx, src/components/PDOKAutoSuggest/PDOKAutoSuggest.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetList/AssetList.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/styled.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/styled.tsx
This PR:
- Renders a full-screen address panel with auto suggest field on smaller screens
- Adds the [react-responsive](https://www.npmjs.com/package/react-responsive) dependency. This is meant to replace the [react-media](https://www.npmjs.com/package/react-media)`dep, which is not maintained anymore.
- Adjusts the `AutoSuggest` component so that it can render a list of suggestions (default) or return the list via callback so that implementing components can render the list in their own way.
=> [SIG-4428] Full-screen auto suggest

src/shared/services/map-location/map-location.test.ts, src/shared/services/map-location/map-location.ts
The lat lng conversion function unnecessarily used `sort` while `reverse` alone is enough to reverse lat and lng.
The `sort` caused a problem when the lng would be alphabetically 'bigger' than the lat.
=> Remove unnecessary `sort`

src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.tsx
This PR fixes an issue where, when the fullscreen map is opened on a mobile device and the address auto suggest is focused, the auto suggest field might be scrolled out of the viewport.
=> (Fix) Map scrolltop

src/components/FormFooter/FormFooter.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/__tests__/StatusForm.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/DefaultTexts/DefaultTexts.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/DefaultTexts/DefaultTexts.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/DefaultTexts/styled.ts, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/EmailPreview/EmailPreview.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/EmailPreview/EmailPreview.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/ModalHeader/ModalHeader.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/ModalHeader/ModalHeader.tsx
In the status form, an email preview is shown in case an email is send to the reporter, before the email is send.
Please note that I've temporarily included a htmlString const to mock the email body, which will be removed when the endpoint to get the email body is working.
=> [SIG 4326] Show email preview

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/__tests__/StatusForm.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/__tests__/reducer.test.js, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/actions.ts, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/EmailPreview/EmailPreview.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/reducer.ts, src/signals/incident-management/containers/IncidentDetail/types.ts
- Gets the email template when the email preview modal needs to be shown (i.e., when the reporter has an email address and sending an email is checked, or occurs automatically for certain status updates)
- Adds tests for the case when an email template is indeed returned, and the case that an email template is not available (404).
=> [SIG 4325] endpoint for email template

src/components/AutoSuggest/AutoSuggest.test.tsx, src/components/AutoSuggest/AutoSuggest.tsx, src/components/AutoSuggest/styled.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx
This PR:
- always shows the auto suggest input clear button when user types in the input field
- makes sure that the list of auto suggest options is removed whenever the clear button is clicked
=> (Chore) Show autosuggest clear button

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/EmailPreview/EmailPreview.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/styled.tsx
On small screens, there was a double scrollbar and the email content was showing below the submit buttons.
These issues are solved now.
=> [SIG 4324] Fix scrollbar issues email preview

app.base.json, internals/schemas/app.schema.json
closes Signalen/frontend#166
The map went gray when zooming in past level 14.
Setting the `maxNativeZoom` to `14` on the PDOK tiles layer fixes this.
Better solution than https://github.com/Amsterdam/signals-frontend/pull/2052 for Signalen/frontend#166.
https://github.com/Amsterdam/signals-frontend/pull/2052 is still a bug fix though.
=> Set maxNativeZoom for PDOK tiles

src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/index.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/index.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/types.ts
Incident detail page cannot be displayed because answer contains an array with a null value.
The current fix handles this error.
https://sentry.data.amsterdam.nl/sentry/signals-frontend/issues/2721718/?query=is%3Aunresolved
=> [SIG 4453] Handle incident detail when extra properties answer is null

package.json
The proposed change in this PR allows testing local URLs on iOS with Browserstack. iOS doesn't allow the use of `localhost`, but this can be circumvented by using the bs-local.com domain. See https://www.browserstack.com/docs/live/local-testing/test-using-local-testing for reference on local testing.
Note that, for this change to work, the hosts file on the development machine needs to be changed so that it accepts requests for bs-local.com and routes these to `127.0.0.1`.
=> (Chore) Allow Browserstack tunnel

src/components/PDOKAutoSuggest/PDOKAutoSuggest.tsx
Previous link wasn't pointing to a valid documentation location any more
=> (Chore) Replace PDOK API link

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/EmailPreview/EmailPreview.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/constants.ts, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/styled.tsx
- An email was send anyway as of the result of updating the status form, even if there was an error in the email preview endpoint. When no email template is available the email is no longer send. The text can still be saved when the recipient is removed, by unchecking the checkbox.
- The height of the email preview is increased to 75%. This was requested by Herjen.
- Styling has been added to increase the line height and to fix issues with sticking out urls.
- Max number of characters was decreased to 1800 temporarily until the endpoint is fixed.
=> [SIG 4324] Not send email when email template is not available

src/signals/incident/components/IncidentForm/index.js, src/signals/incident/components/IncidentForm/index.test.js, src/signals/incident/components/IncidentWizard/IncidentWizard.tsx, src/signals/incident/containers/IncidentContainer/actions.js, src/signals/incident/containers/IncidentContainer/constants.ts, src/signals/incident/containers/IncidentContainer/reducer.js, src/signals/incident/containers/IncidentContainer/reducer.test.js, src/signals/incident/containers/IncidentContainer/saga.js, src/signals/incident/containers/IncidentContainer/saga.test.js, src/signals/incident/definitions/wizard-step-1-beschrijf.js, src/signals/incident/definitions/wizard.ts
closes Signalen/product-steering#93
Make sure to postpone submitting in step 1 in case the extra questions are coming from the backend and are still loading.
=> Postpone submit on loading questions from backend

src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/styled.tsx
This PR fixes a scroll issue on iOS where, when an input element inside a fixed position element gets focus, the OS keyboard will push the fixed positioned element off-screen. To solve this, there are two options:
1. Turn all fixed elements into absolute positioned elements
2. Do not let the input field get focus
The first option is quite troublesome, because it requires a refactoring of most of the styled component that make up the detail panel and the address panel. The second option is the easiest, but it requires the user to tap the input field twice; once to toggle the full-screen panel and the second time to focus the input field.
For now, the second option is chosen. It this is considered to be too obtrusive, the first option will be implemented.
=> (Fix) iOS AddressPanel scroll

src/components/Map/Map.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.tsx
closes Signalen/frontend#166
Have the Asset Select map use the min and max zoom levels as defined in the config.
=> Use zoom levels from config for asset select

app.amsterdam.json, internals/schemas/app.schema.json, src/components/PDOKAutoSuggest/PDOKAutoSuggest.test.tsx, src/components/PDOKAutoSuggest/PDOKAutoSuggest.tsx
closes Signalen/frontend#167
For Groningen we ran into a problem.
`configuration.map.municipality` was set to `groningen`. Turns out there is also a municipality called "Midden-Groningen", having the same keyword `groningen` in there. Therefore the autosuggest of the address lookup gave results of both municipalities, while only results from the municipality of Groningen are desired.
Since an exact match on municipality is not possible with PDOK, the workaround could be to exclude the term "midden" in this case. This is done with a dash, as in `-midden`.
Double quotes are put around each term to accommodate spaces in a term, like `den bosch`. Putting double quotes around the term `-midden` would prevent it from being a negative search term. It should be `-midden`, or `-"midden"`. Not …
=> Allow a negative term for municipality

src/signals/settings/categories/Detail/Detail.test.js, src/signals/settings/categories/Detail/components/CategoryForm/CategoryForm.test.tsx, src/signals/settings/categories/Detail/components/CategoryForm/CategoryForm.tsx, src/signals/settings/categories/Detail/index.js, src/types/category.ts, src/utils/__tests__/fixtures/categories_private.json
- Checkbox and textfield for is_public_available and public_name respectively in CategoryForm
- Possible values for both variables are retrieved from the data and stored in the CategoryForm state
- New values for both values can be submitted and retrieved
- Tests for both fields
=> [SIG 4412] Enable to make category publicly available

src/signals/incident-management/__tests__/selectors.test.js, src/signals/incident-management/selectors.js
closes Signalen/frontend#118
In case the option 'Niet toegewezen' is selected to filter incidents on district, `area_code` will be `'null'`. `area_type_code` still defaulted to 'district' though. For this filter to work `area_type_code` must also be `'null'`, or not be present at all. In this change I make sure that it is not present when `area_code` is `'null'`.
=> Remove area_type_code when area is null

src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/WfsLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/WfsLayer.tsx, src/sw-proxy-config.js
This PR handles the case where the caterpillar api is not functioning.
In the sw-proxy-config I've added the case that occurred recently with the caterpillar api.
The reason why the error was not handled adequately (i.e., remained uncaught) was that the error was send in the request body.
The current PR now deals with this unconventional case in the WSF layer.
A test was added to show the adjustment.
=> [SIG 4454] Handle caterpillar api errors

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/constants.ts
- convert Get to Post request for email preview to handle large amounts of text.
- Restore number of characters for email text (DEFAULT_TEXT_MAX_LENGTH ) to 3000.
NB: this PR can only be merged in tandem with the backend PR
https://github.com/Amsterdam/signals/pull/947
=> [SIG-4458] Get into Post request for email preview to enable more text

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/DefaultTexts/DefaultTexts.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/DefaultTexts/styled.ts
closes Signalen/product-steering#110
Fix scrolling through the default texts modal of the edit status for on the incident detail page by adding the `data-scroll-lock-scrollable` attribute to the right element. Also changed scrolling area to the content only, without the header.
=> Fix scrolling default texts modal on mobile

src/signals/incident-management/containers/IncidentDetail/components/MetaList/MetaList.tsx
closes Signalen/product-steering#33
Hides inactive users from the list of users to assign an incident to on the incident detail page.
=> Hide inactive users

src/signals/incident-management/containers/IncidentDetail/components/MetaList/MetaList.tsx, src/signals/incident-management/containers/IncidentDetail/components/MetaList/__tests__/MetaList.test.tsx
closes Signalen/product-steering#98
When the category of an incident is linked to only one department (there is no routing department) show that department with the edit button disabled.
=> Show read only department when only one

src/signals/incident/components/IncidentPreview/IncidentPreview.tsx
In summary of call, when there are no known contactdetails, text has changed to "U hebt geen contactgevens ingevuld. We kunnen u niet laten weten wat wij hebben gedaan met uw melding." 
Change in component LinkContainer in IncidentPreview.tsx
=> [SIG-4372] Text shown when no contact details are known changed 

src/shared/services/map-location/map-location.test.ts, src/shared/services/map-location/map-location.ts
closes Signalen/frontend#170
This issue has been fixed before in https://github.com/Amsterdam/signals-frontend/pull/2041
The incorrect logic was present in a few other places in the same file. Which still results in location lookup not working for Groningen, and showing assets on the map for Groningen.
This PR fixes those cases as well.
=> Update lat/lng logic

src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx
To component StyledPDOKAutosuggest is placeholder with value ' Zoek adres of postcode' added. Both in mobile as desktop version of app is placeholder visible.
=> [SIG-4480] placeholder text address field

src/signals/incident/definitions/wizard-step-5-bedankt.js
Thank you message in Wizard-step-5-bedankt changed to 
value: `Uw melding is bij ons bekend onder nummer: {incident.id}.
\n Hebt u een e-mailadres ingevuld? Dan ontvangt u een e-mail met alle gegevens van uw melding.`,
valueAuthenticated: `Uw melding is bij ons bekend onder nummer: [{incident.id}](/manage/incident/{incident.id}).
\n Hebt u een e-mailadres ingevuld? Dan ontvangt u een e-mail met alle gegevens van uw melding.`,
=> [SIG-4492] Thank you message changed

src/components/MapInput/__tests__/MapInput.test.js, src/components/MapInput/index.js
When the location of an incident is changed from a location with an address to a location without address, the old address was not removed. This PR fixes that by clearing the address.
=> [SIG-4507] Clear address when changed location has no address

src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx
Removed text 'Zoek adres of Postcode'  below search field in mobile state. Now if there is a value for optionList, then the value will be displayed.
=> [SIG4480] text_under_placeholder_removed

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/styled.tsx
Styling needed to change of the checkbox and the label surrounding the checkbox. The checkbox needed to be opaque and the label needed to be color #767676. I
n StatusForm I changed a label to newly created StyledCheckboxLabel and changed Checkbox to newly created StyledCheckbox. In styled.tsx opacity: 0.3 added to styling of StyledCheckbox, and color: #767676 to StyledCheckboxLabel.
=> [SIG-4482]_styling_checkbox_and_checkboxlabel_changed_in_StatusForm

app.amsterdam.json, internals/schemas/app.schema.json, src/components/PDOKAutoSuggest/PDOKAutoSuggest.tsx
The `configuration.map.municipality` was turned into a string in a [previous PR](https://github.com/Amsterdam/signals-frontend/pull/2059). This PR updates the type in the schema and updates the Amsterdam configuration.
=> Update municipality type to string only

src/signals/incident-management/containers/IncidentDetail/components/MetaList/MetaList.tsx, src/signals/incident-management/containers/IncidentDetail/components/MetaList/__tests__/MetaList.test.tsx
When a category had only one department. That department was shown on the incident detail page, without it explicitly being routed to that department.
This PR fixes that by showing the incident as not being linked to any department. A department can then be chosen from the dropdown (containing only that one department) after which the incident will be routed to that department explicitly and thus well be shown as such afterward.
=> Allow selection of single department

src/signals/incident-management/containers/DefaultTextsAdmin/saga.js, src/signals/incident-management/containers/DefaultTextsAdmin/saga.test.js
Alert message for change in Standaard tekst is modified  in three ways:
1. The number of texts being modified is no longer shown
2. 'teksten' is now always plural instead of single of only one text was modified and otherwise being plural
3. 'opgeslagen' is changed to ' bijgewerkt'
=> [SIG-4532] text modified in alert for change in Standaard teksten

src/components/GPSButton/GPSButton.tsx
The themeColor of Amsterdam Styled components has been added to styling of GPS-button.
=> [SIG 4475] Color of GPS-button text is now black on all devices including Iphones.

src/signals/incident-management/containers/DefaultTextsAdmin/components/DefaultTextsForm.test.tsx, src/signals/incident-management/containers/DefaultTextsAdmin/components/DefaultTextsForm.tsx
When title and/or text in a standard text is absent, the checkbox should be disabled. The attribute 'disabled'  is therefore added to the styledlabel. 
Tests are added that will test for no title and no text, for a title and no text, for no title and a text and, lastly, for a title and a text. The results should be resp. disabled, disabled, disabled and not-disabled.
=> Sig 4533 checkbox active only when text + title in standard text

src/components/AreaMap/AreaMap.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/NearbyLayer/NearbyLayer.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/StatusLayer/StatusLayer.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/AssetLayer/AssetLayer.tsx, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.tsx
https://datapunt.atlassian.net/browse/SIG-4495?atlOrigin=eyJpIjoiMjQ1ZDRiNzQ0NjhlNDc3YTkxNDhhYzRlNGNlNzFjOTUiLCJwIjoiaiJ9
**I added some props to unset de default tab indexes, a setting of leaflet.**
=> [SIG 4485] Set keyboard prop to false, to remove tabindices from marker.

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx
In the status form (backoffice), when there is no email address provided by the reporter of the incident, the label of the text area should be 'Toelichting' instead of 'Bericht aan melder'.
for example at:
.../manage/incident/10959
=> [SIG 4570] Show 'Toelichting' label when no email is available

src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts
When an user answers with Overige in a report concerning clocks a textareaInput is provided so that the user can elaborate if she wants. The answer is shown in the backoffice as Toelichting.
Test has been updated.
=> [SIG 4594] textareaInput provided when answer Overige in reports concerning clocks

src/signals/incident/components/form/PlainText/index.js, src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.ts
Extra_fietsrek_aanvraag has been changed so that users wanting to request a new fietsnietje will be directed to the website where this is possible. Website (https://formulier.amsterdam.nl/thema/wonen/aanvraagformulier-fietsenrek-fietsvak) is an external website, not under control of Signals-frontend.
=> [SIG 4599] Redirect Users wanting to request a new fietsnietje to the external website where this is possible

src/components/IconList/IconList.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetList/AssetList.tsx
When multiple objects are shown in the sidebar next to the map, the distances between these objects are enlarged in order to see more easily there are multiple objects. This includes information is that is giving within the object.
Margins are now 12px, 4px and 3 times 12px. Padding has been added to ensure a visual distance to the divider of 2 times 12px.
=> [SIG 4576] Styling of object information and notifications has been changed

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx
closes Signalen/product-steering#158
Scrolling did not get activated again after submitting the email preview form when changing the status of an incident (and sending a mail to the reporter).
=> Enable scrolling after submit

src/signals/incident-management/containers/IncidentOverviewPage/components/Sort/Sort.tsx
closes Signalen/backend#166
Sorting on district (as opposed to 'stadsdeel') was not implemented yet (in incident overview).
=> Allow sorting on district

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/shared/services/resolveClassification/index.js, src/shared/services/resolveClassification/index.test.js
Currently we have some hardcoded "overig" categories in the frontend for Amsterdam. This results in incorrect fallback behavior of the overig category within a main category for the other municipalities. It will always fall back to `overig` when the `MINIMUM_CERTAINTY` of a subcategory is not met, instead of the overig category of the main category (`overig-{main-slug}`).
This PR fixes this behavior and also still supports the Amsterdam-specific naming convention of overige categories, by adding feature flag called `enableAmsterdamSpecificOverigCategories`. When the feature flag is disabled, the consistent naming of overige categories that is used by the other municipalities is used.
=> Make hardcoded "overig" categories Amsterdam-specific

app.amsterdam.json
Ticket: [SIG-4697](https://datapunt.atlassian.net/browse/SIG-4697)
The alt-text of the logo need to be 'gemeente' specific and should tell where it will redirect since it is also a link. 
- changed the alt text in the app.amsterdam.json.
- How do we make sure the other municipalities do the same?
- The SiteHeader renders a different header depending on the `isIncidentMap`. However, it also uses the Logo component differently. Resulting, for example, in double hrefs. Why is this?
=> [SIG-4697] changed alt text of logo in amsterdam.json file

src/components/AutoSuggest/AutoSuggest.tsx, src/components/MapCloseButton/MapCloseButton.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx
Ticket: [SIG-4704](https://datapunt.atlassian.net/browse/SIG-4704)
With two buttons the screenreader could not identify the roles of the buttons.
- added two aria-labels
=> [SIG-4704] added aria labels to buttons without explicit meaningful text

src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx
When a user tried to search for an address on 200% zoom on a desktop, the mobile overlay (fuill screen search) was triggered because it is depending on the amount of pixels, but this is unaccessible with mobile. 
- Changed the breakpoint to MobileL so the mobile overlay will only be triggered with mobiles and not tablets.
- Set autofocus to search input when overlay appears
=> [SIG-4700] change breakpoint searchbar overlay

src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/LegendPanel/LegendPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/LegendToggleButton/LegendToggleButton.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/LegendToggleButton/LegendToggleButton.tsx
Ticket: [SIG-4703](https://datapunt.atlassian.net/browse/SIG-4703)
The "Uitleg" and mobile address search input overlay did not have an aria-expanded label.
- Added the label to the "Uitleg" button that closes/opens the uitleg overlay
- Since there is not 1 button that controls the open/close of the search input I have put the aria-expanded label to the back button of the screen.
=> SIG-4703: add aria expended labels

app.base.json, internals/schemas/app.schema.json, src/shared/services/configuration/map-options.test.ts, src/shared/services/configuration/map-options.ts
This adds support for EPSG:4326 & EPSG:3857 map projections. The map configuration defaults to EPSG:28992 to make the change non-breaking.
Currently municipalities can only configure EPSG:28992 base maps. Some municipalities are not happy with the default base maps provided by PDOK:  e.g. house numbers are lacking and coloring of the base map could be more intuïtive.
Therefore they would like to provide their own base map. By using [tileserver-gl](https://github.com/maptiler/tileserver-gl) they can easily provide their own base map, but this requires support for EPSG:4326 projection.
This change can be tested with the following app.json:
```json
{
"map": {
"options": {
"crs": "EPSG:3857"
},
"tiles": {
"args": [
"https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0/standaard/EPSG:3857/{z} …
```
=> Add support for EPSG:4326 & EPSG:3857 projection

src/containers/App/index.tsx, src/signals/IncidentMap/IncidentMapContainer.test.tsx, src/signals/IncidentMap/components/IncidentLayer.test.tsx, src/signals/IncidentMap/components/IncidentLayer.tsx, src/signals/IncidentMap/components/IncidentMap.test.tsx, src/signals/IncidentMap/components/IncidentMap.tsx, src/signals/IncidentMap/components/mapTestUtils.ts, src/signals/incident/components/form/MapSelectors/Asset/Selector/NearbyLayer/NearbyLayer.test.tsx
`/meldingenkaart` now shows the Amsterdam map and markers for all (publicly accessible) incidents
=> [SIG 4621] Show map and markers

src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/LegendPanel/LegendPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/LegendPanel/LegendPanel.tsx
When the legend panel was open it was not possible to close it with a keyboard since you cannot focus on the close button.
- set tabindex to 0
- added a ref to the button so it is focussed when the legend opens
=> [SIG-4701] make legend panel focusable

src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/LegendPanel/LegendPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/LegendPanel/LegendPanel.tsx
Revert PR because Oscar needs to double check the tab-index.
Reverts Amsterdam/signals-frontend#2242
=> Revert "[SIG-4701] make legend panel focusable"

src/components/SiteHeader/incidentMapStyles.ts, src/components/SiteHeader/index.js, src/containers/App/index.tsx
At `/meldingenkaart`
Implemented Linda's comments:
General
Lijn onder de navigatie is een drop-shadow
Desktop
Height navigatiebar: 80px
Margin logo top-bottom: 20px
Margin logo left: 24px
Mobiel
Height navigatiebar: 56px
Margin logo top-bottom: 12px
Margin logo left: 20px
Hamburger menu
Another request was to remove the footer. This has already been implemented in SIG-4621.
=> [SIG 4661] Improvements incident map header

src/components/SiteHeader/incidentMapStyles.ts, src/components/SiteHeader/index.js, src/signals/IncidentMap/components/IncidentMap.tsx
As discussed with Linda, several adjustments were made:
- The hamburger menu always has a grey background (not just on hover).
- The hamburger height equals the height of the navigation bar and is a square.
- The hamburger is positioned with 0px padding to the right.
- The menu item list appears below the navigation bar.
- The attribution text of the map is hidden.
- The space between the navigation bar and the map has been removed.
=> [SIG 4661] Fix hamburger menu, hide attribution text, remove space above map

src/signals/incident/containers/KtoContainer/index.js
**Context:**
Linda's comment after testing: @Siree Wijkstra Getest: alleen het woord gaan mist nog, in “wat wij ermee gaan doen”. Verder klopt het
**Changes:**
'gaan' has been added.
=> [SIG-4721] word added after comment from Linda

src/components/FooterContainer/FooterContainer.test.tsx, src/components/FooterContainer/FooterContainer.tsx, src/components/FooterContainer/__tests__/FooterContainer.test.tsx, src/components/FooterContainer/index.ts, src/components/FooterContainer/index.tsx, src/containers/App/index.test.tsx, src/containers/App/index.tsx
Ticket: [SIG-4719](https://datapunt.atlassian.net/browse/SIG-4719)
The Amstedam.app team want the footer to be hidden when SIA is rendered in their app.
- Moved all conditional render logic to the footerContainer. 
- Added a StyledFooterApp (it needed some white space on the bottom)
- Added tests
=> [SIG-4719] hide footer when in amstedam.app

src/components/MarkerCluster/style.css, src/signals/IncidentMap/components/IncidentLayer.tsx
Styling adjustments of cluster icons in meldingenkaart according Linda's specs:
Witte bol
Height: 52px
Width: 52px
Blauwe bol
Height: 48px
Width: 48px
Cijfer in de bol
Font-family: Avenir Next LT Pro (kan zijn dat dat in de code alleen Avenir Next is)
Font-size: 16px
Font-weight: 500 
Line-height: 48px
=> [SIG 4662] Styling cluster icons in meldingenkaart

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/containers/App/index.tsx
The public incidents map is developed in fases. We do no want to show the url before it is functional.
- Add feature flag `enablePublicIncidentsMap`
- remove duplicate "appMode" in app.schema.json
=> Add feature flag to hide meldingenkaart url

app.amsterdam.json
The feature flag appMode was accidently set to true in [this PR](https://github.com/Amsterdam/signals-frontend/commit/e04fb41fd6f493857ddd1722e6b9ca24f82a3694).
=> set feature flag appMode=false

app.amsterdam.json
This PR sets the featureFlag `enablePublicIncidentsMap` to `true`. Enabling the /meldingenkaart on acceptance.
=> [CONFIG] enable meldingenkaart

src/signals/incident/definitions/wizard-step-1-beschrijf.js, src/signals/incident/definitions/wizard-step-3-contact.js, src/signals/incident/services/yup-resolver/index.test.ts
Remove confocusing maxlength validators
one form of validators is chosen instead of multiple for matching the maxLength of a form field.
=> Change maxLength validators to more descriptive ones.

.github/workflows/publish_docker_image.yaml
This is a proposal to start publishing Docker images to GitHub container registry. This allows us to switch from Docker Hub to GitHub container registry. This has the following benefits:
- Better CI + GitHub integration
- Forks are able to reuse this action for creating their own Docker images
- No rate limits
We already implemented a similar workflow in the backend repository, see: https://github.com/Amsterdam/signals/pull/1049
=> Start publishing Docker images to GitHub container registry

src/signals/incident/components/IncidentForm/index.test.js, src/signals/incident/components/IncidentForm/index.tsx, src/signals/incident/components/IncidentWizard/IncidentWizard.tsx, src/signals/incident/definitions/wizard-step-3-contact.js, src/test/utils.js
Ticket: [SIG-4808](https://datapunt.atlassian.net/browse/SIG-4808)
Clear the error message by calling trigger after clearing an input field
- make sure the error message goes away after clearing a field
- test also by going to different route
=> [SIG-4808] Invalidate error messages after clearing input.

src/signals/IncidentMap/components/AddressLocation/AddressLocation.tsx, src/signals/IncidentMap/components/AddressLocation/styled.ts, src/signals/IncidentMap/components/DrawerOverlay/DrawerOverlay.test.tsx, src/signals/IncidentMap/components/DrawerOverlay/DrawerOverlay.tsx, src/signals/IncidentMap/components/DrawerOverlay/styled.ts, src/signals/IncidentMap/components/DrawerOverlay/types.ts, src/signals/IncidentMap/components/FilterPanel/FilterPanel.tsx, src/signals/IncidentMap/components/FilterPanel/styled.ts, src/signals/IncidentMap/components/IncidentMap/IncidentMap.tsx, src/signals/IncidentMap/components/IncidentMap/styled.ts
Ticket: none
There was some obsolete code left after the implementation of the `AddressLocation`. This PR deletes that. 
Also, the component sticked to the top since it was not wrapped in the `DrawerContentWrapper` and therefore was not scrollable on mobile. Passing the `AddressLocation` as children of DrawerOverlay now.
=> chore: cleanup components and small refactor

src/signals/incident/containers/KtoContainer/index.js
Debugged this together with @tcoenen.
Fixes Signalen/frontend#175 and fixes https://github.com/Signalen/product-steering/issues/283
=> Only show contactAllowedText when feature flag reporterMailHandledNegativeContactEnabled is on

package-lock.json, src/components/MarkerCluster/MarkerCluster.test.tsx, src/components/MarkerCluster/MarkerCluster.tsx, src/signals/IncidentMap/components/AddressLocation/AddressLocation.tsx, src/signals/IncidentMap/components/AddressLocation/AddressSearchMobile.test.tsx, src/signals/IncidentMap/components/AddressLocation/AddressSearchMobile.tsx, src/signals/IncidentMap/components/AddressLocation/AdressLocation.test.tsx, src/signals/IncidentMap/components/AddressLocation/index.ts, src/signals/IncidentMap/components/AddressLocation/styled.ts, src/signals/IncidentMap/components/DrawerOverlay/styled.ts, src/signals/IncidentMap/components/Header/styled.tsx, src/signals/IncidentMap/components/IncidentLayer/IncidentLayer.tsx, src/signals/IncidentMap/components/IncidentMap/IncidentMap.tsx, src/signals/IncidentMap/components/IncidentMap/Pin.test.tsx, src/signals/IncidentMap/components/IncidentMap/Pin.tsx, src/signals/IncidentMap/components/IncidentMap/utils.test.ts, src/signals/IncidentMap/components/IncidentMap/utils.ts, src/signals/IncidentMap/components/utils/constants.ts, src/signals/IncidentMap/components/utils/index.ts, src/signals/IncidentMap/containers/styled.ts
Ticket: [SIG-4784](https://datapunt.atlassian.net/browse/SIG-4784)
This PR upgrades the user experience mainly while on mobile.
- When the user selects a marker that is underneath the drawerOverlay we want to move the map slightly up so it is in view. 
- We want to close the drawerOverlay when GPS location is used on mobile.
- When using address input, there should be an overlay
- In general, there should be no weird behaviour while on mobile
- Add fly to on IncidentSelect
- pointToLayer: filter so that selected icon stays in place
- add small points to latitude to move the map up when on mobile
- When on clear it removes the pin from the map
- Added a AddressSearchMobile, which is an overlay that pops up when the user uses the address input on mobile
- Changes some css
Before opening a …
=> [SIG-4784]: zoom to incident on click

app.amsterdam.json
Ticket: none
We need to talk to a different api endpoint since the migration to Azure.
=> Change the apiBaseUrl to the new one

.github/workflows/build_and_push_to_github_container_registry.yml
This bumps cosign to v1.13.1 and fixes signing Docker images on GitHub container registry.
=> Bump cosign to v1.13.1

src/signals/IncidentMap/components/FilterPanel/FilterCategoryWithSub.test.tsx, src/signals/IncidentMap/components/FilterPanel/FilterCategoryWithSub.tsx
Ticket: none
The wrong name was displayed in the filter panel.
=> [bugfix]: fix display name on filter panel meldingenkaart

src/shared/services/configuration/map-markers.ts, src/signals/IncidentMap/components/FilterPanel/FilterCategory.tsx, src/signals/IncidentMap/components/FilterPanel/styled.ts, src/signals/IncidentMap/components/FilterPanel/utils.test.ts, src/signals/IncidentMap/components/FilterPanel/utils.ts, src/signals/IncidentMap/components/IncidentLayer/IncidentLayer.tsx, src/signals/IncidentMap/components/utils/get-filtered-incidents.ts
Ticket: [SIG-4867](https://datapunt.atlassian.net/browse/SIG-4867)
- The default icon in the filterpanel of the incidentMap was too big. Resizing it to follow the other icons. 
- Meanwhile, set default icon where filters are created.
=> [bugfix-4867] Resize filter icons and set default icons

app.base.json, src/signals/incident/containers/KtoContainer/index.test.js
To make upgrading the Signalen frontend non-breaking, `reporterMailHandledNegativeContactEnabled` should by default set to false. This results in the original behavior of Signalen.
Municipalities can opt-in to this new functionality by enabling the feature flag.
=> By default set reporterMailHandledNegativeContactEnabled to false

Dockerfile, README.md, default.conf, docker-compose.yml, nginx.conf
To improve security and to comply with security policies of environments with more strict security requirements (e.g. the environment of Utrecht, but also the new Azure environment of Amsterdam) we require the frontend container to be able to run as non-root. This is also [considered best practice](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security).
This PR changes the container user from root to appuser.
⚠️  This change is breaking and requires to make infrastructural changes when deploying. The container port changes from 80 to 8080, as a non-root container is not able to bind to port 80.
=> Make Docker image to be able to run as non-root

package-lock.json, src/signals/my-incidents/hooks/usePostEmail.test.ts, src/signals/my-incidents/hooks/usePostEmail.ts, src/signals/my-incidents/pages/Confirmation.test.tsx, src/signals/my-incidents/pages/Confirmation.tsx
Ticket: none
This PR add logic that handles the error response when too many requests are fired when a user tries to get an access token.
=> [feat]: handle tooManyRequest

.github/review/values.yml, .github/workflows/review_cleanup.yml, .github/workflows/review_deploy.yml, Dockerfile
This PR adds the ability to deploy review apps for open pull requests. Pull requests need to be labeled with the label "review" in order to deploy.
Example deployment: https://github.com/delta10/signalen-frontend/pull/1
=> Add ability to deploy review apps

src/components/Button/Button.tsx, src/components/Input/Input.tsx, src/components/MarkerCluster/style.css, src/global.css, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/EmailPreview/EmailPreview.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/styled.tsx
**Context**
Per 15th of December the old font Avenir Next is no longer paid for. To prevent fines font in Sia needs het font to change to Amsterdam Sans.
**Tested by comparing local to acceptation environment** 
- happy flow voor civillians
- happy flow, filters and Signaleringen in back office
- kto-proces, not happy with result
- mijn-meldingen
- meldingenkaart
Ticket: [SIG-4891](https://datapunt.atlassian.net/browse/SIG-4891)
=> [feature 4891] set font to Amsterdam Sans

src/signals/incident/definitions/wizard-step-2-vulaan/afval-container.ts, src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts
Ticket: [SIG-4901](https://datapunt.atlassian.net/browse/SIG-4901)
**Context**
It is obligatory to choose either the afval-container or the lantaarnpaal on the locatiekaart. The text above the map indicated it was not. That indication has been removed.
**Changes**
To the options.validators of both afvalcontainers and straatverlichting-klokken has been added 'required'
=> [feature 4901]: text change in wizard step 2

package-lock.json, src/components/HistoryList/HistoryList.test.tsx, src/components/OverviewMap/DetailPanel/__tests__/DetailPanel.test.tsx, src/shared/services/string-parser/index.js, src/shared/services/string-parser/index.test.js, src/signals/incident-management/containers/AreaContainer/components/IncidentDetail/__tests__/IncidentDetail.test.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.test.tsx, src/signals/incident/containers/IncidentReplyContainer/IncidentReplyContainer.tsx, src/signals/incident/containers/IncidentReplyContainer/__tests__/IncidentReplyContainer.test.tsx, src/signals/incident/containers/IncidentReplyContainer/__tests__/utils.test.ts, src/signals/incident/containers/IncidentReplyContainer/utils.ts
Ticket: [SIG-4902](https://datapunt.atlassian.net/browse/SIG-4902)
**Context**
In the backoffice there are two time notifications in the meldingpage styled as hh:mm. This needs to be hh.mm
**Changes** 
1. formatDate in IncidentReplyContainer, the : has been replaced with a .
2. string2time the : has been changed to .
=> [feat 4902]: Time notation changed from hh:mm to hh.mm. 

src/shared/services/configuration/map-markers.ts, src/signals/incident/components/IncidentForm/index.tsx, src/signals/incident/components/IncidentWizard/IncidentWizard.tsx, src/signals/incident/components/StepByStepNavClickable/StepByStepNavClickable.test.tsx, src/signals/incident/components/StepByStepNavClickable/StepByStepNavClickable.tsx, src/signals/incident/components/StepByStepNavClickable/index.ts, src/signals/incident/components/StepByStepNavClickable/styled.tsx, src/signals/incident/components/StepWizard/components/Step.tsx, src/signals/incident/components/StepWizard/components/Steps.tsx, src/signals/incident/components/StepWizard/components/Wizard.tsx, src/signals/incident/components/StepWizard/context/WizardContext.tsx, src/signals/incident/components/StepWizard/index.test.tsx, src/signals/incident/services/yup-resolver/index.ts, src/signals/my-incidents/components/Routing/styled.tsx, src/signals/my-incidents/pages/Confirmation.test.tsx, src/signals/my-incidents/pages/Detail.test.tsx
Ticket: [SIG-4725](https://datapunt.atlassian.net/browse/SIG-4725)
add navigation to stepbystepnav component. To fit it in the current step navigation, a context property called "stepsCompletedCount" , is there to keep track of the first non validated field.
=> Make step by step nav navigatable when creating an incident.

src/signals/settings/users/Detail/components/UserForm/__tests__/UserForm.test.js, src/signals/settings/users/Detail/components/UserForm/index.js, src/utils/__tests__/fixtures/user.json
Add the ability to configure an e-mail notification for a user on user or department assignment.
Closes https://github.com/Signalen/product-steering/issues/82
Depends on https://github.com/Amsterdam/signals/pull/1057
=> Add ability to send e-mail notification on user or department assignment

src/components/MarkerCluster/MarkerCluster.tsx, src/signals/IncidentMap/components/DrawerOverlay/DetailPanel.test.tsx, src/signals/IncidentMap/components/DrawerOverlay/DetailPanel.tsx, src/signals/IncidentMap/components/IncidentLayer/IncidentLayer.tsx, src/signals/IncidentMap/components/IncidentMap/IncidentMap.tsx
make the map accessible for visually impaired people.
- Focus on button when entering DetailPanel.tsx. And go back to marker again when closing DetailPanel.tsx.
- Save last focussed marker on meldingenkaart, before selecting one and opening the detailpanel. When hiding the detailpanel focus on the last selected marker again.
Ticket: [SIG-4871](https://datapunt.atlassian.net/browse/SIG-4871)
=> Refining accessibility van Meldingenkaart

.github/PULL_REQUEST_TEMPLATE.md
Ticket: none
Since the PR titles did not follow any convention and therefore the jira ticket number was not visible it was very hard to see which features where in which release. 
- I updated the wiki in the SIA repo in Azure with a naming convention
- I removed the checkboxes to avoid unnecessary work
- I updated the PR Template in this PR to ensure everyone gets a reminder to provide a proper title
=> [chore]: update PR template

src/components/MapInput/index.js
Ticket: [SIG-4786](https://datapunt.atlassian.net/browse/SIG-4786)
With the update of Amsterdam React Maps some styling was added which caused the address button to flow over the save and cancel button. This PR set the position of the "StyledViewerContainer" to unset, which was the value before the update.
=> [fix-4786]: unset position map controls

src/signals/incident/containers/KtoContainer/components/KtoForm/index.js
Ticket: [SIG-4930](https://datapunt.atlassian.net/browse/SIG-4930)
The text in the KTO form said you could choose multiple answers while this is not the case. Changed the text to "Kies één van de onderstaande antwoorden".
=> [fix-4930]: changed text

src/signals/IncidentMap/components/FilterPanel/FilterCategory.test.tsx, src/signals/IncidentMap/components/FilterPanel/FilterCategory.tsx, src/signals/IncidentMap/components/FilterPanel/FilterPanel.test.tsx, src/signals/IncidentMap/components/FilterPanel/FilterPanel.tsx
Ticket: [SIG-4933](https://datapunt.atlassian.net/browse/SIG-4933)
currently on meldingenkaart, a user cant focus and keypress 'enter' to toggle this filter. With this pr it can.
=> [fix-4933]: When tabbing and pressing enter over a filter, toggle filter.

src/containers/App/index.tsx, src/hooks/useIsFrontOffice.js, src/signals/my-incidents/pages/Detail.tsx, src/signals/my-incidents/pages/styled.ts
Change useIsFrontOffice.js hook. Front office shouldnt be active on mijn-meldingen. Set 960 as default max-width @ overview. Remove unnecessary wrapper at mijn meldingen detail page.
Ticket: [SIG-4911](https://datapunt.atlassian.net/browse/SIG-4911)
go to mijn-meldingen, get token en go to overview. Then you'll see a change in margin of the StyledRow component. This has to do with the themeprovider 
```
if (!getIsAuthenticated()) {
config.maxGridWidth = 960
```
- Committed source …
=> [fix-4911]: change max width and padding top when authenticated at my incidents overview page.

src/signals/IncidentMap/components/FilterPanel/utils.ts, src/signals/IncidentMap/components/__test__/mock-incidents.ts, src/signals/IncidentMap/components/utils/get-filtered-incidents.test.ts, src/signals/IncidentMap/components/utils/get-filtered-incidents.ts, src/signals/incident/components/IncidentForm/index.tsx
Ticket: [SIG-4934](https://datapunt.atlassian.net/browse/SIG-4934)
Filtering on subcategory did not work as expected. When selecting/deselecting a subcategory, all incidents of the main category where shown. This was because `activeIncidents` where defined as having an active filter slug on main PR subcategory. While, when a mainCategoryFilter has the option to filter in subcategories as well, an incident can have a deslected subcategory while the main category stays selected. This incident should be treated as deselected, not as selected. 
- changes the function that checks whether an incident is active
- adjusted the test. Which had a wrong assertion, therefore passed while faulty.
=> [fix-4934]: fix incidentMap subcategory filter

src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.js, src/signals/incident-management/containers/IncidentDetail/components/DetailHeader/index.test.js, src/signals/incident-management/containers/IncidentDetail/components/ForwardToExternal/styled.tsx
When an incident has been closed (_Afgehandeld_ or _Gennuleerd_), it should not be possible to forward it to an external party. In this case, the "Extern" button should simply not be rendered.
Besides the issue described above, this PR provides a minor styling fix in the forward to external form: images in portrait orientation were stretched vertically.
=> [fix]: Hide 'Extern' button when incident is closed

src/signals/incident/components/IncidentForm/index.tsx
Ticket: [SIG-4938](https://datapunt.atlassian.net/browse/SIG-4938)
Currently, you can set a category, press next without blurring the textfield, and while your subcategory request is pending, go to the next step. In this pr the source field is also validated before going to the next step.
[SIG-4938]: …
=> [fix-4938]: Validate source when creating incident.

src/components/Modal/Modal.test.tsx, src/components/Modal/Modal.tsx, src/components/Modal/index.ts, src/signals/settings/users/Overview/__tests__/Overview.test.tsx
**Context**
All files need to convert to typescript
**Changes**
Converted Modal/index.js to Modal.tsx
Added index.ts 
Restructured folder structure so that Modal.test will be next to Modal.tsx and not in a seperate test folder.
Made prop IsOpen  explicit
Ticket: [SIG-4656](https://datapunt.atlassian.net/browse/SIG-4656)
Ticket: [SIG-4941](https://datapunt.atlassian.net/browse/SIG-4941)
Be kind to code …
=> [refactor-4656]: convert Modal/index.js to Modal.tsx

src/signals/incident/components/IncidentForm/index.test.js
This test assures that a source and description is given before the next step method is called. This test suite makes use of a nextSpy instead of really going to the next page. We could rewrite the suite to really go to a next step for a more realistic scenario. This will take some time however.
=> Add test for IncidentForms' handleSubmit validation of source and description.

src/signals/incident-management/containers/ReporterContainer/ReporterContainer.test.tsx, src/signals/incident-management/containers/ReporterContainer/__tests__/useFetchReporter.test.ts, src/signals/incident-management/containers/ReporterContainer/components/ContactHistory.test.tsx, src/signals/incident-management/containers/ReporterContainer/components/ContactHistory.tsx, src/signals/incident-management/containers/ReporterContainer/components/FeedbackStatus.test.tsx, src/signals/incident-management/containers/ReporterContainer/components/FeedbackStatus.tsx, src/signals/incident-management/containers/ReporterContainer/components/Header.test.tsx, src/signals/incident-management/containers/ReporterContainer/components/Header.tsx, src/signals/incident-management/containers/ReporterContainer/components/IncidentDetail.test.tsx, src/signals/incident-management/containers/ReporterContainer/components/IncidentList.test.tsx, src/signals/incident-management/containers/ReporterContainer/components/IncidentList.tsx, src/signals/incident-management/containers/ReporterContainer/components/IncidentListItem.test.tsx, src/signals/incident-management/containers/ReporterContainer/components/IncidentListItem.tsx, src/signals/incident-management/containers/ReporterContainer/useFetchReporter.test.ts, src/signals/incident-management/containers/ReporterContainer/useFetchReporter.ts
Ticket: [SIG-4946](https://datapunt.atlassian.net/browse/SIG-4946)
The test useFetchReporter.test.ts is flacky and fails now and then, causing hickups in pipelines etc. 
The cause was a race condition when asserting an update within the hook. Either a useState update or a get request finished first, causing the test to pass or fail. By using waitForNextUpdate this was covered, however, this would often take too long and result in exceeding the timeout and a failed test. 
I removed the assert that causes this behaviour and restructure the folder according to new standards.
[SIG-4946]: https://datapunt.atlassian.net/browse/SIG-4946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix]: fix flacky test by removing assert that causes race conditions

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/signals/IncidentMap/components/AddressLocation/AddressSearchMobile.test.tsx, src/signals/IncidentMap/components/FilterPanel/FilterPanel.tsx, src/signals/IncidentMap/components/FilterPanel/utils.test.ts, src/signals/IncidentMap/components/FilterPanel/utils.ts, src/signals/IncidentMap/components/utils/update-filter-category.test.ts, src/signals/IncidentMap/components/utils/update-filter-category.ts, src/types/category.ts
Ticket: [SIG-4951](https://datapunt.atlassian.net/browse/SIG-4951)
The values of the maincategories of which the subcatefory filters were enabled was hard coded. Since other municipalities want to have different filters we want to make them configurable.
- Added hasSubcategoriesEnabled to the map options in the configuration file
- Adjust tests
- we should add this configuration in the base file in azure config of acceptance and production
- We should set the correct config for Amsterdam in azure config
[SIG-4951]: https://datapunt.atlassian.net/browse/SIG-4951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-4951]: add subfilters to configuration

app.base.json, internals/schemas/app.schema.json, src/signals/IncidentMap/components/FilterPanel/utils.test.ts, src/signals/IncidentMap/components/utils/get-filtered-incidents.test.ts, src/signals/incident-management/containers/ReporterContainer/useFetchReporter.test.ts
Ticket: none
I added some main categories to the hasSubfiltersEnabled in app.base.json. But this file is the base config for all municipalities. The default should be that no mainFilters have subfilters, so adjusted the file.
=> [chore]: reset app.base.json optionsIncidentMap config

src/signals/incident/components/IncidentForm/index.test.js, src/signals/incident/components/IncidentForm/index.tsx
Ticket: [SIG-4956](https://datapunt.atlassian.net/browse/SIG-4956)
**Acc**
- notifications from a subcategory in wizard step 2 should hide when main category isn't selected anymore.
- in the endstep there shouldn't be a mention of the selected sub category
[SIG-4956]: …
=> [fix-4956]: remove old notifications from incidents form.

src/signals/incident-management/__tests__/saga.test.js, src/signals/incident-management/saga.js
The current limit of districts is not enough for some municipalities. This increases the maximum number of districts to 1000, analog to the categories endpoint.
=> Increase page size to 1000 for the districts endpoint

app.amsterdam.json, src/components/SiteHeader/index.js
In the backoffice, on the page where one can enter credentials, the menu item dashboard was visible. This should not be visible when a user is not logged in. Now it is only visisble if user is authenticated. 
Test need not be added, because there is already a test for rendering when not authenticated. 
Ticket: [SIG-4981](https://gemeente-amsterdam.atlassian.net/browse/SIG-4981)
Be kind to code reviewers, …
=> [fix-4981]: removed Dashboardlink from login page

.github/workflows/ci.yml, Dockerfile, README.md, package-lock.json, package.json
**context**
We needed to upgrade the node version from 14 which dates from 2021 to 18 (we could consider 19 as well but 18 has lts status at the moment). 
For updating node I removed pro4jcompile and the prebuild node script. They seem unused. Also installed some linux packages needed in installing canvas from source: "canvas --build-from-source".
Ticket: [SIG-4937](https://gemeente-amsterdam.atlassian.net/browse/SIG-4937)
- Committed source code is headed by the correct SPDX …
=> [feat-4937]: Update npm and node

src/signals/incident-management/containers/Dashboard/components/Filter/Filter.test.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/Filter.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/Option.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/OptionsList.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/SelectList.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/styled.tsx, src/signals/incident-management/containers/Dashboard/hooks/useRoveFocus.test.ts, src/signals/incident-management/containers/Dashboard/hooks/useRoveFocus.ts
**context**
Add custom accessibility to the dashboard filter.
**testers**
Should add on first render a tabindex on the logo in the header, cause the tabindex gets priority other the normal focusable items like links.
Space and arrow up /down should open a combobox(filter option) and bring you to the first or selected filter option. then navigate with arrows up and down, select option with enter / space, close dropdown with Escape.
Ticket: [SIG-4990](https://gemeente-amsterdam.atlassian.net/browse/SIG-4990)
- Code is well-commented, linted and …
=> [feat-4990]: Add accessibility to dashboard filter

src/components/AutoSuggest/AutoSuggest.tsx
In AutoSuggest.tsx would submit when clearing an input. Fixed with a prevent default.
Ticket: [SIG-4999](https://gemeente-amsterdam.atlassian.net/browse/SIG-4999)
=> [bugfix: 4999]: Prevent location clear default (submit)

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/constants.ts, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/utils.ts
Ticket: [SIG-5005](https://gemeente-amsterdam.atlassian.net/browse/SIG-5005)
When an incident had a "verzoek tot heropenen" request and in the backoffice someone set the status to "Afgehandeld", it a says "no email was send". However, an email is send. This PR removes the logic that causes this behaviour. See screenshot for result.
=> [fix-5005]:re-add send email notification

src/signals/incident-management/containers/Dashboard/Dashboard.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/Filter.test.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/Filter.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/SelectList.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/constants.ts, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.test.tsx, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.test.js, src/signals/incident-management/containers/IncidentOverviewPage/styled.tsx, src/signals/incident-management/context.ts, src/signals/incident-management/index.js, src/signals/incident/components/StepWizard/components/Wizard.tsx
Save dashboard filter object by updating incident management context.
Ticket: [SIG-4904](https://gemeente-amsterdam.atlassian.net/browse/SIG-4904)
When going to overview by clicking a graph (for example areagraph) the filters should be remembered
and a backlink state property be given to the router. That way we can go back to the same dash board filters from the overview page with the backlink (component), or previous button in your browser.
However when moving to a page (incl overview without backlink property), it loses the filters.
**nb**
The click action is currently covering the whole areagraph element. 
- Double-check your branch is based on `main` and …
=> [feat-4904]: Save dashboard filter

src/signals/IncidentMap/components/Header/styled.tsx
Ticket: [SIG-4987](https://gemeente-amsterdam.atlassian.net/browse/SIG-4987)
Implements last feedback on the logo alignment of the IncidentMap. Setting a max-width will not push the burger menu away on mobile.
=> [fix-4987]: Incidentmap logo alignement

src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts
Ticket: [SIG-4984](https://gemeente-amsterdam.atlassian.net/browse/SIG-4984)
- Adds an alert when an incident falls in the "klok" category
- Removed the (is niet verplicht) at the location, since a location/klok is mandatory.
Nice visual:
=> [feat-4984] alert subcategorie klok

src/utils/__tests__/parseTemplateString.test.ts, src/utils/parseTemplateString.ts
This fixes correct template string detection, for example when isTemplateString is set with null.
=> Correctly detect an empty template string

src/signals/incident/components/IncidentWizard/IncidentWizard.tsx
Add alert due to strike
Only on first page of application is alert shown.
no connected story in Jira
=> [feat] banner non-availability of municipality due to strike on first page

src/components/DataView/__tests__/DataView.test.js, src/signals/incident-management/components/FilterForm/FilterForm.js, src/signals/incident-management/containers/Dashboard/components/Filter/Filter.test.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/Filter.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/OptionsList.tsx, src/signals/incident-management/containers/Dashboard/components/Filter/constants.ts, src/signals/incident-management/containers/Dashboard/hooks/useDepartments.test.ts, src/signals/incident-management/containers/Dashboard/hooks/useDepartments.ts, src/signals/incident-management/containers/Dashboard/hooks/useFilter.test.ts, src/signals/incident-management/containers/Dashboard/hooks/useFilter.ts, src/signals/incident-management/containers/FilterTagList/FilterTagList.js, src/signals/incident-management/containers/FilterTagList/FilterTagList.test.js, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.test.js, src/signals/incident-management/context.ts, src/signals/shared/filter/parse.js, src/test/utils.js, src/types/api/incident.ts, src/utils/__tests__/fixtures/departmentsCategories.json, src/utils/__tests__/sortAlphabetic.test.ts, src/utils/sortAlphabetic.ts
Use dashboardfilters in overview page
When clicking a graph, use the filter values for the overviewpage. I changed the filter names a bit, so they are the same as in overview, though partly dutch.
Ticket: [SIG-5008](https://gemeente-amsterdam.atlassian.net/browse/SIG-5008)
=> [feat-5008]: Use dashboardfilters in overview page

.github/workflows/build_and_push_to_docker_hub.yml
So docker can pick it up and provide it to the fe, showing to in the console.
Ticket: [SIG-4983](https://gemeente-amsterdam.atlassian.net/browse/SIG-4983)
=> [feat-4983]: Add version number fe to docker hub workflow

src/signals/incident-management/containers/Dashboard/components/AreaChart/AreaChart.test.tsx, src/signals/incident-management/containers/Dashboard/components/AreaChart/AreaChart.tsx
Ticket: [SIG-5048](https://gemeente-amsterdam.atlassian.net/browse/SIG-5048)
The area chart queried all indcidents instead of only the "afgehandelde" incidents. We had to add this status as param to the query.
=> [fix-5048]: Add status param to areaChart query

src/signals/incident-management/containers/Dashboard/Dashboard.tsx, src/signals/incident-management/containers/Dashboard/components/AreaChart/styled.ts, src/signals/incident-management/containers/Dashboard/components/BarChart/BarChart.tsx, src/signals/incident-management/containers/Dashboard/components/BarChart/styled.tsx, src/signals/incident-management/containers/Dashboard/styled.ts
Ticket: [SIG-5007](https://gemeente-amsterdam.atlassian.net/browse/SIG-5007)
The aim was to make the graphs respond to any screen size. However, it seemed very hard/impossible to make a bar chart with facets respond to a certain width. Therefore we chose to make the graphs fixed size and wrap them the on the same breakpoint as the menu changes.
=> [feat-5007]: Align graphs on multiple screens

src/components/HistoryList/HistoryList.tsx, src/components/Markdown/Markdown.test.tsx, src/components/Markdown/Markdown.tsx
Fixes https://github.com/Signalen/product-steering/issues/304
This PR adds list and ordered list support in internal notes. Currently notes return empty when using lists, and this confuses users. This proposal supports the following syntaxes:
```markdown
- Item 1
- Item 2
- Item 3
```
```markdown
1. Item 1
2. Item 2
3. Item 3
```
<kbd><img width="225" alt="Scherm­afbeelding 2023-02-21 om 19 07 44" src="https://user-images.githubusercontent.com/5213690/220437651-35932ce8-aab5-4d47-a957-e557c97d843b.png"></kbd>
<kbd><img width="225" alt="Scherm­afbeelding 2023-02-21 om 19 08 05" src="https://user-images.githubusercontent.com/5213690/220437655-3d944902-0841-4cdf-836e-2c7d8884537b.png"></kbd>
=> Support lists in internal notes

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/signals/incident/components/IncidentWizard/IncidentWizard.tsx
Since the strike Alert was temporary I delete the whole functionality in this PR. 
- Breaking change! Should remove the feature flag `showStrikeAlert` in the config files.
=> [chore]: Remove strike Alert

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/constants.ts, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/utils.test.ts, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/utils.ts
Ticket: [SIG-5056](https://gemeente-amsterdam.atlassian.net/browse/SIG-5056)
The negative kto flow had a bug. When in the old flow (`reporterMailHandledNegativeContactEnabled: false`) and the user agreed to receive emails and the status of an incident went from "Verzoek tot heropenen" to "Afgehandeld" the backend did not send an email while the frontend thought it should. 
The backend was correct, since in the old flow in this scenario no email is send. 
This PR fixes the frontend so it shows a message "Email is not send", does not trigger the backend and making a note required. 
Attempt from the FE of sending an email while it should not. 
Status after fix. Scenario of the old flow: 
Status after fix. Scenario of the new flow:
=> [fix-5056]: kto negative feedback

src/signals/settings/components/Overview/components/Overview.tsx, src/signals/settings/components/Overview/components/__tests__/Overview.test.tsx, src/signals/settings/components/Overview/components/styled.ts
At instellingen show be & fe versions. Also move Overview styled components to styled folder.
Ticket: [SIG-5057](https://gemeente-amsterdam.atlassian.net/browse/SIG-5057)
=> [feat-5057]: Show be and fe version numbers

src/signals/incident-management/containers/Dashboard/components/Filter/styled.tsx
This halves the size of the options ul when you only need 1 column.
Ticket: [SIG-5004](https://gemeente-amsterdam.atlassian.net/browse/SIG-5004)
=> [feat-5004]: Styling adjustion

src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/index.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/ExtraProperties/index.tsx
Ticket: [SIG-5065](https://gemeente-amsterdam.atlassian.net/browse/SIG-5065)
Incidents that are created based on a previous incident in the container category get the type "nearby" and some details of the old melding. In the backoffice we want to show the container details, but this is not possible. 
When the type is set to "nearby" we don't show any container details in the backoffice.
**Bug**
**Fix**
=> [fix-5065]: Remove container details when type: nearby

.github/review/values.yml, app.amsterdam.json, app.base.json
New policiy in municipality concerning presentation of time. Now hours have a zero prefixed if there is only one digit. Example: 8.00 hour becomes 08.00 hour. Changed it also in .github/review/values.yml so that texts still match.
Ticket: [SIG-5062](https://gemeente-amsterdam.atlassian.net/browse/SIG-5062)
=> [feature-5062]: Changed time presentation in helpText

src/components/SiteHeader/styled.ts, src/signals/settings/components/PageHeader/index.tsx
Ticket: [SIG-5071](https://gemeente-amsterdam.atlassian.net/browse/SIG-5071)
1) Highlighting of the menu went wrong:
before
after
2) Some wrong styling added to header
before
after
=> [fix-5071]: highlight active menu

src/signals/settings/categories/Detail/index.js
Ticket: [SIG-5132](https://gemeente-amsterdam.atlassian.net/browse/SIG-5132)
Because we send all fields of the api response as payload with a patch request we got an error with the latest backend update. They put a new field `configuration` that is required, but we do not send any value with it.
Removing the field for now. A full refactor of the components concerned is on the way in [this ticket](https://gemeente-amsterdam.atlassian.net/browse/SIG-4996)
=> [fix-5132]: Remove configuration field on patch request

default.conf
This adds a `/healthz` endpoint to the container for monitoring purposes. Calls to this endpoint are not logged.
=> Add healthz endpoint for monitoring

src/signals/incident-management/containers/IncidentDetail/components/Detail/index.js, src/signals/incident/components/IncidentForm/styled.tsx, src/signals/incident/components/IncidentPreview/styled.tsx, src/signals/my-incidents/components/IncidentsList/styled.ts
**Context**
As a user I want to have text continue on the next line if it is otherwise too long. This doesn't happen in Samenvattingspagina (omschrijving), Backoffice detail pagina melding (omschrijving) and Mijn meldingen pagina (omschrijving). 
**Changes:**
- added overflow-wrap: anywhere; to css where text was not correctly wrapped (Samenvattingspagina (omschrijving), Backoffice detail pagina melding (omschrijving) and Mijn meldingen pagina (omschrijving)0
Ticket: [SIG-5105](https://gemeente-amsterdam.atlassian.net/browse/SIG-5105)
- Code …
=> [feat-5105] Wrap too long words

src/shared/services/api/api.js, src/signals/incident-management/containers/IncidentDetail/IncidentDetail.test.js, src/signals/incident-management/containers/IncidentDetail/IncidentDetail.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx
Process stopped when category is Overig-overig and status is Afgehandeld. Different to specification of Linda is that patch is triggert by clicking Verstuur and not when clicking Afgehandeld in drop-down. 
Changes:
- added a test in Statusform to see if category and subcategory are overig and if status is Afgehandeld. If so, don't create an email template..
- added a patch to an endpoint that does not accept the patch, so the response will be a 405. The 405 will trigger a global error message.
Ticket: [SIG-5083](https://gemeente-amsterdam.atlassian.net/browse/SIG-5083)
- Pull request has tests (we are …
=> [feat-5083] stop processing when category is Overig-overig and status is Afgehandeld

src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx
Text of global warning needed info on what the official needed to do. Changed to 'Het is niet mogelijk een melding in de categorie Overig - Overig af te handelen. Plaats de melding in de best passende categorie.'
Ticket: [SIG-5083](https://gemeente-amsterdam.atlassian.net/browse/SIG-5083)
=> [feat-5083] text change after feedback from Linda

src/components/Modal/Modal.tsx
Ticket: [SIG-5134](https://gemeente-amsterdam.atlassian.net/browse/SIG-5134)
- Add overflow-y hidden to filter modal
=> [fix-5134]: doorgedraaide scroller Safari

.github/review/values.yml, app.amsterdam.json
Sentry's new addres is sentry-new.data.amsterdam.nl
Release Notes
Change Sentry dns
Ticket: [SIG-5135](https://gemeente-amsterdam.atlassian.net/browse/SIG-5135)
=> [spike-5135] DNS change of Sentry

src/components/DataView/__tests__/DataView.test.js, src/components/DataView/components/DataViewBody/index.js, src/components/DataView/styled.js, src/signals/settings/categories/main-categories/Overview.test.tsx, src/signals/settings/utils/filterData.test.js, src/signals/settings/utils/filterData.ts, src/utils/__tests__/fixtures/categories_structured.json
On the main categorie overview page in settings we want to show the icons that are set per category
- Add ability to add icons to the overview row
- Change tests
=> [feat]: Add icon to main categorie overview

app.base.json, internals/schemas/app.schema.json, src/components/AreaMap/AreaMap.tsx, src/components/OverviewMap/OverviewMap.tsx, src/components/Summary/Summary.tsx, src/signals/IncidentMap/components/IncidentLayer/IncidentLayer.tsx, src/signals/IncidentMap/components/IncidentMap/IncidentMap.tsx, src/signals/IncidentMap/components/IncidentMap/Pin.test.tsx, src/signals/IncidentMap/components/IncidentMap/Pin.tsx, src/signals/IncidentMap/components/IncidentMap/utils.test.ts, src/signals/IncidentMap/components/IncidentMap/utils.ts, src/signals/IncidentMap/components/utils/index.ts, src/signals/incident-management/components/MapInput/index.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Location/index.js, src/signals/incident-management/containers/IncidentDetail/components/LocationPreview/index.js, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.tsx, src/signals/incident/containers/ExternalReplyContainer/components/Location/Location.tsx, src/signals/incident/containers/ExternalReplyContainer/styled.ts, src/signals/my-incidents/components/Map/Map.tsx
This PR makes sure all zoomlevels that are present in the codebase can be configured. This allows using other base maps in other projections and still use sensible zoomlevels.
The configuration defaults to EPSG:28992 projection and the zoomlevels that were previously hardcoded. So this PR does not introduce any functional changes.
Fixes [Teams issue](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:e201681cf65b453db9a98a67467c603a@thread.skype_p_dFQcO7x3vUWrWQ8CGTkI6ZcAD6mW_h_1670844429492?tenantId=6ef029ab-3fd7-4d98-9b0e-d1f5fedea6d1&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FFGW_5LOtEE6gEAEeVJKg4JcAPk8I%22%2C%22channelId%22%3A%2219%3Ae201681cf65b453db9a98a67467c6 …
=> Make zoomlevels of maps configurable

package-lock.json, src/signals/IncidentMap/components/FilterPanel/FilterCategoryWithSub.test.tsx, src/signals/IncidentMap/components/FilterPanel/FilterCategoryWithSub.tsx, src/signals/settings/categories/components/CategoryForm.test.tsx, src/signals/settings/categories/components/CategoryForm.tsx, src/signals/settings/categories/components/Detail.test.tsx, src/signals/settings/categories/components/Detail.tsx, src/signals/settings/categories/components/utils.test.ts, src/signals/settings/categories/components/utils.tsx, src/signals/settings/categories/subcategories/utils.tsx, src/signals/settings/categories/types.ts, src/types/category.ts, src/utils/__tests__/fixtures/categories_private.json
Ticket: [SIG-4997](https://gemeente-amsterdam.atlassian.net/browse/SIG-4997)
Adding new setting to the main category that changes whether the subcategories of this main categories are shown as filters on the public incident map
- Add to form
- Fix mapper to create correct payload
- Fix naming issues on incident map
- Write/Update tests
=> [feat-4997]: Add subcategory filter settings to main category

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/signals/IncidentMap/components/FilterPanel/FilterCategoryWithSub.test.tsx, src/signals/IncidentMap/components/FilterPanel/FilterCategoryWithSub.tsx, src/signals/IncidentMap/components/FilterPanel/FilterPanel.tsx, src/signals/IncidentMap/components/FilterPanel/utils.test.ts, src/signals/IncidentMap/components/FilterPanel/utils.ts, src/signals/IncidentMap/components/IncidentMap/IncidentMap.test.tsx, src/signals/IncidentMap/components/IncidentMap/IncidentMap.tsx, src/signals/IncidentMap/components/__test__/mock-filters.ts, src/signals/IncidentMap/components/utils/add-icons-to-incidents.test.ts, src/signals/IncidentMap/components/utils/add-icons-to-incidents.ts, src/signals/IncidentMap/components/utils/get-filtered-incidents.test.ts, src/signals/IncidentMap/components/utils/get-filtered-incidents.ts, src/signals/IncidentMap/components/utils/index.ts, src/signals/IncidentMap/types/incident-map.ts, src/signals/incident-management/containers/ReporterContainer/useFetchReporter.test.ts, src/types/category.ts
Ticket: [SIG-4997](https://gemeente-amsterdam.atlassian.net/browse/SIG-4997)
Implement the new main category setting of showing its subcategories as filters in the public incident map.
- Removed IncidentMap configuration `hasSubfiltersEnabled`. This can be done in backoffice main category settings now.
=> [feat-4997]: implement subfilter setting

src/signals/incident/definitions/__tests__/wizard-step-4-summary.test.js, src/signals/incident/definitions/wizard-step-2-vulaan/afval.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/afval.ts
In order to prioritise issue for HH additional questions for adval are being asked. Contrary to design the textareainput has been changed to textinput. Otherwise the question can't be made required.
Ticket: [SIG-5164](https://gemeente-amsterdam.atlassian.net/browse/SIG-5164)
=> [feat-5164] Change in aanvullende vragen afval

Dockerfile, src/signals/incident-management/containers/ReporterContainer/ReporterContainer.tsx, src/signals/my-incidents/components/IncidentsDetail/IncidentsDetail.tsx, src/signals/my-incidents/components/IncidentsDetail/styled.ts
**Context:** 
In mijn-meldingen detail page the description of the issue overflows. You can't see the history since it gets pushed to the side. In the ReporterContainer (in the overview page of all issues from one complainer in the backoffice) the text also overflows.
**Changes:** 
Set the ContentWrapper of the incidentDetail to overflow-wrap: everywhere, set the max width to 2/3 of 960px. 
Set the Wrapper of the ReporterContainer to overflow-wrap: everywhere
Ticket: [SIG-5157](https://gemeente-amsterdam.atlassian.net/browse/SIG-5157)
- Code …
=> [fix-5157] overflow wrap the description of an issue in mijn-meldingen

src/signals/settings/SettingsModule.tsx
Ticket: [SIG-5245](https://gemeente-amsterdam.atlassian.net/browse/SIG-5245)
I'd changed the roleGroup incorrectly when adding the settings for the main category, therefore users could not see the pages anymore.
=> [fix-5245]: Changed protected route to correct roleGroup

src/components/SiteHeader/MenuItems.tsx, src/components/SiteHeader/SiteHeader.test.tsx
Ticket: none
This way the (v1) is only shown when both pages are enabled and vice versa.
=> [fix]: Fix menu item text

src/signals/IncidentMap/components/IncidentMap/styled.ts
This fixes a display error for an empty IncidentMap.
**Before**
**After**
=> Fix display error for empty IncidentMap

internals/mocks/fixtures/standard-texts/detail-post.json, internals/mocks/fixtures/standard-texts/index.ts, internals/testing/msw-server.ts, src/hooks/useFetch.ts, src/signals/incident-management/containers/StandardTextsAdmin/components/DetailPage/Detail.test.tsx, src/signals/incident-management/containers/StandardTextsAdmin/components/DetailPage/Detail.tsx, src/signals/incident-management/containers/StandardTextsAdmin/components/DetailPage/utils.ts, src/signals/incident-management/containers/StandardTextsAdmin/components/OverviewPage/OverviewPage.tsx, src/signals/incident-management/index.js
##Context
As a back-officer I would like to add a new standard text. 
- Added a link to button Tekst toevoegen on Overview page
- Added a createpost method
- OnSubmit checks per the url (params.id) if there needs to be a patch of a post triggered
- Routing 
- validation of form happens on onSubmit 
- button Verwijderen is conditional on params.id (whether there is an id in the url or not)
- Standard is state Gemeld selected
Ticket: [SIG-5287](https://gemeente-amsterdam.atlassian.net/browse/SIG-5287)
- Code is well-commented, linted and follows …
=> [feat-5287]: Add new standard text page part 1

e2e-tests/package-lock.json
Bumped word-wrap package in e2e-package-lock.json to 1.2.4
Tests failed on Github due to coverage. Latest version of main has coverageproblem solved, so I copied changes and made a new PR.
=> Chore bump package in e2e-package-lock.json

src/components/AutoSuggest/AutoSuggest.test.tsx, src/components/AutoSuggest/AutoSuggest.tsx, src/signals/incident-management/components/FilterForm/FilterForm.js
The change in https://github.com/Amsterdam/signals-frontend/pull/2620 introduced a bug for autocompletion of the username filter. This PR fixes the bug.
=> Set authorization header correctly for username autocomplete

.github/workflows/build_and_push_to_github_container_registry.yml
Currently frontend version tags are not included in builds that are pushed to Github Container Registry.
=> Add FRONTEND_TAG to Github Container Registry builds as build argument

src/components/RadioButtonList/RadioButtonList.tsx, src/signals/incident-management/containers/StandardTextsAdmin/components/DetailPage/Detail.tsx
Ticket: [SIG-5362](https://gemeente-amsterdam.atlassian.net/browse/SIG-5362)
Fixes:
- We redirected too fast to the overview page, therefore the post/patch request never came through
- Removed timeout since it didn't work. The overview page wasn't updated. Will create a backend story to wait until the search endpoint is updated before returning a success
- Changed the validation so that the validation error is removed when a category is selected
=> [fix-5362]: Standaard teksten opslaan

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.tsx, src/signals/incident/definitions/wizard-step-2-vulaan/eikenprocessierups.ts
##Context
As a developer I want to maintain my code, obsolete code should be removed. The featureFlwag useGisib had been mistakingly introduced and now needs to be removed.
- removed feature flag UseGisib form app.base.json and app.amsterdam.json
- removed all usages of feature flag useGisib 
- old URL has been removed
- in a different subtask all necessary tests will be changed
subtask: Ticket: [SIG-5373](https://gemeente-amsterdam.atlassian.net/browse/SIG-5373)
main ticket: Ticket: [SIG-5320](https://gemeente-amsterdam.atlassian.net/browse/SIG-5320)
Remove featureflag  useGisib svp.
- Pull request …
=> [feat-5373] Removed all references to useGisib featureflag.

src/hooks/useFormValidation.js, src/signals/settings/roles/containers/RoleFormContainer/components/RoleForm/index.js, src/signals/settings/users/Detail/components/UserForm/index.js
Removed unused code that lowered the coverage. The removed code checked for a pattern- or typemismatch and was only used in RoleForm. RoleForm doesn't have an inputfield with a declared pattern, so there never could be a 
patternmismatch. It did have a type = text, but a type = text input element cannot produce a typemismatch.
No ticket connected to PR.
Be kind to code reviewers, please try to keep pull …
=> [chore] improving test coverage

src/components/Notification/__tests__/Notification.test.tsx, src/components/Notification/index.tsx, src/signals/incident/containers/KtoContainer/KtoContainer.tsx, src/signals/incident/containers/KtoContainer/utils.ts, src/signals/settings/hooks/useFetchResponseNotification.test.ts, src/signals/settings/hooks/useFetchResponseNotification.ts, src/signals/shared/type-guards/index.test.ts, src/signals/shared/type-guards/index.ts
Ticket: [SIG-5292](https://gemeente-amsterdam.atlassian.net/browse/SIG-5292)
The notification of an action was barely noticeable since it was removed very quickly. That was caused by the useFetchResponseNotification that was set to TYPE_LOCAL. 
- Changed it to TYPE_GLOBAL so that it does not disappear when navigating to another page.
- Changed the functionality of TYPE_GLOBAL slightly so that is disappears after 8 seconds, just likt a TYPE_LOCAL. Only when it has variant ERROR it needs te be closed with the close button
- Moved the isFetchError typeguard to a shared location
=> [fix-5292]: disappearing notification

src/signals/incident-management/containers/StandardTextsAdmin/components/Summary/Summary.tsx, src/signals/incident-management/containers/StandardTextsAdmin/components/Summary/styled.ts
Ticket: [SIG-5047](https://gemeente-amsterdam.atlassian.net/browse/SIG-5047)
Shows the highlighted search results for the Standard Texts.
=> [feat-5047]: Add highlight to search results

src/signals/incident/components/form/MapSelectors/Asset/Selector/NearbyLayer/NearbyLayer.tsx
=> [fix]: Add offset to nearby incident icons

src/signals/incident/components/form/MapSelectors/Asset/Selector/NearbyLayer/NearbyLayer.tsx
Ticket: none
The icons of already known incidents on the same spot as for example a container were placed on top of the container. Making the container unreachable. This change sets the marker underneath the container.
=> [fix]: Set zIndexOffset on nearby layer marker

docker-compose.yml
amsterdam.json and base.json do not overlap. When building the fe it was breaking due to missing config files.
=> [chore]: Adjust docker compose volume

src/components/FileInput/FileInput.tsx, src/signals/incident/components/form/FileInput/FileInput.tsx
Ticket: none
Make label optional because when the FileInput is rendered in FormField the FormField has already a label.
=> [chore]: Make FileInput optional

src/signals/my-incidents/components/IncidentsDetail/IncidentsDetail.test.tsx, src/signals/my-incidents/components/IncidentsDetail/IncidentsDetail.tsx
Added AttachmentViewer to mijn-meldingen. It uses a different State but otherwise works the same as in the backoffice.
Ticket: [SIG-5426](https://gemeente-amsterdam.atlassian.net/browse/SIG-5426)
=> [feat 5426] show true size images in mijnmeldingen when clicked

src/signals/my-incidents/components/IncidentsDetail/styled.ts
Resolved feedback from Linda, now gap has 16px instead of 8.
Ticket: [SIG-5236](https://gemeente-amsterdam.atlassian.net/browse/SIG-5236)
=> feat/5236-resolving-feedback-from-Linda 

src/components/DataView/components/DataViewBody/DataViewBody.tsx, src/components/DataView/components/DataViewBody/index.ts
- Transformed file to .tsx file. Data is an [ ], because DataViewBody is used as a generic way to showcase data.
- No tests are transformed since 100% coverage is achieved by tests of DataView (which still needs to be transformed)
- Discovered bug; primary key of departments VTH  are the same in the backend. Jelle has been informed.
Be kind to code reviewers, please try to keep pull requests as small and …
=> [Chore] move DataViewBody from js to tsx

src/components/AttachmentViewer/AttachmentViewer.test.tsx, src/components/AttachmentViewer/AttachmentViewer.tsx, src/components/AttachmentViewer/components/InteractiveImage/InteractiveImage.test.tsx, src/components/AttachmentViewer/components/InteractiveImage/InteractiveImage.tsx, src/components/AttachmentViewer/index.ts, src/signals/incident-management/containers/IncidentDetail/IncidentDetail.tsx, src/signals/incident-management/containers/IncidentDetail/components/Attachments/EditAttachment..tsx, src/signals/incident-management/containers/IncidentDetail/types.ts, src/signals/incident/containers/ExternalReplyContainer/useExternalReplyQuestionnaire.ts, src/signals/my-incidents/types.ts
Ticket: [SIG-5454](https://gemeente-amsterdam.atlassian.net/browse/SIG-5454)
Three different types of attachments:
-  incidentDetail management
-  then a mapped one
-  A different "public" on on my-incidents
Did align the types with what is actually passed as data. Many times undefined was used while the actual value was null.
=> [feat-5454]: Aligned Attachment types

app.base.json, internals/schemas/app.schema.json, internals/scripts/helpers/config.js, src/index.html
This municipality of The Hague would like to add their own fonts to their deployment of Signalen. This PR makes it possible to configure additional CSS code. This adds the ability to load custom fonts.
*This PR is open to discussion and should be considered as an exploration of implementation option number 1 as discussed with @SireeKoolenWijkstra.*
(aanvulling Sirée) 
option number 1 was:
**1e manier**
Wijziging in de source code -> maak fontlocatie configureerbaar. Den Haag past yml aan met de locatie van de fonts. Doe dit door:
1. de locatie van fonts.css configureerbaar maken (maak app.js de import van fonts.css dynamic)
2. zet in de app.<gemeentenaam>.json de plaats voor de fonts.css die niet bij Amsterdam hoort
3. maak een fonts.css met de juiste urls naar de juiste fonts en zet die …
=> Add additional CSS code

src/signals/incident-management/containers/IncidentDetail/IncidentDetail.tsx, src/signals/my-incidents/__test__/incidents-detail.ts, src/signals/my-incidents/components/IncidentsDetail/IncidentsDetail.test.tsx, src/signals/my-incidents/components/IncidentsDetail/IncidentsDetail.tsx
Resolved feedback from Jelle. Now in my-incidents the text in the upperleft corner will show either melder or foto gemeente depending on the creator.
Ticket: [SIG-5427](https://gemeente-amsterdam.atlassian.net/browse/SIG-5427)
=> feat/5427 text upper left-corner in attachmentviewer in my incidents dependent on creator

src/signals/incident/containers/IncidentContainer/constants.ts
**how to test**
- run backend and frontend with fetchQuestionsFromBackend to true (docker compose up -d in both signals and signals frontend)
- then add two questions where the alert is triggered on the first option of the first question:
- it should init the 'harde stop'
Ticket: [SIG-5429](https://gemeente-amsterdam.atlassian.net/browse/SIG-5429)
Be kind to code reviewers, please try to keep pull requests …
=> [bug-5429]: Add isBlocking to input validator map

package-lock.json, package.json, src/hooks/useDeviceMode.ts
On the incidentmap, when a user used either the GPSLocation or the search bar for an address, the application entered a loop of calls to the BE. This was due to a dependency on a function (isMobile) that referenced a new function with every render.
Also noticed that Leaflet has a new update and updated the package. Saw no weird stuff with the maps.
Ticket: [SIG-5487](https://gemeente-amsterdam.atlassian.net/browse/SIG-5487)
- Committed source code is headed by the correct SPDX …
=> [bugfix-5487] stop unnecessary calls to the BE from the incidentmap

src/components/Detail/Detail.test.tsx, src/components/Detail/Detail.tsx, src/components/Detail/index.ts, src/components/Detail/styled.ts
Ticket: none
Adding a Detail component as desiged [here](https://www.figma.com/file/W8Bfb0h4xcJ5JcUbRbaHP9/Backoffice---Categorie-filter-meldingenkaart?type=design&node-id=1-383&mode=design&t=BFk3KLAMwuJWQ2JA-0).
Test code:
```  
<Detail
header="Het icoon wordt getoond op de openbare meldingenkaart"
content="Zorg voor een cirkel van 32px bij 32px en exporteer als SVG. Voorbeeld van een icoon:"
>
<img
src={'/assets/images/afval/rest.svg'}
alt="Voorbeeld van een icoon"
height={32}
width={32}
/>
</Detail>
```
=> [feat]: details component

internals/testing/api.ts, internals/testing/msw-server.ts, src/components/DataView/components/DataViewBody/DataViewBody.tsx, src/shared/services/file-upload-channel/index.js, src/signals/incident-management/containers/IncidentDetail/IncidentDetail.test.js, src/signals/incident-management/containers/IncidentDetail/IncidentDetail.tsx, src/signals/incident-management/containers/IncidentDetail/hooks/useUpload.test.ts, src/signals/incident-management/containers/IncidentDetail/hooks/useUpload.ts, src/signals/settings/categories/components/CategoryForm.test.tsx, src/signals/settings/categories/components/CategoryForm.tsx, src/signals/settings/categories/components/Detail.tsx, src/signals/settings/categories/components/IconInput/IconInput.test.tsx, src/signals/settings/categories/components/IconInput/IconInput.tsx, src/signals/settings/categories/components/IconInput/index.ts, src/signals/settings/categories/components/styled.ts, src/signals/settings/categories/components/utils.test.ts, src/signals/settings/categories/constants.tsx, src/signals/settings/categories/types.ts, src/types/category.ts, src/utils/__tests__/fixtures/categories_private.json, src/utils/__tests__/fixtures/categories_structured.json
Ticket: [SIG-5019](https://gemeente-amsterdam.atlassian.net/browse/SIG-5019)
Chose a slightly different approach then designed. The design assume the icon is saved when the whole page is saved. But the icon is posted to a different endpoint, therefor I thought it'd be nicer to use the confirmation modal.
Notes:
- Flow is slightly different then designed. Instead of savind on page save I chose to save with the confirmation modal. This way all logic stays in one place. 
- A warning for pixels is not necessary since they are svg's
Todo:
Previous [draft PR](https://github.com/Amsterdam/signals-frontend/pull/2612/files#diff-6d4d8e6cb1ea85996fe6f4084193e7e076e8c40ba681f7f7a66e093d61a0130b)
=> [feat-5019]: Add Icon input to category form

src/signals/settings/categories/components/IconInput/IconInput.tsx, src/signals/settings/categories/components/styled.ts
Resolved new feedback
Now button Icoon wijzigen has on hover same border width on all sides
Ticket: [SIG-5019](https://gemeente-amsterdam.atlassian.net/browse/SIG-5019)
=> [feat-5019]: styling button Icoon wijzigen

internals/scripts/helpers/config.js, src/index.html
The recently merged feature to add additional CSS code (#2709) seems to only work during development, not during run-time. This is due to Webpack that removes `$SIGNALS_ADDITIONAL_CODE_CSS` wrapped within the style tags.
This PR fixes this and solves this analog to the Piwik configuration.
=> Fix additional CSS code feature during runtime

src/components/pages/BasePage/BasePage.tsx, src/containers/App/index.tsx, src/signals/settings/SettingsModule.tsx, src/signals/settings/categories/components/Detail.test.tsx, src/signals/settings/categories/components/Detail.tsx, src/signals/settings/categories/main-categories/Overview.test.tsx, src/signals/settings/categories/main-categories/Overview.tsx, src/signals/settings/categories/subcategories/Overview.test.tsx, src/signals/settings/categories/subcategories/Overview.tsx, src/signals/settings/departments/Detail/__tests__/Detail.test.js, src/signals/settings/departments/Detail/index.js, src/signals/settings/departments/Overview/__tests__/Overview.test.js, src/signals/settings/departments/Overview/index.js, src/signals/settings/roles/containers/RoleFormContainer/__test__/RoleFormContainer.test.js, src/signals/settings/roles/containers/RoleFormContainer/components/RoleForm/__test__/RoleForm.test.js, src/signals/settings/roles/containers/RoleFormContainer/components/RoleForm/index.js, src/signals/settings/roles/containers/RoleFormContainer/index.js, src/signals/settings/roles/containers/RolesListContainer/components/RolesList/__test__/RolesList.test.js, src/signals/settings/roles/containers/RolesListContainer/components/RolesList/index.js, src/signals/settings/roles/containers/RolesListContainer/index.js, src/signals/settings/routes.ts, src/signals/settings/users/Detail/__tests__/Detail.test.js, src/signals/settings/users/Detail/index.js, src/signals/settings/users/Overview/Overview.tsx, src/signals/settings/users/Overview/__tests__/Overview.test.tsx
**Context**
In the backoffice in Instellingen you can click on several links. When clicked the url was directly appended to the main url and not appended to main url/instellingen/. We want the url to reflect the nesting. Instellingen and not Settings was chosen, because the website is in Dutch.
**Changes**
- In App/index at the highest level, there were two directs to the Settingsmodule, one with the wildcard instellingen/* and one as a catch all *. The catch all directs now to the not-found page.
- In order to append to 'instellingen/', the strings in route.js in the setting directory are now all without /.
- All navigate to's now navigate to base_url + / + whatever the rest of the url is 
Ticket: [SIG-5240](https://gemeente-amsterdam.atlassian.net/browse/SIG-5240)
Before opening a pull …
=> [feat-5240]: 'instellingen' is included in url of nested pages

src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Contact/Contact.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Contact/Contact.tsx
when missing permission sia_can_view_contact_details. Also stop error from showing by default.
Ticket: [SIG-5534](https://gemeente-amsterdam.atlassian.net/browse/SIG-5534)
=> [fix-5534]: Dont show error when permission is missing

src/signals/settings/categories/components/CategoryForm.test.tsx, src/signals/settings/categories/components/CategoryForm.tsx, src/signals/settings/categories/components/Detail.tsx, src/signals/settings/categories/components/StandardTextsField/StandardTextsField.test.tsx, src/signals/settings/categories/components/StandardTextsField/StandardTextsField.tsx, src/signals/settings/categories/constants.tsx
Added useWatch to handle dependency of component on another component in StandardTextFiled
Because the parentcomponent Detail is not always rendered, the formValues are not always updated. React Forms has useWatch to check for changing of values in the form. FormValues are therefor removed and useWatch is implemented in CategoryForm where the showing of the standardTextFields is dependent on the status and the chosen standard text.
Ticket: [SIG-5506](https://gemeente-amsterdam.atlassian.net/browse/SIG-5506)
- Code is well-commented, linted and …
=> [bugfix-5506]: status in Instelling -> subcategory doesn't effect texts

src/signals/settings/categories/components/StandardTextsField/StandardTextsField.tsx, src/signals/settings/categories/components/StandardTextsField/styled.ts
Compensating for Chrome deviations
Chrome didn't show the standard texts (for example in subcategory Duiven with status afgehandeld) correct. One of the standard text overflowed its parent boundaries. Added styling (min-width and overflow hidden) to the responsible div.
Ticket: [SIG-5507](https://gemeente-amsterdam.atlassian.net/browse/SIG-5507)
Be kind to code reviewers, please try to keep pull requests as …
=> [bugfix-5507]: standard texts crossed boundary of parent 

src/signals/settings/categories/components/CategoryForm.test.tsx, src/signals/settings/categories/components/CategoryForm.tsx, src/signals/settings/categories/components/Detail.tsx, src/signals/settings/categories/components/StandardTextsField/StandardTextsField.test.tsx, src/signals/settings/categories/components/StandardTextsField/StandardTextsField.tsx, src/signals/settings/categories/constants.tsx
Revert "Added useWatch to handle dependency of component on another component… (#2734)"
Reverting because the bug it was supposed to fix (filtering Standard Texts on its status Active/Inactive) isn't what that status is. The status in Instellingen -> Subcategories -> Subcategory is the status of the subcategory (and not of the Standardtexts associated with that subcategory). IN story [SIG-5536](https://gemeente-amsterdam.atlassian.net/browse/SIG-5536) in Jira the desired functionality is requested.  
This reverts commit 66ae7c84645ed893533986062ebffe796343fa8a.
Ticket: [SIG-5506](https://gemeente-amsterdam.atlassian.net/browse/SIG-5506)
- Double-check your branch …
=> Revert bugfix 5506

src/containers/Notification/constants.ts
Changed SLIDEUP_TIMEOUT to 3 seconds in Notification
Ticket: [SIG-5526](https://gemeente-amsterdam.atlassian.net/browse/SIG-5526)
[SIG-5526]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feature 5526]: Notification needs to fade out after a short period

src/components/GlobalError/GlobalError.test.js, src/signals/incident/components/IncidentForm/index.test.js, src/signals/incident/services/custom-validators/custom-validators.ts
**Text change**
Changed "U kunt dit formulier niet verder invullen. Lees in de rode tekst hieronder waar u uw melding wél kunt doen." to "U kunt dit formulier niet verder invullen. Lees onder de antwoorden waar u uw melding wel kunt doen."
Ticket: [SIG-5541](https://gemeente-amsterdam.atlassian.net/browse/SIG-5541)
Be kind to code reviewers, please try to keep pull requests as small and focused as possible …
=> [feat-5541]: Text change

src/signals/settings/categories/components/CategoryForm.test.tsx, src/signals/settings/categories/components/CategoryForm.tsx, src/signals/settings/categories/components/Detail.tsx, src/signals/settings/categories/constants.tsx
**Implement useWatch**
FormValues are not always updated because Detail is not always rendered anew. After 3 clicks a bug appears. Therefor implemented useWatch, so updates are monitored and only the effected component is rerendered
=> [bugfix]: implement useWatch to see if changes occur in inputfield of form

src/signals/settings/categories/components/CategoryForm.test.tsx, src/signals/settings/categories/components/CategoryForm.tsx
Positioned FieldGroup Status (name= is_active) above  FieldGroup Afhandeltermijn (id=n_days) in DOM.
also changed 'Standaardteksten per status' to 'Standaardteksten volgorde'.
Ticket: [SIG-5536](https://gemeente-amsterdam.atlassian.net/browse/SIG-5536)
[SIG-5536]: …
=> [feature 5536]: change order of elements in CategoryForm

src/signals/incident-management/containers/IncidentDetail/IncidentDetail.test.js, src/signals/incident-management/containers/IncidentDetail/components/Attachments/Attachments.test.tsx, src/signals/incident-management/containers/IncidentDetail/components/Attachments/Attachments.tsx, src/signals/incident-management/containers/IncidentDetail/constants.ts, src/signals/settings/categories/constants.tsx
**only users with right permissions are able to see/edit/delete attachments**
- Only users with permission sia_add_attachment will see the button Bestand toevoegen
- Only users with permission sia_change_attachment will see the delete button and the edit button.
- Permissions sia_change_attachment and sia_add_attachment are added to permissions for Attachments
- Permissions are moved to constants file in IncidentDetail directory.
Ticket: [SIG-5532](https://gemeente-amsterdam.atlassian.net/browse/SIG-5532)
- Code is well-commented, linted and …
=> [feat-5532]: write Attachments with permission

src/components/Label/Label.test.tsx, src/components/Label/Label.tsx, src/signals/incident-management/components/FilterForm/components/CheckboxGroup.tsx
Ticket: [SIG-5471](https://gemeente-amsterdam.atlassian.net/browse/SIG-5471)
Changing color labels when design according to new design system
[SIG-5471]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [chore-5471]: Change label color with newDesignDystem prop

app.amsterdam.json
Set showStandardTextAdminV1 in app.amsterdam.json to false
Ticket: [SIG-5542]https://gemeente-amsterdam.atlassian.net/browse/SIG-5542)
[SIG-5542]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [chore 5542]: remove standard texts v1 from Amsterdam Sia

app.amsterdam.json, src/signals/incident-management/containers/IncidentDetail/IncidentDetail.tsx, src/signals/incident-management/containers/IncidentDetail/components/MetaList/MetaList.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/StatusForm.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/DefaultTexts/DefaultTextsContainer.tsx, src/signals/incident-management/containers/IncidentDetail/components/StatusForm/components/StandardTexts/StandardTextsContainer.tsx, src/signals/settings/categories/components/StandardTextsField/StandardTextsField.tsx
Ticket: none
Fixes:
- order of standard texts on incidentDetail and categoryDetail
- return null when standard texts are undefined
=> [fix]:standard texts query

src/signals/incident-management/containers/IncidentOverviewPage/components/IncidentOverviewTitle/index.js
Changed <Fragment> to <div> so that title is immediately behind the refresh icon.
Since this is a bug in prod, transforming IncidentOverviewTitle to tsx will have a separate PR.
Ticket: [SIG-5557](https://gemeente-amsterdam.atlassian.net/browse/SIG-5557)
[SIG-5557]: …
=>  bugfix/5557-outlining-name-filter-in-Overview 

src/components/AutoSuggest/AutoSuggest.tsx, src/components/PDOKAutoSuggest/PDOKAutoSuggest.tsx, src/signals/incident-management/components/FilterForm/FilterForm.tsx, src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.tsx
**Context**
Users wanted to have search suggestions for street names in the filter. 
**Changes**
- Instead of an Inputfield for the search bar, now PDOKAutosuggest is implemented. The serverparams are giving as a prop so that only on streetnames will be queried.
- The onAddressSelect is not covered by a test since PDOKAutosuggest is sufficiently tested by itself and testing it in the FilterForm would require mocking Filter, FilterForm and PDOKAutosuggest.
- 
Ticket: [SIG-5485](https://gemeente-amsterdam.atlassian.net/browse/SIG-5485)
- Code is …
=> [feat-5485]: search suggestions for streetname in filter

src/components/DrawerOverlay/DrawerOverlay.tsx, src/components/DrawerOverlay/styled.ts, src/components/IconList/IconList.test.tsx, src/components/IconList/IconList.tsx, src/components/IconList/styled.tsx, src/signals/IncidentMap/components/IncidentMap/IncidentMap.tsx, src/signals/IncidentMap/components/IncidentMap/styled.ts, src/signals/incident/components/form/MapSelectors/Asset/AssetList/AssetList.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetList/AssetList.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetList/AssetListItem.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetList/AssetListItemSelectable.tsx, src/signals/incident/components/form/MapSelectors/Asset/AssetList/styled.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/DetailPanel/DetailPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/DetailPanel/DetailPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/DetailPanel/styled.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/LegendPanel/styled.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/styled.tsx, src/signals/incident/definitions/wizard-step-2-vulaan/eikenprocessierups.ts, src/signals/incident/definitions/wizard-step-2-vulaan/straatverlichting-klokken.ts
**Fixes**
Stop flickering when reverse address search gets new address. Put a delay on icon list on click handler. Capitalize assetlist titles. Change drawer top position logic
Fix scroll, rearrange DrawerOverlay.tsx, resize icon list image
Ticket: [SIG-5438](https://gemeente-amsterdam.atlassian.net/browse/SIG-5438)
Be kind to code reviewers, please try to keep pull requests as small and focused as possible …
=> [FEAT-5438]: fixes for tonen objecten lijstweergave

src/signals/incident/components/form/MapSelectors/Asset/AssetSelect.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/DetailPanel/DetailPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/DetailPanel/DetailPanel.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/DetailPanel/useCurrentAddress.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/DetailPanel/useCurrentAddress.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/NearbyLayer/NearbyLayer.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/WfsLayer/AssetLayer/AssetLayer.tsx, src/signals/incident/components/form/MapSelectors/Asset/__tests__/withAssetSelectContext.tsx, src/signals/incident/components/form/MapSelectors/Asset/context.tsx, src/signals/incident/components/form/MapSelectors/Asset/types.ts, src/signals/incident/components/form/MapSelectors/Caterpillar/CaterpillarLayer/CaterpillarLayer.tsx
**context**
when you click on the map on an object or just a new location there used to be a flickering. New address coming in from the reverse proxy endpoint and for an under the 100 ms no address. Therefore I build a threshold of 100ms that it will use the last known address before replacing it with the new one(or none). 
This will make sure the new address from the reserve proxy endpoint will be used instantly.
- Committed source code is headed by the correct SPDX license …
=> [chore] When address response is within 100ms, clear timeout and set new address

src/components/AutoSuggest/AutoSuggest.tsx, src/components/PDOKAutoSuggest/PDOKAutoSuggest.test.tsx, src/components/PDOKAutoSuggest/PDOKAutoSuggest.tsx, src/shared/services/map-location/map-location.test.ts, src/shared/services/map-location/map-location.ts, src/signals/incident-management/components/FilterForm/FilterForm.tsx, src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.tsx
Context
Feedback from testers was that beaviour of showing address in inputfield inconsistent was. Sometimes it showed just the streetname, sometimes it showed the streetname and the municipality. Also discovered that clicking Nieuw Filter didn't clear the value of the inputfield.
Now only unique streetnames are shown
Changes
dependent on prop streetNameOnly will serviceParams and formatPdokResponse change their behaviour.
Filtering for unique streetnames
removed defaultvalue from Autosuggest. -> Autosuggest seems to be a mix of uncontrolled and controlled feautures (with a useState to set the defaultvalue and an inPutRef). Story has been created (https://gemeente-amsterdam.atlassian.net/browse/SIG-5574) in Jira for refactoring.
tests for meeting threshold added
For testers
PDOK sends …
=> [feat-5485]: street name only search filterform 

src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/SortIcon/SortIcon.test.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/SortIcon/SortIcon.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/Th/Th.tsx
When ID's are sorted from hoog-laag than the chrevron has to point down and vice versa, exactly like Datum.
- Changed order column ID from ASC to DESC
- sortOption in List changed to ID_DESC
Ticket: [SIG-5575](https://gemeente-amsterdam.atlassian.net/browse/SIG-5575), part of ticket [SIG-5571](https://gemeente-amsterdam.atlassian.net/browse/SIG-5571)
Be kind to code reviewers, please try to keep pull …
=> [feat 5575]: Change behaviour chevron of column ID to mimick that of Datum

src/signals/incident-management/__tests__/saga.test.js, src/signals/incident-management/containers/IncidentOverviewPage/contants.ts, src/signals/incident-management/containers/IncidentOverviewPage/index.js, src/signals/incident-management/containers/IncidentOverviewPage/index.test.js, src/signals/incident-management/reducer.js, src/signals/incident-management/saga.js, src/signals/incident-management/selectors.js
Showing chevron after answer from backend has returned
- Chevron is now shown in column that has either a successful return from the backend, or in the column that was previous ordered.
- create selector makeSelectErrorMessage
- made prop errorMessage in IncidentOverviewPageContainerComponent
- set globalNotification when errorMessage changes and is not undefined.
Ticket: [SIG-5573](https://gemeente-amsterdam.atlassian.net/browse/SIG-5573)
- Committed source code is headed by the …
=> [bugfix 5573] Error handling when sorting

package.json, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitForm/IncidentSplitForm.tsx, src/signals/incident-management/containers/IncidentSplitContainer/components/IncidentSplitFormIncident/IncidentSplitFormIncident.tsx, src/signals/incident-management/containers/IncidentSplitContainer/styled.js
Ticket: [SIG-5540](https://gemeente-amsterdam.atlassian.net/browse/SIG-5540)
To discuss:
- The styling file for the incident split components is outside of the components folder. What's the convention here?
- The 'Extra deelmelding toevoegen'-button is wrapped in a `fieldset`, that seems a little odd. It's not really a form section, right?
- Is there a reason not to use the ASC `breakpoint` utility? It's not used everywhere.
- Committed source code is headed by the correct SPDX …
=> [feat-5540]: Update split form styling

src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/WfsLayer/utils/map-data-to-selectable-feature.test.ts, src/signals/incident/components/form/MapSelectors/Asset/Selector_v2_removeafterfinishepic5440/WfsLayer/utils/map-data-to-selectable-feature.ts, src/signals/incident/components/form/MapSelectors/types.ts
Ticket: [SIG-5589](https://gemeente-amsterdam.atlassian.net/browse/SIG-5589)
Note:
- [this PR](https://github.com/Amsterdam/signals-frontend/pull/2794) fixes the issue that when an object has no address you does have coordinates you can still continue. Which is often the case for trees since they are in parks.
[SIG-5589]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-5589]: Add caterpillar to selectable objects

src/components/AutoSuggest/AutoSuggest.test.tsx, src/components/AutoSuggest/AutoSuggest.tsx, src/components/AutoSuggest/styled.tsx
Ticket: [SIG-5574](https://gemeente-amsterdam.atlassian.net/browse/SIG-5574)
The name "default value" was actually used to show and hide the inline button. So changed it.
[SIG-5574]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5574] : autosuggest remove default value

package.json, src/components/AutoSuggest/AutoSuggest.test.tsx, src/components/AutoSuggest/AutoSuggest.tsx, src/components/AutoSuggest/components/SuggestList/SuggestList.test.tsx, src/components/AutoSuggest/components/SuggestList/SuggestList.tsx, src/signals/incident-management/components/FilterForm/FilterForm.tsx
Ticket: [SIG-5594](https://gemeente-amsterdam.atlassian.net/browse/SIG-5594)
This PR exposed the `onChange` event of `AutoSuggest`, to be able to use the contents of its `input` as a filter, instead of only the PDOK response. 
It also adds a `showNoResultFeedback` toggle to `AutoSuggest`, to be able to toggle whether you get feedback when there are no results. 
Be kind to code reviewers, please try to keep …
=> [feat-5594]: Filter address allow free input

src/components/AddNote/AddNote.test.tsx, src/components/AddNote/AddNote.tsx, src/components/TextArea/TextArea.tsx
Ticket: [SIG-5587](https://gemeente-amsterdam.atlassian.net/browse/SIG-5587)
note: remove inline does not impact other use cases since label is often not used or it is overwritten by html.
[SIG-5587]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5587]: Pass labels as props

src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/WfsLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/WfsLayer.tsx
Always setting an X-Api-Key header for WFS layer fetches causes issues for Den Bosch.
See mail 'Koppeling met MOON kapot na nieuwe versie' on 29-1-2024.
This PR makes sure that we're only setting a header when X-Api-Key is defined in the config.
=> [fix]: Fix api key bug

src/signals/incident/components/IncidentForm/index.tsx, src/signals/incident/components/form/DateTimeInput/DateTime.test.tsx, src/signals/incident/components/form/DateTimeInput/DateTime.tsx, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-bedrijven-en-horeca.ts, src/signals/incident/services/custom-validators/custom-validators.test.ts, src/signals/incident/services/custom-validators/custom-validators.ts, src/signals/incident/services/custom-validators/index.ts
Ticket: none
- since a default value of `null` was added to the incidentForm field, the required logic of DateTImeInput didn't work anymore. Brought in back the old code when it was working.
- A new subcategory is added in the main category "Bedrijven en horeca" which did not need the general questions. So specified them for the subcategories that need them.
=> [fix]: Fix date time question

src/signals/incident/components/IncidentPreview/IncidentPreview.test.tsx, src/signals/incident/components/IncidentPreview/components/DateTime/DateTime.tsx, src/signals/incident/components/IncidentPreview/components/DateTime/DateTimes.test.tsx, src/signals/incident/components/form/DateTimeInput/DateTime.test.tsx, src/signals/incident/components/form/DateTimeInput/DateTime.tsx, src/signals/incident/definitions/wizard-step-2-vulaan/afval.ts, src/signals/incident/definitions/wizard-step-2-vulaan/dateTime.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-bedrijven-en-horeca.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-op-het-water.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-van-en-door-personen-of-groepen.ts, src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.ts, src/signals/incident/definitions/wizard-step-2-vulaan/wonen-leegstand.ts, src/signals/incident/definitions/wizard-step-2-vulaan/wonen-onderhuur.ts, src/signals/incident/definitions/wizard-step-2-vulaan/wonen-vakantieverhuur.ts, src/signals/incident/definitions/wizard-step-2-vulaan/wonen-woningdelen.ts, src/signals/incident/definitions/wizard-step-2-vulaan/wonen-woningkwaliteit.ts, src/signals/incident/services/custom-validators/custom-validators.test.ts, src/signals/incident/services/custom-validators/custom-validators.ts, src/signals/incident/services/custom-validators/index.ts, src/signals/incident/services/map-controls-to-params/map-controls-to-params.ts, src/signals/incident/services/yup-resolver/index.test.ts, src/types/incident.ts
Ticket: none
It used to be possible to make the dateTime question in additional questions possible. However, with a refactor to react-hook-form some code was lost and the functionality did not work anymore. This PR recreates this functionality. It's based on how the dateTime component is working currently, so not the nicest solution. 
Instead if `null` being used as value for "now", it's the string "now", so react-hook-form validator is validating to true when "Nu" is selected.
=> [fix]: Make possible to make dateTime required

src/signals/incident/definitions/wizard-step-2-vulaan/overlast-op-het-water.test.ts, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-op-het-water.ts
Ticket: [SIG-5611](https://gemeente-amsterdam.atlassian.net/browse/SIG-5611)
'Overlast op het water' has two more subcategories, 'Nautisch toezicht / vaargedrag' and 'Olie op het water', I've asked Linda what questions these subcategories should get. -> 'Nautisch toezicht / vaargedrag' is unused, 'Olie op het water' should not change.
The PDF shows dateTime to have the time selector disabled, but I discussed this with UX, it should be enabled.
[SIG-5611]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-5611]: change extra questions THOR Nautisch

src/components/AddNote/AddNote.test.tsx, src/components/AddNote/AddNote.tsx, src/signals/incident/components/form/TextareaInput/TextareaInput.tsx
No ticket
Textarea's in step 2 showed the label twice, because is was added in TextareaInput and again in AddNote.
This PR makes it possible to pass an `inForm` prop to Addnote, which doesn't render the label in AddNote.
=> [fix]: Don't use addNote label when used in form

src/signals/incident/components/form/DateTimeInput/DateTime.test.tsx, src/signals/incident/components/form/DateTimeInput/DateTime.tsx, src/signals/incident/components/form/DateTimeInput/DateTimeInput.test.tsx, src/signals/incident/components/form/DateTimeInput/DateTimeInput.tsx, src/signals/incident/definitions/wizard-step-2-vulaan/overlast-bedrijven-en-horeca.ts
Making the time selector optional caused an error when you answered Wanneer was het > Eerder > Vandaag before 9.00. Without a time selector, the datetime is always 9.00, which means the `inPast` validation isn't met before 9.00.
Discussed this with UX and decided to remove the optional time selector.
=> [fix]: Remove optional time selector

src/signals/incident/services/map-controls-to-params/index.test.ts, src/signals/incident/services/map-controls-to-params/map-controls-to-params.ts, src/types/incident.ts
No ticket.
[This PR](https://github.com/Amsterdam/signals-frontend/pull/2813) created a bug when trying to submit a _melding_ where you answered ‘Nu’ to the question ‘Wanneer was het?’. [This PR](https://github.com/Amsterdam/signals-frontend/pull/2815) fixed that bug.
The current PR adds tests to prevent that bug from happening in the future.
To discuss:
- Maybe we want to turn the check around? So:
```
typeof incident.dateTime === 'number'
? formatISO(incident.dateTime as number),
:  formatISO(Date.now())
```
- Should we change the [Incident type](https://github.com/Amsterdam/signals-frontend/blob/b53f397d5efe5fc127eb0a4813e50a27dd37fb73/src/types/incident.ts#L25) as well? It says it can be `number | null | string`, but it can be `undefined` as well.
=> [fix]: Add formatISO type bug tests

src/app.js
Ticket: none
Since i18n functionality is still in development, it should be initialised. The initialisation causes a call to the backend which will always fail.
=> Remove i18n initialiser

src/signals/incident-management/__tests__/saga.test.js, src/signals/incident-management/saga.js
Ticket: none
On the incidentOverview page there where some double calls when searching and clear the search. This PR removes somes actions that triggered the double search query. 
screenshot left localhost, right acceptance when searching and clearing the search.
=> [fix]: Remove double search calls

src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/DetailPanel/DetailPanel.tsx
Ticket: [SIG-5684](https://gemeente-amsterdam.atlassian.net/browse/SIG-5684)
Note: the List component will still render when a(n) item(s) are selected. They will appear with a checkbox. When deselected, they disappear again. Is that desirable?
left: localhost 
right: Den Haag production
[SIG-5684]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-5684]: Do not render AssetList when selectableFeatures is empty array

src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/AssetLayer/AssetLayer.tsx
Ticket: none
Since an Id can be a number or string, it should not have a strict comparison when determining whether the object is selector or not.
Object appear selected on the map
=> [fix]: Make comparison less strict

app.amsterdam.json, src/signals/incident-management/containers/IncidentOverviewPage/components/IncidentOverviewTitle/index.js, src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.tsx, src/signals/incident-management/containers/IncidentOverviewPage/components/List/styles.ts, src/signals/incident-management/containers/IncidentOverviewPage/contants.ts
Ticket: [SIG-5683](https://gemeente-amsterdam.atlassian.net/browse/SIG-5683)
Includes some refactoring:
- Changing keys to English
- Sorting information is now a label instead of key, so removed the key from `type SortOption`
- [bug] When `fetchDistrictsFromBackend` is enabled only the header title was changed. However, the query should have changed too to use `area_name` instead of "stadsdeel". 
[SIG-5683]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-5683]: Allow 'Assigned user email' column to be sorted

src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/WfsLayer.test.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/WfsLayer.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/WfsLayer/utils/is-caterpillar-category.ts
Ticket: [SIG-5872](https://gemeente-amsterdam.atlassian.net/browse/SIG-5872)
- only send key when host is api.data.amsterdam.nl
- fix small bug. A error was thrown when no features where there and the util function tries to read `id`.
- key should be added to acceptance and production config files
[SIG-5872]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-5872]: dataplatform key fix

src/signals/incident/definitions/wizard-step-2-vulaan/wonen-woningdelen.ts
Ticket: [SIG-5630](https://gemeente-amsterdam.atlassian.net/browse/SIG-5630)
This updates the short labels for woningdelen, following feedback from UX
[SIG-5630]: https://gemeente-amsterdam.atlassian.net/browse/SIG-5630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix]: Update woningdelen short labels

src/components/Map/Map.tsx, src/components/MapInput/MapInput.tsx, src/components/OverviewMap/OverviewMap.tsx, src/signals/IncidentMap/components/IncidentMap/IncidentMap.tsx, src/signals/incident/components/form/MapSelectors/Asset/Selector/Selector.tsx
=> [fix]: Show attributionControl on IncidentMap and hide leaflet prefix

src/signals/incident/definitions/wizard-step-2-vulaan/overlast-op-het-water.ts, src/signals/incident/definitions/wizard-step-4-summary.js
Ticket: [SIG-6019](https://gemeente-amsterdam.atlassian.net/browse/SIG-6019)
Some fixes after feedback from UX:
- The summary didn't show the correct labels for the Afval and Overlast op het water categories, and the Verkeersoverlast subcategory
- The subcategory Wrak in het water should not show the 'when' question
[SIG-6019]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-6019] feedback update when question

src/signals/incident/definitions/wizard-step-1-beschrijf.js
This fix only shows the links to the reports map when it is enabled.
=> Only show link to reports map when it is enabled

src/signals/incident/components/ReplyForm/Notice/Notice.tsx, src/signals/incident/components/ReplyForm/Notice/__tests__/Notice.test.tsx, src/signals/incident/containers/IncidentReplyContainer/__tests__/IncidentReplyContainer.test.tsx, src/signals/incident/containers/IncidentReplyContainer/constants.ts
Ticket: [SIG-6155](https://gemeente-amsterdam.atlassian.net/browse/SIG-6155)
Test case: http://localhost:3001/incident/reactie/1aee3125-fd95-4977-8e05-11443f453267
[SIG-6155]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-6155]: Change reaction asked notification

src/components/Accordion/Accordion.tsx, src/signals/incident-management/components/FilterForm/FilterForm.tsx, src/signals/incident-management/components/FilterForm/__tests__/FilterForm.test.tsx
Ticket: [SIG-6455](https://gemeente-amsterdam.atlassian.net/browse/SIG-6455)
[SIG-6455]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix-6455]: Refactor RadioGroup counter

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/signals/incident-management/definitions/typesList.js
Ticket: [SIG-6568](https://gemeente-amsterdam.atlassian.net/browse/SIG-6568)
NOTES:
- Should not be merged and released before [backend ticket](https://gemeente-amsterdam.atlassian.net/browse/SIG-6538) is done. 
- add default feature flag
[SIG-6568]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-6568]: Add projectmatig onderhoud signal type behind feature flag

.github/workflows/build_and_push_to_docker_hub.yml, .github/workflows/ci.yml
See security tab above. The default permissions might change over time, potentially leaving us in a vulnerable position.
So it's better to explicitly define them.
=> Explicitly define workflow permissions

app.amsterdam.json, app.base.json, internals/schemas/app.schema.json, src/signals/incident-management/definitions/typesList.js
Ticket: [SIG-6568](https://gemeente-amsterdam.atlassian.net/browse/SIG-6568)
- Change featureFlag useProjectenSignalType to useProjectverzoekSignalType 
[SIG-6568]: https://gemeente-amsterdam.atlassian.net/browse/SIG-6568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat-6568]: Change projectmatig onderhoud to projectverzoek
